apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: forgejo-local
  namespace: forgejo
spec:
  ingressClassName: traefik
  rules:
    - host: forgejo.home.kronkltd.net
      http:
        paths:
          - backend:
              service:
                name: forgejo
                port:
                  name: http
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - forgejo.home.kronkltd.net
      secretName: forgejo-local-tls
