apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forgejo-local
  namespace: forgejo
spec:
  ingressClassName: traefik
  rules:
    - host: forgejo.local
      http:
        paths:
          - backend:
              service:
                name: forgejo
                port:
                  name: http
            path: /
            pathType: ImplementationSpecific
  tls: []
