apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: postgresql-password
    namespace: forgejo
spec:
    secretTemplates:
        - name: postgresql-password
          stringData:
            adminPassword: ENC[AES256_GCM,data:n1iK6e7SsoSeh4VhL3W5Rw+6PeY=,iv:qPy2Scvlqj2ixURH43425m1bm/RY51SZCvw2mYmYXD8=,tag:Rafw/qBkwDyY5FRjzbpxqQ==,type:str]
            adminUsername: ENC[AES256_GCM,data:O3/U54U=,iv:w5ZByDk7x5VsGyWlaJixysMv1tHl1PncKsS8+qyYLaE=,tag:PR0w1G1JuC9fWgf+LDCj9w==,type:str]
            replicationPassword: ENC[AES256_GCM,data:m3ZMAiCSzWgKXN4gR1B4mFVOKqg=,iv:Pf2hddwkD8ik1WHoYGq4wG/8oo1FjA+J2rrFMydN3dA=,tag:MRlVYY7AVY950zFwEK6OwA==,type:str]
            userPassword: ENC[AES256_GCM,data:ra4SYyLSpSDXZiO3n4YFL7N50H8=,iv:UGQZiliECIpV91oNfV8g/0MohoTwx4f5CUP7EmzRRFM=,tag:CjIoKKogb7WAy/2giLtXCQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcFoyaldKMnBuQWM2dmNz
            bDJvK1phcWZ1U2ZxWnB6QjJqc3FUd1BIUWl3CnlTSEV5NG9KVE44ZzJzWXZZYzFM
            dGtXZlVlNWc0d0t0YzFXaVlaRC9BQmsKLS0tIFNuUGl6TEFBV1NuQ29Ma28zWHdJ
            c0t6OUtvY1RtRFFXbXJ5VkUreWNHS0EK532iMcWfoMpqxJIXW+zDSTiBbLonUEVH
            PCiZ0GuSE0JR9QDRg/6CmOXsTz/9miYWZCNaTZJU8qYtmn4BJE6mYQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-05-24T20:18:07Z"
    mac: ENC[AES256_GCM,data:bgyXDJat4wIAXr4Rp9KA3jzzoX3/z3z+PoEMGdIob2ZG/kEeGMf22r457WBfh4a98So2x+OOABElNy9rfW4vQd88YEVIYvkIRXjhIaV1FyLDv/Sqf/RFwjmAY/Jpk1zIinP06tTL4UtMRSLvJO6SXr4/+Zllg2ohn5t437be7Rs=,iv:olE2LhwORrYvZp7BzocxJTd57pdQyuHfolgJvxdSSbU=,tag:hJdXzmb+FeDWr3xWNTkAqA==,type:str]
    version: 3.13.0
