apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: forgejo-admin-password
    namespace: forgejo
spec:
    secretTemplates:
        - name: forgejo-admin-password
          stringData:
            password: ENC[AES256_GCM,data:xCjlf/GDYAOGGJiSE+TzvNtV+6I=,iv:DB/MFk/8VjdXBj/Tu5aGm4j8scSZAO96at+robGGlDg=,tag:bhPLURsjin/lE5eUVx+ECA==,type:str]
            username: ENC[AES256_GCM,data:bWOq7Q==,iv:U2ZN0vLVrMD/Yp9HSJKUg/ZZKjRpMJEpU2b7CSW7jW4=,tag:Qqxr43swQxyn5Ym+AJShdA==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWVg0SkZtdHcya1I1Z0w1
            L2tjYVp3V01iN0MvdFloYUZ1aGNqYUZ2VXkwCmUyeUY5SWx0UTV2eGdIZGE0QzB6
            U2J3ZG9SaU0xemQ0Q3lNUlZxa05HMzQKLS0tIFdlTDhxejlkbUFwckVEd0tCeW0w
            RmdvdFpOSVQweklPTTVXQVQyNU8rWkEKgNzsY9DDSnXGSvFKTcmAIEQ9O3SxcNJK
            jUsJcPJIuO7JcPWrhfkbBSiUb5RyprhgMKQsr89qxqN3YaWpoFZIFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T22:45:54Z"
    mac: ENC[AES256_GCM,data:ln+wlfGS3gmXLGYmp4TwQ9GQXY2ctST0uSGeXMKKkfMFW3uddY/BEygoWN2oYEo52sJgW4wkraWcPSfEvGqsWFbhnAeFSXTuyJPtQWiHhHN8zLsXRtmSRdblkfE5eFOZhASVBe2YPChh2dnIUDhgpx9s6kqfkLqwz/9IXEo6IPc=,iv:RsOuBrH3UObcov6FqEISuE/uV9Vf5fzbwY+mDUuXJik=,tag:/eSG8e5FKstphMnZ3GUJAg==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
