apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: forgejo-admin-password
    namespace: forgejo
spec:
    secretTemplates:
        - name: forgejo-admin-password
          stringData:
            password: ENC[AES256_GCM,data:nmiMLNotzctTVS5Cr1zO428FgYg=,iv:lWZ2kG9BevjktLqa+sVcOSjXBFci/Ri+KGoiLkVdyck=,tag:brYlsRHAJ2jXbXpKWhwZaQ==,type:str]
            username: ENC[AES256_GCM,data:rs8kNg==,iv:zWNDu5/j1At1MagEqDKq8aVlMAJV+EYhROvragAln/8=,tag:ypov9KuEWw9C1dyiYQMtXg==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bkxuK2k5VXlzeFNtT0xW
            K00wYktlSDhvVktKSlViUkRya3B2RmN1NUI4Ck9ESnNHU2NGaUp0dHVuSW41ZnVT
            L0hkdmNXdS9nc2xGTy9iWVFjQS9NV0EKLS0tIDhLT1AvVFEyNWJVMFNRSW1vWDdE
            ZFlFMGg5V1VNNWYwVHF6RWRTcTdCQzQK4Q30XsjoMGIrGWMiwsrEUeaoxs+uZGcS
            rbpvEN6wzgsrZw/AD4Ko9C6oiIudNlCwTJsCQTDd/5f6i2v9pe2YhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T13:41:02Z"
    mac: ENC[AES256_GCM,data:WJL33AQ4Z9zW1i78keW4MTCylxoB1dJTuh8kdTn0Jt3ol97Mktw6Mkf9CaOa7z+8RY3vuW8XsxmZ0mNnkc+LJqmite3cy7mEWj4XGsQu15mAPsLsJBxefwiI13qBGCw3MN5oAW2Mlpclo4/ahgvfVe5ESkL9agjJlhzzr3rbZtE=,iv:FDq8nc+xK1QIK8SmB50pt8yoLSKsdmqtisTL0cAdX9g=,tag:7JYHagRfh+a8lT03KSFsnw==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
