apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: forgejo-admin-password
    namespace: forgejo
spec:
    secretTemplates:
        - name: forgejo-admin-password
          stringData:
            password: ENC[AES256_GCM,data:FZaomhJt4SXY8Nobi+GgjG6xCkA=,iv:aSEF8NZXJSlrpsLeFSlz2NLys9sJuWK4psviXkp08BQ=,tag:8IbRuC2e0BRJf7Me47KuFw==,type:str]
            username: ENC[AES256_GCM,data:VmVYUA==,iv:DhMDDt/Qz8otEAuE3O+uOHzpRyKZPbcXV/tGDU4Gmgc=,tag:W+7izw2Whfi26GOwTcgxQw==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwb0NTdHc2c3VRTTgvc0pJ
            REFhUkJGc0JSVHVpR0tmWVFXRWZDeUhQaWdjCnZWY3ZpSk1LUm1icGQwV050TmFp
            ODlUbFBVM1ZQKzUzZWpGY1RTbTJob1kKLS0tIGozd1B1WVoxdmZhaG5LTStzekdu
            NkwyU3hxUkhsUmYyZnhTODhXNDV2VkkKbNGIc109Jq8iUjYoB9hVICFGb15oS5Yl
            lRreFVE1lNKrx23whpEeMPe+H61hcIMqrDmohFV8lTOmwFxuHC2rww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T02:43:39Z"
    mac: ENC[AES256_GCM,data:1kDrV2npak5+kR1adkPc76IM4QTjq7kidNKN7xNOBHSNUpHTT4ExN4Zg9x50F55gi170g2lAw+z3TG1Bbp6HC017YdIRw9L2e31nQO1a0TWY5SoAdQpX3jZZgFat1HKmqD3BwU9MjtLL9mNumUdx5uQ9+jOvYZdoRKVDdXrbR6M=,iv:FUzEhGvpjXW3MqcmjJHGweF5OaNM/rdK7o7sANh7j0c=,tag:UzA2oEMNqKf8Q9Dx0rbCTg==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
