apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: postgresql-password
    namespace: forgejo
spec:
    secretTemplates:
        - name: postgresql-password
          stringData:
            adminPassword: ENC[AES256_GCM,data:R0sYPGQnPdi2cPWEevzpjTaW8LU=,iv:zPIxhOolrAYujDS0q8LZeZqxsTJVEHXPqc5Ep49vuzA=,tag:DCLanyNESB8bGb41XCKqDg==,type:str]
            adminUsername: ENC[AES256_GCM,data:hJSnWn4=,iv:nZSDjEu4luATJAUUX/JFzfzIRtHTINznIJN4AeZlAK0=,tag:OeHuwGZee+Y95x4AfmYGpw==,type:str]
            replicationPassword: ENC[AES256_GCM,data:EXgwf4ozrDqDiHT24hK40Eb3YIA=,iv:rZso3HRPEv1VgiBB/NUsThcfkX2QglHFNrrBy66gclo=,tag:UHkMlTYX2r64HM//0k3DBw==,type:str]
            userPassword: ENC[AES256_GCM,data:iVc1HS97iL2+9//xYgrs0S7q0oo=,iv:XAZD1e7aIs+VoMQicF9OVmygiDeQTu0Ng+rx1MCa1BU=,tag:43Pl6s7I9xdlSdF8b97uZw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPd2cyaGJramxJYWx6SnBC
            aXFQRjNONXN3T0FEVnBGczl6eTlqcm9Fc3dZCjRkU3lOZG5xNVBod1JLUG9pN2hh
            NXpwYVlDQzE0Yy8za0lsVHZLZEYwWTgKLS0tIG5nTTdzdHA1Sk1zVTBSZkl2YWpO
            NkxHQStYcmR3TWw4eS9HZXR0SFhnQk0KPp/Azjh2TCSDn3z/eMSICGpJJdwv1bKJ
            eUoaxO+V4DHyxQA81DLGNkyLNwLm1QFOM9E8TYn1Y/1phMr67rxH+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-05-24T19:49:36Z"
    mac: ENC[AES256_GCM,data:QYOziIz2C7DizWdPh5A1FDYIZr4JVZ/MOcD9fSJCipPGyTEpucHOKuJhRPqfkPeCGeF0uWbzAnF8hMY+6prehaIlr5uH2DnsMGecKFOcjtGpTsttw5aKhqf2YI4w2yuVLX0tGZyneXg719KXzW0UqwI3ZJReSCTjrrxfDzt3zD4=,iv:3b/SY0lGfiZfExoFHPvtkfX5lrM6YRbIsxwMzAtg1y4=,tag:nZ6JgnktG3I4GBe4yMvh6g==,type:str]
    version: 3.13.0
