apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: postgresql-password
    namespace: forgejo
spec:
    secretTemplates:
        - name: postgresql-password
          stringData:
            adminPassword: ENC[AES256_GCM,data:XdssV3lM2Ebc/DMXHPAD9wl9Lc0=,iv:rqB4pw7BTFzl8dTgye+5f1BKMcC+QkiUisBXxOVvMqA=,tag:VEXGlmAscFt0Ni/FF6H8xw==,type:str]
            adminUsername: ENC[AES256_GCM,data:TEOAlwo=,iv:I/U56niLHLgZQB/jTUOkygmZQmBDt1/W8pE7PrwmMwc=,tag:lf3vmozXWnP3sm3yqJvgxQ==,type:str]
            replicationPassword: ENC[AES256_GCM,data:yv7R5VCwJs5R+bE8blJ0l/rwVEk=,iv:xPDTjj3vdlF+wGVYH5AHBBZduKsILGq1q6uwFvgWcPc=,tag:svep4I5oixp3ijr6JGWbvQ==,type:str]
            userPassword: ENC[AES256_GCM,data:1yQfqRb+CBeiCyAuK752NVpvhA0=,iv:L9E/OUDso6/eDzSCkGQ5BiZiNa8aphb4JB8QEjTzWZE=,tag:ljGzNdVsN4QhfmFnUV4daw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArOTQveHJDNGFBYVNxNFdp
            MjlZUldyekxYSkJnN201QVU4NlRqNGRFb3lJCjBjUnVaOExFeHA2R0owb2JnRmdK
            U1o3Tk1kUjdpWk9EcW5GT1AyS1k3ZFUKLS0tIG9QNElnSWk4eXVSd0FMUXpxdE1u
            RENBZ1dJSDZ5ZmJJL29sVDJQQ1UyUXcK/VT+d75DoQgERTc6NprYdJ9BKAByayeg
            6iwhi7SIVaA3wc93zPun3K16FlNhX61/vjDCxyGEP2O4/SLYQWrGGQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-05-24T20:28:31Z"
    mac: ENC[AES256_GCM,data:rO2+znqum2e92z2iBXmhQi0ycw8Uwu6th/1vXlXFrfMcacJ1t78VQkWGBbbFfprU4uJqRS70thYvMOMEyXMUrN7RuLgZUIIxUSbT5alXWLjq/uO3WBtYSiRqN5qt6/+wAKwkzH1HDYhOLDu+XTCkRi9919k4zk7mHu77oL0kELE=,iv:+m8RERlBhZWErpdBySBOMkHGnlr8zyRzmCaAEwpWFD0=,tag:YDI6qqbk2Uj6xqAE2jHJRA==,type:str]
    version: 3.13.0
