apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ditto-relay-ditto-relay-opensearch-data
  namespace: ditto-relay
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
