apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Replace=true,Force=true
  name: ditto-relay-ditto-relay-opensearch-data
  namespace: ditto-relay
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ""
  volumeName: ditto-relay-ditto-relay-opensearch-data-pv
