apiVersion: v1
kind: Service
metadata:
  name: ditto-relay-opensearch
  namespace: ditto-relay
spec:
  ports:
    - name: http
      port: 9200
      protocol: TCP
      targetPort: 9200
  selector:
    app.kubernetes.io/name: ditto-relay-opensearch
