apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: ditto-relay-nsec
    namespace: ditto-relay
spec:
    secretTemplates:
        - name: ditto-relay-nsec
          stringData:
            NOSTR_NSEC: ENC[AES256_GCM,data:mHsVik7aaYPzJQBWkRldsYd8L6G7tlWjtxdVf/ah+Emr2OCe2mFCDmAIOpP+x+mGtrSLxDvpi1MuxiMLbQgp,iv:Bskdrm6SEtRWwo5TyiTc2ximsfpkCKAcvXoA7BwuRRc=,tag:0usPbaO6VhCrpY6AqztMVw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WnladXVRNEdVbGJGUkRi
            VFVmQnJuNjNONW92ZFExQzZZRTNWcVozbWlvCnlzN1N0QndNMzB1QU1KMzRBNzQ4
            ZEtpTlE3L1k4UFhvdHVVejlwTnZhT2sKLS0tIDZOWVE1cVJzUThJOXpGTzZYUlFi
            Umx6SUxBbE5BTmNLTS9KNDZGUU8yTWcKa3a1LsRnJtAExrd8m7f4mbF9/w2l8iDP
            RSgA5/yb/6Kv/vok6BcnCuE0MGaVDSsPD9RXkuAk2llXm5AXVtZxJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-06T20:11:45Z"
    mac: ENC[AES256_GCM,data:jzcRzlRQ9swt+UuQobKVfZI/e5UwUyO/T8I4fPc42+XDCAaIZXE+so2yGvYBwpajV4tsi08FExvDCoGSpVsEkBO4YLxduBKGIvubftvcUWiaa9bwKM4+gfSNEowrg6p0lo4kyj8ZL/0VTAFHC9fPAHBBz5jqRnoBNht/+EO1FNg=,iv:9xsr1mBYJmRPWoTiTtXkDBPAs0mIo9wCvXkIjYFOu0c=,tag:rsMurIWGMpdx0SUYsSwAgw==,type:str]
    version: 3.13.3
