apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nocodb
  namespace: nocodb
spec:
  ingressClassName: tailscale
  rules:
    - host: nocodb.bearded-snake.ts.net
      http:
        paths:
          - backend:
              service:
                name: nocodb
                port:
                  name: http
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - nocodb.bearded-snake.ts.net
      secretName: nocodb-tls
