apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: nocodb-jwt-secret
  namespace: nocodb
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6eVRrWDZIVkY5VGwrODFi
        eWFvZVYzbXREa1dSYmdCWlZGakVIZFFTU1hFCk83bCtsTjRuUnRlbmM4RHlOeXFS
        TGwyUG5WUGZwdndDOGxQTDJvbjF6bW8KLS0tIHJyVmdBRElSVGhWRjlkTjJFM3N2
        Q2MreEhoZWorci9PMUpJN2FvOHNqcmcK0GQGfY5g6P/M4gKDU/gPI1UTSF1ebN4x
        ++SrJKLE+wYz/ZKdXjivHDWD62U6wmSUS8SulPSbSjBeE8SixeRPbw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
  encrypted_regex: ^(stringData)$
  lastmodified: "2026-03-28T16:05:20Z"
  mac: ENC[AES256_GCM,data:I6ofSXJo9/HMZS78enZa4pBvH4dRYQyGGFwhnR8eL/khLGueY9AaVToIk0EbzLQ87Gox1JNSAVPBvUoXXr7xUNr3gKzgnzvXxqhJLaHec5wbDM5mq/XV3T2W7eES5rQz0QHlHuSf3F7AB6fzjyAEU2Sv9MM8IkfxN4ul6dhVUJY=,iv:TSK1KsMLipkgpmABw+VagKE9ujCSZecm7YyDFpHVG8Y=,tag:DXA1lGbdRvqv7+xtvuE+zA==,type:str]
  version: 3.12.2
spec:
  secretTemplates:
    - name: nocodb-jwt-secret
      stringData:
        NC_AUTH_JWT_SECRET: ENC[AES256_GCM,data:7zoqUuEiQjmTjjOsdMZmol5VS9/2OuWWFV7lnjnDvNgDO5tdsMsBRh0zfv8LMO23Aq7V5OZed3/jTzBT7YlUSQ==,iv:yI8D4bn5VDAborz/LUNtLyOL/6D7GlHAAzIgKBXkhNw=,tag:X0h/2hchB+tujKdV0yuS4g==,type:str]
