apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: nocodb-redis-url
    namespace: nocodb
spec:
    secretTemplates:
        - name: nocodb-redis-url
          stringData:
            password: ENC[AES256_GCM,data:/Lb+qFJLJ15Jlt2oFPXu0gZe3CY=,iv:fa3/OeC1TImxvfZPOjvvar41Zaovuw+VrIfD0gjx9Ok=,tag:0echLIJ8MTgUOqOGwfAcDQ==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrOVRlcW5JQS96NFRQaTg5
            UWNHMEJlZzE0YklvY01wbG9KcTl0OTJQYkZvCitiNUtpcTV0WGhUVzVDNUdDMG1p
            eU01MGNlM2t5TmNHOUEwZXBMaDhOYlUKLS0tIE1wczcxMHI4TUFtdERiWHIzVUFo
            STd5cFR5TWg2ZXBVK01RRW1oemdCRlEK0MvZCfqyjRY5FOMennmXCnYBsC0hTDUT
            eE/9Z+o3sDnSlF1xatiemLJHvokI0IKENcocDyFlJWKrLDbLIQG91g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T22:56:00Z"
    mac: ENC[AES256_GCM,data:BRrjlE2xF0pr2iSWlyienih6yqgGZXTNYwpYMwF8MQkR3NbqqBoZ7CuuPIsZUzRvI4QuuPUnMXVXPY+VG2Lxq3mHOvD/GN+kWjT0Xfr+QDKrEJo/MkxbZy8kKK0z3Sh5NH8lFBq9yJch7ibkkZzIl0ZMtOfUWH9R/pu7RQ8bIrQ=,iv:paPdfsDJ/5a+ydvQuYyRgKqBw16g9Rm4SHreCJis3w8=,tag:Q0cPRCTAHHKZ4eZfNpdMJw==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
