apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: nocodb-redis-url
    namespace: nocodb
spec:
    secretTemplates:
        - name: nocodb-redis-url
          stringData:
            password: ENC[AES256_GCM,data:fFtbOE85Kfbnlu1l0z0SbZe+9S4=,iv:gF1yyW5JE67ENJtXBcW/6wtwxh9LbHAPNcix3Kqhm/o=,tag:j0xAj4MIH53xK/sZXCxM3A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUWxacnlHT2tXRmpKVVI4
            SExwaGVBN3pkbXZSdng4bm9nUkpwYWE5Z0hrClFwbHc4S25HVjEyb2dLTEMwNGps
            anlOUGQ5aUg1ZlUyVDlnaHpFdWRiclEKLS0tIHFLWGZ0bUdraFJaL2hnNG8yelI2
            T3F5OHJGL3FaaU43aVNiVHp2SDNGZTQKP5XydTPgHLKi8a6oLCDqjthVJgkowmhL
            mQXWfkenePQTjAzsW1wWR3BpJCEFLk+49Bq3KdpVdbM6S+5CllQUGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-05-30T00:52:12Z"
    mac: ENC[AES256_GCM,data:8t+sZcpp4d75RWV5lyLhgpfGaWdvtvCFxVrI1eGrtKGVGc1DHqn4y/EWqbQkfxQaNvyiLcEgvV2CC9egs0m4v5LLRZxZBGK4GYX9PM1W9IGKPSSWgmKX+ivl2hvAiVK2cu02NBQVw64S2l2r9RTU8DiqEU7RlnoIoHlG5T2NzwA=,iv:72dM1M6pmQnEP3wKcd1EW83LI5EIGaV6vh6U8M9cxt4=,tag:ZQw+lyVM0VDWf50rCPwS4A==,type:str]
    version: 3.13.0
