apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: nocodb-jwt-secret
    namespace: nocodb
spec:
    secretTemplates:
        - name: nocodb-jwt-secret
          stringData:
            NC_AUTH_JWT_SECRET: ENC[AES256_GCM,data:qi/Nvr/5ctElYshPAMSHjSKTdxrMXAYQHrWp7OqbK0ec2GFGj6hallLUDbDJzYgV3p/cm1ZrIv8X8Hl64eWdGQ==,iv:c/TVQWbc87APFDHY0LScga0lCV6eckC0nNVnLdOaEyM=,tag:BB4yDspwCH476YfuMnwF1g==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbGVPSUhhWVNSQzE1Nnlx
            bDIyNkc2R2tGSkdwRm9PaExURGY1blVxeFVFClRNTmVRdFNYMmo2eG1lMnh3RGds
            eUJubFk0ZU05SnZYb3dVbktHT0MrSG8KLS0tIG1ZNDNEa2ZRRzhDOGRsdFZKc0VO
            TXdFcVFWYll5aHgwdWpvS1BIS3R4UncK5zlvYaowZtPVgPz4Y1aVYTwJ4vj6afpH
            uxO1Vj3NMdYyYbYBxvHvvxMVq+e/8mP/9rZo/4PX/ZVhbur5B6soXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T17:43:35Z"
    mac: ENC[AES256_GCM,data:zU9uh/45fdhyPszua8O1cTu/5Yeo3tam9Ij3l2Z7UpRNIGuEkaBAVwbmB/gtCOPR3jTFP0sFAP+SXsR1tTEy6ikItXoUZUD9xjm5CWuk56a4QAGizyWe7gyUgsLBBNfPtuBxWWsJxPSU//7lkMAW0ilZUXGpa1dUEP2gmCPKHEA=,iv:/Ka4NR00e73OJI2VYj++jpLhydiGDhZ5jjP0vir2reQ=,tag:5TAB/HAhUbbyNeIIF//dJg==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
