apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: nocodb-storage
    namespace: nocodb
spec:
    secretTemplates:
        - name: nocodb-storage
          stringData:
            accessKey: ENC[AES256_GCM,data:cjDBw2xluOexBR9plW9Ap3FMGob+06nh+BUS5z2+r0Q=,iv:utuDgWE1PbfuSNcwUsx1+R0+V7KE7r4DvG5ZlmlfGHM=,tag:TIVMbD5BWC98Vv50b3j9vg==,type:str]
            secretKey: ENC[AES256_GCM,data:w+1hi4M0u1MglQn+oIfHZ1Y3lQS0gvmgH/6LGbAJW0c=,iv:d/1gS26IDAvw+XwYKATkGWLpadgp7d59DfjvdjcvFHs=,tag:JvBQaunsFZ4+YP2J2PPeGA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZExvYlVGWTQ3Y1lEKytu
            cXo0bGIwVk5HMmMrcGs1YzJvSGkwVDkxc1ZBCnkzQzM4VldlbzRvY09ReFZzM1Jm
            SU5HdXhUREp5U3dreDBYWnMyZENyUEEKLS0tIHdadFpibDN2Tm5OazY0SjRqZ1F2
            NVBYWTFKcXN3WkNmVkt0ck9vY2c4NHMKcdfMoupVoigThIlTv1TA5gBKpBWq5upu
            KgZOl/Dd4RP/sSoVQ6339r7xI/YZgDqYA1VA5isB6our8iSEW4cbNQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-05-27T22:51:27Z"
    mac: ENC[AES256_GCM,data:U+4+7a86Hg4eTe5XBeruR7bXRJZ9jiJCg3tsXQJS+MkGzUHa6o3YdzczEcMpZFi9Zt47YsnpG9U01MFhd8F+y9orSeXAF2X/KKiCuRIrpfTbfy1B12ARe+88yPuXiCHcPSzcICcIw1kNcmqvbtLEfsAk6S7bzQBg8zY6xtVS9I8=,iv:6pqFy/mZCRuYOIl5xBkW1cHKF0p8RJwEOVeHEt7r2W8=,tag:M4rKKp/W32qwo2pp+qwMzg==,type:str]
    version: 3.13.1
