apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: nocodb-redis-url
  namespace: nocodb
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuaTBaT1RPa1BqMUtFcXk5
        cXF4V3UrU0dRN0JUa1g5VTNHUXlUcGJvb3pjCnEwTkF4MUZWZGdkMCsyWUZkWUds
        Q3g1elhFbmo0blNZbmlZa0x5V1oyWmcKLS0tIE9xbTRzYWs2UUM0c1N5OE5qb2g2
        OXlXL1FJZlp1WEtMM3BVVlFEdGNDTzQKN5k2OZEaTlniC54Xm4OeAkbsqgek8qBX
        503DE3qFNL/KuVKS1prDa6odMpUffn9XsDOfV8r489ybpzr8rNDaLA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
  encrypted_regex: ^(stringData)$
  lastmodified: "2026-03-19T04:33:36Z"
  mac: ENC[AES256_GCM,data:cugO8nDZfGSFWAY8MUD/qFb/noxXJuuiD4DPiCrlvD0q7MEgrkZ3bzv62RSNjhAPkuRzchosqpc4Ghfp9G0eK7wgNo+1p7C8aG9wEzWwMQ6RuCR+WyZVIOUFxGXrAqy0cps3uucpWsS3OqyST8e55BB0boXKZUSDWRO//ad55Do=,iv:uwa0l/yXXD5prTDAOJhqILVhzfQQhCl+AL2UBLmCd/Y=,tag:gbxfqfFbtu1rXJVa4Qe56Q==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: nocodb-redis-url
      stringData:
        password: ENC[AES256_GCM,data:XdQx7kCwkBgxoy1tGUKiwHoLym4=,iv:oycAppLPLVtVclOe7s/8fWToyAfBe6+cDmmlvvwHthk=,tag:CZ9SXjnvb+CUW1Q9v/7Gnw==,type:str]
