apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: nocodb-database
    namespace: nocodb
spec:
    secretTemplates:
        - name: nocodb-database
          stringData:
            password: ENC[AES256_GCM,data:i26xMnQuOzAzZRsL88dPljV4rqc=,iv:VqswJya/baUybj7Z8ER/EvG4g2phK6QPtoARKc3FLk4=,tag:wcWrBjZomnceDGOLAK7HGw==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbUJLV2NuNDJvOFEvTDZJ
            c3YyanZ4UUdkQldlVzN5ODB4QTA5RXpJN2tVCjdzT2wrYmdiSnplRHBIWWxveUFr
            Rm1qdGZpcXNOWCtvRDRvbEZCV25FOXcKLS0tIFBoOXVrK0I5WXBmczRvQkxOSStP
            M1pFdVVoMmNUdzZpMVJmcUZSd2piRlUKSvcC2I8NfvqGYQZe6/+IqqcGouiDxNFf
            gZUv99plOEradFsJCkHWWwlxF6/2mCdm18+ki6/XpryxJy0K1YcD2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T13:09:32Z"
    mac: ENC[AES256_GCM,data:wxtNnJ42n44UUVeKeCDNoA08/1U3JjY+0vM5oKln0nQIiJqUKEtP+WONa9x6t3CT7qUShW6RJHn8iAKI16KIuha7BZKhJvzI0T+tRKyuzKxQv8r3pU4r3O5Y4isGo6Fl+IC317yK7b1uvJiKI+HdHw8uF4n0m0ODKT4uaqP38Mc=,iv:zL1En6iDCasvYCohYSXqEAkrp6Kl0TKZF0k/Bs++Vrg=,tag:pZ+vR9n7snj05zaPx0a+4A==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
