apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: nocodb-jwt-secret
  namespace: nocodb
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0em13TUdBR1ZMZWRObzJn
        VUg5MFMwUWpENjI0VEx3NlU3TU5oQ0pLc3pJClAwalRUMzhCb1BCOTlFTWNuNCtR
        ZW9BMGVzczFHUTJvVnpZemN1WGlYNHcKLS0tIHRoSUtGR3IwbCsxRndSZ2U2N0ps
        QUQ3eDUzZWxSUzRPZTQ3S1dSdVgzYlEKnvHiWiGTYvpgnyMV1yugaMKJ1iJPV85Y
        pakYnJFiJ2zfREpz9F4a3Tcyc/pZCJB0gwg33tRGvP3nHLzY1nXGbQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
  encrypted_regex: ^(stringData)$
  lastmodified: "2026-03-24T14:04:33Z"
  mac: ENC[AES256_GCM,data:P3bU57VVoVCXA8cqAyh2+stbp/4V82a0KJd0qg6CKBFH3IaOSJO7A5HPPHtcGF1ps9S/HYnRk2YlKYRmWlJywPSdbnVSPWlxVw6rGg6n6hzc8Z/TEdTR47U1rNQvEOCEwKD18j9+PgFlH/kfE0MNkR7msa2sR1ZBE/TM64EY9ZA=,iv:jP5Bqkn9Sw+ywnybGZ1y7Yycg3TsxkplghbsEZpW5ZQ=,tag:17Bp9Dkx/aKC6zWx6n4IgQ==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: nocodb-jwt-secret
      stringData:
        NC_AUTH_JWT_SECRET: ENC[AES256_GCM,data:VIfrPTv9x6UiNSEDBhWTZddQu7b8mltidZ1ysKHv/RRFGONFL7hpa6a7gfWAuQY0HA8yPZWR/hbyxW4kyVxNwQ==,iv:SwyUAOV+HWdPDgLmQ3I+ThAbam54ovbApbCp+WzwnH0=,tag:YCaMLgZ0tCvxAy3nnbMNjg==,type:str]
