apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: nocodb-database
  namespace: nocodb
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcmc5T1RxdkIveVptV1I4
        TDVDeThtSFVZUit5TGt1ZW9URlJLRVM5bXo4Cm91Ni9jYlFMbGloT0VPN1FZalJX
        TXNtZnNqOUh5RVNJdEdTdlBJTUYxZDgKLS0tIEk0N2h3QkttbDFpTnc3VFJHZzhx
        RFM2VkVJaythWkU0bzNXZTl1dEN0eEUKxriKtpQgp/p4WGXnp+WQ5FiH0aTiomJM
        l4TOhbNQU3H/oG5PF8Txj5/um4DDlOWHsaua/3WlQYtltnv9+v7TrA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
  encrypted_regex: ^(stringData)$
  lastmodified: "2026-03-19T04:33:33Z"
  mac: ENC[AES256_GCM,data:YSfUuD3LdkcJS/9gOQAuWdByItsnY4bBm3ygJ1KKmi24/+ThElLyGYObkTvHUTY7fu+JzHv9ZXRa2KpzOXM0rqP3/mazZTbeaf6Zou3xKtQnvnLhOf4iORGA3yzbmvDkKlWxJlne7hhV0d1NuwWL/8D2tkunKZ0ATKGNq0Xz9ao=,iv:jC83sGpjm5mIFnog9hF2MeiQFh/I6xOeZKWDKAJ/rYI=,tag:WVMJPBHLhJhp7GRT2EDrVw==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: nocodb-database
      stringData:
        password: ENC[AES256_GCM,data:PG+UQlXprLedOIkxjx6eZlgM6wI=,iv:Iz07kzibUgaNH8HL/7Xfp5s9OhbstEXtPdy76ZPb3sk=,tag:3RbJGiI5LKGQuKyQTK4otg==,type:str]
