apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: nocodb-database
    namespace: nocodb
spec:
    secretTemplates:
        - name: nocodb-database
          stringData:
            password: ENC[AES256_GCM,data:HlMrhqQ4k98vuBJNb6IO5mOFraI=,iv:LKfuslleYszQ2zAyk+pYoMBk/I1M20w5uOdnlol9BQY=,tag:lF7a70aykNbEuOhxzjGReQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbExWcDFndWU0bzFZN0t4
            Rlk1UWtrWVpFVEtVOG0wNnFUTEx5dGtPQlZrCmRpR3ovQ2FwK2xyVURUYUp5dUd3
            RW5CTC9hREF5SUxGUVJ5NEF6VkhjKzAKLS0tIGFxL2MySStIdjd1Z2xCUk1DTGFS
            SVBHVDFWdXljTmp1R3JWTFlsTTU5a0kKQlVu/W0L6sUzo8Ga10ev2tnGiChGDZfI
            czM81Z+xH/DeLPkmNMO1WPuL5HqUo11t+KfhEHiFCEGBR3ink5xSaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-07T00:37:45Z"
    mac: ENC[AES256_GCM,data:jE5E44ae2O5UnVCTjNkqFhkO4KSRw3DmBCvzlqRI1i0Yh4pWaBcj4qLbT1rgHRmHAxNp1lPWkV7KvTpYWrh+LOQggNt8yKPd9gfrRw3sRgkQLV1Qh9mP4Qyxg/SB+dzgev9a8rKofNe/kBZ6uXVB70Q2CMO8dg5FtPQPJe01NMM=,iv:E4lucriXlApOXnq5BvuYSAcHgVpY1XHpSiE+gX5WbkY=,tag:5r1irRN9RuE5KLnSoCPc7w==,type:str]
    version: 3.13.1
