apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: nocodb-storage
    namespace: nocodb
spec:
    secretTemplates:
        - name: nocodb-storage
          stringData:
            accessKey: ENC[AES256_GCM,data:U5T1iPK8+AuTy0lWYO+yYouXp3Yc9e3Jpom9r4JEC/I=,iv:UUsm4L0hlbk7tzHB5Vf7ASMwvEuodkWWjdI3VAYrQKY=,tag:/vGM2GtyCJcHsmB5X9FaAg==,type:str]
            secretKey: ENC[AES256_GCM,data:ln/C+zZvJDWGoVU2lbsDpUChwmjK+4pnuxG7mYvrE1Q=,iv:U0nIxRwo4JKg0ISa6MkdwvNkMpJppoMYHn4+EZsOOjg=,tag:OMfCxHsHsXnlTlTEV97gww==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SkxvQUxQWjZEOVdhTm1q
            K1ZjQ0o1c2JFRUVnS3dzajBmUWhPOUZCK0ZrClZ0UDYxdEtsWlcvNStLK2tTYVE3
            YUFoajBSVzUya2VWcnBGTjNMVWtkeDQKLS0tIDNPNHNqRmMzMjJ4bnpXU09rbTVq
            d1VOdHBhNEx0TmJKT0dObElQSFd5ODgKUaM4d55xYiI92qzJv6RUXYkaQIafdXCO
            45sJIor3SG5r89EKYLb3hU32Ofekd6FE5Z5Wf8P59M6yJgsqzuwnZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-07T00:19:35Z"
    mac: ENC[AES256_GCM,data:XZVMeZaywYhg3OOkZMTkTuIrbkNHF5h7m1jf3et4yw75sciKaMUmvQXicxNZRt5YwB2Z/thi179SIRJut3e3v1kFrduOTBBRl3fW/Yoo0cxCie7+FrR4UBeJ0MD5ZAaDj/1pr3+p+2X9LtTMvGTZ8Yogu7Kkp6JcOFyrF2UWFGw=,iv:IwR7Vh4AVR8V7lVuqIJDgcehstlDM3jV/Hyq4h0QSnA=,tag:3tU3QHQ6wtwYV5NmAJbc1Q==,type:str]
    version: 3.13.1
