apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: nocodb-storage
    namespace: nocodb
spec:
    secretTemplates:
        - name: nocodb-storage
          stringData:
            accessKey: ENC[AES256_GCM,data:hhT+M5QDx8ED8pjqdA20T9QVg2ZgpzNUCWL4407W67E=,iv:kWN+eDn/QXV+iqC6khIi/Z/gHUG/I82l3pW/AjB/J5I=,tag:KE10l3GalMPDh+jvIBznyg==,type:str]
            secretKey: ENC[AES256_GCM,data:j2Uphu3hmA0lPnoWfxtKM7pbDd/DIv9Yar+fGpX4ilk=,iv:nHRfRGhAbrrNL+gEa5FbABNLxHFbA2Mz3Rqy7KekLHM=,tag:kq84ErxrmeN7s5G3pYZf5A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPaVhxdmNuVXpUNmVCZklj
            L1NPTnVCam53UEV4WVoyRmQ1UVp4d2VnODBRCkJLa1ZlV3hnYlAzelFHVVZrSTQ0
            enR4ek9yV0x3aXpDdGR5ZkxQamZuMFkKLS0tICtQQWRkdzFjOGhKcW95V0dFZ1F0
            VUZpMHhacVJiUHlTVi91blkwL211elkKud5IyM3IF2jivK9nYpA4qV7LbyAVhgMz
            U1E7bl29HyHMD5DV+fspj94lhy/y+wAc0ASe7WlOGuKcS6cJnJJ5kA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-21T02:16:27Z"
    mac: ENC[AES256_GCM,data:ALS6ckAw9zlHHCViqNID/0pJ2XYkYPw2i/55EniW6hPzPmnHpA5gkCeXpULaQkL+IkaoITbxNDq17bKxCVYr1WHfSiEP81F4lXNMXqtgP2WBwXZONLaJEYJIk6/SFHBn8BxAh+SlfkHE7IrX+rqpGUxoYTkfgE8Yo3mdY5u3AFQ=,iv:tpDFg9a3dJwGGPLjyEiJ+T33o+bCOZwQ1AZgtEUEhCQ=,tag:6WFmzod5OER2B+cKetnRPg==,type:str]
    version: 3.13.2
