apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: booklore-database-password
    namespace: booklore
spec:
    secretTemplates:
        - name: booklore-database-password
          stringData:
            password: ENC[AES256_GCM,data:emW/V8/9hVjYW4iuH0m0mIdfgM0=,iv:u4vdZX+LlBaQLbSgfjyQP41QUi/9tsfBb7olN/IFU8k=,tag:lBZ85vrbexutsJdRIy66SA==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3WEVUeVlTOEJocEpvb3po
            UG1DRlZYZjkxWkk0a0pFcUhiMmxnV05MZVU0CmRsMVJ5dGtBSUhQWjhsb1IyRW42
            cTVyZVA4UFpaR000cUNZTFplUjI4RzAKLS0tIDY5ei83eWFIejU4RGJEUWdQUyt0
            Zm1ma3VZWUF0a1RrNy9qazZxNS9ZVXMKKla57qkmlj3Oo1Z6/NbsuviV4hbQEAXC
            cDw78iuaYeAB26tNg+pOWbEdT8rB8ARIiX6+y9J+ec4BMkk2Im6VmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T03:40:53Z"
    mac: ENC[AES256_GCM,data:xn+jxEIkKr5hxRC5pgoe5zIdAGeqOBdwpkYGTyotx8eCQTtauCXmAHSqBOTz7T8ZzzRusPdNszqAyMR05wCkg95Lptjk54CQ2BLqWNaIU83DtGppXwfucPRqFGnmbHfuLRzvjkyxOkwy/zsd2udKfO0BXtCzbBxq/qq9sX5uWNY=,iv:3en8yzwHP//wdrf3KfGFhM5cI1nNa+kFyqpXrcqIOnA=,tag:hij55TlJd+JSCoUzNqJHcw==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
