apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: booklore-database-password
    namespace: booklore
spec:
    secretTemplates:
        - name: booklore-database-password
          stringData:
            password: ENC[AES256_GCM,data:woAXE9klQo7QjLsn1Ifv4QocDA0=,iv:HmxdsnjsUaJn3wGzG8dPZ3pNr2BsPxx1K8aBIDoutPg=,tag:dxWCuRNMrPBPsZpw0l6cMw==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTzVTdjJjK2U0clJtbkV0
            L21RYW1acWU2NzZ4UGtYanhXYzZDV04vQWkwClNycmFLa05GWmJlUGlzQzFxN0pi
            VFh3Tk0rNzdvNFFYc3Rub0ZMdTcrY00KLS0tIG9SZG80NlU5WFNsUW5uOC9UcVNa
            TmtiS1YzdGJzcTA3MHdqNG1FNHF2YUUKD1RzpgyaCwUUK4IjTFF+SAvs4Cwam1NL
            fW4w9Og38A1jSK4f48CQLELVNpI/h8zwbPWTJwMo0nAJAsiImbs+yQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T06:04:07Z"
    mac: ENC[AES256_GCM,data:11FzVFTW726I2cY1QVyArp8azbJmyVyjzQuYbBzhTR21M6dR2zNDKVqKWRWqZvSY2eN+KuYOJocePsOz8DrHfazdR99RGLhRxturH2XONi9Hf/jEbM3PV2Z4CXwQGf/jH8+e/Fnj1POg42/VXUm5uNy4WEXAj5YVNWRGAVDFlsE=,iv:rYtRiZ4xFl1yAH1/iN5Ok5RcSpoEJGFDg7qPHC3izts=,tag:UEEZsJmopsvzUP79XzGWZQ==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
