apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: booklore-database-password
    namespace: booklore
spec:
    secretTemplates:
        - name: booklore-database-password
          stringData:
            password: ENC[AES256_GCM,data:EUOsXCzA6q2VgBthgt9g7aB+q4M=,iv:5Y9kMAUSI1U6uEiglTs1WF0XjK6K840yD39+U4rMnIc=,tag:ARg8GFawFIoQ/xD3vtbWTA==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5S05sanV1UVlmRnJWT1hv
            NTJENGRveTdNWlNPZ3lPeWFadTIwVm9aQjN3CnVxWlB2QXRtcHBkTEY4OHRjNm5h
            K0JRTy8wZ2o1NlhvQ21wdXlWV1RpR1kKLS0tIFNRYnM0ZmJiVWlwQUdGZi9YMHdY
            eXg3OTlocHBaU3UyNmkyUTRpRFN0WFkKpbdxpm7hWG4ru/DJXE87b8sFyk9kpbSv
            wn2NdnmJRQp7Vee0VJnqtPrzlaZuo5V3M5zKLoNQrrVi63JiP4umEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T02:43:39Z"
    mac: ENC[AES256_GCM,data:0CoE/gi/KfEcKbEiX9wd0Jrq9MvO1l4s2UtVS4TaQv18x65L2DlQcvOf34AqCUOKxlwp3/TI5cz0mxGOQ/o2WCVuv/698Y92peSBxIIfkfWqV4LNy5Dxg59P0EingrsM41fxSkTDH/WLvHnErk5DXvZCoQXuVikwf2xWnlJJ+Wo=,iv:vE7dOCH47a9Q4X8hAvSkLl0/fxHFwHIk0Gu7P40A4Dw=,tag:Vpbt9rSmlFXvOO8EfJcaww==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
