apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: tube-archivist-es
    app.kubernetes.io/name: tube-archivist-es
    app.kubernetes.io/version: latest
  name: tube-archivist-es
  namespace: tube-archivist
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: tube-archivist-es
      app.kubernetes.io/name: tube-archivist-es
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: tube-archivist-es
        app.kubernetes.io/name: tube-archivist-es
    spec:
      automountServiceAccountToken: true
      containers:
        - env:
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx512m
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: "false"
            - name: path.repo
              value: /usr/share/elasticsearch/data/snapshot
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: tube-archivist-elastic-password
          image: bbilly1/tubearchivist-es:latest
          imagePullPolicy: IfNotPresent
          name: tube-archivist-es
          ports:
            - containerPort: 9200
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: es-data
      initContainers:
        - command:
            - sh
            - -c
            - chown -R 1000:1000 /usr/share/elasticsearch/data
          image: busybox:latest
          imagePullPolicy: IfNotPresent
          name: fix-es-data-permissions
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: es-data
      nodeSelector:
        kubernetes.io/hostname: edgenix
      serviceAccountName: default
      volumes:
        - name: es-data
          persistentVolumeClaim:
            claimName: tube-archivist-es-data
