apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tube-archivist-es-data
  namespace: tube-archivist
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn
