apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tube-archivist-tube-archivist-config
  namespace: tube-archivist
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
