apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tube-archivist-tube-archivist-cache
  namespace: tube-archivist
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: tube-archivist-tube-archivist-cache-nfs
