apiVersion: v1
kind: Service
metadata:
  name: tube-archivist-es
  namespace: tube-archivist
spec:
  ports:
    - name: http
      port: 9200
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: tube-archivist-es
    app.kubernetes.io/name: tube-archivist-es
  type: ClusterIP
