apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: tube-archivist-redis-con
    namespace: tube-archivist
spec:
    secretTemplates:
        - name: tube-archivist-redis-con
          stringData:
            connectionString: ENC[AES256_GCM,data:Q4eLHr3jfNP0gCot5hJRhkvPD1t64xAnI+PWKCrdej96OQzhOOTgb+5sgiSRlKP6,iv:CF4a7c1znZrGpna2UbeanTVjCyguBZl9TZx3lDKr33Y=,tag:VFxMbKWLDUJhSbHTbpb6ig==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvak4wZ082dUl2QXlXUE9I
            eXZvVmwzNnR0dGtlNnVTZ0JybGtTaWFuRHlJClI4M3BUMSs0TWV6UjFiT2FRZ2t0
            RGVaVC9VamJGeDZmdHM3bnhGTzhDWWMKLS0tIDVGVGE5aFZLanJCMm9SRlc2M1kr
            Mk1sRmVzbGhISzBaZ2RlQzN4ZGQzWHMKwukCb2kHQUsP6/eDLn2g/UFViVjmgio5
            k/HIIyks8mMgvL8pL2R+C4OZ8ZqUlN8woti3lYHObRo5nL+YoPUwgQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-08T02:33:19Z"
    mac: ENC[AES256_GCM,data:xGBn4ywirhZhkFg7z9RdAIzaL6QxphEoZs1rgUehEpj5rVocF0ukbzm14JSQo45NFe4ihD0XN0wyyrb4C3pq0/1sULN9VSg+ZoXHZ2HllO4FMahuSGMEejirG9j9uv7huRCzQb4wZul+nt9uYTBPqyQpBDmieEwRO8lqrDK9Kzk=,iv:xkZfSUCYEyqay9grxAPAdVkeKsLiFUTrtERffQNzfX0=,tag:fdAD5JWGxwuMB04fiJuHuA==,type:str]
    version: 3.13.3
