apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: tube-archivist-elastic-password
  namespace: tube-archivist
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbTBQN0RDb2ZtRW56SXRO
        d2RFc1hSQ3ZQOFJQb2FKcm5qRDFxSHdLdHpNCkJvL040SDlPai84NE9MYWxlNDhw
        U1UxMlQveGNSMXBsOHFDR2JTUklhTm8KLS0tIDNsS2dDZ3BrQVZudHVyanFqMFFl
        SXYxU01LUW4zTlpZWjVRR1RGVWVOZEEK87TZd2Qk1bjES7K9PutlQ6ssgUy2DJd0
        hCfMMrGAhHznTb1ti6HRjdT+Z2Aac5dJjspscuwL8gHSrdvG9+rokw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
  encrypted_regex: ^(stringData)$
  lastmodified: "2026-03-12T23:39:34Z"
  mac: ENC[AES256_GCM,data:UR0+YLaq2ZHgUTCLPLg7sTdmY57g7UD3yWaRrozI+hIvo7GcizINBXd2Y7gH6uCUeMDo9jRFWZms0yYATOj7JytxaWe1g/LRYDMPjqeJsjfNpT3LoOb1nlYFoDY96siVKBec+DdvQxvZzpmRgXcAJo3vv/uT0HTXpmMwiznRcYg=,iv:JNQg2cU4BSCVqd/ioeDEaPh1KJDh1belunV5fox3PPQ=,tag:akIUPNZRNR208xRbHcHSGw==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: tube-archivist-elastic-password
      stringData:
        password: ENC[AES256_GCM,data:u+wOLBHaPdk9mGWcGRwPX6bJEegjxDshKOtCwP1LZXg=,iv:CjLsQrD6/VkqE6r68JloNf3evdNVTlmJKl5B5uyqqfg=,tag:VcroOiXJn0wOtHtLDLHgUg==,type:str]
