apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: tube-archivist-redis-con
  namespace: tube-archivist
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUGpHTTBDUmlnVnNhamJU
        amFoS3liVE9sNjdlUmNYOWxaTzQwWmhsQ1ZvCjNta2h1RGZXNjcvbTdsUU1OOTZP
        anNVOFhXSlBweUJVSllBZkxqRlZKL3MKLS0tIFBVblo0WmtBUFJLL0cvU215ckNH
        Um1jUVZsMGo0a1p0WlpxeWJRZWpuV00K74Fq59O6yQbvavLDvhx66Kp/PdzJPJAv
        zJbjbpRz60XiDBTWrFUW37sJtw4wCox/+nnjftrBxPdouZTN9dw4RQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
  encrypted_regex: ^(stringData)$
  lastmodified: "2026-03-12T23:39:36Z"
  mac: ENC[AES256_GCM,data:XgyYS8ge2bdG3dRFt8XsSPXLaf7vnXB+jtZYcfL3g6xYusGMnJhdCngoCAomtY1yNMKMldiRUzbrv405TNTiM/hrgpICqWAEq96Oz6ai8qvG1QsyAfVC8DfzuG5yCbKGuq1QKRBGpTUZDJ0/Rl2RlVY2hfkgJihBBynRDpJTzbw=,iv:/59ioEhykM6NZuqqtzFgOMwV/e7/aoeI9tlKU2jWRtg=,tag:UwkC3KvmyGn7TUTzV8xncg==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: tube-archivist-redis-con
      stringData:
        connectionString: ENC[AES256_GCM,data:v1tmqJplQuo7DOV2C+JwLf0RPOrRdmAXDasI/8oWrggSHr9K1JC+P8kaLFrbo2y1,iv:57LtgBffzGyLrlXTNS9KKtnSLwzKNjFaonct3W3rHVM=,tag:umpEUHESrCvTyxG6VzmmAg==,type:str]
