apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: tube-archivist-auth
    namespace: tube-archivist
spec:
    secretTemplates:
        - name: tube-archivist-auth
          stringData:
            password: ENC[AES256_GCM,data:db+YgL3Dvp/lYkVYIRe7mfiMs5GF6gojXDFkVrx22HI=,iv:e2JSCyXoZBfy1851w1nGiwxx1D3twEDA9PwXisxzBYU=,tag:O8szI0YJ8zEumo88eXXMNg==,type:str]
            username: ENC[AES256_GCM,data:3+pYdg==,iv:b/64PUIkdonb+9ye2fcfvdgQJSUhf9yvyj/1owsfSIk=,tag:INsEPbkFQTc8QEIkrmBoLA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNzVBNFJnTlhVZjY0dzlz
            YTk2UVNlOXdrcWdrd3k2NHBVdzU4am1RVkdVClZ6UzZYbmlydzBWMUZwQVQzUllF
            YmdLYzk5ZjdqNG40NWJNMDFoWWhmNm8KLS0tIDdWV09mTUJoUGRuNzFOd1lvYVpT
            dGZ6N0Z6QjNhQldPcTlzaXBGb2JLQ0kKsmfhfsits8Y0gR9yrHH9QdWyHqO8AXPX
            xGh+JOz3YAluB67FDFhkBKMBifG6l5VA1xLrGrIpXELu25E+mjp3tw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-08T02:33:19Z"
    mac: ENC[AES256_GCM,data:MobUOiK2z1JxjiVet3Jlmv3p2u8VgDh1/8j/hIy4uzSPkx6rOmLdloxBL624Q3GID51jN9d1qJlL+kIKKAhFTGPk0HUmkji4JkXKBpXoLrYb3zDACbVx5Em1SBcSN1xgSQuDeFhQDZ2SejKM5X071NOidW5AlRxgx+ngd/L4Rr0=,iv:OZPiHB5XibJf+qtg85KdEhuM9kD9qC7EH06BtBimhK4=,tag:dLNunaOfBHcXvEEqH6T8AA==,type:str]
    version: 3.13.3
