apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: tube-archivist-elastic-password
    namespace: tube-archivist
spec:
    secretTemplates:
        - name: tube-archivist-elastic-password
          stringData:
            password: ENC[AES256_GCM,data:GoZswwXU09ak99YQWySFgfszOaw+LQSY/BkpEmS2S1E=,iv:YdgDLVSHJl9Iu9+GbiMepLJk7z+GeATJ0k2aO0T158A=,tag:Cwvtx5TX8URxCe+/7ev/cQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUVhxZ0VJUndGWFlIYzBx
            TUJiNDVaVlZGRUJSenc0WVUzVDBwUm1yOEhFCjIxQzl1dmxESDUvUld5dHp0QmYx
            KzhrM2xCNFFVR0dRbDI4ckQvVUJHYVEKLS0tIGo2RWlRbnYrQ2FybkdUd2FrNXRn
            TzlKL1R4eDg1d0FpNVI1MGlZd2lSeXMKMzXfpPEN/lPqolzTy0Apqi2U3HYHE4wg
            yb+LXmxnjk9qfusEI5bzA6Lk4Qhwx0zZjDV6UoDQ50fCAFaNu+cvVg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-08T02:33:19Z"
    mac: ENC[AES256_GCM,data:GYVfUdR1yTGzukM64+NOUf1XG3AF8O1pKQqApJKEbvozuFSTpjppnIRQFAF9M90uyoXkK0eapBNh8Pn8EGU38wejIoMxYEG7wMvZPFeqEvtco/B5pMpVLhSHvQE0uDMcpgkADmimiH4gNHsV3DET6mB1UjCW5Dvcjr5zfTNae9A=,iv:6YEcTQjplWgKLhD4n7YTsIynZ/qSKwMUlF74W/bkTOE=,tag:j5yMGbnYZoLYXoa9Pk9A6A==,type:str]
    version: 3.13.3
