apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: tube-archivist-auth
  namespace: tube-archivist
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndElQcUxxUDY0MTQ5YnJv
        YjIyeXN1SlMyc043Ui8vc1dsSjE3WWxqcENvCndpT3l2aUw3ZkxkMXlIWlo0N3Uy
        N2kxdXAxUnRZUjZLMEN5RFlyQVo4MzAKLS0tIDRBYjFzc3RrT21XQ1BTMHMvTGVj
        L2ZkNzdlT1AwSHYxN3NHTzMwdlB2akEKxcSllJ7z0AmNATj+X733fNSLO0c7dDyu
        0sMxPNG2rKnOQm5j9YFA05LI2et/tOWrkHaiIn2wtwu6XhHhyRzgCQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
  encrypted_regex: ^(stringData)$
  lastmodified: "2026-03-11T04:16:35Z"
  mac: ENC[AES256_GCM,data:gjqYtNl+r3j5aCtXjYXKZrCF/RA++Y5XPJO2R71howZPc+ZEMKKKh9If5fUP+KMQzzXddOFJR5i2U8A2dozCeG3qM9xOYpalrHFPIaDC7LKvOBtuAyed42VDOaST7Pyt+XhJ8WDSm90pLlY4mpg4hROv5aXwQJcXzCINqJzM/MY=,iv:/7KlKL+StijveOGjW3cqxnE/cadparUoEkXs+8V7PJU=,tag:kGCia7KssR5OhM7G66qCvg==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: tube-archivist-auth
      stringData:
        password: ENC[AES256_GCM,data:3lP6I2S88+fqVpTfLtbKcbHTtBA9M7PQCqQgSsXSZyg=,iv:0xDO8W+eghARUO4SfFX/9alUn2bYmBbi+zXn9qGS+Wk=,tag:3zn2XBkSgbVMN0Mq8vZr8Q==,type:str]
        username: ENC[AES256_GCM,data:zseceg==,iv:CRZzN9xVPFzKGq3Ga1hhyE0uxzJkWrnu3s9duqtaraE=,tag:AomHhS4xCm4g9qr4938DxA==,type:str]
