apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: tube-archivist-redis-con
    namespace: tube-archivist
spec:
    secretTemplates:
        - name: tube-archivist-redis-con
          stringData:
            connectionString: ENC[AES256_GCM,data:0zezXi55qBqUItRbpuVAIWfqLNZkpG81b9bl1xUDS5+pzeWL16WrM7QaZ1a3pZ+7,iv:KugMBwfUNSM4+tMgNdy+fhbwXudSV3AaL5xrgfM9dE4=,tag:KS/7hKWZulv45ps8m7+aEA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbDRiY2kzNFhUbVlYUm9a
            VkVNVTZBeUtTUUUzeHVka09UMjJZR1Y5a2dNCm1pWGNkK0VWRmNJSW56WElHSmtn
            Q3RIMVFDb3cvN0dnQnFMTmdNMkVyUFkKLS0tIE84N0huVm5reHcvd1NwVGQxbjZn
            TmlXV0tyR0ZJRW56Y3k5N0RUWFJ2TTgKEtuzGtGlvxjUugWb9Ly4uuD4GRLdUE7c
            P7wiYoiWIjv3Li5oWy01N3OQSjb81d80o3FOFLxZj2c/evH0LZjsTA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-08T03:26:53Z"
    mac: ENC[AES256_GCM,data:FmSPYaFfD2DXGfia8oEHNx5IqAhLRXSHyFmN3NWtrSyO3tl2E2lnkvOgerpa6DJ09/mELxczvIuGpqtxpBRbmMwC0wcTVtMh8EK6R0qdHxydOOKarZDKEpmwJXbC0u8J8SkX2G6i1opVvpjOgmAv9f4SQrYii0linKORHwxI9fI=,iv:p2cMiydpVhnFiSxJwnsYWzENzm0PsBSyGDyq5Ux9BMk=,tag:s6HvVQ7gkH1NPuf/Jgvcfw==,type:str]
    version: 3.13.3
