apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: tube-archivist-elastic-password
  namespace: tube-archivist
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyM0dPbjlhOGtURS9UNGNt
        MjJVQjRKbUZ6bms0TEg4bytJOGUxOGp2emtvCm12ZmVwNCtUVUpxZVg5TXYwU3FG
        d0ZrNTlNNTZEWW9zeTVwQUNxdFlyTkEKLS0tIG9kaHFZNTRGN2l4eUthOXN0RzNK
        ek1hRVFzS2xJNDZCU0l3bno4SkZXVEEKRthDUMugIAlAGuLH4wyNNcxHx6T8U08P
        T+mi4Cyi18bH5RO/+aCcFaSxtsOmZnSsvOzJScZskSsGrkzAvSZkKA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
  encrypted_regex: ^(stringData)$
  lastmodified: "2026-03-11T04:16:37Z"
  mac: ENC[AES256_GCM,data:uBQ5krIeZToyH7DkF7vi4iMMLN/chqGpFcgOPMxPSRI1+TisFn1Y09MSUixQ/ezNKUceLISu4gnQmXK+moQda/JH7MU55Ust1fkWmGX41Kv+7vH7flDTuZXRxgUbpinH4GHwSzFrJHbCukuYXYvyMsPfcG2on90+BH75zB82TTg=,iv:Z0CUg87fYKu/i+fic9HK7OLt59wV4+03hLMd38ZfoCo=,tag:4qipriwYBRqqgo5NgOAyDw==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: tube-archivist-elastic-password
      stringData:
        password: ENC[AES256_GCM,data:Qy/cFkOM9+y+pk//AQYVehPnTXUhlC42Hf4gxcw5snk=,iv:mBn33Laee5gQYWe1Vwdx8TV50sCbrZxPY37yE5lB0Ao=,tag:75D70wmzNvq7dNIiztQrFw==,type:str]
