apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: tube-archivist-auth
  namespace: tube-archivist
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdkczYmdIblNKTmlPaU5k
        eG9HVXBWL1BnZmFkb2lZdGFRV1IrTlRyVW1BCnFOcmwrOWxMbWpCVlFSb3NPK2cr
        b0RyaTZabUZsb2lORDdaSE9YdUNmOE0KLS0tIGRyOFJZT0RRUzNTdkdYVXd1cjFH
        bXFZQ0VYMlluVEpnN0s3ZzJFczlqbzgKDBIfq2T9+fTr5WKm/RtA2dpb07OA45co
        GlXUx5B+RP4QyIcK6IRrczEjexvm542XJNHKENUmBJpQeyXjzhKPaA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
  encrypted_regex: ^(stringData)$
  lastmodified: "2026-03-11T21:43:17Z"
  mac: ENC[AES256_GCM,data:RIPY0wShmtEFE89o9RpaG52G5CM6oYBXmRzQtNLPWvsrHA/i3r2YGgSioskQ+XG1+itDwfxbyK+hyt9M0pepeCD5cOL8kVCRwf+IBMnrDGI7SvkpExXnjTx/jnjLEX6cT1Bn0Oykm3U+P1qnenAS53MPzKCQgmAgts93WOTcASY=,iv:6+ouFPWi8Jh0iWAndMVzdNcoKoaJn4Xv/91aEDUxhpA=,tag:o6JQMu4VVQraRIXJ25pFFA==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: tube-archivist-auth
      stringData:
        password: ENC[AES256_GCM,data:JAab3/vTyxu3zK04X1MKRWf8eu4NronG5t0bJa46bio=,iv:vC7ubCtTLLJmTF4wRYMd5C2Bzyeks0drVSbRH06bWME=,tag:J+ZEMJ6yw4ts03/0OSN6Ew==,type:str]
        username: ENC[AES256_GCM,data:EZNDkw==,iv:sUiYPw1mG7EkZ8KbjhsAuKU50qdlKtR+f/w794Dpd3E=,tag:w0B9cZskUU355hZbwdOqJw==,type:str]
