apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: nostrarchives-db
    namespace: nostrarchives
spec:
    secretTemplates:
        - name: nostrarchives-db
          stringData:
            DATABASE_URL: ENC[AES256_GCM,data:hWWqV4zKvnQAI0VdJS+mwaxQTR3Mx0zoBdn59GBJJrd6HdR8BmDIziFIn2dHwYQ7qcgmT5XAXsrSUM+V3DE/vvUBnytBUDCMQifeEApS3zsjanQEczFlkHjmUc0EM2/z8kxcBA==,iv:VgZJvXJmpj610NG1YvC8RDQD9XA0/odSbNBoBd0j33Y=,tag:OELzmjW1BBweM4CGB9l3Hg==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVEF3N0Q4czVlaG5EYllS
            Umh2c0ZScFN3Q09XelhWN09jMUxVZWpxcTFFCkhTOGdreGJVRE9FOEJSaDV5azR4
            d2lucE03dG14Uk1UaWFsRnRoMEVqNm8KLS0tIEk3ZEdZYURmSy9NaSt0WHc0THlV
            VlFBKzFDQ1JhQVJ5aEVCUERUTkE2Q3MKcjCfF275uuLuGvi8iYGbVus7wR2pIhca
            ndlx/qt3WB9syiYUt8pIa+Laxz8bFhIMqegytudpbE+QvCFmwQv3+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T17:15:08Z"
    mac: ENC[AES256_GCM,data:II9ZPFirGb/J+/oU/YbFvxRNTC+uE9kuRFcjxSX/k4vuupiZA/H87HRF8zj/rKpoL0vbapuftnLjeC6rklRU2Bp9SxPCEXNDO47AYC0wPJ9KMQvrJ1Trd5QDYVPqe+tZsYoF+K8R8Ue5Ed6SXbGDPWDhF4jUFr/0nJNzhdz5ZRo=,iv:hyH04ia3oIvXS/LdzRPKuBq1Vvd97ichKBuq9Kt6cCU=,tag:rZhvIrpAMqe4M0rmAhpXSA==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
