apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: nostrarchives-redis
    namespace: nostrarchives
spec:
    secretTemplates:
        - name: nostrarchives-redis
          stringData:
            REDIS_URL: ENC[AES256_GCM,data:1M98MbfuptGY3outqgaa5KG611JIlBLnA78PFsISiJyE6EDNu3BgUi63Aimy4xbjpCPNp2/511SZU4FBZDw=,iv:tOOQ4GbppVetvv/bs2Gw8+n3Qmr7w2G8dy4z4RB0R1Y=,tag:lbWmvB8zJqsh4qfo7tx4gw==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2QWhaVnBxR000eXNMNW9W
            SWwyZTVpbGhMSytqcWxLM08wVk9qQ3pnWWs4CkhDUzBGRDV4TlBldzJWWXVjb1ls
            R1gzcm1OK3pwVTdaaFgreW01K05yMncKLS0tIHJZbUU0ZW5CVGRnNkRxOSsvSGdv
            RlkzWEhVYlJqbzZXR25odlptMVNNMEkKfJVqJ85nJojZHGh0t7IHt8wq2HZCoNpK
            pK3HXrJorG3ryHrEi9YVuumuIDVf4AdE5AAvrqBlP3eJ16iw3GSOHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T20:11:04Z"
    mac: ENC[AES256_GCM,data:hEfYnaV0yNdDnj3OuMqSjmDNiyPR4NXJkmK3fRjkD14fduzckAL9JqOhuXMHeuni19DZJMllqcPetrW+y05IkpHS/0y0sBRteoz9bqs+LzaRcWAUV60BrajG590Pq8qLYWU6uRcvisQtLpkwTDxZ8UQccITom6nEqUTGhcmQMG4=,iv:lZmp5UvkhuuP88i123BFfkxvUzTIU765gAzVa1rhAG8=,tag:jImnNWjmG+ajEk+nzUv9kg==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
