apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: nostrarchives-redis
    namespace: nostrarchives
spec:
    secretTemplates:
        - name: nostrarchives-redis
          stringData:
            REDIS_URL: ENC[AES256_GCM,data:QlzTHPHq4ucBxZ/LnqHaTMES20tQ1kdDNPnlQc8I/C3aCNeIdFnAemyU4uo9VoVeq1iCR9cvLsKTE7X/kK4=,iv:CT7IRJcj5NEjFdOsUFJtTShQgb9EiSQC97GwD2J8EGY=,tag:E03VBBKfJBvc93iEMX3qpw==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJcFptSjBBSFVseDYwYUtR
            ekgrcXd3WFcyUHBraFk0VkVmTnFtMmN6TjJvCnZqQ3VwUEtQSTVjZFJqRy9VTDlS
            YWhDMFdKUDYwL3pIVlZnZjFpNmN0Y1EKLS0tIFpqdTF0MGlpZm5YZWR5b0lHQVNC
            K1VWK2hIUTAyWlRnY2lZZjVib2VmT0UKz9tTUa/Efb3Ulo3InTQ3U/EqDouP2Y6Q
            tukqVCDTvBQevVLqUa055Xd05NTSkVIEudVlLNfmnu1CdEDR8GDQeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T12:54:17Z"
    mac: ENC[AES256_GCM,data:uX9HfOSXvKZzFhqMjOdW8s3/auSCOtNqmDMT6DD3sgJ5GeIQt5OQ2QDEl0lciE7vQCqoST78/L3vkVCUfOzxDDFMf08LOKxhYcI5aTWuEeXDUJ2DXaT/ig8YEAxhiZ+AKnW7t2nxmgOwUpdpjl1WtVlIL3OiCUjSMjfNkQt6mBw=,iv:5Ih7crj69lgceJtm4Zu//MoSb/1fFukr91c0iyFoESE=,tag:jxjIt9zUZViOAfdx0PcPPA==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
