apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: nostrarchives-db
    namespace: nostrarchives
spec:
    secretTemplates:
        - name: nostrarchives-db
          stringData:
            DATABASE_URL: ENC[AES256_GCM,data:2T464NEPrfAbz+IYG5Lho5k5ns3eCNG2XSL1dZN8/0j5qjSOP9o5vnwGekaDc9VS0IeSDVYx/zndc/DWP11oOfglwePqhJAGioV23NHp0g/PyOJcDibXQfuAS5qH/N6S9j8qIA==,iv:YoAS4UJVWGau8/kvr+LgtRwbCFMi46tsY6s/SReVcEo=,tag:q6gXwpnWHc+v0x0GKXihOQ==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMm9MQm5qY1JQVUl1bjVh
            QVVobTFWdmNuN3g4a1pXaUs5WnBzUHdFRlhzClBYTldRaUp5cklRT3R1NEZDMFo2
            N2FCdDBWUlluSVh0WGVsS3dJQkIrNm8KLS0tIGhldldaNGtjd3N2WUhzWTJIYytu
            aUFmQk5ldHpmcXZoVjltYy9qME9IejgKDlgb1CNegk9iIyv50wiOOLSkgECC/6D8
            Qm/js4fRHQWd4CzpOELyGFUP67QKgf/LkoeKzuOmb332uL1C3WWGaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T19:05:35Z"
    mac: ENC[AES256_GCM,data:0HCyf/fVuK4Eyl/AfpE7DaNLgjCAHn0fxOoWgExX+/3WichM7kpiPCJZ2Sqg+nZmwnD2YzAwH5spW1mtL9UKuNTQfyQ95OG8tjFxCIIHT9nFCmQKaVYIB2hFBBi2KMIDndtUJ6YvgKdmsTheUgPsn4aCyAFV7rMys3Ag89tBi1A=,iv:3d7va3KNgFb84Pbk5sWqyTe69037OoqPRfGCjcEkYUI=,tag:vizEWkJteLsdEr0V1Z2Jwg==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
