apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: nostrarchives-redis
    namespace: nostrarchives
spec:
    secretTemplates:
        - name: nostrarchives-redis
          stringData:
            REDIS_URL: ENC[AES256_GCM,data:htoSrcdIdciDpkMplOWAxNhT7VsPg8lBh4O12LC5ZTHUjUpuiXvCD8X//tQ3E0SOAuDzYRBRJGkyorkpBuQ=,iv:3rJLFUOOI72ybwx5i96/mpmVHpzrmImM7q6mFqbPGVk=,tag:THMp1swpg0HUoUyYHziJzA==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwT0FiSkp2bDVYM3VEMEov
            dTJ5NDFicmc3VVFkc01wUEE5c2RTS01lWHc0CmM4Tkw3OTBYYzhwcjJyN1lkTzE3
            UWtiNE5DenZvUlNLa2pzWWw5eEU0TlUKLS0tIGdXemZyYnRLbm0xajI3cGY2SFkw
            Z3NtaW45NDF6ek5pbS9oM2FoV1RWTlUKbza+ZGg/JR/YWVjal+tr+tnqyUdoVKrl
            yq7keKD0ino3QfK63rLse0KWRtEg0gcOKl+SssFwWZis4nqiWOel4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T17:15:08Z"
    mac: ENC[AES256_GCM,data:AN9QsOpAjdji4ZpyD8ejbH6NdFUlTXZulImwja1ISlYGfznvCB+6i4d3kZA9TFJgEEIrqpi4r/oOO8axpKvidW5ytUFh5jweFdZ+9tyBtIjW13HL9tlBIC2ths8BKLD5LMRHe+so/5tqLuAgQvVj4kSc0tpI8V72oxm0A3lCBa8=,iv:eg77M13LYsm8XHwmApkX1MRkW4bZ40poIDVOQ+GaJyo=,tag:hAheiQDpDpwIN+Iq2ADHjQ==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
