apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: nostrarchives-db
    namespace: nostrarchives
spec:
    secretTemplates:
        - name: nostrarchives-db
          stringData:
            DATABASE_URL: ENC[AES256_GCM,data:GWQMCqeK2MAjeHNSDYNlgNIVjqQ3L0fT04VS2pKouIt6dhE473lhKiFHpCF8terxCzXjfJtPXy8P9SUL6lNr8aPgzSjzW1imRUBaZQfSxJcU7wMvGVAus94jC5yjo8Ihp2p2xQ==,iv:gOAu4zMylBCxf7nT9Fg8pySn3ievSHZ1/DOaQ1qHiDM=,tag:I6BhMzjPfRHNG3DgBCoh1Q==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4RkJUQXdKbU9lRk1LM29V
            VTBVc2Z6Vlo5dU9GRHRyRFF0N1FoeVptMEJRCjVQbThEelNrb2dwNmRXbWlWUW85
            NkNmTktVTlNRUEVrUm42QThEMmdhU0kKLS0tIGtlTWlnajdLVlJiZEdjdUZhYXp3
            MEF2K1ZralhKMExMay9mSFd5SXZPeVEKX8KSI6wgH2Uy6kv0s9wl8e1gHHdDwfs7
            etwPMjyF6G3CsOnRw86DApBIh0nekeS5BoJzv+HfTS2KpmAxbxjXsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T23:45:30Z"
    mac: ENC[AES256_GCM,data:2qR83tBI2SD/f7cInigvUV7w1mSM9KdFiBNQ2mPkcTZj4/uAEd5+gTSTmA5Hf6GRvq6WfixFFzOYbpAiVjCVPQIJMH2I2QMcjNJ39xR8nwR7E0S2OeE94nNQpwSHaDNpVyFwsbCaiapq1PElAw6Rz1jGnaUgO/ZVBNC/zC4ytII=,iv:tfE9eTVXBSuUWXqmjlW1vdSelhDA4yx5mCI1CpWNkdU=,tag:q+uYDAXqUkaXHclP1YJrBw==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
