apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fileflows-fileflows-media-movies
  namespace: fileflows
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: fileflows-fileflows-media-movies-nfs
