apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fileflows-fileflows-temp
  namespace: fileflows
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn
