apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: rustfs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rustfs
    app.kubernetes.io/version: 1.0.0-alpha.85
    helm.sh/chart: rustfs-0.0.85
  name: rustfs
  namespace: rustfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: rustfs
      app.kubernetes.io/name: rustfs
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: rustfs
        app.kubernetes.io/name: rustfs
    spec:
      containers:
        - command:
            - /usr/bin/rustfs
          envFrom:
            - configMapRef:
                name: rustfs-config
            - secretRef:
                name: rustfs-credentials
          image: rustfs/rustfs:1.0.0-alpha.85
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: endpoint
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          name: rustfs
          ports:
            - containerPort: 9000
              name: endpoint
            - containerPort: 9001
              name: console
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health/ready
              port: endpoint
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          volumeMounts:
            - mountPath: /logs
              name: logs
              subPath: logs
            - mountPath: /data
              name: data
      imagePullSecrets: []
      initContainers:
        - command:
            - sh
            - -c
            - |
              mkdir -p /data /mnt/rustfs/logs
              chmod 755 /mnt/rustfs/logs
          image: busybox:stable
          imagePullPolicy: IfNotPresent
          name: init-step
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /mnt/rustfs
              name: logs
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsUser: 10001
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: rustfs-logs
        - name: data
          persistentVolumeClaim:
            claimName: rustfs-data
