apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: rustfs-api
  namespace: rustfs
spec:
  ingressClassName: traefik
  rules:
    - host: api-rustfs.home.kronkltd.net
      http:
        paths:
          - backend:
              service:
                name: rustfs-svc
                port:
                  name: endpoint
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - api-rustfs.home.kronkltd.net
      secretName: rustfs-api-tls
