apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: rustfs-local
  namespace: rustfs
spec:
  ingressClassName: traefik
  rules:
    - host: rustfs.home.kronkltd.net
      http:
        paths:
          - backend:
              service:
                name: rustfs
                port:
                  name: http
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - rustfs.home.kronkltd.net
      secretName: rustfs-local-tls
