apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    helm.sh/resource-policy: keep
  labels: {}
  name: rustfs-logs
  namespace: rustfs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
