apiVersion: v1
kind: Pod
metadata:
  annotations:
    helm.sh/hook: test
  labels:
    app.kubernetes.io/instance: rustfs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rustfs
    app.kubernetes.io/version: 1.0.0-alpha.85
    helm.sh/chart: rustfs-0.0.85
  name: rustfs-test-connection
  namespace: rustfs
spec:
  containers:
    - args:
        - -O
        - /dev/null
        - rustfs-svc:9000/health
      command:
        - wget
      image: busybox:stable
      imagePullPolicy: IfNotPresent
      name: wget
  restartPolicy: Never
