apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: rustfs-credentials
    namespace: rustfs
spec:
    secretTemplates:
        - name: rustfs-credentials
          stringData:
            RUSTFS_ACCESS_KEY: ENC[AES256_GCM,data:t22bn+XV6xAMtl61XuTBnj/5M1tIq0wacxuI7yXep4s=,iv:616H77eWC8RhhXdixNuc2kNTVBI8AicB7lrIBSFebVM=,tag:rq5lNX0uUkuQRsM8AEUSdA==,type:str]
            RUSTFS_SECRET_KEY: ENC[AES256_GCM,data:GjSMGA7edpiXocA68uq51X5zQ+r6gyF7MHix4298Eok=,iv:dxwStqvnTulMN6I/ETbGtIMF5UFCAzwc8LJX5u0dduM=,tag:zvABtU8BD7gpf2bFbrgEJQ==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbDdXZnRYbldSbTlYL25D
            aHNMbkJNQkEvZzhRVlNyYjB4cnR6WEZmQVhBCkpzVTFWMlI4cXUxQ0VYRzF0YTBv
            SWhOak9FcXZkcHZWdHZ2bUp5MWptWkEKLS0tIFhTeEQzUFF2NVhMZHgxQVpxNjF1
            RTJZckRWUzluUWVUR1FsK0lObWhuaE0KV3+60WVMjZlGTPsivzgTm7JrNTiYzHke
            BcHlgwXYOCta5j20maswIwzwOcx+xs3pnCuppmeFJ0rs8a+b1w9Z2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T15:54:21Z"
    mac: ENC[AES256_GCM,data:nNppz5uyYd37hO3Fz8ImZJjBoSSDkqqF9TG9Ww5pFyQSApKSqJqPix0E8GkiVR7Qdo5ZvcxZ3v+D9C6ttQ0IL1mkhcFIcSi2/1h2WxSq+d/05/2zE5hWkl8HQeGluevgjWGqTw5ZxtgOn5UWL0CM6xeFiz9CLims4ciqFGgqFb8=,iv:3AVuS5YtEIY8fLk9qNVI7BZqQAoSCmRja6JLcevNibY=,tag:cwTHkeGbpuJDbpGs67eN9Q==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
