apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: rustfs-credentials
    namespace: rustfs
spec:
    secretTemplates:
        - name: rustfs-credentials
          stringData:
            RUSTFS_ACCESS_KEY: ENC[AES256_GCM,data:UXEhUL5FMESImTuR7l2BpDevYgY4X3357RZ3SmPoe8c=,iv:eQn48HoPXYLX8yuOkyXU2UhsIN6/m1xMc/2O4AN8cWc=,tag:wYpnWXi9Pfjyr+7yISReWQ==,type:str]
            RUSTFS_SECRET_KEY: ENC[AES256_GCM,data:tA9vAx2xILv4/SC/d2tTe9EgLfEDakdr5voQwV5yHeg=,iv:tBVOfgfyKnBY1kZJgCufNstGaT72HP2o8AMnklUbDWA=,tag:tTj5wRo+O76ITua6SYSt8Q==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bjU1SElKS0lOL3p0WTcv
            aEt4dnNBVXRGcnNOOWJ3NzI5cjZvazdZcVhNCjE3UHNMV21KbG5pSFYxK01jMVpi
            V1dFaGFZN2h2UHNiTmRQNVZHREcyOFkKLS0tIC95Q0M5NmxrY0YxTVZVMGZndHV2
            N1VLWU9oMUNwTW1tQ3hheCtydFR1NVUKMZ6+RAQzmmbdexHSsB1EryRCRUPB2EoC
            FBGcCYfdNgzFkcO49nLqLTwXJPijf1XpuZuzIV+Jgq/FQG2H4N9Z0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T15:02:55Z"
    mac: ENC[AES256_GCM,data:kyrFlNLipqkfLa8nwOJx4/U/y1cQaEBVMyw9W01Z7DY/ndPazTB0HLr+g4PeQu6mJpbu6dNxQzB5dlBBP80fHfs0cxBGrpkrXY/1GcGEN7ZJXwOpKWRL7vM0YiEP9a4F0dUOU9/jIZl6X3OqXFNrmYnUp9volIBUKrpFRvHntmk=,iv:hJogCLlOK85RtOU3gcvmrTnZQX+4ZZYN4iD5h2y8TcM=,tag:joRFzp11V7ouZJC7TinT2Q==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
