apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: rustfs-credentials
    namespace: rustfs
spec:
    secretTemplates:
        - name: rustfs-credentials
          stringData:
            RUSTFS_ACCESS_KEY: ENC[AES256_GCM,data:KOwRPe50GqTKuXD9VIBcnG7Rpwmyg2EgMuBDKyFLneA=,iv:hk8LqVK/HmPblv9jZz8im0ZAWHUUMPD3tcEW7pH+l68=,tag:ACaXFR5iM5oDzYSGgghwKQ==,type:str]
            RUSTFS_SECRET_KEY: ENC[AES256_GCM,data:KzB64HqDDyxyNGVNXha+CwG8r2uWnkBUCkGug+jviAM=,iv:rwCQL1zpcx+lIecZEpeHBbSechAgorbxnji7MPGdn6A=,tag:U/b7hy1Lc+stKf3RCkxrqg==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSlBYaE5wSXNocGlGTi9j
            MWVEZVFqVUw0bEtUWGplVGhtaGY0aDlEWG1JCjhTMnlaK1drZXN6WElQMzZXT3pw
            cFlXMEhPQUdmMWhSK3JCM2VnVGRhSUkKLS0tIER2UHFTR1l2dW1kam5LM253K2Y0
            Q0VuT2pOUzVXdGNtTnI5RHVPMEJ5L1EKN/6elVadJOlWQiRu9bqy4CU+LtqTPNAv
            SV7BbxMkLeYoL6p0/YpwFp2XDHExt+MUHna/e3dlACZDKDs8mVuBAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T15:14:24Z"
    mac: ENC[AES256_GCM,data:t+4f1ZFnk9PkwaTtFyW0Mao78qBfgZIdxwRwlQQEYIJZhCNUABm+bqtAaTBO+3oEV/IUl5j5AqlmQ4KYQJoHxeUrmgLt+R4BwV8eVzovVwwc1HQGdvlede/iC/2O/VhcwDdrKdy8k7r6zloxjy1ItClXrBuXc09Qtu7SW2w8WYU=,iv:rpBcXVBgzBBp+255c/UOqyDNCXvpPOujl6lb6mm8bYI=,tag:mxmNOGf7nm+FKptyAtZO/w==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
