apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
spec:
    secretTemplates:
        - name: cloudflare-api-token
          stringData:
            api-token: ENC[AES256_GCM,data:ZJFukrjfP687PVQ7WDSBSa6rMz9rl1xpcweioC8SWL8h7y9gnc8+aDt+ianUQWHO8ADj0uo=,iv:TCmM1znVre0m0wst9qgxx0P5nqxnngwi/UlsnmiM/xk=,tag:x7dhlz2om6/h6b4FofJb8w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLM3VUQ2ZCQTRVK2FESFor
            eUhiMkZXK0VTbWFXUW1ib2VjdVZMZHU4d0RrCkY4dGova0VydmM4cWdPdjluOWJj
            L2NJYVVtek4wem8rYWFZeGY2cHplTDAKLS0tIGhWSjZEOTRGdjY0bzFFdkZiVElr
            WmhxMHdzL3ZYc2o2TFR6aGRSbkl2alkKWOcj8x+QifJTZ2WucTuDgEGmSdvPds1K
            alZZyDnn4ytJyZJelIvd5M3emsYzHY9slggpeuDYzh1FRuSq/KMPig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-05-27T22:51:27Z"
    mac: ENC[AES256_GCM,data:t35JbLa9rgdDE809V/Szbpd/XMbG7zZBtWkv5j86vxaI22uVyV9fovzcd2tRkuMxDOUUJEOeXfYSf6iZDncnMmMVjR1XlxmSvB1QHBSGp+GNTwXyV0ICqNOLrEShYk87tPozK/OM8Z3hHX4o2EkGYle0tU+NGDZjp8z5GALUXT0=,iv:hVWyiAWrESlbpPYR8w6cIwHVySiqbLT5t6xNSmdl4yI=,tag:UjKwlQrcb0fF8JLmCXLpSQ==,type:str]
    version: 3.13.1
