apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
spec:
    secretTemplates:
        - name: cloudflare-api-token
          stringData:
            api-token: ENC[AES256_GCM,data:PCoUplFIybstjVLY28Q8oZvPJoeRItXAH2OnXhKHwg6+fI1cIGpz386zH1Bhml1VIcww10g=,iv:76+DsFsCd0H9+5AZfjfRtcLVBUvC8SiPIbU+bKc4RDI=,tag:hhA0ImY2m2x/X/oilMK6ZQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Q3pON3U1WGx5TUUzNEcr
            TVNjdTZqUmx5ZnM4WUZEVUdRUERZNGJJclNJCjMxa1R3R0VlallkY1hobjVDWTZR
            SWljcmpxeDZaMnQzUVpIVXRSVjRURU0KLS0tIFdHZUMzdUVBUGgyQnFPN1UzM3FL
            VnM1RXl2dTQ5U1dnUjhNNk5TVnA1bmsKPOmRq67LJxIi4j5O6+SC7FUtxnskMFik
            yCfd5c/9/PdLuPo7kg8W8GvfWEeCdePNDoXUBNivZXdO/L1yRDTcOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-05-29T12:14:26Z"
    mac: ENC[AES256_GCM,data:5lSVy2JWc0BkdxFgssQi353UMcA6atkfXDApugz/qvQAwoq67DubIEFF+Gvleol7QuFkHSedFDsxldtRfy3wqiuxuAKEUK3mfycRfbypjUoggqLo8qDEDMlm05CCzoiEZ3RYVYpRs+3XVAWaFc5F17eMFNcdAOhp904oJT7CnSs=,iv:FakfMlPVn4/RtOv9+gcEeVToj5vWXrm76yeBUoUB7T8=,tag:UvcpZAkTGgYknmWD4RHecg==,type:str]
    version: 3.13.1
