apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
spec:
    secretTemplates:
        - name: cloudflare-api-token
          stringData:
            api-token: ENC[AES256_GCM,data:2j/RXuWxX+vvG3v5QArWXbz9xNZQf4yfS1mXl7IMCO/zaM749prkS5pXsGrDyEvXMeCW18Y=,iv:LrpXbgfdigR1IuqWXTn22vy+wGNnrV4p4cvvQHc/Iik=,tag:d3F/a2qE+9SG1L2CYhm/Rw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MktwamJ6TG5Cb0FXaEZ5
            Mm5FTEdZalk5MVpteGowT3BlcUJJR1Z3clFFCjFSajJLN1NTSGxucC9qbE9YL0pY
            UlBVSHM0MFhmUHBBNGtSbnRvaUg1cFkKLS0tIG5mdlJEZEtlbXBuMUNiZDFMbWZZ
            V3JMZjIxemprYjZySnlpMUUwTENrRFkKde/eL0ekmE/3tvIqqpuFWk8+RRcLhhD1
            8fUhH/ae4gP4tdVBZFRtw3RIaoanGOdXPmdyV5pI8xZloDnCN9biGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-05-25T02:57:53Z"
    mac: ENC[AES256_GCM,data:vuwn3X+GLVAgGDtzSPYJhK9IAb6NkJ/gpIHQXuab6LHxJ0hDdllMWGfwfdpUhj77bmjsi053gwA+oP2jb//mVSvMQHsbE5zN52PjtTcGwE3Ir5qEX6z9F01OILGaBCmQ94kg6ILouC2DTwNF72UEd0+EKpTVW5Kym7BngVdgGiA=,iv:QXxQn7mvEuN8s8rB19rueQx9bl7VIswjirG9R062mSk=,tag:BsqHYPuP9t+TlpyI8QJLUQ==,type:str]
    version: 3.13.0
