apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: soularr-soularr-downloads
  namespace: soularr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: soularr-soularr-downloads-nfs
