apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
  name: soularr-soularr-config-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      dataEngine: v1
      dataLocality: disabled
      disableRevisionCounter: "true"
      fromBackup: ""
      fsType: ext4
      numberOfReplicas: "1"
      staleReplicaTimeout: "30"
      unmapMarkSnapChainRemoved: ignored
    volumeHandle: pvc-25589b0e-1276-441e-a91a-2e4e78ec378c
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
