apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: soularr-slskd-api-key
    namespace: soularr
spec:
    secretTemplates:
        - name: soularr-slskd-api-key
          stringData:
            api_key: ENC[AES256_GCM,data:nheuD1MM9JgxWtT5I6uNL+Z3Qr6vNXCEq5MOrA97C+s=,iv:5GsyKFzBBmh8AnoZFW9vJHnjst2FzTWhF+Dw4a3PfiI=,tag:OZzrnYqe+nPawHETZvuSZQ==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MVNCWUFPSE5jL0w0TTNL
            K21xc05PVTUrWDAvaVdFOGZVclRRQksyVDJZClIwa2dZZnBLaFlpRFNMU3c1czlm
            OVVDUnpPN3ZmYVQwTkVPaFVlOTluVUkKLS0tIHJFcW52cmpSOUhGZTEzNXNMVHFL
            S1FPTENMQTVpaGdKMk5JRUoxbTB4eW8KsS4wIdKQDDjoKBeA3YOzm8w20aCXinsD
            hvkTR2I+YT2grTzl3H4JknX2OlOcHppCd1ukHtZ0aOOe+NXjNbNlLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T01:40:20Z"
    mac: ENC[AES256_GCM,data:x3NglhYUBpqFs0c/TDfv0Nri4aq5SLAbtRaQpX9tYg1fEf7NTKHQrtYPaluW+qTcWH5k8Yp8yyOvmcFidlzwrh+vBCW7uVa1bK7GAIlLrm2VWj4IZbsst5YhKJb392agP0ljsFISJIHKfjSIGMvtFJzZm76t5DGVynRG6hOZcTU=,iv:QmyWI3KWvk+QryjxeRlr9J8YO+9y51CIiHYJr9/403Y=,tag:75Snt3rV6Vaq1t5BcGhY+A==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
