apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: soularr-slskd-api-key
    namespace: soularr
spec:
    secretTemplates:
        - name: soularr-slskd-api-key
          stringData:
            api_key: ENC[AES256_GCM,data:Oel1kTF55m4GBP65tCB0UTA1z0CxG5i9UdMiLbbZhxw=,iv:VLE+K6uxhZ0awowgvD/th0N88wyHFLxk5ivTh50vXIA=,tag:SK9h6XhN5J4D60hdX4yfxQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaDVUczR5NnRYdlhaYWpQ
            TGcrZzVpejNHTmE3SUN0Qkdmc0Iwc1ZmbUhVCkkxZjUxekY3NUdlNUo2Q1FvNVJm
            TktTZmU3Q2ErNmlZdnZCaEdwZDFETWMKLS0tIEJTeHlKb0xCVGZWRmV2Rkw1L2NZ
            aW4zWlE3SUlremMzQUlnOTZFQWMza2cKB6ajOg6DgG6QXEg6r+dM2cZzXEibOB/8
            i1OCO+QdoOplaRB83VoH2qnVEf6bs8DpL3SQxRx6n9Up+W+7FHcvOQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-06-01T14:22:15Z"
    mac: ENC[AES256_GCM,data:ymouL4XneUm24kOdE3nWyptICAResRzIJn56qRAale6pBjt9/GzNh4urHoLKMHMZwIHVIFb+DjMHGEvbtjAcic43TahUthAhJ1EtxqoV5eNBsiKiMLN1U2WPv7rUjLCKtNBaCr/0+wUErEncqmgzcxClzGds3XKQqn3ovOOOYFo=,iv:UmvKHJtIXvjaakV0zYscsHcmjnWY7ts+aJRXXZRdz0g=,tag:TiP0WWErz6qdEn+++Y7eeQ==,type:str]
    version: 3.13.1
