apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: soularr-lidarr-api-key
    namespace: soularr
spec:
    secretTemplates:
        - name: soularr-lidarr-api-key
          stringData:
            api_key: ENC[AES256_GCM,data:Oeq7Vu+OHoGe0/fKWCy2PN9OK2+lEJGJNLZR7aVHlUo=,iv:VOgJwmpG9JHW+vPSRcHkDgaZWoGSp3lBdqy9os6bFpE=,tag:aCEkpY+sYuqRdxpj/ByJWw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2MVUraGhOTmREeUFtT29L
            OW5kL2c3cVRFT2FZTFoySUhEMGk2UWY3OXlBCnd5aVBhNEpLTVByYkJkY2NZSkJk
            a0hzNm1ubHZUejAxVXZzRXhZTHZFaEkKLS0tIDIzZ3NtK1RLSnpXTDVDSlFpWDRv
            N2V1bVNkUVRVM0pUcmVJb2t6dmc5eXcKkKHdbB8g4EMHMQ+6pa+w1kSELFxijKEj
            0ode+lEVgzR5U+tzw+Vyt8iWSiTWeIiFgTA8HbxgHFEbvrKyyBnBsA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-06-07T10:58:59Z"
    mac: ENC[AES256_GCM,data:AWwpfxm5jEhUVj2hE33AcaNvh1O1a5nRvUdSdz7dhO+mshOlXmGIUAVovmTVuAnh2WWM7nNeEQbyJyXoZde1AMsBEmS6dLUXhXR+O91yNhqcnvigIO94UFj1q0InG4ndEArwZFm76Tvho1HTgwd+bOEF+K7lia15d3rENjJ+ZXA=,iv:COaUnRufuB2nMgMyhPS8nAefrX3XKu7cW7rs8CnR52g=,tag:qziGgnKxRJdQeyufP8p/iA==,type:str]
    version: 3.13.1
