apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: soularr-slskd-api-key
    namespace: soularr
spec:
    secretTemplates:
        - name: soularr-slskd-api-key
          stringData:
            api_key: ENC[AES256_GCM,data:vzAw/U6fLD8PhlSo0d9HSUxalun7/BJUNz8i5ETDtUc=,iv:Lc3ATVJdWvw124YcVYh/Six9gnNt5Vrev+0a1q5AvGU=,tag:lhrQ1rVhUFnIlrwBreCdWw==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZVErejJaZDhNN244TTZH
            QUFVS2kwOUNwK3B3ZTVlRUh2eUtFckczalNjCm9TSmdSTjF3RDdXRDNkL214OS9V
            QTlBb1hSSUozc1VTWEhlSHp0a3ZoM3MKLS0tIGFvY1hzbFZFd1Uza1JaN2dCVDdo
            UUlYWVduZWlDUURHTjNaL0JIZGNud1kKeFjpr3MY4FD0XZhpoih//Veqd6nWJCpx
            Ltr5irid7T8598AWWbd43Pqp+VnLg6eQg7Shw5S2xdIsp/W0nW/Zxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T02:44:46Z"
    mac: ENC[AES256_GCM,data:Sadx6EcxwbbyYlE8xpDbhVWsGXSZoANOxxAald/GnREcPwkf3A9do4vCZTNqEFdD4r1eJvZ8nQhEqqDYisUPlqS1Bzs4Ccfwp7DlNc6RrRbkmFsJpbCusJNuqpGZ60cKk5OhMg0Vx9jtsQN5C8/ipTVHZEmBpqgp1pcw98q3Frs=,iv:QIBUVraqGY6ILJNgmXsflcjKOHXwQGmDqdvzT4tMHlk=,tag:+ttQsm3eYW7kPQPXYFtaDg==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
