apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: soularr-lidarr-api-key
    namespace: soularr
spec:
    secretTemplates:
        - name: soularr-lidarr-api-key
          stringData:
            api_key: ENC[AES256_GCM,data:4C68D539WN6lciYPVAndMXaCYCuLLIDS8F2zdOF+Yqg=,iv:3laowFxIawiaaxvnVC598MSw3onKLjIPsfqyz30jcMg=,tag:6E1maQFbSc/lARrye+kQDQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSGJ6K1J2eEc4RE5uNU10
            a0dKMnlpdWhRSHhwTDhORHZyb01iSXMrQ2cwClRYcnpnWExRZi9Hbk4yczUvQXNt
            b1RkMEJTUlhnMG5BRzZHbDhvTDZnVjgKLS0tIDQzai8vMlRyTk55ZEdtSmhCeUhX
            cjAxVWFibTFaMlFiK2gzM1N4OStIS00KQzGFUfAkU6UxKIcFObH34Bwdpv91+z1A
            NvoTFBUfsLjj3mdqJDqBssaWTvWoUcl4Ns/wnFiHYNaYNFIWaBhvQw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-05-29T12:14:28Z"
    mac: ENC[AES256_GCM,data:cKqO+GAlbjSzNhogGPywk7aSLxkMu2BY1FPzWR+OiqwLUGr2vzXxsAQ9UkjCzRc4F34vJhUWq9K3U7LqDKI1LrOG6joFsJnzmfRlwRWt+ypNi+RJc2mB/KiFuPdVqV+o/6HVBuzWG8M3abXC1CEiO+4/153V4J8SV1ob6LmuvRs=,iv:zpuCTvDgYFByea6dDfQr6la29hHrpWKP+xEOHXGdsAA=,tag:enRYKEuNac5fQb6qnsYkcw==,type:str]
    version: 3.13.1
