apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: soularr-lidarr-api-key
    namespace: soularr
spec:
    secretTemplates:
        - name: soularr-lidarr-api-key
          stringData:
            api_key: ENC[AES256_GCM,data:rnlGJlI0xH++OygYLMnjDp7H/Q7JXPm9w9WQGn334U8=,iv:j9USOllGUltvpgBqNUpgw1GFGEPQjsBYMpLlzmlaO6s=,tag:7m6HvnlbLi9K6UKHb+vL+Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEL3RDWjVkQjJVd3FvUXBj
            UWg5d2pxZVZhUDdkVkJSK3BxdEZQTnBhOTE0Ci9jdFhXbUdXb2E5dUpiNWNCUnh3
            SytFU0RMaWREM0ZWOER5OHFlQlZneUUKLS0tIFpCSEtndUZ0cHBZRzdWVzh3T2E5
            V2xteGFVSHJUbGlSWVAxZVFZNTdpODQKOu6FPqSsFAGJSziwFLNr8hRu3rDGISha
            WBE8mL/xbanMAjK4KShHu5tIPwTmK5XrjqYPzSne3MMjjAlSzP0Vig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-05-24T20:56:13Z"
    mac: ENC[AES256_GCM,data:91QlVR9/AHWIDucHtqiWMfaF1f+cC0/icgNd5H+9MrP0frbCysdFclmwZy/GJj24i5ujdtAwH1xZRA3KzrMb+kego/vfyUAmdBLG37qw00RTn53p1M4WMiYGQ5EMS49KnAS4CO+cheGhE0sUT8ZIxPNqmjyVq18tmdLImUTTzik=,iv:J4w7vmF82/TVb4hj6yPqZ/o4nkKa1/sjq28XGhB5zAc=,tag:8jyrfbVPc265UHyzaYWRIw==,type:str]
    version: 3.13.1
