{ inputs, ... }: {
  imports = [
    ./adventureworks
    ./airflow
    ./alice-bitcoin
    ./alice-lnd
    ./alice-specter
    ./argocd
    ./argo-events
    ./argo-workflows
    ./authentik
    ./cert-manager
    ./cloudbeaver
    ./crossplane
    ./demo
    ./dinsro
    ./forgejo
    ./harbor
    ./homer
    ./keycloak
    ./lldap
    ./memos
    ./metabase
    ./mindsdb
    ./minio
    ./mssql
    ./openldap
    ./opentelemetry-collector
    ./postgresql
    ./redis
    ./sealed-secrets
    ./spark
    ./sqlpad
    ./tempo
    ./traefik
  ];
}
