{ ... }: {
  imports = [
    ./adventureworks
    ./airflow
    ./alice-bitcoin
    ./alice-lnd
    ./argocd
    ./argo-events
    ./argo-workflows
    ./authentik
    ./booklore
    ./calibre
    ./cert-manager
    ./cloudbeaver
    ./crossplane
    ./demo
    ./dinsro
    ./ersatztv
    ./forgejo
    ./grafana
    ./harbor
    ./homer
    ./immich
    ./kavita
    ./keycloak
    ./kite
    ./kyverno
    ./jupyterhub
    ./lldap
    ./longhorn
    ./mariadb
    ./marquez
    ./memos
    ./metabase
    ./mindsdb
    ./minio
    ./mssql
    ./n8n
    ./nocodb
    ./openldap
    ./opentelemetry-collector
    ./pihole
    ./postgresql
    ./redis
    ./romm
    ./satisfactory
    ./sealed-secrets
    ./sops
    ./spark
    ./specter
    ./sqlpad
    ./tailscale
    ./tempo
    ./traefik
  ];
}
