apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-uptime-kuma-data
  namespace: uptime-kuma
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
