apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: gluetun-mullvad-wireguard
    namespace: gluetun
spec:
    secretTemplates:
        - name: gluetun-mullvad-wireguard
          stringData:
            privateKey: ENC[AES256_GCM,data:CbGx9RwBNxr1TyCzUgw2JLUmNkcfPJu13hPl4cMh5yHyfiBCPrHuHCxkNuE=,iv:QRXCBIFALenS7mHLzE+4JkjXe0QpgyNINhMOBoMONvQ=,tag:F0jAy6olzls/dYyWB6fOpg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZFVlTHFIWVpmTzd4cnpL
            V0dsZVJjMGZ1SnlTZnl3U2N1dGxaZlh5TWxRCkppN2lnTTcrMHpJZnp4VmZVK29t
            WFpoL0JUYUd6cEZsR0I3TVBRVG00a1EKLS0tIGtWWkZwcXdjSU52di91YUY2SjIx
            WklGUmpyME1jZ0lRdjRoWkUzTmY5aGMK2+EfvaP2BGsHKgsQrnxMf4LLuImDuw+O
            R2/S8vcieHqB44gCH8mWe2R6NzvriQ/ccr+TqlCRN2QyKMsjwuTuXw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-05-26T01:57:41Z"
    mac: ENC[AES256_GCM,data:FwDovyqu2IntGlqn2EheHS3ouPvSvm26oLC+ch7jffWxy1F2N7HM8/Tvz5/86LEH+ZIW6jVlki1qinY/Lm8WZSuHBb1PQr0aTCc0AoPoN1RJ4hm1IO4RYMQ7Rm9zek4yoa15kiEzILC5B5Ti5V3ft0FeN8gIjRzC2TJrX4ZtgDI=,iv:832Cb1KlvI4MFt9Sck0oe6lMl/PRNf+M9zR95AVCSSs=,tag:GvpZpGNpKPyjuIWigk/Y6A==,type:str]
    version: 3.13.1
