apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: gluetun-control-server
    namespace: gluetun
spec:
    secretTemplates:
        - name: gluetun-control-server
          stringData:
            authHeader: ENC[AES256_GCM,data:YTQC1Ko7wQIcONF3XRVsCjdWmkZY1R9nrwi2r/jo1cFbQZiri8Vb,iv:PRkzzaWSXUMmVl28YfoVmNhXtyzOXFGJzvooX/MUbHc=,tag:ZqKxXJ4R0kZ8W9nb+VY+KA==,type:str]
            password: ENC[AES256_GCM,data:9SpwoIy4H2sXmsVV8gbRLw==,iv:bE5f/p+7IdanK0HJCwoKG0jfBwhbcZWBdhHi+gK2QZo=,tag:JKuWfxnNQ/lCFHcDFbyXsg==,type:str]
            username: ENC[AES256_GCM,data:lwRtG3U=,iv:8F8AizDqDMblfmnrXmNDv2k7ChxcGubYrI5JUh25cdc=,tag:8ZLrfeJKsrPRJhA2ijEWqw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZHJpb2ZRSitxZTB0WVh5
            WWZwRW5Uc28rVVplaGRvV0d3WVhtZks3dEFRCkozT25ITmMrWW5TeFhoZ3FnN0Jh
            QVJPcS9hbnJ1Z2I2VnYzczM0dEpTRVkKLS0tIE1nWExsNDJwNDRhd1A0Y2VGd0tz
            U0RYVUpGYU1JVnVoZXlZWkpiT1RJa2cKyTYMYHB3PkLRnJy9aVhRY67L5+Cz0rO5
            oUYAVkMsxNDuz8T6MwO9ceSL8i/KFlXSSd9GOBPC4rbS3pqNOxhjOQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-05-25T02:57:53Z"
    mac: ENC[AES256_GCM,data:HvOnqNWWg4Onulg/0QVhyYFKNY9r5cQOUCERhmXQm7PkXTk3BS7lkpxV8Cnj9ilUTLWl5HBwmhjpwqa0W2P7wI1NI5OCRiGgzXRZXWAYAf6Xq+csrds22vc/9xqmXO12XpeLD2QXTM2RB3fYA54AqLpanvqEP4ejjfP8RrB2FBk=,iv:GcPJQO9s9OMiaUxETuEg+k2OJqipBxvcw0ZBIqYa1og=,tag:9R8GSnyj59JpJW9jcvNTBA==,type:str]
    version: 3.13.0
