apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: gluetun-control-server
    namespace: gluetun
spec:
    secretTemplates:
        - name: gluetun-control-server
          stringData:
            authHeader: ENC[AES256_GCM,data:iS4IhaW2FOr9QV7gxZab1qnO1FrFLPANzSJ1piP8fTgqUJDMsvQ=,iv:s142WZ2zaT8DAdjTjAtM/RIF7hFKvnXsPI4jwLndgyY=,tag:cukFcP2DXIQShZY1VftfXg==,type:str]
            password: ENC[AES256_GCM,data:03uPUwrClO7pT72+E4u2pQ==,iv:kBR++svDhm6PSAL5CN9fWcd5CsUwsqK96CcQsLKnNwc=,tag:5ejNLmmfxEZfF21WqEtEtg==,type:str]
            username: ENC[AES256_GCM,data:fW0IcVQ=,iv:2g1gJRKZVyXNpDpQiVYiPvMD1MZ/Q8e2VdB1HwSTROk=,tag:v0fIL9EXu+tPetUUWo7Reg==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZE1zL1pWcVhZTTVYWGw3
            V21RcVhXMHpRSkJsK0cvVndZV3h0WFByS0c4Ck1SR3VXc0dUYUJVU2pKTVFFOVNP
            MnR1TjRNNGtaakZNSVBLR0lMYU9wdWcKLS0tIDQ4WHh4UXZjL3RPOHhPcjc4T2ZZ
            QkpuMVJGV1JPNHcyQWlkNzJGZFFrRHMKiZEYm3VjnxhOpXXmhsYVVr5G4DRso/0l
            DHSCatyH9se0ueXIc5Lsjj4SuNf9+xDp7JzceVgJqQIObD7tTVtayg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T17:28:47Z"
    mac: ENC[AES256_GCM,data:HCIumg+1t3RQbrxvc4JeaKBmDwdIku4vvchUoJzqldEAVLD8dXthsKewnQgpjKQLiT/xLqsZhwVhw8K3LCsO6VGsirFt5gtRXX7Ncd319NTECyKhI5k+h/ywKZtC3VXhjl+CnxH0Z1kA8OyN/t7wX0nvv9+eqWVz2V+nmy6r13o=,iv:kn21hL1/VWQDXsFAuhsgAqSsj5bX4T7xnb4E1Doa1eQ=,tag:VgzN0uuFRqVIah3F2wLrQA==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
