apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: gluetun-mullvad-wireguard
    namespace: gluetun
spec:
    secretTemplates:
        - name: gluetun-mullvad-wireguard
          stringData:
            privateKey: ENC[AES256_GCM,data:0ghPMRcxhmpq4zgTpX3h2y/2dqSArguZynvpaHCu5g25NFq5ZLArrwMgv1s=,iv:TZ0qfgip797eoAkXVfOoElI2ytBrpzrosBxGMSbiAOo=,tag:ft53xNvNfTzGiefJHOC4aA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWSmZIQ2FzZjltcXdSemV1
            VWYwQkhuWkhhSVVpT2xZajBwOG9GTnlzY0FFCmZCbEdZNHk2QzJsUlNVTG03NHZt
            eE5FRFUrbEZyZ1JXQ2NlOHM3a0sxOGMKLS0tIC9iUVBsMkc4N0xjL1ZyaVhVRW13
            eFhZTUtjbkh5UFhVRVEwR0JicnBkSW8KUZOPX+L1Rm12xjZAdds2cGHDB7RBXLNv
            Zl8YVEfP68svh8vR4b0lia50hP7Hdqq3e9FMASO5Nva2Uu8dYdG5fQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-05-26T01:32:20Z"
    mac: ENC[AES256_GCM,data:YxpiobxUBrUNpj//mcWsSys7Wc9IZjbutA6XHJny4CFLqFhWznkqZOfOqAq/K7mMFsCvKLywYHx17eG5LveQBfyVQ/iF7fmoEtZDLbaWzGVToS+LjyvRflEvBwQBXEKoiUFkg3feZVGHh3rE11WRWCaxEzNgsdC24UoyJYl/x2g=,iv:OQ887bwmR1ZhdP/du2sp4DUWhuCcbm7xjrfaRpc5yFQ=,tag:G/N7NJ44Qtp49QgOzc+VFg==,type:str]
    version: 3.13.1
