apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: gluetun-mullvad-account
  namespace: gluetun
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyck5IaUtlOFZ1TmRUeEFX
        a2E4NzJYZUVQZTdjZG5QMzQyMFZFWGVJSlhNCnlueXlIUjFHTEdSNHR4UjdYSlZl
        OTFRWmpLcXBEOTF5SFhEMGhBSmFmTVEKLS0tIDZXZldXbGpXTEw4Z09KMWNocHdi
        TXU1QUVuNnRocHc0Z1p2QWZwOWtGdUUKsEsAOpygH2Yf1mTFV5ecsWDRQ411kcx5
        zNEAjMFnqysN5Pim4C1E/8qQKsVKsrwCyCXjxKBfQ+uPYfVPMqncZw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
  encrypted_regex: ^(stringData)$
  lastmodified: "2026-03-11T21:42:42Z"
  mac: ENC[AES256_GCM,data:drHPYSzHQXt8uZ3/JOTgN0yEwCeDZ79/rmbwAXSJEwM0p3Rl2ZedAle7xWvZ9059+dtuC0ssJacN7NsgoNE5bJg6jO+w2n4euAWvjNnuWlmhNjh8zGtcxpko/D2QO01ftavUi4qPstkOEr8VbHSJlWccv/h4UbY6+Zz1RuJ6+L4=,iv:1jyEEEjSykfMFlXc8Zse4a16ePocgEJDhsIbR48jEJ0=,tag:bNwQXR3c3WAMakwnY8dqWw==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: gluetun-mullvad-account
      stringData:
        accountNumber: ENC[AES256_GCM,data:rN6sldXueWnMU6V5Mj/Evg==,iv:c3uykuVSV4SRVLFVnYzwhYFDk1Gk552FBHp1RtOf0Fk=,tag:RuDVDmLRDmz90TXHvR6ZIQ==,type:str]
