apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: gluetun-mullvad-account
    namespace: gluetun
spec:
    secretTemplates:
        - name: gluetun-mullvad-account
          stringData:
            accountNumber: ENC[AES256_GCM,data:iRgi75C2pAVr592SXw6BlQ==,iv:vaoatmOa7AtbAmrk4Y/bY21KIwVesyej+TyFGm0tmpE=,tag:s6DgXprbOe1eLw33fS5/iQ==,type:int]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhMmVWZnU4SUhLczZSeDhK
            MlB2TFBLVUkvZFFMWVIyNTRBR1NlZXNoemdZCm1mU2ZrUTJ4K09HNHUyV3QvaDZk
            K0xMTnRRR0RtcmlTUTk1ZDA1b1U2V28KLS0tIFo4TFI5UUxUaklhWmJad1oyeklo
            Rm5hRVZoUzl5aG1zNUMxdm1Za0FhVzgK+ue72w1987j/Q0vLZd5t0zFXv7YJeAO4
            lXk9Utovcpqt5mSLsZVd4ip0HSep3avLF509i21YMQe+vqhG2cTv+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T04:02:29Z"
    mac: ENC[AES256_GCM,data:wSRrp3LeZirHs0MmImOz63okGVojnv7DYq8349+1UkaG6c0K5L/nvRf4VqmAadjJhVPXiTghxuouVUeypkt/0pwjlXQ6U67xm1iZNDSfNWA0EaDwz3OIg9OV54lcs0iVHB1qhB8WNnBxScffxKHHphFIVVRH7DTNcI9xE9PsGPM=,iv:OEkzrxEccPcn0ZRsca0ylc2oz1cMk9bQz3gA2ZZcKAQ=,tag:c/+Z+0tBNxY1JFT9Em9tIQ==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
