apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: gluetun-mullvad-wireguard
    namespace: gluetun
spec:
    secretTemplates:
        - name: gluetun-mullvad-wireguard
          stringData:
            privateKey: ENC[AES256_GCM,data:LKL1JsHyz2EPD0ygyVPWr+TXMObwEOJv7+QlM6qV8ji5O4fWvl8zPlUHjVo=,iv:pdFWYEwAoo9y37Qhqi4F1zwTNGBPV8KySkiz6ziop/8=,tag:Fb9tEUbCHKp78k4OO2Y+iQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0cGdjVmFHTUVENFlQK1g0
            cWhMcHE2UWNVczI5ZWZ5ODlISWJrY3Q4SUZzClhqR1Fqb3NrODBUSVNucGdXR3Nk
            YkYzRkQvSzhqVkZ0OW1hY1dQOW41L2cKLS0tIDU1cE1maTArQ0IrZkNRdlpNL09p
            RUpvVEk3T1JUM1B5SHZMbDV0djIzUUkKml7E3SpTtpNxcAXfi8gn856DMZr/iFMU
            50nhtipSbhFRBRDKNQa80t1GHT2VSjgJmAVAyY9q7N1MJTucR8oZuA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-05-26T02:00:58Z"
    mac: ENC[AES256_GCM,data:ngJzB4ubd/R892PFS5oTfFOHrzbvMdvLZcMZZPBMqEwxijMRr+nscxZmeqNbX2N5gwmtSXxc+yhdMi9AXj8nb+FYqkGB8QE41L+U2Kt0N4oIiem9fZ7xJ6iwu6ghncpob+Rn/im/CyDahKDdrdiU8fCAdUUTjx8ICiVeKi/5Mpk=,iv:D/csPYexi2IMgwg1R49xCZufXNFry0IK7yFDoQivw50=,tag:P94xrZzcF2UEQ5/vxNJ69Q==,type:str]
    version: 3.13.1
