apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: gluetun-control-server
    namespace: gluetun
spec:
    secretTemplates:
        - name: gluetun-control-server
          stringData:
            authHeader: ENC[AES256_GCM,data:kPoI7A8NOXprNIHcR9oKVAiDGKK+xYtHttQejApp99i3lG9jOAxg,iv:oIk6EmbBD543qcZW5NwqJXz7TW2VjERCut7fEzoY3EA=,tag:+XlQUsZg5DYvad0UeEVmOg==,type:str]
            password: ENC[AES256_GCM,data:gtUvbkZndwIiapcuBvZafA==,iv:lhWtqspO9TscK8tXJq77bBnqvkeJPv/ZSNNaTnJQdCA=,tag:zoxHNuKNfZlYP5Oe506vIA==,type:str]
            username: ENC[AES256_GCM,data:1vDgUVs=,iv:U0lqqZ8/71+zWEsTcgjtmB9MoaVi2VmjlVE0F5eFcD8=,tag:Av2Sb/MYtePBnTmpF1O8TA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCa0F5SnhJMFFKd2pOZ2g2
            VmJ0dDd4NlJaV3BJcjF1dmhRVHRlcHV6VXdNClQyV3MzQ3JRaUdnbGRNR2tucWw5
            MXhXaTk3bnBmdktEbVVoSGQxa2tSck0KLS0tIGFyUmJPWndFNzdyY3ZNZzcvc0VW
            K2U0b241dkNKcC9SV3F1Nit6KzhSYTAKMw0FmAKlNEE5f+L3IAop1+UbwIKixPZH
            5UxOLaVeLTpacSBf6aVYFiCoau62Ts/oG6vn4AHS/aaGdp1uaRJFmg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-14T03:04:09Z"
    mac: ENC[AES256_GCM,data:y3XzAsdmoF50lI+RnuCwJ4DTkgmel1TyoqJ8fa7yk/LLVZ9BRRdyH8pKtVacuEhexqqOcnOLrYv+6mrP3I4C1X+Zc3ENrg53/ijCxEiAV2gQCz+zbYJSMM7ql7ly5R7SApQbdNbRZR05+TmV/NhfiDJIvW4N5v3wQlABsfYTl7w=,iv:oaxiICihGzEUM45+ru9IU6OhrY1IFFhjKNAyuwrUD8k=,tag:Vapu1vH5jzCPS4CA/DjGZg==,type:str]
    version: 3.13.1
