apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: gluetun-mullvad-account
    namespace: gluetun
spec:
    secretTemplates:
        - name: gluetun-mullvad-account
          stringData:
            accountNumber: ENC[AES256_GCM,data:ppQAm+pAO0k45lg+LP1DzQ==,iv:6KGQ87of3SF0LFHKO39AEUu3Pe3WEKXpSoY4SCd1Z1Y=,tag:yGxi+HoDyDcCthtedNH9MQ==,type:int]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUldKaFlmUk1xME45VWtS
            U1VvdlpFNFBXdUZXSmpvc0pxQjdVV1Z2MTJzClRKODIwOURNWkVBZWUzdXZDZys1
            cGtPdGszejRyT2tvbWxjQnUvUm5xSUEKLS0tIGpYV2RLYmVsbDZ0Z1RZdzA4MHZX
            WVpGZnpvc28vb2VlRGxST2Z6T2I3bEkKA37rJ0/cSYFaVW87s9NOq1pSF6tuSaws
            j9sl77DHNrAZ7y+1r39yRMoJ8inQStj7JmM5af56WfGvdlNmP+gdSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T04:23:49Z"
    mac: ENC[AES256_GCM,data:IwIC8boj4biXJgZQmyUTOsWYXUhOMb8VVz2HWrfIxMghpI6Ec+7OD5KzxRJpD/OEHoLMOwmkif85RRNAHNh3lsOqF7ETtvqXMw1s8aGRSrfeDZE7Fnr2DSodALroOSFnfBV/Ju00CgmWuFZwcp6nNbkSMvee/PLv844EroE9iTs=,iv:M0RrVZxo+llG/WPukRx+ilZb/tKGvDWucKwVaWv4af4=,tag:RvH91P5FZfwJKyBnt1fBnw==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
