{ ... }:
{
  imports = [
    ./affine.nix
    ./adventureworks.nix
    ./audiobookshelf.nix
    ./airflow.nix
    ./alice-bitcoin.nix
    ./alice-lnd.nix
    ./argocd.nix
    ./argo-events.nix
    ./argo-workflows.nix
    ./authentik.nix
    ./booklore.nix
    ./calibre.nix
    ./cert-manager.nix
    ./cloudbeaver.nix
    ./demo.nix
    ./dozzle.nix
    ./ersatztv.nix
    ./fileflows.nix
    ./forgejo.nix
    ./gluetun.nix
    ./grafana
    ./harbor.nix
    ./hivemq.nix
    ./homer.nix
    ./homarr.nix
    ./home-assistant.nix
    ./immich.nix
    ./kavita.nix
    ./keycloak.nix
    ./komga.nix
    ./kite.nix
    ./lidarr.nix
    ./listenarr.nix
    ./kyverno.nix
    ./lldap.nix
    ./nix-csi.nix
    ./loki.nix
    ./longhorn.nix
    ./mariadb.nix
    ./marquez.nix
    ./mealie.nix
    ./memos.nix
    ./rustfs.nix
    ./metabase.nix
    ./metallb.nix
    ./mindsdb.nix
    ./minio.nix
    ./mosquitto.nix
    ./mssql.nix
    ./n8n.nix
    ./nocodb.nix
    ./openldap.nix
    ./opentelemetry-collector.nix
    ./pihole.nix
    ./postgresql.nix
    ./promtail.nix
    ./prometheus.nix
    ./prowlarr.nix
    ./qbittorrent.nix
    ./radarr.nix
    ./redis.nix
    ./romm.nix
    ./sabnzbd.nix
    ./satisfactory.nix
    ./sonarr.nix
    ./soularr.nix
    ./sealed-secrets.nix
    ./slskd.nix
    ./sops.nix
    ./stashapp.nix
    ./spark.nix
    ./specter.nix
    ./sqlpad.nix
    ./tailscale.nix
    ./tdarr.nix
    ./windmill.nix
    ./tube-archivist.nix
    ./tunarr.nix
    ./tempo.nix
    ./traefik.nix
    ./whisparr.nix
  ];
}
