{ ... }:
{
  imports = [
    ./affine.nix
    ./audiobookshelf.nix
    ./argocd.nix
    ./argo-events.nix
    ./argo-workflows.nix
    ./attic.nix
    ./authentik.nix
    ./autokuma.nix
    ./booklore.nix
    ./bookorbit.nix
    ./calibre.nix
    ./cert-manager.nix
    ./cloudbeaver.nix
    ./cloudflared.nix
    ./crafty-controller.nix
    ./demo.nix
    ./ditto-relay.nix
    ./duck1123
    ./dozzle.nix
    ./elasticvue.nix
    ./ersatztv.nix
    ./fileflows.nix
    ./flaresolverr.nix
    ./forgejo.nix
    ./garage.nix
    ./gluetun.nix
    ./gramps-web.nix
    ./grafana
    ./harbor.nix
    ./hivemq.nix
    ./homer.nix
    ./homarr.nix
    ./homepage.nix
    ./home-assistant.nix
    ./immich.nix
    ./kapowarr.nix
    ./kavita.nix
    ./keycloak.nix
    ./komga.nix
    ./kite.nix
    ./lidarr.nix
    ./listenarr.nix
    ./kyverno.nix
    ./lldap.nix
    ./nix-csi.nix
    ./nostrarchives.nix
    ./loki.nix
    ./longhorn.nix
    ./mariadb.nix
    ./marquez.nix
    ./mealie.nix
    ./mediamanager.nix
    ./memos.nix
    ./rustfs.nix
    ./metabase.nix
    ./metallb.nix
    ./mindsdb.nix
    ./mssql.nix
    ./n8n.nix
    ./navidrome.nix
    ./nocodb.nix
    ./openldap.nix
    ./opensearch-dashboards.nix
    ./opentelemetry-collector.nix
    ./paperless-ngx.nix
    ./pihole.nix
    ./pinchflat.nix
    ./postgresql.nix
    ./promtail.nix
    ./prometheus.nix
    ./prowlarr.nix
    ./qbittorrent.nix
    ./radarr.nix
    ./redis.nix
    ./romm.nix
    ./sabnzbd.nix
    ./securo.nix
    ./satisfactory.nix
    ./sonarr.nix
    ./soularr.nix
    ./slskd.nix
    ./sops.nix
    ./stashapp.nix
    ./spark.nix
    ./superset.nix
    ./tailscale.nix
    ./tdarr.nix
    ./trilium.nix
    ./windmill
    ./tube-archivist.nix
    ./tunarr.nix
    ./tempo.nix
    ./traefik.nix
    ./uptime-kuma.nix
    ./whisparr.nix
    ./xysat.nix
    ./xyops.nix
  ];
}
