apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kapowarr-kapowarr-config
  namespace: kapowarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
