apiVersion: longhorn.io/v1beta2
kind: BackupTarget
metadata:
  name: default
  namespace: longhorn-system
spec:
  backupTargetURL: s3://longhorn@us-east-1/
  credentialSecret: ""
  pollInterval: 5m0s
