apiVersion: longhorn.io/v1beta2
kind: BackupTarget
metadata:
  name: default
  namespace: longhorn-system
spec:
  backupTargetURL: nfs://192.168.0.124:/volume1/LonghornBackups
  credentialSecret: ""
  pollInterval: "300"
