apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: longhorn-backup-target-secret
    namespace: longhorn-system
spec:
    secretTemplates:
        - name: longhorn-backup-target-secret
          stringData:
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:PQYmguJQ7XbMQgOStcn/khxuwuiCWqmQkFSsmzCtjEM=,iv:h+bIkEUVxQmBo6GRyB0/sW3HRncgSq2UQSt8BSpwu9Q=,tag:e7zxEsFBvC86pSlxa1ji7g==,type:str]
            AWS_ENDPOINTS: ENC[AES256_GCM,data:czrlkwSVHw8iQlb6A5s98N0CvowHJ6gug9/6EgU=,iv:c2svyMLHBVYAdMUdiMzXr3dOLpHii3l6ba0nu8tXl3o=,tag:erPgTWtd14ruy9t0BWRiVQ==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:5/gfcqQTr7MqkBvNhU9LTwTR7MkG13+BWmLAi/Twgks=,iv:E3uuBICIehBhuYrsbcaW0VdXK4weybd1s4e5MCFB5Pk=,tag:nDbu5kQMkB/Y0WMManG2pg==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUTREbVFwaDNKcVdYSERI
            a21penY5bXBqZy9yNEpXOE41TEZMR1E4MkZZCkN6RUpnYnhZY0VseExPeGJQM3NS
            SFoxZkhvMWZFVlY1K3J1dDFSeE56N2MKLS0tIFV6MGVObEVjTnlPY08vQ0xLenhG
            OHo2OHY2TFpQK3dFZEk4WmQrbFpsSmsKcbb7ODJ+YRcWweLoQ4TF7/cko5bq5ItC
            R6RVculkdPej5PWggqZDce7ZxfllPsWTEXEvP97yIRmYZ3rV0X91rQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T23:45:30Z"
    mac: ENC[AES256_GCM,data:va6cSpAJhaYi4tG3JMD2axgclhrr462WTqv7myHCow4BQdNwT+KHs8W5Nwolqe7ZOc5V/DrHMBiu+uo4PBqo6dS3ZIE6rXX04tylyAkB7JEaz8cu1xYtx7MToZZpIhxkQpIhPklqvVuo+qyLXbAP141Vq4XSOi3PDp+JDuSDn3s=,iv:r8KNvYZqd1ZXZWvoo+qafJWFiXvMo4ImMhbhYx9RpiE=,tag:bH1RLf1vtAvWg946fFTjiw==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
