apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: longhorn-backup-target-secret
    namespace: longhorn-system
spec:
    secretTemplates:
        - name: longhorn-backup-target-secret
          stringData:
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ZuJUpNbT5BA7sv9sALXU1ZgT0G6qUaLSMuwPdhySiZI=,iv:jRmk130b3MahE3FPglKsUt9yEtJygIAEeGLsYc/UNaM=,tag:5DVxHJP6dIZbzKsQ2QCoQA==,type:str]
            AWS_ENDPOINTS: ENC[AES256_GCM,data:RiQc2wW363Taf1o2GAPFhGesPFC/GoPwaFJJBKs=,iv:oj1OI+eI05nbBYU+mWClHd10Ath5Or+cCpBswqZkSl0=,tag:D0mqGQwxu/4ORSspzL0Tng==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:zzhX/bkcgmzD89TwyxCBo5HH2ynfHrdn9ysNvcI5AiI=,iv:f//CSQMt5yILXKSnWwpr7gTN4vCbMDl/d8Fo4EGHThs=,tag:BdPTySXwdPjU+eTqCg4G9Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwL09iYk5aUG9TUE9QM0RN
            NHhNL2FPUy9kaUY0SjFUZWNYcC9ucmVaZ1ZrCm1BdHFBN0R4d0xYb3o3RjhkeWFp
            NTBBdk9FTmxCdWxxeFBkU05XTTE3STgKLS0tIE9yUUVzaG02c2U3NlNBeE1tTFl0
            aHV3cG53eHBaVHBuejh0N21TbEVUazAKzgvQs9bMS2E8G0nhxY1K3eSVF+06Xz2v
            n/Pss9RfdxPtMH9T+aachWpdO/WQ7WaqWMFYuVLRbcSh9gnYW3h9kw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-16T00:34:46Z"
    mac: ENC[AES256_GCM,data:Ytah5vo+S/8xLpBwA1ueH+p50YBk7FmX9lJXqkokohLaS+huogKrPG3W5MBAE2RkP7vUsPVsPBA1ky8HrroCpcfJOjz/5F9AMlfthGfCrt1n+ny2YNQXNuXd/R12Nw+p6r/Wpt6Z+tt7CygIYDmnfIqw/+A2nqBvh69SMl6TaR4=,iv:MGCzPjKRdGCd6TBGBfIzKcgBPrYGMFp83j187ToFw4k=,tag:UC7Ly4mYD02VlgKAKLPXPw==,type:str]
    version: 3.13.2
