apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: longhorn-backup-target-secret
    namespace: longhorn-system
spec:
    secretTemplates:
        - name: longhorn-backup-target-secret
          stringData:
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:tKiXXW+vRxGTLx6EvceIo8waN1kLeLK33GUQCyixmRk=,iv:Lq43vhAWLI6khMG9qgR7JebrSAyUgAyBj/uUgdjxNiA=,tag:X1+JZj80BKdb9TzA/VsQGA==,type:str]
            AWS_ENDPOINTS: ENC[AES256_GCM,data:9jCgipz6+72uxvsJNAgmYO/0Z8/OaGvcu9+um7Y=,iv:p5QyExiu9iUe61HzdY1LMHBPin0upSGT0NbI7ilQH3Q=,tag:oQyExkHsyHlU+Axu4Ck3/w==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:MM8nX2D9Qe52X+lRROqaIrhDqhA3iA/Tuqoz2ei2ZdU=,iv:vztR6Ve9Qzbufh+TCvP8rClR1uZMAih/+e/osqcuPhE=,tag:lvyymq54AAC1FVe1DLveyw==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRalJNSG5GWlM2a3dEUVJL
            Qk8wd3lWUHJ2S2w4bGNFVXVrbUc5UTA3Mnk4Cnp4UlZ1SWF3bFArNmR1K3BNU0dQ
            T2UwSW42Z0dzQlAwZ1prVzFCT1hSdFUKLS0tIHVIS2xvQ1BKVHE0b3dSV2tOaXRq
            ZjNhNTJiUWdMTUlHNDVURk84Z00xZlkKmozJWovY3lXbNu+MNWLguaeAQKmOTNNu
            EBwJC4nPRI/ZDPED4vk2HaVSQq/YRDh3LMOFlNxlKSdrcEeoEKLXKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T13:09:32Z"
    mac: ENC[AES256_GCM,data:t7MGh1+qGfBB3j218bihaGeGjLt0GebjLaVf91exGyzLSqBVcBohv2pSPr1wt8U+mGRBpoF2vgJeMbshbl4wplYMKxxXgZ5qIY1rMOMJ2918UohbE6gyL71lyhK4mIpfLMWpBmzWva2KXnUW+iMM7HjAH1f3kv1VcBFvXAdUd14=,iv:DxJ3GtNhYOMixsxhg3o4XDkCK6BdLCPaeZ5cJDCvV+s=,tag:H9TzzGu5/veycX6GGcMpjw==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
