apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: xysat-setup
    namespace: xysat
spec:
    secretTemplates:
        - name: xysat-setup
          stringData:
            SETUP_URL: ENC[AES256_GCM,data:FOGwaBIh2evYi+IN2CqyBaXDeoUquBgTuQbk+y38yn+UvEVBqv5nPXpyFmKo8F4OoK+susAOveKk5Q8Zl5A4oVD3Tcl5i6Z/r3evYY0zitdI0xHqkhKk1Cvs0Jsa/Q==,iv:mVkN+IcNNVRPffzN3PnEvVuTQUYhmwMjT8m3o2zuR0I=,tag:G0Dp/51ZK5vRdT2ncPeoVg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVzlnUDFPNHp2MnlDbS9R
            ODZZbUZwRDU1cmVGMERLempQVW42THNqa2pVCjhGUVBEc09SSU12RDVRWVJPVE1h
            WFp4ZHMrc3FRdWJlcHZaUUtWZEl3L1kKLS0tIGtKOFBCdEpiR1RLSHp5cnZhazly
            NitaZUJFTmliZTNEd25GckhHQVMrLzgKgvDn0ZI2cf6uV6tpdYboIZdE9QmqehYo
            qj2jnyZr8gd8FHPK3IBArIANg+0k5EOQt82qvGfWm0l+i7SsQacXMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-11T14:48:42Z"
    mac: ENC[AES256_GCM,data:wBg4dqMpLEtriMsoPa0QrI4lUpvwBQzpQtM4i2QU/bpRTsKRyQjDST1vXk0xoV9/5GMsWvcyYVytiqqYN0lbnzZULKSOudQc7qekIQ5PonPVRTJ44n/U9MnfVoj+0VFK0qoh1G2EiY7c4SolUFnEwRHOK4TDnfOJGQJ5EVT6/os=,iv:TFkLg8n1C6F6CIeIyNrwiTqvfNx1AEi+hc4otBXczp4=,tag:/MelKdMfXJZ6zQJLL7Lzrg==,type:str]
    version: 3.13.3
