apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: xysat-setup
    namespace: xysat
spec:
    secretTemplates:
        - name: xysat-setup
          stringData:
            SETUP_URL: ENC[AES256_GCM,data:v5c+xT+sQ+LpYIKgmorqzCj8355a/Gf4/4138eZZnVziSoE797AsTPeQl42ybIpauPVB3BxDtnaqUrtppGjAh+MAzaHrhcAIWjRv8BUX3NIcqsKPfR7M84y9HtpbdA==,iv:woumI67qca7Jx1IfzIaWsCC4xZb4uIfxYolqSVTbVFg=,tag:wBj2gg4hFuwnEus2o6UZDw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSYzNFY05MZll4Wml0dUl5
            ZXBmZWxoQytCWHhHVDJrbGY4dHpReVM5MEJBCkdrNUo3OUZmUUhIeXR5RzRiemZ3
            NHdBa2RxK2hEN2tQR0FXSXErckc2aUkKLS0tIHg2ZFozaTVES0l5TE8yT0lZMUI4
            NVFjL1RWeGgzMUpoY00ydTVQS1FVYm8KAceQQJjV9Z1LZTGriGgB9j720N4yLL64
            s5arzYVKJgLHzBSys2ckDbOvu7Wx7xg9TySwr4P4gx1swBfKywJyFA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-01T01:03:27Z"
    mac: ENC[AES256_GCM,data:tIlXnEMmN5jEMfTzieVwdkNfmmxAHID4BtuzGotxcyUDEmfJbWLswcRbQeV1gdbmdsBt4i6tGwxoee4dMX0r7oNYshdpAnuW36aCS6tpgujKyiRKtMf3bJIZiy/vORyW0GcMYbhardJQO3RN2UFzNlFzEdYG+Oe+40kbjmCPgGY=,iv:VIBv9TxiYTvHQhJhbb3tN2E57cjcDMzaTH4NuNxbVHI=,tag:4hOHeZBmROUfEfyoMrDMOg==,type:str]
    version: 3.13.3
