apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: komga-komga-data
  namespace: komga
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn
