apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: komga-komga-data
  namespace: komga
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: komga-komga-data-nfs
