apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: komga-komga-config
  namespace: komga
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
