apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Replace=true,Force=true
  name: komga-komga-config-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      dataEngine: v1
      dataLocality: disabled
      disableRevisionCounter: "true"
      fromBackup: ""
      fsType: ext4
      numberOfReplicas: "1"
      staleReplicaTimeout: "30"
      unmapMarkSnapChainRemoved: ignored
    volumeHandle: pvc-a982e08c-30f2-4e21-928f-970d367e417f
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
