apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: cloudflared
    namespace: cloudflared
spec:
    secretTemplates:
        - name: cloudflared
          stringData:
            tunnelToken: ENC[AES256_GCM,data:nm1OEdzGnPm3s/ELmNcRGio+Khtg4RdlCFzcL6KJguTvdNG9loiGR+A18HxXMKYia2O6qsKNnCSZt+jAisfixgFltJ9rbePjwRjW39aJ5knqmFAiXfyiv4HcIFpd6SIDdp9qKGOjz4XIsCg2kF4fts9vBWFbjHhdWG8OyGJ5BR7ZxZLUb1rGWm42rn+vEang0x4mdDGXO3pdtdXQs4anqhEewe5baEoHN2OxUHypxBAPXrblZyI56w==,iv:79iRlOyLIZo4eG0eUdHVGEvbAYQmmMsNF1SZls57PRw=,tag:EkRTMzIhausss/JofeBR9w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2WFZmRlllSkV0eGF5c2RE
            SjFObUs2N043OThmNGJxSC95MnN2RlQyZ3k4CmF5SXVYR1ljblJwUjcvVXZxQndN
            cEFFbzlXMTVDZ3V1YVhvcG4zNWdiZGsKLS0tIFMzQWFuWG40RWhGa0ZkNTR5N0Uv
            TVdMVUFKQ2pQdXdOV1NCdW9oeXJtZmcKvNgORoA2ioxBn8vs7/s97i6OujIRuacq
            l+ojpgP9eeCa0PifXnz7qYEJB4s9xSqt3W2IZGJkUKKXzcZW88wE3A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-08-13T23:17:32Z"
    mac: ENC[AES256_GCM,data:ueIxx51F5A0QJK44Oei4K76Hc2HMSA5gds9JhFAPxD45ckbmwqKaqWrufPUUgacefvk06huXk93NuPe7KxTqlCLfDerhQENt4AL3uvTBm506SS8Sifnv8apxYADulVneL7iuVW5V9yfhkWcbQ/4AbJKS7vsizOGuAcemCs/HqdY=,iv:0tzD1D60fsLkjjNQfL4GPJSiqsbrbUw7X1Qk9cqbORE=,tag:gMkVc+FAZgr9UZs7qH4rOA==,type:str]
    version: 3.13.3
