apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stashapp-stashapp-config
  namespace: stashapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
