apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Replace=true,Force=true
  name: stashapp-stashapp-config
  namespace: stashapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: ""
  volumeName: stashapp-stashapp-config-pv
