apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Replace=true,Force=true
  name: stashapp-stashapp-config-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 200Gi
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      dataEngine: v1
      dataLocality: disabled
      disableRevisionCounter: "true"
      fromBackup: ""
      fsType: ext4
      numberOfReplicas: "1"
      staleReplicaTimeout: "30"
      unmapMarkSnapChainRemoved: ignored
    volumeHandle: pvc-9d446279-6623-466b-9937-143eeca518ca
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
