apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: attic-s3-credentials
    namespace: attic
spec:
    secretTemplates:
        - name: attic-s3-credentials
          stringData:
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:QLm6SFaD04wxBawVVdI3fMVAmVe24FKV,iv:c0Vdter9zuGF+0GvrNWQL3ycdbcUGs4YuSBLgcZAzWc=,tag:d11KnsL8GbsPNkg4BFeGfg==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:I1Fizq9S0AWWwd2BPPg4GkkCbtXqV4kk6CTvBYLDWRvSXRXPEGMUPUj07KztyLfRqwG2SUzSAx0qhZ9xNnJJIw==,iv:k3N/tNIUHeB6iaDttF313UJquYUDILjrvrczB+x9KZA=,tag:dibl2uEhlUKOxhl3dFUNxg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzT1VGVUpINGJxUytPMnhw
            T1lMaDlwSGZ4Q284eEVINkljRXhvWmJINFFZCkk4UEdsYlVFaXRHZGg4cVVHc0s4
            d0lZcWJGdUd2Z3hKL2R1RFlIak5IaWcKLS0tIDlNcFF3Mnc2M2tBSHFwN3BwRzBa
            ditWRmFRVjFLLzJydHRHMVo5Mkd2MUUKeWRpu+cdfQRwXRRummU6aas3VWVC5wbL
            9MXJBCpRF0ks4ESfQ9si2MDiVBIutix3KMBkH9lZl+vVFBmsIzRT5w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-01T01:27:09Z"
    mac: ENC[AES256_GCM,data:NEfAzZ34p/AVKIOBDmYjA34BPn6J7syD2BFe3CF7Ms6ye6Qg602lI8P9XACIsguqf1h/FTsCiCXxCXYdbHMgUvUTnejXZxzlXAYGq6/EdZ/Y10ALnbZViZSRQneJ/ByDu5LrfSWltHS85o2Dan22ZVpKumLFEzzm8HOTvx/TdXg=,iv:8Rbv4LAiywUkeie2pJQlyoTInJZOSAQB6py4iSk8+nk=,tag:3tcb/1GHfcDOYNVPx7QBuw==,type:str]
    version: 3.13.3
