apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: attic-s3-credentials
    namespace: attic
spec:
    secretTemplates:
        - name: attic-s3-credentials
          stringData:
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:CShVbSDFTtPJ43wabanLDrEEbsAW0ZIbAte/ZKrc5ZM=,iv:Rcs69M/f2xYFevm832Ql+d1yCSocyu89zYYTaZu3HmQ=,tag:1UaDbEcxOz4X1iUEsJBMHQ==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:lZxM3RLytA5KxsbkUx3YK4ZN1bmDkjMoJ0FsLWyYIoA=,iv:6XsV/tltgD8XQZEuXz+UbQCQIIUyETM9ELt79GaDSmQ=,tag:T565PluXjfJexhKGa3jzAA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSG93MmtjMmpkYmViUHNp
            b0ZiR3Q2T2dyNkwvQVlTRmdkcWZzRGVtOGk0Ck9kRFVtWTVpa0JBQnlWeVRDVDVL
            L3Z1WXEyeUhaZlhUaWVJa0Y3WUtNRVUKLS0tIEh1U29wM1JsVFhrNGNiUlVLOGZT
            c0RzeTlOaGRmWFBrWDQrWkwzVmFXbzAKQ9YoB6bPfPHoJzu2pF+rcx//ig3WQU2t
            4Mdi6Ap4CR4B2u1cXhkG+lXgNw+dStc9/zfM/5YLg1nVqXAZ54XcYA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-08-11T22:52:11Z"
    mac: ENC[AES256_GCM,data:163L/yRV1UWqZrARCmMSfq1n3UsZiLXHDqlN4j5LCPU/8I9prMybHLHgcoqN18kt3fWJM7Uhu2ci493iVLBUnrO0l7Zu1FlEuc80U/otLKmXqyQCOxQp32SJrcUabyYOuLS2mH2w1cmr77UVA/nH3VKMTn8Y6QiPFawYbO8QXy4=,iv:ocq5/XT16uQuz+66Vsx+fnylZn+5Ua4urHJBhehm6us=,tag:G5eczY37n7rGeVa+owgxRQ==,type:str]
    version: 3.13.3
