apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: attic-token-hs256
    namespace: attic
spec:
    secretTemplates:
        - name: attic-token-hs256
          stringData:
            TOKEN_HS256_SECRET_BASE64: ENC[AES256_GCM,data:fVlikQsGwXFZAICx/h9GtlguOeJJMKGS7zqmnYYfjzWff+a7aMkuFge0lzM=,iv:UtggM/5L2jgCP75PjZpxZ/lB7D+2dG2PKUUtelQgf2U=,tag:WKTm0SQ9ER7AsQHhgDBC1w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaTJXWU5BVTdTRXRKR21o
            dnhRRXJ2ZERkUzRVNXZ5WCs5dWRDWDBDT24wCnJnTVdmRWROSTBxVVBKSkpZaTFo
            UGxNQW1kdnNjZGJ4YXIybEVRR1FyM28KLS0tIGpqM1hYZURWWUNnRzFwKzNxL0tT
            aHlMbWZFN3dYZURaQzFRNC9IVGVKdlEKL6nRKjUDI80vT4a6kcgIyB/gX8bPvsbw
            om4JUGjyQ3BJWqo7vvCLG50M/pA7ay5GoYMrXJJh3Br2EdrIBqyCGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-08-11T22:48:55Z"
    mac: ENC[AES256_GCM,data:1GL2NQca40GG7yF58QHquJ7VzglN3PvQNkUPBExQnxYyxvTyE0grYp4CoPCpabyxREr0AVvTXrAQgeLKr7JSMjlwDmH3nTXGWgOeyR6QXHz4EUmTix8Mc7vdziPL+HXLvO2AFaiRzLEqiAzwP/uhfyFfqIR+2HnBsKilnvvEoso=,iv:JCoCZBHSPnzhBgxL3CPYPZEtxjrnyPOk1USqBRQqDqc=,tag:yEn6sFfDN+e+ncFktbquqg==,type:str]
    version: 3.13.3
