apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: attic-database-url
    namespace: attic
spec:
    secretTemplates:
        - name: attic-database-url
          stringData:
            DATABASE_URL: ENC[AES256_GCM,data:BMd2BFwF+2q89uupEtyoZdGPmGqhNkNNjS/4wYWWn/xw7+3ynMWt2v3j2+qyd944xNuoVMV145RW/dYCzLMZQBi/KD56tDsqDh9nN1+4gUDYJzl2,iv:pnAQ0bDMwV71ECLZEv6uszVm2iA4Rl+AikRRTAwoULg=,tag:dL9s6puSkGnHx9QAz6CJnw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVVZYN2dsT3JYWWVRTnRZ
            d3lha3dPSlJONjQrdXJ6TGloMHhUdG1jNmdZCjRiTm9idDdoNzlUZjdJRUo3ZGtQ
            VldaYWtjK1d6NTJ5SDFtNk8xcTk4L2sKLS0tIFp4eGhaSGJEY0gxNlplNnVMOU1w
            dWZKNTcvVnlpTTF2Mk5GUFZKVFFTejAKOUeenl8xs/bn2grXyZg+P+U23VQs37Vz
            sH9wfTIZkPxLxBhZloYr5zJ7dODhqSctbgbrsE6goQuRrK9M5m6zxA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-08-11T22:48:54Z"
    mac: ENC[AES256_GCM,data:YvcmXpF9MOEJntrhGvhmJGtiVHP3xIj1UJ5HcITJUlif+1uwu4nqHfA7+xAUP/2CkNt7FzsneWWhPRqMNErLd4B4VPcdKHUidvzfxrbRuh8wZALuMlGcO3Aii46txFWiNeg+dEh2FxKeBQthn9ZD3BOELM7+45Yw6Ou6SaOJGy0=,iv:sGkXQfcqT/NVvPuSZ8SwPOrnekQyAzf9H9ebl3GC+4A=,tag:/nKXEweDplU0tnF0p8e+2w==,type:str]
    version: 3.13.3
