apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  labels:
    app.kubernetes.io/component: ingress
    app.kubernetes.io/instance: superset
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: superset
    app.kubernetes.io/part-of: superset
    app.kubernetes.io/version: 6.1.0
    helm.sh/chart: superset-0.22.7
  name: superset
  namespace: superset
spec:
  ingressClassName: traefik
  rules:
    - host: superset.home.kronkltd.net
      http:
        paths:
          - backend:
              service:
                name: superset
                port:
                  name: http
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - superset.home.kronkltd.net
      secretName: superset-tls
