apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: superset-env
    namespace: superset
spec:
    secretTemplates:
        - name: superset-env
          stringData:
            DB_HOST: ENC[AES256_GCM,data:GHicji/yAotchcEE3djBXjqa0oZm,iv:LVRfx0/sdlYdDwJx18oh+jpX1yQ3ODF0sGKb/g2RQLw=,tag:C+XUIp81i8tRQojzzRLiCg==,type:str]
            DB_NAME: ENC[AES256_GCM,data:+Kq4np72tVo=,iv:jGG1jA3ali1jXY7Z+s+FXMwMSdK1W58VJ2YWhJXQ6JY=,tag:7tFqf9IIQAtEe3JY/WWR9w==,type:str]
            DB_PASS: ENC[AES256_GCM,data:kBgk7WQzuIR9FcsH8KHhbiiJR2lnF0m/ThHetla/EG1xWcNc1f9065ulfrWi/igt,iv:cXGDWgK88kKYR68wvQXSR1eSt/6LhIuxf9VW+0ppmnY=,tag:SYGr8ipQivxXmLmFTpiE4A==,type:str]
            DB_PORT: ENC[AES256_GCM,data:X+3AoQ==,iv:HGNgSjmHybHjEhjRWQIXpMAYpyrFRXJFt/STEsNORPA=,tag:xmP298leYhSSxZgUD3bHaw==,type:str]
            DB_USER: ENC[AES256_GCM,data:8avFXNwl4Oo=,iv:5cPRnI+CbEHX5hMvFtFRT/WvbuVq4AgQBXLV7ocwy6Y=,tag:/xonUrc6xEVyoCqeJrO1pA==,type:str]
            REDIS_CELERY_DB: ENC[AES256_GCM,data:0A==,iv:+oJ4oQiA1g5z4rPFC4PtjbHC+eKRDmhvvRJCtGlXwr4=,tag:g6oMux5o2ZOoGAB1xgnznQ==,type:str]
            REDIS_DB: ENC[AES256_GCM,data:fg==,iv:jmToMC5tsflqDafiDAGbje19Z6BcV+020k/pNjGL7so=,tag:kJA3Knk27vaYupc3d3fn6g==,type:str]
            REDIS_HOST: ENC[AES256_GCM,data:6/bSmiSum3dg8vg=,iv:JhR0gz30imkcBoMTpPRxaeX8KH4ph4/x5lu/hIm/GoA=,tag:OwAKKXW8+1Oo7kRn4yPxOg==,type:str]
            REDIS_PASSWORD: ENC[AES256_GCM,data:YM8T4WkPgyE5pvmdCGQinfZQmxk=,iv:JD6YOVVFvEOmMmew/w0jtayZK2wuWrkSg0xWmvJAS9o=,tag:H/2F/Hkjq/Bi6eilmM9Qtg==,type:str]
            REDIS_PORT: ENC[AES256_GCM,data:/90NXw==,iv:JQkMJuOL8nOeY58cTrXkjSBiC9POPhl8Nr2oqotvui8=,tag:pirbuS8VT7amlQDVnwdX8g==,type:str]
            REDIS_PROTO: ENC[AES256_GCM,data:beanUu4=,iv:wT2qbLrm5KLOil+TJNWne0zb4xd+T08c/1eyjeTpGOM=,tag:6wH4R49G0wRTpzDERPTZVw==,type:str]
            REDIS_USER: ""
            SECRET_KEY: ENC[AES256_GCM,data:aDGAwTTtLywoXtM/P91EY+QcJex7pf/nyqA8dUZl+bCI6sbHGQjISbU2OLrKgZJFA9wmzRiZFfQi933Xcwkx0om5wqLRo0ToDzBQKAcvLl2qoMbE,iv:J3RGIPyTV4jxMZ+dXesYAlwWU4MJ7l3/LVhQy2gqUcI=,tag:Z7fIzz8xdQIT7Xuz/hLpQA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZCtOZUdsb0ViY0RrM1NI
            RENQbE1LRHNUYmdFbzk3bzhPWlh1YldudUZzCmd1QnlldHdYOWw4SjdwT29ISHIr
            eXNhSFBKTEkvWnFqMVhIUFVyRzZ5U3MKLS0tIFZ0aWc2djB0MGpOSEl0aVNPaHRK
            M1FNTVJUZUpmZlFJMk9ta2J0NnZkcDgKiJuxIlX2I+wWXhASsqqmHnSboCOE5DID
            vKQT1tRXx2G7Y40TALritiU4fqYgM3UGaBYl+CSwFxxr9tKV7qrouw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-10T03:33:37Z"
    mac: ENC[AES256_GCM,data:a5bIi5ZO+OnBhVR5JyGUSvmG7ACZNmI5G4bVi+7/MboCOM5V6NKY012R4gNe18NGb1kneG+6ew9rJnstUZpWdLn+Pj9HHqA81gP8hPzfsoEG2I3PHd0YoY7vOT5yfUEgPl7Xmr51MruY7M4Gz2PKv6lea0XzLmo+lhDDPMXDg50=,iv:HVXg0o+E/m+Hu3fMvlr91UZjLU6IiUld8uGpnkyIY30=,tag:tTZLPwVp+l/j71wl3HWZHg==,type:str]
    version: 3.13.3
