apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: superset-admin
    namespace: superset
spec:
    secretTemplates:
        - name: superset-admin
          stringData:
            email: ENC[AES256_GCM,data:uZlmIvtIUsTSquBsp+4FVgI=,iv:UvtQ7n9p10Z5j3M/HfNAVmrlRfbQSCi3194+lgXQ9/s=,tag:wFAUdZpFfZQh4gasLHZdRA==,type:str]
            password: ENC[AES256_GCM,data:xb7acpcfPkOs/FzAoPdsdrVFZEe657xpFPLf3/P5DBV6R5MuNrgbew==,iv:yKRU0AM7NmYBMXqp+Sn9SZnNE0Q+ExQ4mHq4upzYgKs=,tag:L94d4u9DNxSyQcdrrY7KXA==,type:str]
            username: ENC[AES256_GCM,data:hYTx/5Q=,iv:VdZVC+uJ7cuLWEQ3bwQvL4hbWdwHO3GQ+iNeDcqqxQg=,tag:rmWhfC2/N0hlg5ajb1kfvA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvYzMycjl4LzZXRENmeGJq
            aEZqbnV6NWtXYzNYVDFnd2p5cFIwNnpWb1ZnCkxjcHhJTkxnVlFSRjJjZ2R6TFhC
            Uk0ra3liaGp6bXhCcHFUM0F2aThXeDQKLS0tIHF4MzNYNzl0Qmh2amFOMXhMNW16
            WmJGL2dvNktMY01CS1JGWVBmR0gwUjgKw9gjTtVUZMgYW8Wd1VxVd6ofasXyg7nn
            etsb4qaoKEVOgT060y44EZKjcsNR5TfxLsPLoeMDMT2yhu3HdKJ7Yg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-10T03:33:37Z"
    mac: ENC[AES256_GCM,data:rO6tlqNsWPl714RGFfviFF8t7RMFtpmDKV2q1b16SzLbWYFYUzY3l1v8xFV0jkkx3hoXCmK4CS1sKG6jXRItfI+qY0VQ/quq/afkURDuNhCKOgx748EPigpgRkeJiVEydTScRe7h9KGZbl5jbaM579MbmY91qQjRrwkCxX+9qxk=,iv:kvokLXywI8X26e5M+UFL1PyDmX0+UPetn6+wzL8fk8g=,tag:uTFbXrP1WYu4opukAaEmSg==,type:str]
    version: 3.13.3
