apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
  name: gramps-web-gramps-web-cache-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      dataEngine: v1
      dataLocality: disabled
      disableRevisionCounter: "true"
      fromBackup: ""
      fsType: ext4
      numberOfReplicas: "1"
      staleReplicaTimeout: "30"
      unmapMarkSnapChainRemoved: ignored
    volumeHandle: pvc-49f888aa-c2b9-4a5a-9b6f-ee96c10f8e6a
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
