apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
  name: gramps-web-gramps-web-secret-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 50Mi
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      dataEngine: v1
      dataLocality: disabled
      disableRevisionCounter: "true"
      fromBackup: ""
      fsType: ext4
      numberOfReplicas: "1"
      staleReplicaTimeout: "30"
      unmapMarkSnapChainRemoved: ignored
    volumeHandle: pvc-c604575b-fd8f-4597-b3f5-dd1a51a1aef4
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
