apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gramps-web-gramps-web-thumbCache
  namespace: gramps-web
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
