apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: gramps-web-redis
    namespace: gramps-web
spec:
    secretTemplates:
        - name: gramps-web-redis
          stringData:
            brokerUrl: ENC[AES256_GCM,data:dlZ00mMGESSPZwShNun/Zb9nO7gTBvaTnn9bGHs+nfYOj2MlENCO+5XXnETsoUnengwDiTP+N9FbdJUlDooUJw==,iv:rixUe8ha6ogmYBoMaLG/iMDpb8QUzsevA03Sagug15g=,tag:zEVhKRDexJSCs1A0A4UJ9A==,type:str]
            ratelimitUrl: ENC[AES256_GCM,data:iYwZE+K2mHRm5bXPZvBLpJ4br3LjN6DUcu5JO6ath5veeaM9023v/Nl+9gS1LLl/MtV9P1it5xV28FQnE3LlkA==,iv:fY0kj6N99lRB4pQ+lQ9trjWzkQ2vPuCteMhbMFd5V14=,tag:2mdAZW9kk0dtjMo6fw3+rA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZldzaGtsME8vSzJYV1hE
            Y28wN2lBeHNpbm8zTk54Z1NPTWowL0FmbHhzCkFrRTAzbHJFa1puZVc0WlBHNUFl
            endOMFAvY1AvQUR2Sk9UdkoyVEFpRlEKLS0tIDFhK29UMHRsMzQvQjJsVUxwcjEx
            YzNpaWQwWmNxdVBXMzcyamw3Y2xKSEEK5/Zld+NyOYAxrnY1UTnLiInL2js/BuFK
            yvR6uHOKqheoA85R4gf46dLbixxP99Kj4GHZ66yR1/ZZuC0GwB6ijw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-10T23:54:17Z"
    mac: ENC[AES256_GCM,data:bGEKjCTXfLY/WSvisa/1g1Nn2WIpTCKjIqpe+N6wzvlVblCJJI570bPi9f1WRg4Curd1eYbEk8yPen/j518wc5Jg5zGqvuY2bs6ad5BDR1zA0c7bn/H/FeTjHHXPd6xxc7Ef2GLk7zohYUh1yN8by4umwbBvdQBB56oe61qHm/c=,iv:0nLJiJOR7xfpd60ztSkRwJjqIxA4dqU8QJK2vYWBkQY=,tag:++VO3H/2O8fhQXJL0ah8Ww==,type:str]
    version: 3.13.3
