apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: gramps-web-redis
    namespace: gramps-web
spec:
    secretTemplates:
        - name: gramps-web-redis
          stringData:
            brokerUrl: ENC[AES256_GCM,data:w8YXUIouI3EewHAArMCSkUtsUhL/BSDNu8VfFfEWFSTZeXeRDYTSda4uh2QTFfMCJkMe9wYzSzXPSNWn5VLl5Q==,iv:kmxoAArwAydIslcrV70mRc5qmz7H5v0hHxrW1/kAgys=,tag:ob3zoGDtS8HwqqyQLQNEUw==,type:str]
            ratelimitUrl: ENC[AES256_GCM,data:XshUM4EmaQx4/n7ypqqGF/Lqciuo8C87JkT3nVQT+9n0zVXRHBmkjcPyL2zwtJje9L6SowBZApv6VscydcdqTQ==,iv:posVVgSpoC4bSgW4ZemIGwDH4iF0PfCg+4ccALEhjOc=,tag:W6LaVgQiOqEP9L/mx8iWRA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvemhVTjJ1NDBDVEE3YlMv
            L1d2MGpJRjQ0ZVY4N084T25mY3p3YkR0bFhFCm5RZmNyZ0F1amY4STV1SnN2K1Np
            NkZ6K2N3Rkl2bkFnZ3Z5aGI0WUNrdGMKLS0tIFJsUmEwbkx2L1lBVzVNRzY1UEt3
            aFAzNnlja0pMVjJTaStnZ1pRNGdUTEEKSPiNFpgMiNhz6Ya2dq/RmRurOS3JhA0f
            fsJX1yZoxp+NdkU55cb1rziQVMVPA5wk1MbbL+yZvp0gW5d57Wkwsg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-10T23:21:11Z"
    mac: ENC[AES256_GCM,data:GKH5v6ZiHK2UoaK9w9ICroy9Uc/oYQwjUZg4Esycafaw5di/1+EKn7XGYVG94YhTX/NNwlrdrraHfTHO7MuPYrhdv0/SIdp32/4O6mQL/RPkp+dMk32VB4IySwgjmmab33VW6l1GuRPA2mfdNtFICOj0HqIxNG34gj2XV0sD/kA=,iv:7lSlgiRb7z8so5iUguYZ/r99SNbHRZ0Jlb8zfxU5Z+c=,tag:hzfoD6GBZ7quggNj/nFNpA==,type:str]
    version: 3.13.3
