apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pinchflat-pinchflat-downloads
  namespace: pinchflat
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: pinchflat-pinchflat-downloads-nfs
