apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: pinchflat-secret-key-base
    namespace: pinchflat
spec:
    secretTemplates:
        - name: pinchflat-secret-key-base
          stringData:
            SECRET_KEY_BASE: ENC[AES256_GCM,data:+BmPAaknkN3mvCSdgKb91az5KhpOgYcyTgkTVaBaJx8WNaqWFJDtaWJQ2DaSUxGaQEtpJewyl8ACTjgYFno5DQ==,iv:1lCOGOS0tkxSk3hcNu19Frx58tIT146Pp1Jw+NLi+S4=,tag:CYEF6guFy0/k2dcdurjJPw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGV3hsOEZyM0pIVlVDdWNs
            aEZ3aDZUem9XcHhrTk5iTUFrTWpBTmRDSVZZCko2YTVsMzJMLzJvMWxWRTBBT0JY
            a2hmN0JUakg4MFVvcGlmdEI5VStDMnMKLS0tIGJ2WmRLMWFCS0JRMXZmT0ozemhF
            dGFVWE9NRjVOZmFxWGVRYzU3ZzN3VHMKk76o3TY6ojs8l4+eogRgSzhvNHG2ivCp
            wDMZQGcip8eLkZWRwKfAk+Js4vI76CVodwjGOUNeLjwMnko/RUEj3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-08T03:48:14Z"
    mac: ENC[AES256_GCM,data:Ucuruk24Cy2ZJk5KWQ3QDsocxUOHsOS3jPIqe8Y2+5SJpg9IPVoWhEjBb9f70lxwMyzA0BrSLeT1KMm9js3jWY60tPMCNE99XvyuqmPhwM/4t/o7XShXh488fJkxV29MocG1YOx8C6Acv9WSkqe7RTVpYMtTazN3vk4+PNAJOB0=,iv:zdj0m7JvUqboWHhcD9KwaXIBvA7uGz+brRukPw84YAQ=,tag:wOd12uRTEZUzBPKB5Nr/7A==,type:str]
    version: 3.13.3
