apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: romm-admin-password
  namespace: romm
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHbDRuSCs3VGhEcGNmeGhl
        dklRMW5vTStBM3B5S3FpR0E4Mmc0UDVLMmxZCjVBb0xaMDV3UXpib09aTzd5VmVH
        U0hXdjNtN3Q1WWFFOUd3L1lwQUdKeDQKLS0tIGtDOE01dlpIczh3UEtsenE3ci90
        UUNRUzcyclFWbEhCMWNMVC9nbi9lblEKIAmnps2CVhJGkk5CWzUFGCGQpW0unH43
        aHvmtoZ3DATRa7K+epu1/oHAi+owlvSERqnjn111dUhM4s3Mfl0OgA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
  encrypted_regex: ^(stringData)$
  lastmodified: "2026-03-28T20:11:23Z"
  mac: ENC[AES256_GCM,data:bPHJP3nOEJXbEFvwd3Wy/DRrTG3mpApZCwCMu2VGo7yl53kHkCq4Y8X00N6yRWBlJDEhIqTD1+RbdhpGYxJZIdxiFmH5Dk1cDecu6OtWjgKJHwCVnu/kSJlH/aaEnW3+vYU0PfPhb8UzSIKxiBX650QgJmSObuA0wd+Bjeb73KA=,iv:sl6c/ulaUgCtsWuEOHiDeZZS7THp2bnO2HraTN1XlZ4=,tag:ciN/fqlOlgDXP4ZMUiG3eQ==,type:str]
  version: 3.12.2
spec:
  secretTemplates:
    - name: romm-admin-password
      stringData:
        authSecretKey: ENC[AES256_GCM,data:gqxV6Si8Ip08r2i5XU3Xve6jHls=,iv:9A5HSkmpS6+9wAxeNzGhzrttdNK0CTp0aN+Y6gbA5pE=,tag:GN3M9Epd5WtAXWS//94qLg==,type:str]
        password: ENC[AES256_GCM,data:Yx/LMUBWhmaKYS8iHpe15Q6m2ls=,iv:+Aopg5Vcr5z877JRuVSCZ/UKtAopLYA2IZG1VUYCXH4=,tag:aNqq6vrgQ2WWTUyuAuqPPg==,type:str]
        username: ENC[AES256_GCM,data:t3BRnZ0=,iv:QNy17G05h9PfmL8L+d+fKhTiOn2U57PdJEz7mVcQ1xc=,tag:eQnwiIzjjnNh5NKnGOkATw==,type:str]
