apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: romm-database-password
    namespace: romm
spec:
    secretTemplates:
        - name: romm-database-password
          stringData:
            password: ENC[AES256_GCM,data:k0hGaKdlEJxULdeb6QTJ4ea4DYE=,iv:sA62Blwb9JfJxWgXc6cFpxQs3wnId88F/rgg9w5yrNI=,tag:FtHk2vdBXNSbcBYGXuuV/Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUGI5S0ZPTCtWT3gwbVRP
            SUIrZk44bHE5VzY5RDljeitjVDNVZzZyWEVzCm1MNkttRG1RK0Z2R0tRU0FEWEd0
            WDlWYlF0QXdPR21pODBpeWNBOWtoY3cKLS0tIGJva2o5bE1OSElLWHpjZ01HSHc5
            aWRlTzZBZnRzMG92cFhyckhuRmc1MEUK76iDg13P27FjEO9kmLHx12cpbJcMMUEs
            jDjR3D92kvExJrvFRUG8bIeWt7ec8aldadk0PRQdWfXiD0aWKYqivg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-16T00:34:47Z"
    mac: ENC[AES256_GCM,data:SIyNTcNCIDHy1iIUebQzNYwQw2sBV3fPH5OiWkBwYDrzYhkNmOknYBEVSwPVGyxfyxl67kVLDGxcIAkQyh7Zd6kcVg1JlPwdaghkq2OHxuSG3bHtqdrxhCYNyooRbOfvjZLDNRnQyjVkw5vrkBfZhNZ/gPn8gogeW8+vYElfSz0=,iv:FYnw0IJKbxrqOMEd99xxwq2MLMnDS0LcQ9EMRfMfbA4=,tag:5D+BoMqmdeUVg9416p+sXQ==,type:str]
    version: 3.13.2
