apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: romm-database-password
    namespace: romm
spec:
    secretTemplates:
        - name: romm-database-password
          stringData:
            password: ENC[AES256_GCM,data:OjKlQBO2ETIDw8cNHRnsYe4In0o=,iv:fkUscetqol/p9kez+GxJg1W63RYJkw2gc6LPf4nSDTk=,tag:NEr0HZo99oqikhxIsC/CzA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkYjF0Q3UwdnNFaEhEb1lp
            K3k2SFRxRS9Xc2JxL0hRU0NDUU5zVXR6Ym1ZCjNXR21VUzRQNDJWZTBjQ3VxZ0Rh
            U0ZNaXZoSlZsN0ZKcFp5Wi9MVzlzMWMKLS0tIGxnQnY2UVhVdUdiYzNBREV0WVRL
            dlVJK2phb0NjTHFmdUVadzRVSDN2Mk0KxzAe86BSE4eQ40byBFu9Ba64ZaPZn6NO
            mhhNc4cCKUiBGkwONsNATIB0MmgmO7QcTZwIQdUeNdsnHUhU6aDHiQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-07T00:37:45Z"
    mac: ENC[AES256_GCM,data:H4ijtbk5IpgJzSkTFM/qBHXEDaq6dDcljIkxL83mkaJOlWLYb13tvWWY7ZirldHAMd0RSMKeCJ25JkDxvwln5nXHyLeRay3MMBD5SjQL7PadWDJB4OB8VL/aO5bwcIQDs1/fZDxabzxVXsnldlMQjAu4YVhhrt6wOzGDbIk+jwE=,iv:Zr0VNgFC4JlI7/zXK/lijq4zO5PfRkyBV4eaCpH7YHQ=,tag:OxlqlC14Iqk0KP2ty3oE+Q==,type:str]
    version: 3.13.1
