apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: romm-metadata-secrets
    namespace: romm
spec:
    secretTemplates:
        - name: romm-metadata-secrets
          stringData:
            igdbClientId: ENC[AES256_GCM,data:M+fQJxZaoHKLdB8HXI8+HWJYa8qnbiG1QeqeAdN5,iv:Mu9ENw5O/zE+K9qaS8f29bZ+0ES8YFlBM1VDJ1cvB9Y=,tag:IbEKL0GJ76mNBgNETaJF3Q==,type:str]
            igdbClientSecret: ENC[AES256_GCM,data:b6bwitiP4px9NNMkndYLSi4zz+JNWtltolR6ezpA,iv:gnGvrepnHkSVyd4FC3M7RgKTD83P+j5MbG4+6aGu4ak=,tag:LcKZ50caD4fLEw2urcxl4A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJd2hGN0pJUmk4TzNmUE5P
            cjV4bnVDVElET2pVQ3J5K3pBbjNiZUI4bUQ4CjJ0R0NuUTIrV3BkczVMVmJlSEpV
            TlR5QXBQdnVoMlFqc1FuSm5GZkkxZkEKLS0tIDFvTEFLbldoRjlYcXpFejhLUzdi
            aGRJeFdSUWRpbWtOWmM5UGNzRkVKSUkKeDymBhGLnhtS7c4zv602Lo55whqwHlzY
            u3G4jy7q0VOKLU7D0YpjUH1WZKEwicPlZ7TohPArhf76EGco38CCYQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-05-29T12:14:28Z"
    mac: ENC[AES256_GCM,data:8BBtTjo3gLelBzqP1K2eV38YBdl11xjrUspHmT6b8XCP8gyWAwZhUmNRtBwNpox8XE/Tz2DGnevLNdI74IgWnN3eHox+zESqRhk+95dAsUrArJlaSXTLklTLd+lnanS1QtNEYMGgwNNJ1gXtgJc0IpppBFsd6PCDG8s0V8BX2Q4=,iv:hImBkuXzOPLVCjS64L2cWv30dwCux2jOx2bC6pD9gsU=,tag:Bf50O7SvGUSAYmO17jZA0w==,type:str]
    version: 3.13.1
