apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: romm-admin-password
    namespace: romm
spec:
    secretTemplates:
        - name: romm-admin-password
          stringData:
            authSecretKey: ENC[AES256_GCM,data:T0ST4KiBbFf05aBNr4xNVTVi0mY=,iv:FgMXB+7+ap3M2N/Ak0JRDk7t/do8EKWIVR0+SPkbNb0=,tag:iQK8n8FnSKj73PNZme0akg==,type:str]
            password: ENC[AES256_GCM,data:SeHYMe4r8ZE4HAtewegFA0gSaHU=,iv:bWLvgct1iCN87OpmLSjYuWTebAKVmWPRZ9Zx2mUrAcI=,tag:1WFDVJZ+h8HUgX+ugN8h/w==,type:str]
            username: ENC[AES256_GCM,data:cIQT4cU=,iv:cniCEQe0HyEjSSvxTWwH+Z86fCecMqQoE95Dnvs4Ue0=,tag:GP7RFOZ5HY1OM9s4RY9z8g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMR2pBd2pUcXZjaHc5a2JS
            K3FQT0dGVU84MkJzN2FYNncvNmQ4Z1MwNWpnCng1NzdHN3ZaTnd3dERRWWpvU2xG
            WlQxVzdaYVBldHI0OStxSTQ4bHBUNEkKLS0tIC9Ob2V3bS94Y09hWGt3NFFIcldp
            amxkbE1JNEhkWkFlQ0RlZW85QThkSUEK3JW3P5M/JR5UkXhazZ6psiqXdKpjspt3
            RImww4trJ7TeZAVRuyvliKMl+tKLqvmqUkVFbUDEyHPB5G8zwmlv0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-05-26T01:57:41Z"
    mac: ENC[AES256_GCM,data:8hBP1sn3EKpnQzHd0Z/C93f1UlxU7slLJN/zMS37O97a5iIfCGs7xSU9h2XFO9ZRv6ortDK4p68H+6cTwrIMemNP2DVYr32eQMTiw7sHTEZmnGuIkEkClwhc4bZMVmXXDK3W8GRtBgy4IIOv9u76SH8gftSpmxUgWFTEcCZGHg8=,iv:onzazFCqoGW2eXrKJjhm8l34jpxQt8+IRAX7girO/l0=,tag:isn6rMJZTB+uHx+6xGf3pg==,type:str]
    version: 3.13.1
