apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: romm-admin-password
    namespace: romm
spec:
    secretTemplates:
        - name: romm-admin-password
          stringData:
            authSecretKey: ENC[AES256_GCM,data:CKy0cnw0pSbQKLR+R/hr/UuWo8c=,iv:vIsx/dHkswBuy8L7UovakeZmUjqKYjyPHljYrIDPfrs=,tag:Ai7H7N8/BfKZB6N3aX7YDw==,type:str]
            password: ENC[AES256_GCM,data:7zbRuUJUbO4ijtKKJ6tE88jxriE=,iv:DGKozYdoUzKjyL75fkYtzXQqx+BnO79lwQCsXwKmcqI=,tag:HU87s1Qe+XqqV4sOgO04rQ==,type:str]
            username: ENC[AES256_GCM,data:tB8UiqI=,iv:jK1PnvBRqRuwHIC5+osef285pCo4pWmCZj8UPcBGbm8=,tag:r/GmDX/4k9oTDPqvi6sJvA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNmtlNVJybG5xYU5qMVpl
            NEhoQVZEOUhlL3RBNDYvU21DZjVZRUZaUlZJCnNoTXZycFhoOUJIUW5XaGNrZE9V
            WkM0QTBjTm9acFBBcGlURXJpeGUzbzQKLS0tIFhWZ3M3VnJvaWZBRHhhQmlXaE84
            RkpzRXRFaE5lWmgzYSttbnhIY1Q2K0EKYCNq51xnM+mIsohyl/0LwibFAfe/A6kT
            NgOqcbiQbRokKITYICor/axSOmPCIqYZb2gBoyWaQ+NZENn4sUEqtA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-05-25T03:54:07Z"
    mac: ENC[AES256_GCM,data:EY7RgsfXUpSjlVKX2msIn7NB/2leyprzQbaEOc7Csde+N2WVVUtGvLsqWNrtq/T80mCXq95fyWFwBOvZrqPDajEfEbTf48IvrRW+xc5EIVf5gQElHfvTnZXQrFGtQFNou5y6HVKjb/vBnSavm/ZCSXpwg3CXe5ZS3l7nbwJlCCc=,iv:4nhDpDWogdk+nvPlncQNXo+TMqSCuEzJ9ZG6K0im3dM=,tag:tluP3lQaG2R5mbjktZLXtQ==,type:str]
    version: 3.13.1
