apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: romm-metadata-secrets
    namespace: romm
spec:
    secretTemplates:
        - name: romm-metadata-secrets
          stringData:
            igdbClientId: ENC[AES256_GCM,data:vKbFLpDGZisJSjurw1TtRT7zGortbZLoIPJ4bUK4,iv:u65gOKvgwhh6Mrt5tD7YpeAq/WrL6AB3yQgvmet/XZI=,tag:jgzVvW6ax/7cyYXr/iAhjw==,type:str]
            igdbClientSecret: ENC[AES256_GCM,data:8V6ldpckMvq1dGWAbz722VDouX+GENKY5CDjK3lY,iv:Updaz3+7LRcD32s3z34ssduKz3Uvc+LZ+2D0suskLHw=,tag:mdbohi4qgjBcMcwFkTtu3A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Y0lnR1VUV2FjNENwRFJX
            WUJGSUo2RFBmU0F4dm1NTVpCMkE4UXBsSzFvCmcxSDlwaEVGSEViSVhSamF1eHpa
            NTRUVVFuRC9DRlNRZVdzbWZGckxkRnMKLS0tIEtkSHdYL0VmN0NvcUVWc0lNbm01
            T01sb1RMYzVyMWd4TkVIL2dGbTZtdGcKh3mLYUUesb++4NgnnKrokEPwj/3i6EBQ
            dpZ5qpDbF/KmqpawzW2MyPGY2zLVPyg0QwTU9IxxFGGIWVsRhEE9Yg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-07T00:01:26Z"
    mac: ENC[AES256_GCM,data:/cKqAhiXy/DKD6k23gDZtIXz5fKqHWI2F/f8tUN4Sk9c3LoCp9dV51KJkQj9uQL7E4WOxcN/h4IaKGGClBHQFL/4eVDthqAeahAyX8ow6uj0k7y5bZQj5+CzI62ilurnf9j33UWHECzMBjbCxxRW6bkm3HAdyIf+ihAnYhS1wfY=,iv:zVdjSFlIuvQ4H8KJrzqD6Usp27js253PR486YY5qaYQ=,tag:WDBYLlD3+YBD4e33HColSw==,type:str]
    version: 3.13.1
