apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: romm-metadata-secrets
    namespace: romm
spec:
    secretTemplates:
        - name: romm-metadata-secrets
          stringData:
            igdbClientId: ENC[AES256_GCM,data:TQwlhjv2JsmGt3TZ+i9tXTVkEwUL1cjrSdFu1P96,iv:Xvavo9+PQ8nATjKyUoO5thBziMPJUFYrVk+xHoV51jI=,tag:wqWR3LdLjX5jSfRMB0vyHQ==,type:str]
            igdbClientSecret: ENC[AES256_GCM,data:blL7Lll4IfZxO6aBm9zr3JNEnj9gLhiW5Z2PYFhX,iv:ok7M4kE0ble2Kq5Ez1u20aNRBC5ZFQ8C+VRDaZn7lxY=,tag:fRlLBqezB90xnRfFZl2jvA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ajRERGNNOUMxVitYQXRz
            K01na0Z4YnBnWm1SR3ZEa2NlUi9CcVJBWTA4ClZFTCtxOUtUUFkvZ3RldnpBb0ww
            Wk9YTkE2bWZjZ0trY1Z2YjJaU3FxamsKLS0tIGlzZ20yVlFMM0V3cktaTXRMazg5
            WFdFeVd5cXpuNUpQdlphY1VLeVhkU1UKKdEYl4/dIoKQEbOxvD+vbc8PiOoAFDtB
            SqZpwaZOOhmOoxKCabqMPdremJmnsSsiW5OaboUlof7dcQBJN1n4NQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-07T21:09:40Z"
    mac: ENC[AES256_GCM,data:cMPv5f+AOyLRQFtgrsLAK2lt8pPGC5xM6uh9RFb/q+TibCCoMZA0zGbgIknWaUdabhh1Mx7t7jOIdXbFA9ElWKlUXsn7FtYpsBBVl0EykdVLrpmLL/SsMWAz6Ssxs8Gy/RmzBLyTnwHfekuzaYsGBoD2+d1SNhFgu3okNkrdN2U=,iv:yRAKCVOekOJ/cmTwRBEWk8AHbvW4Lpac40OZOI9SMI0=,tag:lKSwBumEjHnhtzkrDadI0g==,type:str]
    version: 3.13.3
