apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: romm-database-password
    namespace: romm
spec:
    secretTemplates:
        - name: romm-database-password
          stringData:
            password: ENC[AES256_GCM,data:P2ZsNOI5/MFPHWt1xGFIRlVLazk=,iv:9PfEIio6kSx5OV2lF92BlBZOS25FmcvwX7bnTMulzkg=,tag:5vdN5Cz3H3MAKbXBC4bRVg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaHNyOVd0Zy93bG1oNU5K
            KzdOMjQ5L3BPWnpCNTRjUitwU01HRlA5U1E0CjNKYzY1SjNiYU1Ua2hpTUJ6Yktv
            aHVxY2tXNVlGdVF3OHg1cXRoSkttU3cKLS0tIGVwRExSZmYrVGxwMitUZ3AralJl
            S09kZThpZGx4MUFSMVptRXRFTjZvY2sKxVHBK5kIo1ccQJ87T9Gdxos2f/TBUpze
            X3Ir4I3s/sABZPkj7SK4NpvuRynzENyIAe8vuJpv+Ml2sgHWOTzxJA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-06-12T01:03:11Z"
    mac: ENC[AES256_GCM,data:VfUv9mSTHSq4Yu335sRtQN0rfYte7goI+lBlUxcUyUxw7mUp5QCkWb3MVuGrqtOOak0CYEAr1U6fxbzw4cAog//oFQbTQp2ipkziACnwjgxvzEaOyuXSi+LeJD4knK3pkk/QpVZy903BZypeYotFiP6cnFDvhsnIuGKi5IwvVss=,iv:eivGz+POpyndezmObuOejs3uTvwjFdNVODszyF7hoto=,tag:bBB3Dex8h7/EtkWu0WZNOQ==,type:str]
    version: 3.13.1
