apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: windmill-worker-native
    app.kubernetes.io/name: windmill-worker-native
  name: windmill-worker-native
  namespace: windmill
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: windmill-worker-native
      app.kubernetes.io/name: windmill-worker-native
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: windmill-worker-native
        app.kubernetes.io/name: windmill-worker-native
    spec:
      automountServiceAccountToken: true
      containers:
        - command:
            - /bin/sh
            - -c
            - export DATABASE_URL=$(cat /work/database_url) && exec windmill
          env:
            - name: TZ
              value: Etc/UTC
            - name: MODE
              value: worker
            - name: WORKER_GROUP
              value: native
            - name: WORKER_TAGS
              value: native
          image: ghcr.io/windmill-labs/windmill-full:latest
          imagePullPolicy: IfNotPresent
          name: windmill-worker-native
          volumeMounts:
            - mountPath: /work
              name: windmill-db-url-work
      initContainers:
        - command:
            - python3
            - -c
            - |
              import urllib.parse
              import os
              user = os.environ["PGUSER"]
              password = os.environ["PGPASSWORD"]
              host = os.environ["PGHOST"]
              port = os.environ["PGPORT"]
              db = os.environ["PGDATABASE"]
              enc = urllib.parse.quote(password, safe="")
              url = f"postgresql://{user}:{enc}@{host}:{port}/{db}?sslmode=disable"
              with open("/work/database_url", "w") as f:
                  f.write(url)
          env:
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgresql.postgresql
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: windmill
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: windmill-database-password
          image: python:3-alpine
          imagePullPolicy: IfNotPresent
          name: build-database-url
          volumeMounts:
            - mountPath: /work
              name: windmill-db-url-work
      nodeSelector:
        kubernetes.io/hostname: nixmini
      serviceAccountName: default
      volumes:
        - emptyDir: {}
          name: windmill-db-url-work
