apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: windmill-database-url
  namespace: windmill
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQ2RYTm1rMTRCWTNJSzd0
        VVJRWW4zMk11VExJeWs0TGJlU0phU2FtZWdVCnZ6ZUkxK29NUTNHMnIxZGxmOWFZ
        cVZ1ZVpGeUUxK0pCdk5MbVBacGJZRUEKLS0tIG8yYjh5UDJwaVVOT0gyMEU1a2ta
        Yy9rRm5WblFIZmp3d3Z0TVN1SnJrN1kKYLY4ixni9B3KOhVokBfS20RNkRY1MGXx
        YIECmqEz742s9F6iRrA7lchM0xDf2BeguOpwAuDbR6PLLAmcTZWluA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
  encrypted_regex: ^(stringData)$
  lastmodified: "2026-03-12T23:50:23Z"
  mac: ENC[AES256_GCM,data:UlwP7WDSHPPKNRUqow5nPrlXvnu9IajYiqIlEeYBUaFJ6AL/RYabZ/6dKe1hYSn/2nYpjIKj6TpY8azKnHRuKF6KGvPPnIrOd3MynYClGNknnRzqF0ugS2qnmurbr6eXLZ9aEGduLnS2yG+ZJWHIXr6WoLiTT6VylrBnwEngjwY=,iv:muqDB8WTsjZDL2RLjHSck+d+RogeXrabEusEVRzprUw=,tag:40kjn1O9X8BFSY/DTnSKyA==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: windmill-database-url
      stringData:
        DATABASE_URL: ENC[AES256_GCM,data:6eVGV90GbQjmJZDEI9il9BuUhrxAYGfc4Hj9NUctEw6jn3C/ZX1903oDuvLdWkuWEBERTLZzBK4rnlyjcxmJctaI8MdhI070Qq6J0zvI/bKIIMzPJaSb8og9CghB5B8A5v1Uzsw=,iv:KwNcEeodTJtfXZraKLgsEizP2Zv2Zlxf5AREqtJpIMg=,tag:wRiS8+U6YuQRgb6h52SbaA==,type:str]
