apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: windmill-database-url
  namespace: windmill
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQnh2ZDh4eXBtck13UzQ2
        azZFZVVjaVNnTmhVZDNrSUJzYnBmbThObzFJCjJKN1RUSWR3alN1MXp6ei9SRnk1
        cGlnMmFiTEJiUzF4SjRWdG1ZL01NeFkKLS0tIG9qZmRCdU13T1pXbTVhUmhZRDJk
        b1ZuRHExeDFBbTJWTXMycG9UbWdJclEKRII1VNZjob2m4IQyJ8n0j3oqx0oBaLe4
        oYGIC/9uIFKZ+9FUBy0b9ij44SmsFppN0nneuFaJKtlBxF6R7KC7/w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
  encrypted_regex: ^(stringData)$
  lastmodified: "2026-03-12T23:39:38Z"
  mac: ENC[AES256_GCM,data:wS5Pc1iXT5mL1MqS0k74ntgwrMCexYaT38594L1STUVTS+ZQ7gO7KeMQh2mjN05ZzT83A5Xap8LJru6cs3oN0U0kU8q/xLUGZhiXME7AwhWbEO12YYU7fbPrK+OIJyzvT0TiYFTZBvIiLs8EhHH6k6aoSpx5owQQpfJ3ndZaQlI=,iv:o33CrRyj1D75EPLb26E2yB9nKERJO/IE8R0+oqfe+WY=,tag:tujlKzEgulcZXrVLUpdBLg==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: windmill-database-url
      stringData:
        DATABASE_URL: ENC[AES256_GCM,data:Ojqk2T8pB4VYMibJ60N8oudIdzUd0xYt8s4xPxExdT7fTilYnSqzg/CBKRqllzRKjqIbqqVWaVclFlh+TvnzzpN6bQU1L9e9LP3AoyEId3UILdV/wIC2/kfbk2S+gw8=,iv:CscVWhZlskYN15GTCyjOPKtHAPxUAFjxzJ0q1uPpN6o=,tag:fpsDyWx4lPggQCptJVzTkQ==,type:str]
