apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: windmill-superadmin-secret
    namespace: windmill
spec:
    secretTemplates:
        - name: windmill-superadmin-secret
          stringData:
            SUPERADMIN_EMAIL: ENC[AES256_GCM,data:mVg/e8rT9n9mMRt0Dz/29cw=,iv:eioiZq+lFXlHGh/NpSs0GJNsZU/DZQNW+MC0tfvaeRo=,tag:/Mv79Q4K/i3Tz1xfheAUHA==,type:str]
            SUPERADMIN_PASSWORD: ENC[AES256_GCM,data:AIVd6Gy6/wnbpCGaBLYAtHYgx0uyIMLwYr6HphOJLPI=,iv:08S+Y0X4rY761lFiMssaSL2s82GbcpTdl7QcH538rX0=,tag:SPT7srdnhM4dmZPW2P1sew==,type:str]
            SUPERADMIN_SECRET: ENC[AES256_GCM,data:QE5zHABZX7ZcC5Lqvz5c0wf/1lHnPnYQwUtgqCvadPKrOI7aykKuaA==,iv:IUJJnusiuar2dmPF6xDAbuNI0IgHfSu/epNK4yi5T9o=,tag:qHlDfMCBv30lI9HDWBoTqw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VXV3djlQSlA2Yk5LWWp2
            Uit1bjRLZVBKZE81UURNUWFOK2hNajZlK0dVCnN6TWQvYTJJaEtqS3lBcldQNHZn
            NGlZYmJ1QXU3T1A4bEVQT2Y4bC9CaEkKLS0tIERaM1c3L0lTS29XK3JrTFVON1Zs
            L1QvN0JXRXVOTXRRbkRSZHIvOGRaTjQKRtXdGAgVB/AAXiSeYO80EoeIG/Z0nJCD
            KRKJTLUyewPyzquJPOxdGBLWll+KoRKj5T3p5gqDbb5201CyxRDIgQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-12T14:47:24Z"
    mac: ENC[AES256_GCM,data:X577X1uQQfn0yRww/iL/2LmpYJ1/WU2m3Ld7X1EwhH6jcTNYJ2NpzX5VaLnAQItQslO3h1lleBmO/Hymx2fP/10AAYr45isDM3mMqc4ILjFm8dMpNTJK/39Fi1UUeoV1a1SCcRU6XM2Fbxulv+ZwnmPha21rMhHQFkE4rrdg/bs=,iv:wgI1YcpeL0fVVYhHe02NpWjkb2o1XDbFeWQ2NP2k/3s=,tag:vCR2zIyA8Javy4hbR26a/A==,type:str]
    version: 3.13.3
