apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: windmill-database-password
    namespace: windmill
spec:
    secretTemplates:
        - name: windmill-database-password
          stringData:
            password: ENC[AES256_GCM,data:HSidJR/P5PtDh9IGnOw6Q4ItF2E=,iv:0s0vjyM3DUsFILdL9v3Oel9gWqaFYBav0kOtYTGboRc=,tag:FaDkdATp7rBHWW67XEqQ2A==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuQkRXWmRESHdtaHZPUW50
            K0JuNC9lcTFmUkEyWmZJSDBmVlNHb0I4NEhRCkMyVy8wa1hxQXBRbVFGbURmN3d4
            RFhsWWpMWmFLd0J4akRQaHBsK2lzYTAKLS0tIDZFdk1RWkxjdEZGYUlCTXNsUHll
            Nlg0WFVvME9rOEVsRllIbkZOWGtJVEkKI8Owpy2ZUn1DoCABsPJpWjKO0zXjxNZv
            TPNdh0pkmjiYmFM2kGO9ySMzCJr3cIYa3TsXiAl7kmaZ0ziohMJddQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T02:44:46Z"
    mac: ENC[AES256_GCM,data:xvPhK6vU0BBssqa7aXezSJlFj6rBN7p0krOxOOMnGI6lz2BbfqnH/wbUhzGxYnj5kvbq6J/5FjhsGWzcuEn9QWmiiD92KcJ+AHfemCJ4AJBhtN4XFrv/5WAcJOomMaVbxH0aeUUJJwMzfw0Qpt+jpGylMUbm9RrnnaIu5qJB1Sk=,iv:QqIVxpEOVqfeP821IB+/vnpdBcErtRBF9s0x6QN9KkI=,tag:3HyMz+9OfZtII/Fg+4szAg==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
