apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: windmill-database-url
  namespace: windmill
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTUlE4bGNsNndDMmViUDlE
        OFBoZGlxUy9lNmdoMDF0UHJ6STR4dUdjRXgwClVLcWllK08xSUZtSHhFSWlUTXBz
        YzQvZWZyRU9QV1M2V3pxc2dlSWVWQmcKLS0tIENqMktvWU92NjJhZDNkL1gzVUd6
        QSt0aU5zOWFNTU45aDhRSTRBT2k1ODAK8jlmmkJPIZttGjU8qdS9hV9AglDXmysE
        hCE8sORZlRzMcb3xdqQCUvWwiAesUNIk3//jofTl1Paw6tg9hMUX7g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
  encrypted_regex: ^(stringData)$
  lastmodified: "2026-03-12T03:45:05Z"
  mac: ENC[AES256_GCM,data:W6GfqivRc9E9NL/NG8/CLnofRP+Q6eAz4oAp84AIEQ3ShiR0Ef6TvdseBEPEGi/jyE+9K3BJ2gwFixfT2Ys3HDdM8cnOPjwtVT0ujpXO1ZNqz8WO4Hx7TlKqLCnbAPlTK1N+fyQHWfZrj5oh+EE6o3VvyUD3cBuIvLvuDJd1k3k=,iv:NQb4w9Qz2U7M1GdI1ALwDqGOLEod5+tamQM8Na4rnA4=,tag:fha836qaLn1kzTX+nndXgg==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: windmill-database-url
      stringData:
        DATABASE_URL: ENC[AES256_GCM,data:cTE+jFqbxiHkb6k/hwK7YP0/yZHnikJt6ofvD3SfWH5D+gjdKcTm0l9Inb5jDnoYA2Kj/ywg05+Gtc6qMS53Q6zw0Z3QnZtws5scw8QhAQC6gfDHfm+/q7+3ng==,iv:XyQhmY+iG6QRg7efEFrBl2vrE8BUhX2qxL2b+MH7GJc=,tag:1SV84LdgVWYXfeXGko9jBQ==,type:str]
