apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: windmill-database-password
    namespace: windmill
spec:
    secretTemplates:
        - name: windmill-database-password
          stringData:
            password: ENC[AES256_GCM,data:eJKaQrjb6sG9Y8d3BKilA9M88xA=,iv:oIR39dzItkeprB8Gljkk8itn65EhMs7faZEYNE5BxhY=,tag:5p6llN1mhalIWg5eBssw3w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4MWV3eHdaNU56dy9WVExT
            a0NrZVdGOXFHY3VhOERHNmJiRjdZNkp4UUFBCmN4akxFL1dhWi96b3RYd2pVbVBj
            MjZBL2g0TTViWVk5djNZdElJV0pMTmcKLS0tIEsyZ2dWaDR5NnZvOWlKZEdzemM2
            WkFNbytIaEFYT0srajhPQmdoaEpHVmMKEMY3w/Z3m9jp+xCcn5VAwWWO+ao9fcxr
            ws2JqHPgZxKMeQWWXjlt0ipUKacbf9UFa52qurLSa1z/sOEtQSCbtw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-07T00:19:36Z"
    mac: ENC[AES256_GCM,data:mmC+hOizhzgCzmFOGMx1eUxHrRecZ61AsXwGxhQgZ4oTnFiSzKRhwomJYct7zuWwHKOr2c9bnZYOdGjJHplq9Dpg8eQwlcrGh1pffCyzLSawicFvuvNNjm7zHMVhgO50AvkvUDWEZ2JwUNmn/W2BiBBwvhIaI+s15kvFKqPFNGc=,iv:q+0yp5pgrvjvWL14aEu9UPfcHQEl/FzZEIrXwwoazzk=,tag:zFyGnruKNa0gEkDk9mxOcA==,type:str]
    version: 3.13.1
