apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: windmill-database-password
    namespace: windmill
spec:
    secretTemplates:
        - name: windmill-database-password
          stringData:
            password: ENC[AES256_GCM,data:Wlf2LA8/G04m1zHbR4pqupiSGNM=,iv:RqZb60P7AhhTpAyv+HeoOFhznVa5tExLIKkqjMNgfng=,tag:FLgHbRr2bKfpaUQeoiPQPA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dG55bHN2Z1BjTGppNU1V
            QXg1MUVZOXlZSlgwaUpLMS9QbG1BYmdVMHpRClRCWFk5NHczb0Q4c2N6TnhnR3FB
            RUkvOHZqekprblFVNGtCTlAxK1JOeTAKLS0tIDVGVDZKZUtFMWF2RFk2NXlmL0s3
            UzFJMVUzdTVzc3dvTFM3NHYya05yRWMKK3x2h9ZtMuQD40g7joCUV2FXt+n99GwI
            /NUT2/USa0gBO48vYxQU7KbTpUzf8x1BJso/ggmO+md2QtRlmF86cQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-06-01T14:51:51Z"
    mac: ENC[AES256_GCM,data:sRZxymTvf8hamnZ+nNhNDvvnz5QblLxixvxYk/xrIwzPdtIEHnGeKQQIbzMuDrpS3MGIuqc1vI66cvxWJ2t098Rxye2unYGOLqijaCrD5oZE7SXQStxcqBO0MLJx5Gopv1/D3Y8FGPjS7fMsb+/ta/cXwphsHa/uAdD6OPDmNJA=,iv:l7BsYSUya6GeCQRGs6ZYKfuKzfp+MrJCkZrfldWZx4g=,tag:d+5cyeOL5w5iUE3bducFXg==,type:str]
    version: 3.13.0
