apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookorbit-bookorbit-data
  namespace: bookorbit
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
