apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookorbit-bookorbit-audiobooks
  namespace: bookorbit
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: bookorbit-bookorbit-audiobooks-nfs
