apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: bookorbit-database-password
    namespace: bookorbit
spec:
    secretTemplates:
        - name: bookorbit-database-password
          stringData:
            password: ENC[AES256_GCM,data:4zmJx1uOttvi/VnwUSalIWQGh9Y=,iv:NWtCRY7QUXXvkXf+TJFZJ12Bhf4kSoRmeRLpNWnum/Q=,tag:9Nyq7QL2iSXi5pt3EnJg6A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VHQ2TCtucWo0NXErZUxP
            OC9GcGNEei9FR243NE93TG9yKzJoVDBPM1hNCk9OV3ZzVmx3VGNta1hqY014cmds
            ajg4a0E3dW9WN3hBRU5MN29ZcXFxUmMKLS0tIGhLeC92eFoweDFOQ3EvQWFTVFJL
            TnR5N0xPZnlyVHRqWU8vYzhoWWtDWDAKoSZm4gwhGwTNum+8itNSzsLKlwAIJNfw
            w4zOKKUpM2EYSgBUtrBfa/MNvq1y3L/H5eZekAenskLiaomeKP15/g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-06T21:20:55Z"
    mac: ENC[AES256_GCM,data:R2BKuIC12qBV9K8CxxdrjN05TsfEgXXwWdP8ohg6aXkiQ7ODbsRVvXMDUdjJERgX2FoADG2gqykVHNgKMM5Znv6Y4bOJkwzAg15IzA8Fzw8znng2xI39IPJsk9KTo851bipzFZWBO6DQeLVLyW7ynH+HKttw97TKBqVc6YzjA2k=,iv:wPVXnCVf1GuXFVDYQ8Hn4O6iHHhpOyX4gl/Gp7ishhE=,tag:Ve5AG/XQ+SGcRRNnCAnwaQ==,type:str]
    version: 3.13.3
