apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: bookorbit-jwt-secret
    namespace: bookorbit
spec:
    secretTemplates:
        - name: bookorbit-jwt-secret
          stringData:
            JWT_SECRET: ENC[AES256_GCM,data:x2NjOIV0HwPjNk6fc9ccJ5EMy4/C5pSdCsANxnOVqZKW+TKElfEYe068oda4/RTbxoyBnpJ/CyJ0Hn28f4yADA==,iv:myyuv6qqEDGy890Gfh9tpmkZquVkoHvurOxRslARahA=,tag:2o77R197RFaszTwrMLjbxw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ZFVEUnNlcm9NTkFNV0dJ
            aWNWUlUrSVdNSEdZdUl3VXN1WC9ubk9paDFvCk5XcG1TbXd3dUorUmx1TVo5bW0y
            cHdVdTgxMmh2cGp3ajA0VlRObTJ5cjAKLS0tIHhhcHhZM1dxMFljQWwrVDQ2dnF2
            ZjdnYUNDaUU5WVBDU3RPbkpJRXZmdHMKay6gWe8NLyqcz4rAyWOiXB6L17w1d523
            0hTciKxeZWtlqXwV2NwmKxWIpuSmsUtPfO18B6zsa8XXuMJl8v53GQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-06T21:20:55Z"
    mac: ENC[AES256_GCM,data:61Rb+Lj82rrZzdAP9rcNdhieummoiODxnoJoQdSLBi7UX5fxjrPanr0vd8JPychkRtU8OgRKz9VvzFBCY/kEruRPO2NiXeK2tefFNXfbICTdibzE5Lxdms4yfcrepHSV56CY6KCTsxp5mr7EpEb4k9veiIv6jFZ78sOgnr07CWc=,iv:HR1IoA2LmJJGlpxaH9rz3NY9D2cpB6bd3s7DTFUpVDo=,tag:8mPrTlKg+wBAspOkmI/Rqg==,type:str]
    version: 3.13.3
