apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: bookorbit-setup-token
    namespace: bookorbit
spec:
    secretTemplates:
        - name: bookorbit-setup-token
          stringData:
            SETUP_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:ys0B17iiZ3AWA86EN51wtTIK52xoC8gaIyf5G/JSxHRwwguXSEjw61trDrG7I/6CzTgQTQ7ZYUKyCuW9CdYA6g==,iv:/4zAbW3Df8f0IX6RoDzY7x+zh1JZU3C4PGRpzrnJue0=,tag:LY8JKtrERVWXNl0N8jlA/g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiK1hDYkl6SjRCUjcwUUsy
            U1NJcVYzRGgvMU5nVml5d3dxb2lMWU1JVTNBCnJORXlQUmNoaUhIYVllNmsyTGth
            cCsvdTd5ZHAxdjJ1Ym1SZ2plRW5KcEUKLS0tIDVDdzRYTkVEbnNaY3ZUT0NNR1U1
            UEIvckxCa0pBMGM0cmMzVDA1ditNSlEKRotHvcJy9l483p4KIIEMNnVljtVm6TS0
            aFoIaCezPuYFS+48MbakBapUuNTfGCnH5NsNLqeUmc0ytmsTpzdgGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-06T21:20:56Z"
    mac: ENC[AES256_GCM,data:SpC+gc0O+zqtXe+6L6NY3z1mM2vcXzRGMgCqgEatgCN4K04tJAOrM3xy37WcWC7RZ49Q56NfdaGxZecX1gvDEYI9m3cRtg7ZrxTmS75UAQ4WWYKFRjHBzYorrh16/I0Bw/NjVvtorEljrUDMP28xgN0jmzUo3R6wyGw78WO1fSk=,iv:cIoLZuFa0HZSD5CSmrYdLUkdeS2AA606w0eO/BT08T8=,tag:rtGT7vyLRL/rZgLRmdK+SQ==,type:str]
    version: 3.13.3
