apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: homepage
    app.kubernetes.io/name: homepage
    app.kubernetes.io/version: latest
  name: homepage
  namespace: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: homepage
      app.kubernetes.io/name: homepage
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: homepage
        app.kubernetes.io/name: homepage
    spec:
      containers:
        - env:
            - name: TZ
              value: Etc/UTC
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: homepage.home.kronkltd.net
          image: ghcr.io/gethomepage/homepage:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              httpHeaders:
                - name: Host
                  value: localhost:3000
              path: /
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          name: homepage
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              httpHeaders:
                - name: Host
                  value: localhost:3000
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          volumeMounts:
            - mountPath: /app/config
              name: config
            - mountPath: /app/config/logs
              name: logs
      volumes:
        - configMap:
            name: homepage-config
          name: config
        - emptyDir: {}
          name: logs
