apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: homepage-widget-secrets
    namespace: homepage
spec:
    secretTemplates:
        - name: homepage-widget-secrets
          stringData:
            IMMICH_API_KEY: ENC[AES256_GCM,data:b8VMTaR5SYZTKzN3NXVevbimHobYNM563WVa71Lljt0lGit78VShMSA=,iv:TE9HZ2ieG2dlKfxvtXGAHQfRryhK5ghwApGXXEOO1i4=,tag:4yukxgDpllYuskvavlqnFw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtN3h2ZHJ6MW1nR0QyRVNX
            a0taN2N4MVlVNzVkUXJLYlNTcncyZUt4eVVrCmFHbE9za3hnSUgrcEhZZmJqR0M3
            RTVZb3NlMnFNbkdTajdHK0dIbnF3OVEKLS0tIEorZVE3bVpNY3J1di93ZjRUdWRC
            bENrdFBoZ3FlWWZIckYyRE9leE9CUG8KPgE2oVRwTUTdUFiXfLRc/7kQuT+dPVd8
            KS2ADleRU8qd1HSfDuL8GvRwqto0WWJQOdlMs+f/m1ytPtDD0APtGQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-06T03:58:11Z"
    mac: ENC[AES256_GCM,data:gJKHegwtfLbWxyrFNdgXklS+xxPI86YtyGzeSuGO9swQC5+5XbXgJfUZoAtJHMMkHrkVO3dvfoX2CVsXdmDfa+ST7xLTJI7fThUJZi778LeommW8SGjvXqDEXzRp65at9kU2a+cCG24luhvN7wa3RwMV/tm0VWMciOEiIZiOpYk=,iv:ejH7hyzlNtUCVel1G2/69HldRPJxNPHjEE75qfJRWu0=,tag:NZEEPFOsM4cKOq9s0zy7Vg==,type:str]
    version: 3.13.3
