apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: homepage-widget-secrets
    namespace: homepage
spec:
    secretTemplates:
        - name: homepage-widget-secrets
          stringData:
            AUDIOBOOKSHELF_API_KEY: ENC[AES256_GCM,data:6ZqClNYWMmrI/lj2uuiwymXYVp6RUHkke6ml0woc67ccumy+uZMQr3I+TTtQy/BrMiIBiaxoLlT8R6HPzRYMCCjAS3VZzEZhOYdJXhDmKMV3if15PoXnA2p7d+6eNaGEiGx+oZeT2JviGc0nmF/naSLRqz8hQRRpt90yrpn5KQVcUYLP5L4Moj9AWXdHULbmXAWGw+VXeRHrM6dfqBJ1LMCFGDHAE0mvz23ItrRHoKRxkbkAtXh0KTNnyFbABfftNpMH32JgsYnS0LvrCNB+KNE=,iv:MuSL1cNVP2B0+uj2/M64lR1cGAJyr6PUaa+dE+cCpFU=,tag:PCjroM6gt7xMiSepywh85g==,type:str]
            IMMICH_API_KEY: ENC[AES256_GCM,data:U8Yf9UaAohmClqEd4hB5qreT6+iyZJ9U1//4u/7xE4w58yKbDRqQLkk=,iv:qZFLIz9UCPLOPHEQmo69SRkGABaB7UOv+lXpgBqrq1U=,tag:pQ0+x4GxrH9PM+8imytmwQ==,type:str]
            KOMGA_API_KEY: ENC[AES256_GCM,data:Sg2Stksfpvy6r2OzZ9xhNG8MN2k3UaDy0U/T5miMuZw=,iv:BNzTb+oHyc9qMYNM1VCrzXFBnx3cg4AGmd4Z4cqQ8GU=,tag:bQzpOOAuclopvIM5OrAyWg==,type:str]
            LIDARR_API_KEY: ENC[AES256_GCM,data:pX7JJ/nK0dChGvRbOi49QJV/sQJyKmFhDFnz8KIwIR4=,iv:Cq46D1BZzQMDXL/UariNmmHRb1BDBCV0NJ7sAxSHRgc=,tag:rMrmtKc+l7qchND76PNLfQ==,type:str]
            PLEX_API_KEY: ENC[AES256_GCM,data:+Y+FqD+oK9Pl9vvlskIg4reDAOY=,iv:eCuN/pxPbpDOoX2/e0Lffc1vPXpFf+IjDuC4t9QkSJE=,tag:Vnw5LlkjLNVK0kyumQjNUg==,type:str]
            PROWLARR_API_KEY: ENC[AES256_GCM,data:UcKRSOWpVNQNNHAOW25WCxdVdxioLjwVXCBMLwrm740=,iv:KDNic0n6/qCSv+75houkteUL8PmpUP5Q0CLIA3AS+Bg=,tag:UhFntb1K0dJinpMaAFfoeA==,type:str]
            RADARR_API_KEY: ENC[AES256_GCM,data:MF6k6sGJBJyL7kfOb8zMWXwGYoNldZrXiXTrRT5T0e0=,iv:KXNss6CaO2sFDT+857z3H4bTeTPVUJC4IzJJ3MVsmJY=,tag:w/CNfQ7eQwobQyV8ORqPDA==,type:str]
            SABNZBD_API_KEY: ENC[AES256_GCM,data:6IFFZiYfW/kuxW31WKei3V9Knl/BY6pHtHnDVrZFOwY=,iv:Otm7Qn6+TOA1hpbGtLBTL9w287Rk1Qzibvev3sNS78s=,tag:XWE4YX7X86v0UHqWvNP0aA==,type:str]
            SONARR_API_KEY: ENC[AES256_GCM,data:heGINtaLDAmdQNrCjpaRtB4QHVI/7sUl2zmgk5Pbt9k=,iv:q6C32Mo92AD1fA/eXWg9U+UrgSJ5zx4x5Qe/44s/8vc=,tag:UCgviEan2G4a90NpU4FvuQ==,type:str]
            STASHAPP_API_KEY: ENC[AES256_GCM,data:4MCgOfTTsaLFbm2e4qTcUXTqjQ2vYOaOif/bXLwJTfNomW80vAsIRsUyaOm0TZYmkiXymB+RVG2DQIa/kkzZo06N66QzHB6GyloZ65XEWT8B/yNotfy7vohbPpFZSRDqB+BG5r4eegJN+e9gcdyBgKNRt6mqxmQqLEwcYdOEL5d9WaeFeE2GKz1wH2WKGtk=,iv:OCmCvSygMSw/9/DVOlJTRPl/C2enCdD+lA1h8ECvmUc=,tag:e5yjHTnFT2uPQhXRwG9kgQ==,type:str]
            TRILIUM_API_KEY: ENC[AES256_GCM,data:u6yyEhxlw4WVZbmd7ZAawBR4wHGu2qG5DddP5jsseEWLppyDZPouPvko2EVbSVjN9cPzSlSBT5Ip,iv:ws6YMbBtuHmRROjIRmgheJLpqjwYQENhuyz1fUx5luY=,tag:bZPkiflzwKhZ9ebq5gWMHA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKc2hDZFhKY1YwNzJpVjhr
            Vmh2bnBpdDJpSi80dklRYXV3SmNqb2d6OEhnCmNxTFhiZzRCSlV3REV4R25pbWxQ
            aFcvbDlRSWxzL25nVzcxZFh0UzlpdjgKLS0tIGdDZ3JpSmNxTDltcnR0VHdpbGdo
            RUQzK1Fudk9ma1h3RE5ocWpCWFNrQ0UKaWpJwI7oWje9acEgFxzk9+2UKPGlsTbv
            C8PV1EF8Hv0UENRl23734k2RL2tnV0YMfTErI+UjsAE7aM8et4WyTg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-06T15:41:50Z"
    mac: ENC[AES256_GCM,data:lSST7PekS+fcXUattQx2PoFbMdOn5TOcUDEuAIUPwX7PHBFOH/xC4KrTNW0JsDXMp9zyEE+LjfBjxhaulFt951jHqesWs9nNEbHljvLbsE1w9V8+NFKsu8fWykgLhfmQElxD385rW7b8+rSL36i1ymYAf8XQ6owsxGaLYGOSWY0=,iv:KrPmxBVQos4/8tU3yFc2dmBhErTTslTG0JTiTus9fIM=,tag:FWIXUYX1zoa65p1EO4IqEQ==,type:str]
    version: 3.13.3
