apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tunarr-tunarr-config
  namespace: tunarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
