apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tunarr-tunarr-movies
  namespace: tunarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: tunarr-tunarr-movies-nfs
