apiVersion: v1
data:
  init.sh: "#!/bin/sh\necho \"Start initialization\"\nif [ -d /extrascripts ]; then\n  echo \"Copy extra scripts\"\n  cp /extrascripts/* /scripts\nfi\nif [ -d /customscripts ]; then\n  echo \"Copy custom scripts\"\n  cp /customscripts/* /scripts\nfi    \nif [ -d /extraconfigs ]; then\n  echo \"Copy extra configs\"\n  cp /extraconfigs/* /configs\nfi\nif [ -d /customconfig ]; then\n  echo \"Copy custom config\"\n  cp /customconfig/* /configs\nfi\necho \"Initialization done.\"\n"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: mariadb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/version: 11.8.4
    helm.sh/chart: mariadb-4.44
  name: mariadb-scripts
  namespace: mariadb
