apiVersion: v1
data:
  init-booklore.sh: |
    #!/bin/bash
    set -e
    mariadb -u root -p"$MARIADB_ROOT_PASSWORD" <<-EOSQL
      CREATE DATABASE IF NOT EXISTS \`booklore\`;
      CREATE USER IF NOT EXISTS 'booklore'@'%' IDENTIFIED BY '$EXTRADB_BOOKLORE_PASSWORD';
      GRANT ALL PRIVILEGES ON \`booklore\`.* TO 'booklore'@'%';
      FLUSH PRIVILEGES;
    EOSQL
  init-romm.sh: |
    #!/bin/bash
    set -e
    mariadb -u root -p"$MARIADB_ROOT_PASSWORD" <<-EOSQL
      CREATE DATABASE IF NOT EXISTS \`romm\`;
      CREATE USER IF NOT EXISTS 'mariadb'@'%' IDENTIFIED BY '$EXTRADB_ROMM_PASSWORD';
      GRANT ALL PRIVILEGES ON \`romm\`.* TO 'mariadb'@'%';
      FLUSH PRIVILEGES;
    EOSQL
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: mariadb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/version: 11.8.4
    helm.sh/chart: mariadb-4.44
  name: mariadb-customscripts
  namespace: mariadb
