apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
  name: mariadb-data-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 8Gi
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      dataEngine: v1
      dataLocality: disabled
      disableRevisionCounter: "true"
      fromBackup: ""
      fsType: ext4
      numberOfReplicas: "1"
      staleReplicaTimeout: "30"
      unmapMarkSnapChainRemoved: ignored
    volumeHandle: pvc-7ef8145c-7770-449b-a78d-81b1df2e17df
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
