apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: mariadb-extradb-passwords
    namespace: mariadb
spec:
    secretTemplates:
        - name: mariadb-extradb-passwords
          stringData:
            booklore-password: ENC[AES256_GCM,data:HFvbHCJ7rSDvlqhI/T+asj1pcuM=,iv:j4dNX9C901QiJUHphsE46zewMrJMhYdT/8Ix/cYVGLk=,tag:yQFi0r+tUujsctEk2lPrVw==,type:str]
            romm-password: ENC[AES256_GCM,data:3aL3/qaVMG/zI/vrIrR1GfsTRo8=,iv:LsC1xFyN3CwFHy5aZ+Z/arcBxPSw01ko3T54Rs5kyGQ=,tag:ODK/IaYVU2XTKWPOqlQ/5Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2L1dib2xRNzhtWi9zNytj
            bExYb21tQUk5ZzRnRy9aODd2NlRnTGMyR24wCmdvekRJVWFaQnVkbHI2NTlIaktG
            UkNsL0Vhdzk4T0ZUK1dzeGVuUUVucWsKLS0tIHBtdHRGclBGS1RwZlRXaGFOUjAr
            L2xhUUhYVDNnekQrOXFhK2ZoclFBZ1UKc9DnQeq/bUVC8g+bbEwpGfKBUHuARg4j
            3jeMJAIRZTiObbEbOVz7J3cNvQlodyzPOLzZ7BDDddMPeRNFJgbSGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-07T21:22:31Z"
    mac: ENC[AES256_GCM,data:LhFizm9/p0WcOHOS8SN1+V93tk8Z4p3HWQTcAkGGBZJCqljE4EaxKG5MnvJJSb4pwkPIfXkFNDNaImtk0sdqHkju1X/WkVYR6LwKVM4FNmIeZNPapin4QcOfVWdYPZt+4K96HOpPfVNVPvFoU1bzHGozst7vMXMV2rBoxGbfxf8=,iv:hHFIPJfsmixDFJGtpc2CN4O9P9ZGMuayFs7dZeZqcQU=,tag:0yiXyEEe4vT5dJe3wCJlEA==,type:str]
    version: 3.13.3
