apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: mariadb-password
    namespace: mariadb
spec:
    secretTemplates:
        - name: mariadb-password
          stringData:
            database: ENC[AES256_GCM,data:XnlcGA==,iv:eLhI02bAneX4b5yf5Hkxv/1aLDQgjwT7bxqwSjPj4hg=,tag:5+IpQGk40cxxiNDA/SL+qg==,type:str]
            mariadb-password: ENC[AES256_GCM,data:ulUtW+KsY3MK3NJscbBWQx6xN6Q=,iv:isj6oRPN/oevWXoVW4lE0qTK8rJifT4ZDHU0koKy+A0=,tag:u4nAIHpAJKX23E/HwCW3vg==,type:str]
            mariadb-replication-password: ENC[AES256_GCM,data:94JcuZOlRV7MHDuQLm/El1b7s00=,iv:EomWOJqy9AbBXJcYJND6VocYxxCbSUCV9gWJqAm9/j8=,tag:TcQziDHwBLqOSNKuIKiyNw==,type:str]
            mariadb-root-password: ENC[AES256_GCM,data:fZ7jvfxfFO+ZIa1hDbaca0bcPhU=,iv:i8arRWR8wPAYIkOerCRjzzZ3MpgX5Y1FnG7iJ3LmZkA=,tag:5mEhncy3oq4CXkUzfGNq4g==,type:str]
            username: ENC[AES256_GCM,data:dN79BfZbgQ==,iv:P0UAt2dg2bhSKeSVetAq9eCb/SZBlenCbFzEtV4ieak=,tag:YfUrXCDQ3y4+tNmZC4w2qw==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZ3BkZ1Rocm15T1RVdzNh
            ZkxsTGdiR2c3RGd1NlBxUWI2S1pQaHREclI0ClhneitBT1UwRWRrZWdlOEhOSGNk
            Q01ZV1hyenE4N0lVMytBdFZ4MWNYdWMKLS0tIC8zRmwydlg1Q0tmU3BLcUVuRVhn
            SFRXMzJOMmlDZVk0QkwvUm1tdXRCR2cK7dAG14bS0VUQPzzsgGdO3go9QFhurW19
            VttAbchZHarJ0gCMJfrdQAUNJlX5t9w6RURGv5g0ErZgSo5oW7yklw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T01:06:59Z"
    mac: ENC[AES256_GCM,data:J+0Nh8lftqMaxyyvSwpPWwSJfOP3QBflxzT2D7RBcZcYlEmJ3xuJap7Y8U3Xadbbct1j1AcK81BrcWy7V515Hf7mT26ul0Q4uoIhWuX27TG7s4oBeJmfuCxlUR67tugCzgDzmO2K90NL4ElVu1c+IGN3TxWlzcI9mrbZn8sxO6w=,iv:QxCD02g00ombN9ADi9G1yIPIX8HA/yRyOJX7EzZn7wI=,tag:9vM76YtkoX7KryRlMKQpRQ==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
