apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: mariadb-password
    namespace: mariadb
spec:
    secretTemplates:
        - name: mariadb-password
          stringData:
            database: ENC[AES256_GCM,data:1VQOcg==,iv:Qy+FLpEU6zbIQioBy/+j5pJ2Tv1jCvQ/NgYulqsxans=,tag:SpQRQbvrFlN4mQ0BUzbeIQ==,type:str]
            mariadb-password: ENC[AES256_GCM,data:OMHEJD+SosrIYy8btJWy7riNy8c=,iv:5TdG0R+JK3MJ7N0IVDRlzWaxDtmKUHZnOY3orLuaEZc=,tag:bcIxefxbl6wH6kDweQzhQw==,type:str]
            mariadb-replication-password: ENC[AES256_GCM,data:c6t889xe91RGxG6JbxeojmZDtAo=,iv:6pgFhvbiem/RFncV56MLI0gOAtzwaoms7sYuvH85ip0=,tag:z/vvcdEMpRBgzOUjjgmQfQ==,type:str]
            mariadb-root-password: ENC[AES256_GCM,data:8OOyQZ3JZFsyl0wofckRDW7x/gM=,iv:vckAQq9D8ukjHoMo/o4EpIZ2QUuujQQ1C8dc1I1/x7c=,tag:ZgZF4VX8X1v6YOe5m3B9JQ==,type:str]
            username: ENC[AES256_GCM,data:b1dazBtViA==,iv:LbuW6TtdgaPHl4GpxuKlPkWLlVOCTSxiUfdI2cbrzUI=,tag:E5g5SN3P17Dqmn8rvd9HwQ==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVWlNSUpnVWw2SXpVMmF6
            dGxYdURUUmJxVkNmekhzU0d5Yk1vOHFvK1NzCkpQSnlDUUQ1cTZtb1VrYWZiWE1Z
            RldTK0treUJod1d5WHVtUk9JakdIUDAKLS0tIFV4OEkzeEZsNjlnM1l2ZjBsUTBi
            a1c4Sm14TllOV0JpTEkwQlZXRHYrb3cKnRKDjvfvdhA6l/fZjcCuC6Zub7dLHmeY
            7ZYE9fZ2D7e5NsXprKKf97THOuSlaZkbgiQfbRLyB46JpGNfXr7Hjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-08T02:51:31Z"
    mac: ENC[AES256_GCM,data:l6+tvN4erCZBoUfbFPGZrGnRwnjcKrJP1Cy6MtRAmzJrA/l/x4YtdQuoC7VkJesviT+0+7lXsgvYR3MpVCoTSz70vSCNcNcioQmFbYcJHBxNNu3LHrwC6ke46zLX2Q8fVuPo/5+56G0i3VUOQuAEeTpfdc3ksptxX1fUBBB7uOI=,iv:NWurtaQxGojL5UpmXj+eMvqFsd8FaPG79U2z3a4ajn4=,tag:0FspCTUop5KCFXKp4zv+tg==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
