apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: mariadb-password
    namespace: mariadb
spec:
    secretTemplates:
        - name: mariadb-password
          stringData:
            database: ENC[AES256_GCM,data:bb6Y9w==,iv:dkpLxnSNoaR3aH0jJ4oEPXSfFsBjbREMAcbkmcB3Pew=,tag:QMjXbT+TjHoB4YUHp7Hc4w==,type:str]
            mariadb-password: ENC[AES256_GCM,data:WQxLhMRv080qgwCV5G+y1aHUOSU=,iv:J4DzA5V2oFdApXMwirb1IbUYuZEpbQzqCrXgDyGmIX4=,tag:a+Yjf9Sa70LBVhVUr6z7IQ==,type:str]
            mariadb-replication-password: ENC[AES256_GCM,data:HDIkFNm7Bk6PIWDNh0lulT5yDpA=,iv:v6xXCuUp7VVvTE2qcej7Xl0MxMWD3GC5/kp1sVIDMmU=,tag:hE58SlzX4B0/McuyedPqrw==,type:str]
            mariadb-root-password: ENC[AES256_GCM,data:K9MtY7yfUuquFbiSvq4+HyZvV+4=,iv:0ZBbDf2cwqCiB9E3I6wD/52eFe6xZAux9C5c0JKUDPQ=,tag:jTkH07N/h7jx3zgoETDALw==,type:str]
            username: ENC[AES256_GCM,data:MHh8iwrW2A==,iv:FLNpc64CCcdFlsVeNlc2r1lIftkofQEnkm9idMm6GAw=,tag:o26p6TzzmwrwwpLgl2OAfA==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArM0tnbWZ6bkFLV2JiQWxw
            U0Z3TjFTdjhSN0hmaU5ZYXAvVHEyNTgyZ2dJCjBZWERYQnBMaEs0Q2htSG14ZkVq
            eTJjNDNjQUZLSVJHSStTRHhvcUJxSEUKLS0tIDd5Q0NiS3ZoMEtDaE9DTzd0NzRW
            WmlIVDBiM2lqVTFJK1FGS3grNTZZa2sKGXabvy8iDmjyqIbT9B0LOnCaEXb62aWs
            TZT5sqJuWFF6BiR22mPLGovbkXwc+XdB7yHy7UcQS2+X236OqIAOow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T15:13:10Z"
    mac: ENC[AES256_GCM,data:728mTybk1MxR3WGeJTkt0AVuSG+mvSxi6BKAsAPuPryaU3EsLBp3isUP/VvE57+pV69LKhDd8ax/C7+pju4XQkYnIQEqBk+8mo9jncvU2AImqp4Oa6fhoqZ1H83MCsT5HqXVmFm6h9muL0IDu6qPzjiQ2gwBAkrNbCepB/nAfgw=,iv:SUvO2PEFesIHLIGa+S27KsdY9xrvcr8QCfMf/xEtKzw=,tag:LYZNfc1zVssKL2cjg3wOyw==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
