apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/instance: mariadb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/version: 11.8.4
    helm.sh/chart: mariadb-4.44
  name: mariadb
  namespace: mariadb
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: mariadb
      app.kubernetes.io/name: mariadb
  serviceName: mariadb
  template:
    metadata:
      annotations:
        checksum/customconfig: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b
        checksum/customscripts: f00dd9a577d192a927be6bd2d8ae09bfa9267540be0abed152903d494b82f88e
        checksum/scripts: 5c5d50c344ec1fdc574677a120b2fed8545c6fb46f4c20d2d094abdfe5f65992
        checksum/secureconfig: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b
      labels:
        app.kubernetes.io/instance: mariadb
        app.kubernetes.io/name: mariadb
    spec:
      containers:
        - env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: root-password
                  name: mariadb-password
            - name: MARIADB_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database
                  name: mariadb-password
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: mariadb-password
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: user-password
                  name: mariadb-password
            - name: EXTRADB_BOOKLORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: booklore-password
                  name: mariadb-extradb-passwords
            - name: EXTRADB_ROMM_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: romm-password
                  name: mariadb-extradb-passwords
          image: docker.io/mariadb:11.8.9
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - bash
                - -c
                - healthcheck.sh --connect --innodb_initialized
            failureThreshold: 3
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: mariadb
          ports:
            - containerPort: 3306
              name: sql
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - bash
                - -c
                - healthcheck.sh --connect --innodb_initialized
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 999
            runAsNonRoot: true
            runAsUser: 999
          startupProbe:
            exec:
              command:
                - bash
                - -c
                - healthcheck.sh --connect --innodb_initialized
            failureThreshold: 30
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: db-volume
            - mountPath: /tmp
              name: tmp-volume
            - mountPath: /var/run/mysqld
              name: tmp-volume
            - mountPath: /etc/mysql/conf.d
              name: configs
            - mountPath: /docker-entrypoint-initdb.d
              name: scripts
      initContainers:
        - command:
            - /initscripts/init.sh
          image: docker.io/mariadb:11.8.9
          imagePullPolicy: IfNotPresent
          name: mariadb-init
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 999
            runAsNonRoot: true
            runAsUser: 999
          volumeMounts:
            - mountPath: /customscripts
              name: customscripts-volume
            - mountPath: /initscripts
              name: initscripts
            - mountPath: /scripts
              name: scripts
            - mountPath: /configs
              name: configs
      nodeSelector:
        kubernetes.io/hostname: edgenix
      securityContext:
        fsGroup: 999
        supplementalGroups:
          - 999
      serviceAccountName: default
      volumes:
        - emptyDir: {}
          name: tmp-volume
        - emptyDir: {}
          name: configs
        - emptyDir: {}
          name: scripts
        - configMap:
            defaultMode: 365
            name: mariadb-scripts
          name: initscripts
        - configMap:
            defaultMode: 365
            name: mariadb-customscripts
          name: customscripts-volume
        - name: db-volume
          persistentVolumeClaim:
            claimName: mariadb-data
  updateStrategy:
    type: RollingUpdate
