apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: grafana-admin
    namespace: grafana
spec:
    secretTemplates:
        - name: grafana-admin
          stringData:
            admin-password: ENC[AES256_GCM,data:kEfrsa6NVyzg9i0VbQyVee8Bkxo=,iv:1D1ZC+0Mz+nzwYmaT2lSTT1J3ou7fvYmjvZbTm5oUWg=,tag:YqiXY+8HK1WUWBgZwk2A6w==,type:str]
            admin-user: ENC[AES256_GCM,data:G8FhSjY=,iv:lLMvVs9JOtOunDmWMfNDzYmOGME2TtaxHYmqZd1K7EI=,tag:qQMJ+8gNX5wuhvn7YfA1QQ==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCenJBbTlwVmFxUXdHZ0Fw
            aHJRdkdBVGlEVWpKRVR6ekpqN3Y4UXA4QTJZCnZBQ215U2dFSDVPTjNxWS9YS0pn
            cW9KMGtqNnF3aDA4VW9XSmhoWTd3YU0KLS0tIFV1LzFyZ1dBVy94UWMrczFaa0tT
            UGZkOC9HTGdTN2NHRjRna2diZS9Ja3cKQCoZXTUxVppxwiiuAw5UuEWwBR2L0SQC
            iQWZkQDDCSe4ZL1BxE+N2Rnrywi9pbf0YXkzOWdnsRteVvEyge4jlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T17:15:07Z"
    mac: ENC[AES256_GCM,data:hx0cIbbe5lt9B1snAM+tkLXPOljIhy9ZqZPjVimcrI4GQzBbVj/fS4HRwlqPouzRN/qL35eRh0tYxQCGrcj5+zCeKkJdoPhtgsAtScNiG2QKuho51ey+XNgIHSl6ulb+qjXAbLTW/yZxrzM3weNJqhAe2Vly01wF4uzX9ILZ2z4=,iv:Ed7VKuu8YhRSSCJIIHumPt9wAwjoDJIl+sVw/vB+pSk=,tag:fMbT+5fXVI4FO16bjKbxWQ==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
