apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: grafana-admin
    namespace: grafana
spec:
    secretTemplates:
        - name: grafana-admin
          stringData:
            admin-password: ENC[AES256_GCM,data:Cn3qig30PqQaC7xyVHWpKHh+xPE=,iv:JSWQTN0uRAM1bf/XJ+DSaaqnrF9idLdwNClxIvWr8iU=,tag:YSRbYpn/zTWbs9c9N0aKUw==,type:str]
            admin-user: ENC[AES256_GCM,data:mHPYsYM=,iv:Mo4oGCT/mxwebVg6XcaINFWu+Hrl+Ga5OyLayior7V4=,tag:AWZ85bk5QDATyvilU5j9dQ==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEd2gzU3FSNTl6THBnclVD
            V0lIenFjRDdTb1haUU1jdlRNc0FzOFBFNFRRCnlFYXEwRldsbUZCbXUxT3NBTjJX
            NFdWd0cxN2lZVWhvaTB5MXkvQ3czVWcKLS0tIHdPSS9od3FZQU9GQTVuS1FPT2Rn
            SFQrdGdNRHp1QUllRDJ4MFJwNHA3Qm8KaUq3FrWuLO6JuhPMJn3Btm3EvWPgbmFR
            tNW7bgTn9KCGwHJOzK+qtwjVoaT9m+aT3iwMovhMlfnPWk0+G5+cjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T17:43:35Z"
    mac: ENC[AES256_GCM,data:pFfCPNOuOSmzvXj7F9dfyfq/fr4ruVf8+pbcww6XHYqXY9WdgPlJUrIg4T/pbW/mVgHMFyK+TDxfMbUpvlMFvj03IJ1Yab8I9Njfy1NriSdPms4aaHHaA6h7iUL928RqbMPHbFsQ9xQ1RoNCfxXFr5sQu0MlRNLYPKzulg1QAZk=,iv:3cKPVKKOPDR2gARC3MP9AB6erqftDLNK2RG1iD7S7Zk=,tag:CKCBV+GDREDPAYxQ3WSh/Q==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
