apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: grafana-admin
    namespace: grafana
spec:
    secretTemplates:
        - name: grafana-admin
          stringData:
            admin-password: ENC[AES256_GCM,data:vylibP29Er2qb3k65PBJG+z4q4M=,iv:rlAe+ven+jkGUaFyoAkVmhD3UyCeqbR+dbgS6Bzg87s=,tag:6R70TUVqDC28WW61gw6loA==,type:str]
            admin-user: ENC[AES256_GCM,data:x9OXKLw=,iv:JXDdcZdZobX66+NYw6TgYTfF0T8G4bmqugrge9sDRtU=,tag:cAPlUernQ5p8c+INhQlqsQ==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWERTaWE5ZzY3angvVEE0
            NnNSSkphdUJJeWZMN05jV200cUVINEUyODNnCkVIVFNObFoydXIrb0dQazYvZEtT
            aXR5Q25FRU01c0paZjRyRE1wRk9SSlkKLS0tIHMzYUZsMkw3M010RFFkV2lpbFhy
            VkFEZGU3UWtKSmdaRmtnVkoxbzNPRWcKNJvOP6jjVPSZNt5iDYkadqZ8RWvHE4JZ
            Hk1Bm9PxsQLJhLcv+t7IkutDyg/uCtpVjEHX+K909M+znC37N+VLvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T04:46:52Z"
    mac: ENC[AES256_GCM,data:Uzvp/BBMRrgT2EmkI7/R7hx65EChXYQbTpRTc68KZmPU0AMA/dbYd6fo3MwrGZ39WQG1Jwdsii/esOz5Gmt3OrUVfSkse+UnagJgO3j0hcjcDkQ6cw1KjFLdYP0W3exNE5bs9N0vIDAym96FajyD/Ku4qBjFpx/vEoBtQFa+1CI=,iv:esXHYK3KYbFdhSeFmupUl972537YuYokkGfNzp3+z1E=,tag:5TamI0aPAvKW21JljpE+WA==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
