apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slskd-slskd-shares
  namespace: slskd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: slskd-slskd-shares-nfs
