apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Replace=true,Force=true
  name: slskd-slskd-config-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 40Gi
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      dataEngine: v1
      dataLocality: disabled
      disableRevisionCounter: "true"
      fromBackup: ""
      fsType: ext4
      numberOfReplicas: "1"
      staleReplicaTimeout: "30"
      unmapMarkSnapChainRemoved: ignored
    volumeHandle: pvc-3daa90da-e4b2-4dd2-8cfe-9a1f98764991
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
