apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: slskd-web-credentials
    namespace: slskd
spec:
    secretTemplates:
        - name: slskd-web-credentials
          stringData:
            apiKey: ENC[AES256_GCM,data:K7MuN7pHUNsJxVHHQ7vily3jQOq9EwWqXiPBJy8rgpg=,iv:B9SR5S1P9umLtDjOuZdCu4qRZ+AQja/xD2sQvwesBTI=,tag:psPds5tT4hoVQknT7cZpbw==,type:str]
            password: ENC[AES256_GCM,data:j49574AK5ae5bkVUUwR3nw==,iv:FNXIo1Omi5pmUc/u1c/AIVPg4y4+0rs+3MJdv1U3PwA=,tag:Ce4fnLwaOF+YsPefh6ZGng==,type:str]
            username: ENC[AES256_GCM,data:EIqdMfsvDGE=,iv:oc9kAuSOB5qDm9lm28IeI15+S4mtsG32KfWm+nKQDt4=,tag:h2H4SPRQ0QLPf3NzHuAkmw==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZV1k5NU5EQVZPZWtTSzlq
            c2hrd2wreitPY1NNejVLN2trWXNvVkl2QlI0CkoxcTg0RTVFZnhFcitXTFRhZkpZ
            NldQMC9uVkRTL2pKTCt6VDJ2VjdPWmcKLS0tIHZyaEhIZlJ4cTlpRjk0QkVibTZn
            a2VJRnFra2tTY0ZxNUNNNXVoM01EOGMKzqV77SBMwY9pPxtm5J+9fTPHEheC0rnS
            qS6CYNmEPw5qojPmSGpax2AcPNnvG80g4pIGKiLJxZY9JgWQLJyZ/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T18:14:39Z"
    mac: ENC[AES256_GCM,data:b2fjNFtw6WdZ5iqlR4pUk7KRxDQ2nwmPaR9IrDihj8EqOQzjYk0iCx+0J9zz911AuBhN/sGc0TE/sdKi8TWF1sJVs1yxnhrkppe1+5XNuppGXwnFcvnTXh2OLr8C3W1IcjB8mi2ZN7GP4bclG8lCr2nZTuhAW5oBO9FP9GFBXqM=,iv:f4Pg66FnN6y9c+X/H12hCdQ0HbiotM0a15I7egJJvzU=,tag:mPIpWYnQdBeIbhNzcKyd/w==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
