apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: slskd-web-credentials
  namespace: slskd
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYXZ3Tm9WQStsUlZTb3JS
        RFdWa294M2crVTA2Y05meGIwQm9Wdmd1M2gwCnAzUUJsMmhYUTdsWkJqa0dEd05r
        RDk3ZnNpZnRhdTNuVzdMODNjRWJ3RzQKLS0tIEZGS2tDaTlxVUVZMmxvaVo5Tzg1
        eXdVMWZaT0UrVzQvV08xWkRCWTVRWDgKJiZTas6a7W8VubODqQCPivHKj77moW0X
        ibkCFg+rMttiIjAaZcMp01TONZib5n6f0Vr0e5HCscywGYMnNSTJEA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
  encrypted_regex: ^(stringData)$
  lastmodified: "2026-03-11T03:58:07Z"
  mac: ENC[AES256_GCM,data:7KKI76zWLRi3eq5FlXXjf+nffPRW6YpAj4coT0AT/72QiJo0B/NqYQ7pUWk8DZ2cmmneC6ADCLtE9tQbBG+S75BRHyGmH71nzJQo6NOJsqtl4/5ucAeyawFt+RDvxMH+765sJLndpQXl+LDXlq7P9f/Jql/0wPmjXc6BONlG7/E=,iv:b5i/vyXDMUcD1jjeYu39oEdYeTmdlmY2O8+obcIeSNM=,tag:bkZ+4otenJEibnsK2WQk3Q==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: slskd-web-credentials
      stringData:
        apiKey: ENC[AES256_GCM,data:Bn7zmO3yFBbQU2d8wmTsI5FF02nYtfxzHtS0DRa1T3s=,iv:M5QNLV4XtXsRdC4lFAEJTbiWUseh8DR1O/6jAsaRpNE=,tag:xXQCQvNPzkFbPYGuQ+ZyVw==,type:str]
        password: ENC[AES256_GCM,data:i9T5+ArWHu6Q2HoiQtTnVA==,iv:0dBmuC++mVk3k5HawpLlxtsdPOnt7h4YgkGdINy6pdY=,tag:QwLdZmqCGt4tKIuqYlbwFQ==,type:str]
        username: ENC[AES256_GCM,data:CYQu2W4DZss=,iv:6FmwuKycSybht+oylIWAvydQ7WLT0bSCIy+Onqgvn4U=,tag:xGkEdeAnf6o2dFCsq7yWrQ==,type:str]
