apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: slskd-web-credentials
    namespace: slskd
spec:
    secretTemplates:
        - name: slskd-web-credentials
          stringData:
            apiKey: ENC[AES256_GCM,data:2lpFCu7rTPTcTyma4gEpBveuyZ4INm+AB9QEM1JknoM=,iv:nfilmodEXx/WuA9FUkAXxWtqe//WEsEmMiZNjz/VsCg=,tag:WJ+yF4+e/PX9fvNa5EJK6A==,type:str]
            password: ENC[AES256_GCM,data:EVLCar7Lj2DTGUuIB3X8Yw==,iv:zSNzpO71k3fuq64zlRzD+mrBDlEqj3pxwCrdToSaLjg=,tag:4GeMZau14mdK3iKr+KFt1A==,type:str]
            username: ENC[AES256_GCM,data:URf+L1NBxzA=,iv:c3WqJvaFra3CdHDZK4RUicVDvfbdHwxu1yhDXve8GzE=,tag:yJs4aKmP2r7yr8qZDShPew==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1OW9nU2tPLytiRTBzcWQ2
            czh5RHczYVdveGFFZStJa1lCSnhYdThQc2lVCjNBNUV1OVB1aXZwTXNuWHdvWVlW
            YlVwNUpKdmZBb0J5L213K1g5SmU3NmMKLS0tIEtLNGdJWVR1WnNpLzRQTWZkMXdK
            TGlUakdPb0RTMk1tYloxeGNZYnI1MmcK/Nj0RisX3qyRM9CmJrxWLfQ+bC37FwPt
            SpEYex1DMVGPS7XkFF8XmsAZ8rvJiGJTU19mqL7ZqCIHU2WPFfugmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T22:01:40Z"
    mac: ENC[AES256_GCM,data:TY3P1JcxbUWqjWrg+AwvAltDwyp9yB+nTLIpdHhMsFEivf8VI3QTYAie9ZWLJsKbP9NM/So2QFRYPunc+yHF9YgjEdrV8eHw5MwzK+pduR4Q+jsaoXjddtw2SZXfU/oejTrJ6s5HC25tvajKkl/HMBEIfIDccQmH0shsOB3BqvA=,iv:tGplZkyidyUTuX+n5dlsif2tKJUpQRy/PRm9GpxypTo=,tag:UElrI8mTVOuR5TV8XUmdkg==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
