apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Replace=true,Force=true
  name: lidarr-lidarr-config-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      dataEngine: v1
      dataLocality: disabled
      disableRevisionCounter: "true"
      fromBackup: ""
      fsType: ext4
      numberOfReplicas: "1"
      staleReplicaTimeout: "30"
      unmapMarkSnapChainRemoved: ignored
    volumeHandle: pvc-fbb22ab2-e000-4d67-a760-1d14cac3bdc9
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
