apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: lidarr-database-password
    namespace: lidarr
spec:
    secretTemplates:
        - name: lidarr-database-password
          stringData:
            password: ENC[AES256_GCM,data:IltacSIwpn2ueaJF1MRJXkoS9sA=,iv:cot7VxxEVW/JY2kksa+fgK12H+QUBz6NCq2mTnQcCTg=,tag:TYHwvua5fb0JX7KwrBYbPw==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvbEREbmdqeDNOYzNVYkww
            VmthVElsWllVcEhudm54R25QY0FDQ0VwWkdNCi9GdFNVYi94K2MrZnBWb0RrTEV1
            U3VjTjNsUHFMV3Axc2JKTFpvQ3paanMKLS0tIGFydWVxNHNYeDA3cEw1cEQ1WUZy
            UmNKcTM0K1JUczhOL3FYcENZR25NQ2MK11fNMrJmYAo8/xbrbZfd/fI+GT9qUS2Y
            C+185xzhxzh9CnYd+riVzNjICeLkqo31FnBo/IB2M3yyZ9x93Q4hKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T04:23:49Z"
    mac: ENC[AES256_GCM,data:KxiB9qlyMVaoo7tT20ME6HIBsR3qYc8QoS5Onvxq7lnpwYYGBp7UAupbCyN4YztISKXZO6PZ7EZj6p0zkdjEsdX5piIy7d5lcvlJS+OysdmorxV5GuL1JhMKg6y5gLmYZq0AxB0NO6zOUz0hunRawL0u29GFx0bdursknZYSbQ4=,iv:u191RJRrepvc8yr+/jeS17HtXm5ODpLEmZP475RBUuY=,tag:whbjpOIN64g5Tzjwq+pMag==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
