apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: lidarr-database-password
    namespace: lidarr
spec:
    secretTemplates:
        - name: lidarr-database-password
          stringData:
            password: ENC[AES256_GCM,data:OaNWZ0HKOgenPgwZ/qTh2A1rav4=,iv:bUiWBPrJi8JG83/THlmc4mSmQgF1PkB6+ZulYyfj41U=,tag:ZYCZ14ojSvEEic00ToCRKw==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlQmVzbEhHMUg2TitiYWpV
            ZXhnejZBMGR5ZlFzbVY3N2E3dE1jYzd2bXlrCjZabTBZN3lyNzU1V0czc3RpN1V4
            NFF5NTF5STZwRzRiQWRZYTRiRms1cFkKLS0tIGpvYTlQTVpJSEJhSE1xelUrMzVm
            TnhLOGFndjV2Y2ZuaSt4bUV5ZkdIZ1EKTIMvOpR5A8w85jmQ2cpOMa9rzJQDTQpR
            s/A9hlTQp+DCUXUkSvCzlH/JT7FQItuE+ii2IcV4BP1XsjW0R4Zjpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-07T02:12:25Z"
    mac: ENC[AES256_GCM,data:VxLCQqtq1jfFHmA1/NQ0F6RoLcYMFmzwr88q1rUgG9qQhXKzflIl9y8b4NH461qj1y9+JqpU9GnGRZK0QposTNg0V0TAJ4Niz5BILESG4FUlZkaUvP5+5Sx7q/+20u7smeX953tAkdSSL5Q3saermjEZ8bG4J8BJYrS/lLZWSt4=,iv:fc0RMlwS+WZZP7xAPmG+LYLbhrh7Zthews5fHHYSGQY=,tag:XLHSEr2egIl2stFlPsOxcA==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
