apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: lidarr-database-password
    namespace: lidarr
spec:
    secretTemplates:
        - name: lidarr-database-password
          stringData:
            password: ENC[AES256_GCM,data:S3nTMcbO29eXg/dToR2rz5VHEdE=,iv:p+8ttG7yYggoHHd0HmthGQgG2ptQeJI/QHPVtJTduYY=,tag:9IFV03+MX1j8A6zJrPJDmA==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKa1JuMEtUckNzYUV6emJT
            d1FnUS9hajEyU3FMdFZVamQwWDRYVWUrVVFFCnBjV3pXYjZBaDNlYmRFVUdGcE1G
            dVkzYzhLaC9SdUNvTzhZcGpaR2ZEa2MKLS0tIFdvVFRZVjgvZW9ZdE56dmtXQUV5
            SWpCc2s3TjR5Mkt1UDlEL2c0TnFSRGMKbMl7Mjagkt7/luKdC4aUZx9KoRDTWQgL
            +7iR5Vn2BzkzooOdmdYO6teqI/26MfGK6tV3RQQmdu/Ux3UOWMIsJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T22:56:00Z"
    mac: ENC[AES256_GCM,data:GnvWV7nTzMCsC7rWiq39jtpQqxoyttdzrKYuy19h0/cxvkVecsAqb9yFDd+t9Ew4MmEVZ4yL3tz7iX60p9t7wjBb1ZBMq5pUTziNDrnQOmtmKL65eYFyVeUacDeEL4ys4vbK0muPUDvuwhWbBSPeizdLq0aTEGUpxDJyQXRfz94=,iv:waynl//FcjXJKfRgIBelXb0KxhSVIkNWQhRleIcKy9w=,tag:9W7Kis/j3VH0OfX7tjq5/Q==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
