apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: affine-config
  namespace: affine
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
