apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: affine-database-url
    namespace: affine
spec:
    secretTemplates:
        - name: affine-database-url
          stringData:
            DATABASE_URL: ENC[AES256_GCM,data:HAca9W6l3rmOt26vEAxYy9aMc8ydzD3hfMacxD9exsC/2JHN6hhlHkPidsRkpEvd9dbpieYsgni4gOgjpErW9mvEVHcBypk5IzE=,iv:w+TssvXAE6sldTHzm4pOpqBELUOsqNnpNPgU6y5W5Ug=,tag:QPjK1HutC6MBLy1HSuZ26g==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByT0d3RVJrVlNEc3B2cWNB
            ZUh3QmNtcnlOeVRtNGx4bkNKMEJrMGdsZW5FCmNTVnlTd24xWFRvQlczWXBXblJL
            VDNaVC9PS0lOWHdNbTVEWnhKTkx2czQKLS0tIHdINDVrQU9QRy9CWGVHV2I2ajh5
            K05Zb1dJN2VnMUZMTDMxY1dTRG9lancKP/Ao6IOPpl+DWrhjd8EajQ47bDxSuIR2
            cqGllLO8HZBPfTRO7O8cfHpEWw38+e9s0PWLNU6RLb5C3l+5GxcYtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-23T23:13:50Z"
    mac: ENC[AES256_GCM,data:sn8FHNCcG+NM8YfLI+14Cul9DFxkSQyJU4auV9FylI47gnn1SJooWvVWBKMBqNXsM+oQBk+cAnKyrHKajFycntUv3PH+9KFXSgKP9yT13t1zC9IJ0rk4UCNAd1724bsefd5ePmMHQ7yTG5GJk2p/DsoNxxaNOxVwZkALFhEnpxs=,iv:P0shl0yiTN+6WrIvJlZ0G59LpC7DfGKZ7QQ6Q+VEx70=,tag:e1fXcoW/6Hya1K/PriMByw==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
