apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: affine-database-url
    namespace: affine
spec:
    secretTemplates:
        - name: affine-database-url
          stringData:
            DATABASE_URL: ENC[AES256_GCM,data:+9mXSyM8WpugC0xgWGrAGwRG5Lyxti484JpvYu7YxS9A4/tXcwfRuF/5x6gWBJe1oPXcWm8hwI5uelooN2pJLW0M38FKfVuIPEU=,iv:sfn9cwDyCoA+sB2leXoRuA87KaCSV7PTbgk07qtcQmM=,tag:X7d1D1erTDF8MNxJti2Cvg==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzejZxS3RWK3MwZWhDZnRs
            b3FuRWdicjI0K1g1WllsMVZMOFFCanYxU2dRCkozb0xUSnlVWnBjUGhDWEp2Y1Fu
            OVFSTVdsZXlMcHFLTEgyY3VEM2RKVUEKLS0tIFJOWFFjTXZ3dmxOZXZmWFRhM21z
            bFFyTWdCc2wzN3FndGlYRTZFYzJQWWcK1shGYzQxfd7iEuBB8dg5ElshA0xq0j3t
            WH0gr7qMuXbpAzm40V6A/XQQgKOTJVay3hqYPhhCRuKwogvkRJLsow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T18:37:18Z"
    mac: ENC[AES256_GCM,data:lBxBzNAlgpZhv2mexH3TkvxFPiWd85PAUX3qFMLSPIDgUvuUbJMZFhcti/hQWZkB/ZFMHehHzEU1o0IVG7nd9kCni16n0ieJjPgR3xKOVcxsiVLiG6fgxnPWOvR5aNgXKT6b9XMJsJKwnPf6vGIvpV38+O8BT1VgcAqUOK7Tls4=,iv:NtCiBb/lp+kfdDiZDb3weD188X25GVRqnxw5a/zoDw0=,tag:60ApLAVNsAHaleLqNxhjHQ==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
