apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: affine-redis-password
    namespace: affine
spec:
    secretTemplates:
        - name: affine-redis-password
          stringData:
            REDIS_SERVER_PASSWORD: ENC[AES256_GCM,data:uLfmRd+7iVuAIyLkOAuwGHDBTBs=,iv:OldVFV8cqS/ffvaaEBM8W4NrXkoBL/ATw6IHbymFLu4=,tag:YEupBXx4ooUeaXwWGLI3Mg==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dzVNczJyZUZLQ2Zlb3ph
            RlV5M1p4a3RCYWNSTjI0TkpPZGo0UDJSY0Y0Ck8rbkdIWnlSRHNFYmYwRERCVjgy
            K3hBUENnSkxCVDhkYjFxSmZZcmRmZzAKLS0tIFdZcDREZEZDQnN2MGJFcXZYQ2R0
            djhldHQzSVgyVDJOWUxvQnppb3JIQTAKcG7iF5A+ti0IoRglIT00xRk4WqhTvjPJ
            VC/iNhQcz2JZqWLuOqt0AtAYZAvbaAIoA5rFNJXWjsb1J3nb8K29aA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T21:39:15Z"
    mac: ENC[AES256_GCM,data:IOQAErAJOYm5dhfjmBvqjlRpJuGK2efucWs/nmIpnHxZmR0UzxEzi3oq/UTYUvW2JntsqWzFkin1FSQDt/HUkDUFxyf289c3VB7jWc5LpRTyUmkwiPsSyfKxRfb2PWuiAM9MnprS4YT8BH6BFPW+11ywn5EHh9B53XsMvWaL89w=,iv:hI36if4eJsbegiYr3PjOGazGbUzNf/RcL7hDaPoIzRk=,tag:m0RzFZ0mKx1K27qqSsQhrg==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
