apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: affine-database-url
    namespace: affine
spec:
    secretTemplates:
        - name: affine-database-url
          stringData:
            DATABASE_URL: ENC[AES256_GCM,data:/5AECF9Za0tAWgk8dbIcU6EU5ZaefKe0qUMt+UypUCVljgkQn0bfpPQPuo1AkT8HQJdV3BsprOTztFWdLHa59KW475HZ0wImW3M=,iv:YkFSs/lrS7ibc0cvhKH0bwQsTJPAqIrfziaUw4LnCwk=,tag:JBrr9qiQTn0SNA251oOjFA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbVpiSVMydHl4NVJFRFJ1
            ZDFZTFgyNFdVWVN3cEtUR0tnZUFnNE11dWxJCmhQUlE0cmgvalk1djQwQVN1bk8y
            UUkxMUdRVEJRWEJxUkw0RXkyTGdZdG8KLS0tIEFlZFVPRE1hYytJN1ZLeWtPZWJn
            eEJwVmVIUDhDd0ovbGtCQzFQMnpaS1kKn0v4rro5HeMql+cOtWmScTZq99nW+sbe
            tZYGfr/5z5GDbarnRup3vGczc4tYv6cFRv5suuzyH5WubywIfHPn6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-05-24T20:28:31Z"
    mac: ENC[AES256_GCM,data:dhciTK5ALkrVqoZBIm3ENqOOM43ae8i3hTEnao975N8re+9+VOOC24QSdak22MPw176bTZYwzckz3CnajYf8PNSdPaKa9O9APtCY22YcLexrVc73Fa/53CqWxivUvGeb5QQmaa/2q26T90E3cCuZggbi2SNJENF4eUyoz4TrNGc=,iv:At8Ty4LpiMDjHV0nJbOMR+vpr5w65eD/ajmdMTzhSuM=,tag:4dG2EXt43PCYucvkQAYEnA==,type:str]
    version: 3.13.0
