apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: affine-redis-password
    namespace: affine
spec:
    secretTemplates:
        - name: affine-redis-password
          stringData:
            REDIS_SERVER_PASSWORD: ENC[AES256_GCM,data:0dzMfjor+M0kbl06TcdVYnJMAYk=,iv:8aUFnoWS6W6idiG3MVGp8Wgz199EIDTLE1c/MXHQDnc=,tag:6qaljJts2BS85Lg/DAu6og==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoWVRWTnFjZzlDMitSbGM0
            bW5YQkFtV3prM20xTG13a2t5ZVdVcWc1YTAwCmhpT3dDOUZLcksvK2VseVhXUGRx
            eTBHMmRaWHQ2YjhzZlYwZnN3c2o4cWsKLS0tIGtOWGFINDhmTlhrY3Z3WTMydnFu
            Wjdva2ltdGlzY1dQakhqWEJteGl5N2cK/rdvzvn7UsDZBxAobbXIOuRhctuS7hGa
            MXBi7DTXiG8NmSFmC+Geg9gcF8+sk+9JETKiWVaFb8W8S2/GZ8Jutw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-07T02:17:11Z"
    mac: ENC[AES256_GCM,data:F/9U+KWYI8bTgtWaiQad6CmWc1jIaeSEoxR1aelQcM3qwrLj98E3NZKpzbXG1Bhpkim1zhhS40cm0gZLvqJU1yO4gEm+LlyIsWXVyc6HybO1MFBelbgZ3Hd64EP9LNjF3IgRa9D1k0NWSTokJg/Ce9SEzcbs6unl2y6KTv9ize0=,iv:h52k6Oc2jgIFZhKaVNlOLeqkxdcbTIRhruReYKX9Cf8=,tag:L8YAtBxL5eljvTQgSxVv0g==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
