apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: affine-redis-password
    namespace: affine
spec:
    secretTemplates:
        - name: affine-redis-password
          stringData:
            REDIS_SERVER_PASSWORD: ENC[AES256_GCM,data:dk3kkR3nkfMjXvfGRU/hz/t1Ekc=,iv:yfkhJ2esMjfKjUya7xlRoYobUZd+zjV35lovG0HWuwY=,tag:vi8ei2+RDyY97WO1Wz5PCg==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNTBXVW9JZHFFWW5CV1hT
            Qmc4Y3NXbTZ0VUNuRlRvYlA4dTNibyt0U0VrCkIvWUZEM3hVaitORFR3N09TQ3hY
            YWVRVkhqa3dUeTJZMU51SXVPV1haYk0KLS0tIFpCUHdoYlV3eXpJb0Uwc1VaQm03
            ZzJGdlJnYTAwUHBlbDdBbVdUODJncEUKzOWmZV/BJRmC88136EYhEZlm3EXe36Bc
            m1QxIpkawWMqsHx+qiaAru0PU7Jl3rMEMoCt1BAKy4hTthHPf/plyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-08T02:51:30Z"
    mac: ENC[AES256_GCM,data:WAgYGNJm8ZkvC3feCfsuszDJh6LtDsXAiA+8LzqNSCUvuvQ74PyTJ/7B6Jc5bFE7x6S4KuyPiuJwje+mlisUBVRvd+2dJgTkAy5rhqCuQV2O+ibC5yrmINfSe7ONAe1Z94kflwck6fKiUFNwKiQu8umV9hoBU9q8Fh7ip3IUck4=,iv:n8jLqcx2vbzqNYJk9JGXABIDFo69XOQr6UQKYCkFmg8=,tag:WxyuHraFkF1KEyQbsyWU7Q==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
