apiVersion: v1
data:
  JWT_SECRET: VTNWdUlGTmxjQ0FnTnlBd09Eb3pNVG8x
  KITE_ENCRYPT_KEY: VTNWdUlGTmxjQ0FnTnlBd09Eb3pNVG95
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: kite
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kite
    app.kubernetes.io/version: v0.14.1
    helm.sh/chart: kite-0.14.1
  name: kite-secret
  namespace: kite
type: Opaque
