apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nix-csi
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs:
      - get
      - list
      - create
      - patch
