apiVersion: v1
data:
  authorized_keys: ""
  ssh_config: |
    GlobalKnownHostsFile /etc/ssh/ssh_known_hosts /etc/ssh-dynauth/ssh_known_hosts

    Host nix-cache
        User nix
        IdentityFile /etc/ssh-key/id_ed25519
        IdentitiesOnly yes
        StrictHostKeyChecking yes

    Host nix-builder
        User nix
        IdentityFile /etc/ssh-key/id_ed25519
        IdentitiesOnly yes
        StrictHostKeyChecking yes

    Host *
        User nix
        IdentityFile /etc/ssh-key/id_ed25519
        IdentitiesOnly yes
        StrictHostKeyChecking yes
  ssh_known_hosts: ""
  sshd_config: |
    Port 22
    AddressFamily Any
    HostKey /etc/ssh-key/id_ed25519
    SyslogFacility DAEMON
    SetEnv PATH=/nix/var/result/bin
    PermitRootLogin no
    PubkeyAuthentication yes
    PasswordAuthentication no
    KbdInteractiveAuthentication no
    UsePAM no
    AuthorizedKeysFile /dev/null
    StrictModes no
    Subsystem sftp internal-sftp

    Match User nix
        AuthorizedKeysFile /etc/ssh/authorized_keys /etc/ssh-dynauth/authorized_keys
kind: ConfigMap
metadata:
  name: ssh-config
  namespace: nix-csi
