apiVersion: v1
kind: Service
metadata:
  name: nix-cache
  namespace: nix-csi
spec:
  ports:
    - name: ssh
      port: 22
      targetPort: ssh
  selector:
    app.kubernetes.io/name: cache
    app.kubernetes.io/part-of: nix-csi
  type: ClusterIP
