apiVersion: v1
kind: Service
metadata:
  name: nix-cache-lb
  namespace: nix-csi
spec:
  ports:
    - name: ssh
      port: 2222
      targetPort: ssh
  selector:
    app.kubernetes.io/name: cache
    app.kubernetes.io/part-of: nix-csi
  type: LoadBalancer
