apiVersion: v1
kind: Service
metadata:
  name: nix-proxy
  namespace: nix-csi
spec:
  ports:
    - name: ssh
      port: 2223
      targetPort: ssh
  selector:
    app.kubernetes.io/name: builder
    app.kubernetes.io/part-of: nix-csi
    nix.csi/proxy: "true"
  type: LoadBalancer
