apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homarr
  namespace: homarr
spec:
  ingressClassName: tailscale
  rules:
    - host: homarr.bearded-snake.ts.net
      http:
        paths:
          - backend:
              service:
                name: homarr
                port:
                  name: http
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - homarr.bearded-snake.ts.net
