apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: homarr-secret-encryption-key
    namespace: homarr
spec:
    secretTemplates:
        - name: homarr-secret-encryption-key
          stringData:
            SECRET_ENCRYPTION_KEY: ENC[AES256_GCM,data:N3BcdfefgyF1IFxCrbR9mKjDHKe9Vu6T0A38Vn7ghJ2+PxabFD25dLYAhkKWTU4yFIK514DCWFSaGKF1Y5X4Xg==,iv:vuE1ZTMEy6YazKHBejkAAE2jwjbGpwlZqj3UF7KFhuQ=,tag:cOd6LIx9OFdwNDZsfdwjWQ==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bXdpWXBRR0lsL3VUV3pQ
            d3BjM3RYeGRaZlFBbzhyMEdkKzJVKy9JQm5vCno2dzRsbDVVd3J6b1BEN1FtakNa
            bHhxelZWcDQwSXVGUTgvVDhaV1FHbXcKLS0tIE5yR29hZzJSSjQyRVZDZHRPOTJr
            SHFFOGJZWTBOS3BocFE3V3lkQUxHcDAK6Ro7vu/PjWC+0KK25Wm8dueMXj6ryl4S
            PWr0zTRqCX8VQy2cuCQlg/F2GbRwGmmr9dHucIUDtJNfIFwuoPHKAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T15:02:55Z"
    mac: ENC[AES256_GCM,data:hnOhW5gIUATqB0nn9EqziRfL8Ukod1lRNiYgeiZbikfxAcOYgqYA4O6GHZf+RejqmwqTc1RfYrjm8Se1MREFl+5ynUui7MR4rgBt7GUM3Zo07oXsCXMEwPCjL3QcLHtD5W9G4k771pSo786Zz5M7hDyEe111owrrB57BpdpxqD0=,iv:cDgu34Pj2+omyAw4V9FgvDEKbnsIunGbaQWSzQnl10M=,tag:8u8PUdfFHN0VIshParEncQ==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
