apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: homarr-secret-encryption-key
    namespace: homarr
spec:
    secretTemplates:
        - name: homarr-secret-encryption-key
          stringData:
            SECRET_ENCRYPTION_KEY: ENC[AES256_GCM,data:88DLmNLF9a5s0bXWn0gHz4qPfNMT7ros48dwmXzYqh5/QdSomt7cjzaa8O9425YP+QrbJM2wLWS+V1UXPasLeA==,iv:8QrVE2ZpCfC5f8Iz+PpgNXjT8/5tNfWaBjhrthyV1os=,tag:OuMtdRT0iu2QC8kPJ7hlJA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUHlPUFFYVVJYdnJqVlRD
            dzEzLyt1TDFTOUwxVW9YbjFNQUJJMnM5YlRNCkJuY1BCc0JZbGY0UzBvYUxNUVJh
            cGxQZ0pHbVlLN2tGZHEvdWZYUFNWYlkKLS0tIDBPa0wyWmpVOXphV1p2c1NYemE3
            RkIwNHBDVVQrNHBJck1GVWROK2hCb3cKaQBd7X7MdSu/ihcov3fGre4oe7Vae3Ff
            OJLcRF+oACOk1YuXGUSyHKd8HaYUmGkmoT2DouMQK4nQ3eyp4WMe/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-14T03:04:09Z"
    mac: ENC[AES256_GCM,data:U88vYiicG/+4NTVeog0jbzRqP1Ff9rjHMxE5qVqjR1DLFgm8tPK14je0d76k/txPAmUbZ/5SrvdgMiu7CqhhK7c+dstgGwQ40jU2aNEW8zYTsw3GM96/wEtguxOds3OrIEfhImY3d2cqA88IYyPZLogtfUeTMoPUho2iGPPVatc=,iv:BW4zP82rSp04ypZcBLsCMdynWvridPDYyxsMTdEe2PU=,tag:4or5oxz+SMkbUWgfgmZcHw==,type:str]
    version: 3.13.1
