apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: homarr-secret-encryption-key
    namespace: homarr
spec:
    secretTemplates:
        - name: homarr-secret-encryption-key
          stringData:
            SECRET_ENCRYPTION_KEY: ENC[AES256_GCM,data:DpV2gWTOwbMnvccyskvjAu/7QYLsyHhTKa9Fn4OaeXpOVz/E/eS1gjGMipdh6DSDniE4TCpPgpfsmYvE2yd0xg==,iv:yMT7fvRvg0b4pKT+ZOJl/yYjcVXhl8UiGEc3TB6DBhg=,tag:KwHUgeCVl5JwK43J1GD4TA==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQT0c3TEFFcnN6U2NIVDdG
            czNDcENyUXo0b2tDbEU1S3FySGpKVXVQdVZRCmU2eEUrbzV1Tys2Sk9HZk9IRFVz
            eVRKMFBDenprc3puYnhoRi93UWVISDQKLS0tIHFzZFFCTHB1aXNYVlVBMkQ1bnEv
            TDRiUzVlNmZhNGJEU0pUNE5SSDI2czgKTMohZPYmJ5o5dH9V0lFJVi6MyHKusiee
            ca/2Ab7fh//epRi1Q+fFngRs0AAnwtfpY6PcVFKwEhXtOyMhDhlbbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T03:24:37Z"
    mac: ENC[AES256_GCM,data:ioqsaQM2QPqbbR24RqohkaKCAwA8Fyb0J8TgVQ0+smJdkxfptCKC2FZ+l3RPGQ5yiKBA9qxO6VWzq+FOO8dOW/dKolBlDzo9P7ffbqnaCYmhsN8rVLmynRUskDrO3FiZQDCAmGYAOboYXgaTOwUxaUUdSOWjTDOMaFtci65PVAU=,iv:GVYl5tA2t1rVGVVw+RBEUjrvqDfVl2siqdL00EgAGdU=,tag:w3PcEZiZnT8y5ekgJuyETA==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
