apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: hivemq
    app.kubernetes.io/name: hivemq
    app.kubernetes.io/version: "2025.5"
  name: hivemq
  namespace: hivemq
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: hivemq
      app.kubernetes.io/name: hivemq
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: hivemq
        app.kubernetes.io/name: hivemq
    spec:
      automountServiceAccountToken: true
      containers:
        - image: hivemq/hivemq-ce:2025.5
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 90
            periodSeconds: 30
            successThreshold: 1
            tcpSocket:
              port: mqtt
            timeoutSeconds: 5
          name: hivemq
          ports:
            - containerPort: 1883
              name: mqtt
              protocol: TCP
          readinessProbe:
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: mqtt
            timeoutSeconds: 5
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: 250m
              memory: 512Mi
          volumeMounts:
            - mountPath: /opt/hivemq/data
              name: data
      nodeSelector:
        kubernetes.io/hostname: nixmini
      serviceAccountName: default
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: hivemq-hivemq-data
