apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hivemq-hivemq-data
  namespace: hivemq
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
