apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediamanager-mediamanager-movies
  namespace: mediamanager
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: mediamanager-mediamanager-movies-nfs
