apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediamanager-mediamanager-config
  namespace: mediamanager
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: longhorn
