apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediamanager-mediamanager-images
  namespace: mediamanager
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
