apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: mediamanager-database
    namespace: mediamanager
spec:
    secretTemplates:
        - name: mediamanager-database
          stringData:
            password: ENC[AES256_GCM,data:TPXsw0MsgQ1wc18LKp9lm19VEJv9RsSyi00E7a1vdsY=,iv:c6IGarmQEfjsPkfS2TCrX9Gw6yCDT3G3wzvAM2n+S1E=,tag:vTe0t91Z5LEzHjS26tG2Sw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdjd4RkZ5LyswdFNjTkNC
            K3lBb1huRUFaVHZkY2dpd0Z5cE5HdnZhcmdRCmdzNkdmamtDbllIdTFFUVRrSnJH
            bHcvb2VQQVR6ZDVhZzlBOWlFdWFDM2sKLS0tIHJvUkxzNjV6T2EvL3M0SHhvYy9x
            c0Eyd2hlU1pVU1VYMkVCd0cvb0EvVTAKKgJ1Dy/4hwv8f1Lx6yxGn2jGAcxaow7y
            OqLc1nPk+eCvWDv7H/yxAXFq3YJY2NbSWBnfk1IFUElqjLQmkBz+aA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-11T21:19:21Z"
    mac: ENC[AES256_GCM,data:KCMqBk8snd0GwGbx8FF14UsMg/yVVYI6xPcfHbHj31RqJBIy95ldTlzXvZGWjRfIC5YsRPmt22tpDbqVLHt8C0VQ1lmv1e5XfxAWCAPLRXzGL5y+LupZE015zp/TrJXa2NHWEm7voNDou71P9ZTfKACvTkZiCqR3T6iWfaJBDkU=,iv:OYf22fXgu32RatbCJYX5VFr1+RkSRsPoQA5qV6EVWs4=,tag:bvaweNAeDda2MA2IZ9ZX7Q==,type:str]
    version: 3.13.3
