apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: mediamanager-auth
    namespace: mediamanager
spec:
    secretTemplates:
        - name: mediamanager-auth
          stringData:
            tokenSecret: ENC[AES256_GCM,data:uVShcz9+6aoLUelc5hmXuA2Ss+r0WWDJoxpOlSx3vcCGbeurVlZRhorxB5kUZ9KGA36XvMkgU/IOsLJEYn0gJw==,iv:SbHSxABs99k8zlRA8t2UA4/epPdoc7YvIRfFPte/X0M=,tag:NeJSPSjK9nmAi2gtI45kJg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cm5Yc09jaTlKNEVxdS91
            Y0F1SGFjSW5NMnhhTzV3T3NpbUorN05nc2hFCkhRbldGWjY2M3FPbEg2bmZvZEtS
            RCt5b3czckc1U2Q1a0NhWkJnQ0lGMGcKLS0tIG9tZkpkcmZLNWxXd1kxaE15Z29m
            ZG83TXRaMGpBMzY5RmdFOEoyN2hsdG8Kdpr5YSoT1f/WGAUaqGqjZMLjB+u+03AG
            kHxnW+QqFas+/772TuDhHcfK4dtlMNuYbO4zoslRSjBvFybfKL7XIg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-11T21:19:21Z"
    mac: ENC[AES256_GCM,data:3i0FaGP+rb8kfkFq3TL/Gn9iZuGAAPWxgmQZAtQmQ+8K13OS5KtwRkw04VosSMkC9EzvaKKgGFyLulznri/zOKc8W+i2gcqri/Yq2+NIvvpEGVfHYMT7ufLPCKj6WYzLdz6/fHAowXyQztdaLaf6rKaNTfJN+GPexARkDIYR0t0=,iv:IniKvA7l9m5rQB2feNCQPq+EJXERvxnPq5bMhvN94Os=,tag:eVOO32/rWqnEdgOLw2f7XA==,type:str]
    version: 3.13.3
