apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: radarr-database-password
    namespace: radarr
spec:
    secretTemplates:
        - name: radarr-database-password
          stringData:
            password: ENC[AES256_GCM,data:O8GKMvcrv2MHKGhISAyI/DRHVoA=,iv:XZB8cvy7ebgYMJMc+RsYHpvasXPi2/F5ywf0LBD2e9s=,tag:apy3mZlbHnDmqIjysqlSLw==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCaUo1T1hyR0hDc1BSdXN2
            OFM1NHlNNmltNEtFNGF0cENwYllFT1lZNGpZCm1la0lPdC9tS3pIUkpQVmpKRTYr
            dEUrQm43OXVoL2lwUXg2M2h4bkdQT2cKLS0tIHZ5RGpnSHRnWlFhK3NTeC9NU1JC
            cGtxYk52eWhlT3p4Z2w2aFI0YTI0VmMK1fBDnTbqgQpghj+dqR0An1BXsEvMcdg3
            TMYyrSRn+8Iu96R8qYvS9tWoMa2VyQgti3dqaMpo9veNZ9f7liQP1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T18:37:18Z"
    mac: ENC[AES256_GCM,data:w5+gRFboixBGimvYyNSxmclagZGtD/xtnfsxKAVBX7IFZpqSBuYeSaoesvtekU6puWM1Lrqg0RCKpX8j4oH7H4n5dqIO4nmifN0+0WeTbJmxqWKAu1W8QSNRCmu2DV5O1alNvLTmT28V8+VuS5Q++K2zI5cFeM1kqxJzYNRURaY=,iv:Vsy3Etcbe/LZiGvc5X9fTtdIb8IPQHmFybqVJ6ksDzk=,tag:PuNaPbV9hfsIP9ACsdogMw==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
