apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: radarr-database-password
  namespace: radarr
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsckwyZVV2YkNLYzVwRzVq
        R1VXcGVwYmZZOVlidms2eTZabjVTS2pqUWprCkFsSTdQSG9zT3QwKzZuYUZTRzNP
        d3R1U0huV29mVmU4VnpueFQ3ajZWNVkKLS0tIDBCcWNLUHB5MkRvZWFIait2bnUv
        OHFKSlgvR0lkRjhVcWpBVnQwLy9hdmMKje6CFTt55MjeYtHQm72hCpRi2GIudQxb
        0FKSanjxcFc+4qzveGBPgG/UdRkYn+4JQTt2H/k4oEFpGJUSN1MqJg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
  encrypted_regex: ^(stringData)$
  lastmodified: "2026-03-21T17:45:47Z"
  mac: ENC[AES256_GCM,data:N7P8w4rHjRa3SUmQKUKSBJsrS2uAB1vK/q+OrGgIyiMshMxYPPMfhWC7T+Scz5YEdXnW0aJ4fWvWCNA/0ERmYqLRhLulmInhkOE0GMuF16th8SMJbCw4Unz4FA7u8mNH85EHcTSZk6HGQJ8aw46U3jhAuufXRPxnvRfo44ZpfrU=,iv:aOOiJi/3TWsFlL94D+3llr2Y0LR04xJ8jAznMROFlgA=,tag:PIqsjag0cUNQPU8yb+8UHg==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: radarr-database-password
      stringData:
        password: ENC[AES256_GCM,data:iOcZVeUCw+AkN59Tc4sqEgfF6zc=,iv:ACAu8aj1Ix7rbM+drANqv1iwmbz17tZ87Pd7ieeGBAE=,tag:ZWTY27QNkzeHZHiw2u7wAg==,type:str]
