apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: radarr-database-password
    namespace: radarr
spec:
    secretTemplates:
        - name: radarr-database-password
          stringData:
            password: ENC[AES256_GCM,data:HoDcxk4abdEpdgMm8F/qPPBVfE0=,iv:GhGOCoj288Tj99mdWjQPhYZet17YyJkX77/9omPJhqM=,tag:eQcreHTXEHWPhqu1dsUMbA==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3b3JITGZ5MHQ4MHc5bDFm
            L28wQU5oQ2wwNWpoeUNYL3FGTW5ralg4bkZBCnB1eWRkVUZ5SVJLaEdSYngyMG9p
            Y3RjQWVoeEoxbkwrb3QzaUxUL05rajAKLS0tIFJySU5tUDZyQUkzLzJham9nRUJY
            Kzh2dmVsSmNvVk1tejVtMmRmeVMzc0EKgaohy2UQ+15MitTA4+9Kdf/nF4UQ1nlL
            BYUteYJefCUX6OpWCwNUEoY6rxoOlc33OPlZphsH1aUy2ojmL2AFXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T22:19:46Z"
    mac: ENC[AES256_GCM,data:TonQQAYOiGX3SRoURCM88z7q/T31FpxSGtR88mV3AZRmE0xndmakbYe8Qo2JTYT0YZkLA26+Ty1G7oRKXRGCEFqL3ZuVutAN/BCgfEubQTi9SB1l2bF77uk1Out2cCDwMu6B878JO+Bml625lfkj7tnMv0ey6B2xbZbXF60gka0=,iv:RuNU9hnSST1IZa3WDtn8OpBs6uCQFn99vg1hA9gnOKA=,tag:u1dsr4ADWeENWYqFbAPInA==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
