apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-immich-external-library
  namespace: immich
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: immich-immich-external-library-nfs
