apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Replace=true,Force=true
  name: immich-immich-library-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      dataEngine: v1
      dataLocality: disabled
      disableRevisionCounter: "true"
      fromBackup: ""
      fsType: ext4
      numberOfReplicas: "1"
      staleReplicaTimeout: "30"
      unmapMarkSnapChainRemoved: ignored
    volumeHandle: pvc-d794cdee-ffa7-4885-a2be-b741de8dd416
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
