apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: immich-redis-password
    namespace: immich
spec:
    secretTemplates:
        - name: immich-redis-password
          stringData:
            password: ENC[AES256_GCM,data:EpvfDYHIuxUREJ5f3gyJET+Xsz4=,iv:CICa83cmse2Wg1yyyIzwfU3JJwBDphPEArvU+5ATX10=,tag:PWKoT2osMX4wK8e3EyoOqQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlaUFsRGNzVGdYU1F3WTNR
            TG9uWlU3aURueGZ4V2JMbTdwcm1aazdiNkVVCkJhZ2pLYlB5enRWeHJod1M1M2Vu
            Z1NRR2FnbVZuSysvOVBycGhWVEVTNDgKLS0tIEJLTy8zc3lOTGVvRXpIbmUwdFhs
            QXRkQ2dFTGtwZE9vK29aam1tUVJMNU0K9+dBLq4/sN/zS/Ya9JPTFECjxdqB8twQ
            X2yNudP8cLcinmkiMvm2Y9qSwaR8EF1pPuL+GzSPMRFgtudQ4hqH0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-06-01T14:22:14Z"
    mac: ENC[AES256_GCM,data:oM41PhdzAOL7PGNKEskziaTqpwaT1+UB+avbfBnHhl0esla5CKbhAm63A0qTxwLDXACIi550BPUN69uh26XtODlkjv2xJfOoxmkpHaEO7xldFzqSFDUpTEQ5AMpAC932S/sOrJy52/XPxkqHG/K/iJn1GaoFH/N9YZeG2UI4vr0=,iv:qc+ok4rZpXk1ZDHuZd1eJvsfV6NGe6COdEjXhKAthAo=,tag:yGX7bgILCewVMmy3jqSJyg==,type:str]
    version: 3.13.1
