apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: immich-redis-password
    namespace: immich
spec:
    secretTemplates:
        - name: immich-redis-password
          stringData:
            password: ENC[AES256_GCM,data:Thj/lpeT5nHwZQZf2N6gBRym268=,iv:dhLCMKUfxnquaO7ox1dfAoBtkejLESroai4rEjXV5TY=,tag:m0QHU4bOnCUVXPZ1NVpgXA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqenk2NExxTE45UUxlc05D
            QlNRSU5TcERLQTNSQ3FiRkQxYndFc0FYYW40ClhZYjhIc0tjNVUycDRJbzZXVVdk
            ZmFCQklSamo0RVRJSHdFdmhnY0JBN1EKLS0tIEZTWTlpRC90T3BvUEpWbzJ3ZDlv
            UGFKUmwrN245eExMYWNmV1F0WnBhSVkKysr0810derbXQpv+77S7dCaJOwwnfoWu
            B1Oo7m/WlH+PMkq7uANANUSrNJjRUQYYziWlQydmGtB0UVfqHuzRCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-06-16T05:19:28Z"
    mac: ENC[AES256_GCM,data:qTRcD0QpziBmZwO4kLe4LQUI7p+LPvvY5bheRPO/4247K0QcvX8guolB4Lkc875ponGL3afGr+TCDsBYXCTeN0xdeIo8TJPbOmwQkSps2OI+qsxGpAhQ14ct+IfSHSNyuE+5yETb061H9BoDqKZHyuLezef8Cuq9b5Wf7jxCvkw=,iv:k8fF/qgHWx+oFtrYiNHkhSTYzU7ExC3aAMOB0J21chI=,tag:tEBGYWkf+wfcYZwkinrsew==,type:str]
    version: 3.13.1
