apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: immich-redis-password
    namespace: immich
spec:
    secretTemplates:
        - name: immich-redis-password
          stringData:
            password: ENC[AES256_GCM,data:eKupaGvPNZOMdUcrj/XShcjWVMo=,iv:TW3l+NM16UtYo5W+JTQCJZwoGt9coHHQsRZWZ5hpjPU=,tag:F+6nH5FrVwyLOcgwq7240A==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnR1BNMlBhN1NVTUFtc2Zy
            d3dlZmlEbGkvZmZDTWw2SFRZVlRGbk9wOWlJCjVLaE43N3NTeitnNEk3QktlSXhO
            OVMvV25OME9vYzF3VWk5bXpoNXFnQ2sKLS0tIEJmZ0RVTGRzY3J5NHpOZ0lmVHJX
            U1RjZFEvYnhqMnVxdy9WS2JrWWdzcFEKDvikNy8YbdIXi4WmDfevADN2WsGxzSsr
            00qg/WeNHw4QVmFvERagMI+2aUfUR57eD8tZgmWglo9Yc7MKDLgCrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T23:45:30Z"
    mac: ENC[AES256_GCM,data:oQS/bGhhBZWVRX0pyLUzhC3IJ62h6KbB9TgGcEOhzTyMHnCshURCvPNYVAn8Yb+mnuD5vCnmgU/pKEZu+ejiYGRPmXjYzqux7XLhujzmmvHlqLrZw/l4XzTTPmt+lAQtcbfJaA8UBWJSNbsDmDbs1bLv9zxyXz2S9Tg7T3mVDpc=,iv:435C3pWODqnWhFwqh25fN8b8PfPUxkZxjngzasCGU3w=,tag:4ouAQIxHTqBFdF0U7M9gxA==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
