apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: immich-database-password
    namespace: immich
spec:
    secretTemplates:
        - name: immich-database-password
          stringData:
            password: ENC[AES256_GCM,data:5dd1QhbtTrY8OG8dMPoD5l25rBk=,iv:rPaUKccGzkxn0FzrCGw2c4maPWZeTUZrtoNYxlmwXbQ=,tag:Hpcv9tOYoTmF07IhztrSag==,type:str]
            username: ENC[AES256_GCM,data:8gvxqImnWkE=,iv:z8+nTFvFINOF2oWAmOuwFK2Eu71M4ZIIvK8XAWZfVvU=,tag:6T9DOP2HKtQpozCeaczdLg==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESG4xVmNJREdCcnQ1cmto
            KzhVOWI0eVVWYXpoY0hTSUgvM0xua3Z4OXdZCll5TmJPbnNNaDNNcld5NGRuZEs1
            MU94Zm13THdyTGIrd01rREwzUjBwb1UKLS0tIG1FZWkvc2k1K2VFMmV6Rkl2Skpz
            SGRzN3lqRG80Z1lVL2p5S1pXVTZSc1UKXWrEzTdAmSxyUi0EtjBdnBISC1VHVJGm
            aAwV1A/P/Su/SBtllpHootyvJcSZlP8XENF0bsN05AbXTjvTDFHpdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T23:45:30Z"
    mac: ENC[AES256_GCM,data:xaZmDO8dD8WX2URORplTLDKe1FCZzif/Uz/iIuoNZkL2T0/ODv4JP/y+WJL7Lj4NSIUSolbBJ/1csn2Q/uEBcX7iVXGSDxDE35lpMx3zF5naA5pgswsADa0mz8/YyfZU/ilymja5Ws0fWW68dXcgyhib0DiXK1nLhIqy47PhSzw=,iv:cFztN2kuznjpGXemKRFpaHCLQg8X/HcPkMawDu4t04U=,tag:AeuUbjzkHMCRcWFz7r9LrQ==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
