apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: immich-database-password
    namespace: immich
spec:
    secretTemplates:
        - name: immich-database-password
          stringData:
            password: ENC[AES256_GCM,data:zCsLyaF3DogfHPZFxUsA3OdWk5M=,iv:nEue2LmFA0ILnxBQwGje4B/u7vV5Plo2pgjLQJ24omo=,tag:NxK1OLcR1Of3BlN9z0ZL+Q==,type:str]
            username: ENC[AES256_GCM,data:fEoQ3fBeY5Y=,iv:zATyjczOmrqgf2RIRiGadJzo2VIpIOP94+eDloDskVQ=,tag:fkyt/4WxYV0L2hcyhm3Pdw==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0d1J2aU5zVlVZb1NBUlBK
            Qm9hcWdPcnNVSDBObmZWM0g1NW5hY2ZVb1JrCkpOb0NmMXJrMmloVk1hN2o4YzFv
            TzFRdkxJaVVsNXQxV2ExM3dZeVI4akEKLS0tIGRDRW9pN3AvOHora3VlUUZzWW9s
            b1FyRkpoVmN3MWZDcDE3dUI3NUJTbGsKp+MEd7++xZnlAY/mkUoMN8qQOjDdx09E
            hNxxXhXUlcYKPyHUi1nsplX+5P97hVYBdm+zAMy95WNGqaw28sgKIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T15:02:55Z"
    mac: ENC[AES256_GCM,data:Hsx6bGfUzfN/dSIQdcqJmIzXCdm5U4sE/qYkD7X50+GVHkZddNmUT0yFSvJuh5Zd1EcZCKVN9MBtGK6qhn8tre7/DB59Utntz7sNLpUNsW6QfeNt08sraVYFmyyhUOKltg40B6QSL1NERDWoboNa9XX0fcz/6v+NvW8GEYAyRaI=,iv:NgRGQ9ekDdouD6JH4CtvHE21aOWK2JvP6pjBburuGY0=,tag:ms5cBguWr8XrH2d8mH6saw==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
