apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: immich-database-password
    namespace: immich
spec:
    secretTemplates:
        - name: immich-database-password
          stringData:
            password: ENC[AES256_GCM,data:s2Yyc08DV8po1rjy0K9GT3Le4Ns=,iv:hqJl2QaOoL2QnCEtPGV6YnMlHkOjmK1fD9D7HQe3UIs=,tag:9tpJ0wacA7R1uffPvhB7Fg==,type:str]
            username: ENC[AES256_GCM,data:Eq6bmtSiT6k=,iv:W+IufM5uzOFCidDnQhPr8DtyB87DEPI6wgKKDo4ktgA=,tag:VzHtyN3TWere82rc+inn4g==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnVEtRNm5kZjNrT25oQTFL
            TUJWTGFSQnZRVm5uRFl5VFNGaDdoVUZxQ1JvCk9zdlA0aGFEOFVHWmRJNWdSZmlm
            Sk1GQ3NFdHlLdHJuQ1F3REZSb21iWDAKLS0tIGEvSS9OWm54VUxCRHlLTlZreWta
            RmlVcTkrVE4veTJQN05ES1FqeVRYcjgKdkB3jnVy3TZp1pDQ9sTjVBILkZCQjBTN
            HvyffzMgAIZFqD91ziDUJNhIrjzg5BS+ucKRhbAnZSvPCT3b/GRcUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-08T03:05:48Z"
    mac: ENC[AES256_GCM,data:Fp4zjni6EzBNmU2LDCl7oKe9TOxIT9QpGSi410nRHuZ8NCX2DjF6+2V3DGjE2LRs4irreTInHWOdLOHz6yD8937mLTS2pX49d8YYdqV5b9syP8gtKSSuLvY+alnvAYVBALGZvrB0+ueir/3J6g+NiiiPjHtG8FRUzr9P1nOUgUk=,iv:c3EbkV5pnua8h7cm82URHhxj+5Fj2MZcCPdWvKIDjpQ=,tag:DxKhcFaQG8D8wxuu8t1Vpg==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
