apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: audiobookshelf
  namespace: audiobookshelf
spec:
  ingressClassName: tailscale
  rules:
    - host: audiobookshelf.bearded-snake.ts.net
      http:
        paths:
          - backend:
              service:
                name: audiobookshelf
                port:
                  name: http
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - audiobookshelf.bearded-snake.ts.net
