apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-audiobookshelf-metadata
  namespace: audiobookshelf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
