apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-audiobookshelf-audiobooks
  namespace: audiobookshelf
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: audiobookshelf-audiobookshelf-audiobooks-nfs
