apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: metabase-postgres-connections
    namespace: metabase
spec:
    secretTemplates:
        - name: metabase-postgres-connections
          stringData:
            CONNECTIONS_JSON: ENC[AES256_GCM,data:dvpKsCcwbuxcsJMPninxxdTOrFUNY+roF1B2CRF2wweZEgkzoRIuj+L3y/eh7j2fGMdA1467C+Qq9hpSK3geLLxLIXX2ukiMrocY9SggFIIN4xOx4XBI68sE5N9hvnAuJ3UqSXbN+g6BiEVQx+Z9Yd9EHMw=,iv:iHNfrpwABm4HNeuY62HWfsHh7PhmH8toRvcF3o66Eug=,tag:x/mx/A/G4uGesyE+l9YGow==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTUd1dGJzOXlETEtCbmtx
            UDhvTEgzbFdxOXpzdEcrUTZKV0ZTSHNYNkU4Cm1zM0dwYWdPTUtDL1lHZDJhbnYv
            dms1UVNNRkFwV1BMNGtSbkFOTVRLdWMKLS0tIFhvYzh6c244UEl3N05lWWxDQmJj
            cUg1RkRCdlpBaHRlTDBqMmJxa0d4T0UK1BU5MsX8MY3mbTyBEdTk1r3TXbHAFo0G
            x3xUgXvx032d6PycPj+Xe1pewU+QE5sTHPAGwKcagGj1QtEd91fNEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-12T03:06:02Z"
    mac: ENC[AES256_GCM,data:t5OktPB69uniCGf9POpgOvgt6XR4YWzA0rSR+x7vhu4FBWi/fy/SMSYUXOF7z3yxAFO827im1vo7VJw/+1RR5E499H3XDDHbRSSItIRzENpVyiFBvBsQk8kNhXpL/EY4S53qouxH6oIraZOG40/veXb1YnxR8QuKvygbS9KJ2C0=,iv:/o8suE5KV9IX6ir8Z+69QWW42CCSeYFq8o4YZL6X6F8=,tag:U/L3x1tKsXdwIjdLfEKSJw==,type:str]
    version: 3.13.3
