apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: metabase-admin
    namespace: metabase
spec:
    secretTemplates:
        - name: metabase-admin
          stringData:
            EMAIL: ENC[AES256_GCM,data:idrY15shBw2WaJWpClrKpvg=,iv:bHageVOOm/Kby7j7mO3/gbARtgL3REgAbCa1iSAztoU=,tag:dbJKgBslZL9BDX+lo2sqbQ==,type:str]
            FIRST_NAME: ENC[AES256_GCM,data:TRZ3fXc=,iv:wHlPKt+sDwexSwAr7igxOBWV93WDa4IfcYytSNEJjkw=,tag:1itLnsSDU8A9vUYpWg9iIw==,type:str]
            LAST_NAME: ENC[AES256_GCM,data:MvNP45w=,iv:vWj0dlU4PLlX7JpsNLChHfyF9mm66L2Vln7CeaduBSU=,tag:y4h0+kFhs2tb5XHIUaEZNg==,type:str]
            PASSWORD: ENC[AES256_GCM,data:hVyuWTNq+AMCdJ8C,iv:TG8qBsXNmT36XPtmWbwzE/uzblTcRV7LYmUZwNO5P+U=,tag:Ag1gGFnO6H3kH+7TU22A5Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMS3RGcHdzZUNucVVjOUJN
            Y1dZNU1IV0lFdktWeHJHU0krbjdpcFB1a1VBClp6T1pkczMyZHI1TS9nNXpQZTlL
            KytnenBFa1ByeTIyMm42YVI0M21tMlEKLS0tIGJYZ0hYaVUraEozb1A3bm94ZHVD
            eCtFeTk5V0lhcFQva3pjSFNxTU9UTmsKhe3R1Y3FnNQUbtKEKyJ4E4KsJTgeRoq3
            fG1TCSRsrVKDdu4hYZeEUO6PzJjI3K7+QN7uTMAnde3hlBI0FrH+pA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-12T03:41:55Z"
    mac: ENC[AES256_GCM,data:V3r+x8gg4E2kZ1SswNc6ibpp7AurWLuAdDb8j375g0+pvxVo7XUKDhzZ5E68W/KRVX4Mf9ynS0hrLqQvYc1yvt122yEiFi23ywCaYUjrbxvkamHJ6pHZ+CDY65GIk0WmyuF7hTB1csLL2N+I5I4e84XDxEJJc/c6Qb7xI+6Ldqo=,iv:h5k4x0jadRrmmTiJlBuFz/3enwyprdpN9gtDFkkpPzs=,tag:9YOA96MZI9FMfhrfCasunA==,type:str]
    version: 3.13.3
