apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: metabase-admin
    namespace: metabase
spec:
    secretTemplates:
        - name: metabase-admin
          stringData:
            EMAIL: ENC[AES256_GCM,data:56pNTKAV17KfiGKYwVOuCPc=,iv:ONRRS8/zb8kM+E9dto0KzJcQb76TOGzcWyqoKPs1bw4=,tag:5yFRkyPVgNPplMs3fC1NCQ==,type:str]
            FIRST_NAME: ENC[AES256_GCM,data:JbNrBkI=,iv:jVgCSjnTAA9SDWp7k+DFwJ0PFhP2GqqlkYNNq2RTOeQ=,tag:4XwgDb9e4aMKNjn3dkRvWQ==,type:str]
            LAST_NAME: ENC[AES256_GCM,data:PIDGSt4=,iv:apjCAemmI8J7eV182QDZmk5iR+2UdKK4UkrlT3Iu9qE=,tag:oIp+llxksOM/bwmokbe2Cg==,type:str]
            PASSWORD: ENC[AES256_GCM,data:O+CjJCd/M0uzCQDSuQQWnhOa0gxooj8EJ96rWru4Qj0wi4g+Kn0QMQ==,iv:FaqHMnigBsSwYqQSuEQnvO4pb8ZhGs029KwjpZjgrl4=,tag:Vb5Jz+XU4ANAqTxgRGE1Cw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxc3FRZlc3bEptbEZxTER3
            WUxDTkFuZHorMFd0K2tGTVkwT1ZZRkJnOXdJCk51aE9nSVhzNXBHT3lNSHozTkhY
            OGdxV3h6bG9McllmQUJ5SGFQN2FUQnMKLS0tIERvT3BQcHEwd3VZeUpkeklQL1oz
            VW5ISzFoemNFbjhkMEhMcU10ZjdiMW8Kd8L4p5Ytl59eeOxQRmXwVY/meJqEl6i3
            pLYtVjVNWPEaqvET0KIlJOnmJKHYT0aCp4yESIor2e55z0ekx4IFKw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-12T03:18:45Z"
    mac: ENC[AES256_GCM,data:QfS4IAWkmqRYWaAFc2SsXZaH0t7ikZPCSgu3uEQGPpLd/ZKzudtk+fEgM3Yb0B20reERUQeexRw+pvMnRluFl3o9g2Npj3tkrjvgYQd98jzGDlmoBnp9A//ZnhG5EuWAWU08yyIERiWvKDF5bOm1k5MHMQe4A+Izm2LK7v8AxbQ=,iv:Q+JIjH75Fx5SSAxcw7Hg45oV1zc5M1FezxHpM4qssOo=,tag:zlwoIYkMOm2EHpbFTK+R2Q==,type:str]
    version: 3.13.3
