apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: securo-securo-embedding-models
  namespace: securo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
