apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: securo-database
    namespace: securo
spec:
    secretTemplates:
        - name: securo-database
          stringData:
            password: ENC[AES256_GCM,data:da9c0i94gORnQlsbKCIR8SqdhXA=,iv:jKyXzw5h57sO/CBDulvltWrIcFBriZelrWikViI27GY=,tag:oBXCpdrDHlRN3IyBPAvxQQ==,type:str]
            url: ENC[AES256_GCM,data:hewSsTMuOeqRjRenDSBPuLgDMu5J4agQEISlYn+pZjvjtb9uZTWJfOi25Snu/dR9WeAFvGT215wknSyzMZis8r/ekwJfv70nlJawBig4sTlfCajP4eAMGVUZF1LPlQ==,iv:dPwc0dbNqooywZbqIyZQRYxPDC18Q5lC73UMuOknBXA=,tag:YkfgPWdME9fe6Yaz1vPyqQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdzhjQnhTSXhpR1N5akFK
            SjZuTnRIM1I3VmxVWC9pM1lhaUEvMXFCVUdrCmZIQ0tmQ0ZNcjdqOWQwL3lVRXBE
            NVdYSVVQSVQ0TXFRSkNrT3JHZWdrRm8KLS0tIHlTb29PWWR6bEFtdWptelI4VnBx
            WEMvVEtYS0g4azUzUlhqYjJZdzVzVXcKMXy12/+dAcTHH3Vd9rNyx7c1VBrrmuEy
            vg61Wonu5Fif+8jBo3fu3HmpnnAhbNaV9lLqcNAO0TnPLjKbTu2rOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-08T04:20:48Z"
    mac: ENC[AES256_GCM,data:mG7hJT0BFVLoTKOE8fnk7EfQG1Rou4COrV2qy3a+JF86fEx64w5RP+zL+n1VKixh4J3EQiEPzqzwO6dZ43qU3DaFJv6NgOvvkcQFe5eZtp4qcHg+x6Vy9Eo3SGtUw0+gKiycc1jOWholn+OZJFMj5kaWNUw2dyQJRF47fe/i+mE=,iv:oDzyrOwnmlVRQk3hs0TxlJ7JEGwU5RSuJxvgCs/MBa8=,tag:nJO4kebIzreXKtlMYEyXvQ==,type:str]
    version: 3.13.3
