apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: securo-redis
    namespace: securo
spec:
    secretTemplates:
        - name: securo-redis
          stringData:
            url: ENC[AES256_GCM,data:x4E0JFYFmDkZehXumqkcljGMVPf8WtR4fw2QE1wIZwfuGOlbsRJeQBACCG4CtoOPemOlTaNeC0exya+ftEo0jw==,iv:poQMRZKUFXW1cm8Qo84d5eSdmXnpw6ylCdAdztNi5wM=,tag:ZiOddv9UNowLWsiNVIvO+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjV28zMFg2SG5pOElteHRT
            dFlyS042cmdZeGtHZ0lUcDQzOFNUMjBMOERnCjR0S1VkSHZDeXVYK0daaFlGZ3Iz
            TUl4UlBYZm91bWJvZ29CNmNjdG05cTgKLS0tIGw0NVhYcUdyTFhNWERmWjhQMmxU
            VmdpM0o2R01aLzNidWVvclA5N0MzY0EK7pCBByKNnlNGsz2kZeZQlyEgSPt1W9wc
            htHE2XxL8lO41HIYy1zghK4ODBNTcwNz4XsUIUVUpzFreaWnQw+JAA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-08T15:56:45Z"
    mac: ENC[AES256_GCM,data:lhsLsqjjSlD//vA/t9fLOp/BB03TEOkt5H9X3raGmy5/1rNPC3j7fLKvyjmIalIkub2iJDNljEiZPtUTyU9Fw103aidvn247XOh62NmzOaXOEhWSCgG5FXvA+ucCeQZmJUc6q6w0+jQKycfRKIvR2i8S+gxKHaG/ssXNQIjAldw=,iv:NY7208uyENrSl10Eqt+4F0jgaVI7vC25/U2zYuOZB9g=,tag:JQRBga1alRDWg0sdKvhxZw==,type:str]
    version: 3.13.3
