apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: securo-secret-key
    namespace: securo
spec:
    secretTemplates:
        - name: securo-secret-key
          stringData:
            key: ENC[AES256_GCM,data:N0vCeFyuFRLbtjLGFTd3vNsL9ubYAFRkI55npusu7oCVnDcbuqEws32evpCIPQd9il0LHNLYO1CA02QYRNsFdw==,iv:zuYsnO1UWkd3r4/UA5fNjSnXPk4JEey67NtgnQW1VIw=,tag:4mOHeleRw2phIQ5G13Koiw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WTBGdDZDL2hrQ1NsdTh0
            c045SFhGcjVoZ1gvUzFQbXlzWDByajJPY1djCmZldjMvU09hcXcwdmtUYVdvZjJJ
            cTNXcmk3OFFnSkVDaVZTUGVPNVhPZHcKLS0tIGVnaDRXQ0RaaU1nVENYeTBrTFZj
            RE9KSlg5ZzVHNE1tLzJmc2xRRjA0cDgK5YK4B/fUc2drvvN0tQ7j1D9mITTV7n5u
            wfaQ9jO0r/uAo+WsKfGw1yv/D9pxjN0BMJBV0PTLa4WE0bJIhs0BHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-08T04:20:48Z"
    mac: ENC[AES256_GCM,data:tLDocwyEUcdc4N4HKwGUSPj1ZVHcRS+/t04LRr2JzJC0eijg0SZsu3G+GW102LKueBgSHPQdk2AhFx5vs0P3TO8XKOA0vwW3YkAxwwDXtOd6r7SdIGolXur2wNZTqoG1A2Q8v0rdUwaF7TPwLoMEiaGv7T7ySmVyVWehbnzMi8A=,iv:LPrhiEhZf08ZGuFsbLWaliB9/zEbMlfBr4M+nUb9PS8=,tag:wM1d+5jk26OVMQ+g4QLgtQ==,type:str]
    version: 3.13.3
