apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: securo-redis
    namespace: securo
spec:
    secretTemplates:
        - name: securo-redis
          stringData:
            url: ENC[AES256_GCM,data:XCN2STfa1+FMGav0hr+ldenrmmZtiYc+cYgSaepQD0N9St/dChOFMnh0BMoqbp1B9/cX0n7wT5VIvC52qZn73A==,iv:+Mp+4dfwuHabcb6GLtqTg8AktTBRXKXhab6nMPuN3zA=,tag:S6RJW5t0rUivUVv/L7dHmA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmM3ZWRStuS0JpR3lrb2tN
            eFhubHhsMmVhamV5MFQycU5yZDQ2SHR2b2o0CktlTXU0MnA3UDVwZExQeFVEa3VJ
            dzFIUmFSNzlnVmdZSFpGbUJ5eEREUGcKLS0tIERtOUtLcy9ubWZ3M09RZFE4QWRW
            NC9INGRGTFkwWjZIc1pMcU5scVJvT2sKJuRMAKlfPDvk+xUIQHAga7ZRJkSx3Nqt
            kTyE033qF8dTv5MEUVOt5dP9CZdC7Ksqwoc2I5zjDqWRCSxXXEft/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-08T04:20:48Z"
    mac: ENC[AES256_GCM,data:47xklXQpL6+J8/EVp8ZJ/YN9SGqpqOhqUzh0ecn20/SBlGavI3L0MtAoGw3D7XzoSyen54P/9PoSByVsxCJz1K0iLLbL9yXBmK+FE6fwyBm2P+UoZ4Qz/AFKxTJfB7HDMONQDt50iwR9HNgYYL09fxwUoDOb6HdHQ0ddLvZUJaY=,iv:hge3OuWquGss36wRnrLcjwz+KO2U+PzVNA6+hf9MgmU=,tag:/RyXu7KtzByMFAHUUZdK+g==,type:str]
    version: 3.13.3
