apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: securo-database
    namespace: securo
spec:
    secretTemplates:
        - name: securo-database
          stringData:
            password: ENC[AES256_GCM,data:C5nChGOQTV8n2UKA5TeTeH3FE6648DVkkU24iUgvE0U=,iv:2z+LLkBsrT3xvc3B4uoGK240OBXH+ECF5qA7Q5obw6Q=,tag:9AuREHgT03nL7e8PE7+EuQ==,type:str]
            url: ENC[AES256_GCM,data:2jgfJmPr8BKGG4AdXvymWHP7QtJlWMGervyyDv3Edz5OpY1wXiILmiOTNtV/yVOKPw2UaIh6wJVUzN3et1bvulP3Jk/hXqgvTZZ0H5Er15tmMEl1ZwL+wMGcYVTkfA==,iv:8D4SNV7F3bzxVwe3LhTSBf2ID1DVQkthqfGBnqZFdRI=,tag:sxWWdqvJnKtVRgl3uZfq6g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUWIvcmZERkowbGh3KzQw
            RW1rS2t4QzZPdGYveUtURVBUcEJyRnJ1eGtjCkNnVWIzVTdCZFdyeHl2dUlIakM3
            TFNvZnNJTlE1Yjh3d1F4VTduSDB0SHMKLS0tIHAzc0lkb00raklIdXJDTTQ4UFU5
            bE43MTVDVFNSM0JCbUk1QitzalFrdDgK5eR7Kf29G/EOc/uQMRvR78Z5vR4Qm9fD
            7qJKP9u4FauXV1WKgsF5L2ZqS1OndSi8Cr8jsDmltal1o+Pqc7JGDw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-08T04:35:42Z"
    mac: ENC[AES256_GCM,data:ysqcb2DBjrNF5d9tMdNa201Q8tfojTIapi5oVM5n9jtwBy+TDZmDkC4u+bnjZb1oB0zw9blMgBJTv0CpqEbV+AXXTPNPEDkyvlNSdnIW85cYKxe+bSR9336tV+TVEhHlbKs2Nh8NS7j7vviqwCS/LuJSxZuzMcbt9rUFVYg/xxs=,iv:wdwjcRBm3djyV5nryzKzLxMnsDR4PV74LPgAGR/YH4Y=,tag:aBKTSaDvE6qG202KtNPMKg==,type:str]
    version: 3.13.3
