apiVersion: v1
data:
  garage.toml: |
    metadata_dir = "/garage/meta"
    data_dir = "/garage/data"
    db_engine = "lmdb"

    replication_factor = 1

    rpc_bind_addr = "[::]:3901"
    rpc_public_addr = "127.0.0.1:3901"

    [s3_api]
    s3_region = "garage"
    api_bind_addr = "[::]:3900"

    [admin]
    api_bind_addr = "[::]:3903"
kind: ConfigMap
metadata:
  name: garage-config
  namespace: garage
