apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: garage-secrets
    namespace: garage
spec:
    secretTemplates:
        - name: garage-secrets
          stringData:
            GARAGE_ADMIN_TOKEN: ENC[AES256_GCM,data:Uw/z2Y6csoQYn5F6djN7uSH/efLFUJ+AMWySJOfG8PcQWSl+ehMVOzrgsVI=,iv:O1h3e7vrW8Ge/Gp9CCqg44qxVrwQUoLBoxDCo/cXHaI=,tag:goHapzx0f3YJiE+/xXRdVg==,type:str]
            GARAGE_DEFAULT_ACCESS_KEY: ENC[AES256_GCM,data:G5HWJg+w/e7vtIoMU0fPPjnea496Gzm7,iv:upyRA1sJZH0Y+BkY7eMFcsLPGPjXmaAh47lLV1JJJZk=,tag:Yo7JVFE1a3M99ddIb63Cfg==,type:str]
            GARAGE_DEFAULT_SECRET_KEY: ENC[AES256_GCM,data:0jNpfiO97h6kqLP92G1YX2jfTwlSGMdwDOhEx92L5eiklYgzYT5JKL0ONxnyBZSm7md3PAoO3O4ieoye6E+iCQ==,iv:xicw5wvkGBGGD99NtJIE3z5KkgqFVBT/R431ZDrsuJM=,tag:rCJmAVRjvxVK29v5WSBlXw==,type:str]
            GARAGE_RPC_SECRET: ENC[AES256_GCM,data:NfDFkxDFQhiKHu12xw+vKiVZ3i5LLSbdNaG/txynmxbAlYo4fpPCVVCWbigavEeKqf6kIE4JnqUOU1cZr4cuiw==,iv:Xn9+im+MmDg4GaP/aqrocwzVde8D/9ce11wNTAyKRkA=,tag:nn2Tsqek3VkyEyjQJKrk/w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVQnVuVDR2RytySHJRem1n
            Tm0rWUVWRDdPSlR6SlhneExmV1ZJMngwUWtVCjFmTWdNdE9xTDJiR083Y29acnhq
            MHcrYVZsTjFIOHZ0c0Z2RmhPU2k2blUKLS0tIFZmaXRlL3oyWWc5ekJ0NnlUYmsx
            R0xzeEhRRWxLcUM3MkY3MWV3Z0w4WE0KcZO/zFtPewP8bMjDsMArtobWib85xR0D
            2yKAmYQuTdqmISNpMpO019n9PrhHUyYuCr9Eu9NAg6cRNSz1qH/snA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-08-31T23:25:56Z"
    mac: ENC[AES256_GCM,data:47X3zRaxopkJafBCRUXHJ12b3/vzimanBG/grj/A3N1xuL/L35hKDsOh4XsKd6xev7Eg8VP+GtYJE5VUNp50l9Ab+9n3yqsGuBKdirvMBJdyzR0dQwukwo4ZSMQ4Vxy0cuRSmel22wXeoSYmE6zosMPGFNT5APEL9nuh10sUlrQ=,iv:f9O1hA/NSM2GKTB54YGI2KFUFlXlgGVf1VBX9CZgRG0=,tag:cxcnlvteuCc2Z2BhlBLR9w==,type:str]
    version: 3.13.3
