apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-navidrome-music
  namespace: navidrome
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: navidrome-navidrome-music-nfs
