apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-navidrome-data
  namespace: navidrome
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
