apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xyops-data
  namespace: xyops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
