apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: xyops-db
    namespace: xyops
spec:
    secretTemplates:
        - name: xyops-db
          stringData:
            PASSWORD: ENC[AES256_GCM,data:0gdKPY1NaHgJ11njAV7L/+dJA30=,iv:U1hkKZUHITPxmmunV1tZE1mB5UvlyL4K5T9jo0ZfWc4=,tag:QTUBbGy/yR1q4235ZNvnzA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArYUloVUtZOU8rQTVmL3N5
            WjA3RWxqWlVCWkd3Z2VWclJkMUg4VUU3SldFClh5cW9KbWlLT0JaSjJ3Z2t6VHlF
            Y0tLNmxPTmtjUEV1VlN6TGM3S1U5WWcKLS0tIDdZRXZ5SXBRS3pibytjU2xjWXYy
            WnRnSjlsdmorbU80L056ODNyZ2RjajQKqvvh8xL1quhrzTt48VHuYoduU66j9uux
            FhLxeXPm6Vs/ejTnlqZR+p9ol5o8V0DEWyE+O5u6GfHW1LAYUIhqQg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-11T14:48:42Z"
    mac: ENC[AES256_GCM,data:1gVew7hb1pTScUPW5FK6z5ssMfz/M4ZcgYt4s8LaYw+Ohgk/OO7XF37InWryKumNgKlQI2ejRfc4SoGgFQicVpF+rdLQJV607Nut+Eg34wkpDE44DC9cXQI4jzeUfzdV/um9f/2mwmnZDHzyrjUVZCOcQGjdb2wgB9oK2ZwvMEI=,iv:nO6iIybnDqAM51tCCgfYWrNParA1ZCAiFqk8U/FS204=,tag:fO3cLv6L+iswNazhw7GSvw==,type:str]
    version: 3.13.3
