apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: xyops-s3
    namespace: xyops
spec:
    secretTemplates:
        - name: xyops-s3
          stringData:
            ACCESS_KEY: ENC[AES256_GCM,data:s8yuXboqbEoyyvFuPyEPdrdz6Oqc+Gvk,iv:yyo83IWkQVsfn2vUB3IWH8EEk94/hSFWgHyRKr/LX0I=,tag:JkxnfgzLJ4ua30OP3PX2Ag==,type:str]
            SECRET_KEY: ENC[AES256_GCM,data:69PvnircFd3sq+01AkMp8P0NWEjNu4bl40BE4di+IG+xlIHedokN7zyVJfWIUdIeStIhkWgARdFCrFMgAseHnA==,iv:ekE/8Vp6JqD4Q9nYvbGcOXrYVEFgyj0If7w8BUAoc5o=,tag:zF654KzvtLh2AdJRLldoBg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVTdmWTAwTWxDaVhKZ3hF
            Sm9uYytheXNNaTN2N09LMzN0ZUxBTitPcjNBCnhLKzRCSW0rUkRjYkJzUkRVdlVJ
            WlJjMHJteVJCUlRlYnN4aThuRU1VdmMKLS0tIFhycTBaQzN2WWpYdUphSkZRZlIz
            YUt4b0FsR2dyWndtck1aaEpxblNud1EK1ZypT++nOqf6GqLvWKzFfstFimrBp+QS
            c4C2KI55JWHq5tpvKLRLUL5RlRVTsmAhBorhNfbvG18xdun+dmZj+w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-11T14:48:42Z"
    mac: ENC[AES256_GCM,data:2ZPOQE+e9ihFzhnbAGt8fSuSvvdRpadXHSI/W+eM/3ihaAr4b/BqhooRWF341JnRYfpAWk3WPMlfkMx+EJRXhXeboN9WgGtltxFfgGoHiEgdQemzmoO6vlBEFXPeuYgqipw0TFBnG/DuOocjPSQeU6iYAEUF9Nkbn+CghoIM8QQ=,iv:Dgk5T4hty+UMC4vNFyVemdx1TnhD0Lj6xUo8TV5mvt4=,tag:iWMlEOvxksq/4WPse+Nqqg==,type:str]
    version: 3.13.3
