apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: xyops-db
    namespace: xyops
spec:
    secretTemplates:
        - name: xyops-db
          stringData:
            PASSWORD: ENC[AES256_GCM,data:gIZt2mlzbRO0QeBb5YJ9GWEO18Q=,iv:aV2tbm44Diew76QZbENu2B6JI58xG7QYX3+wbVyhzJ4=,tag:Ss34LiRoZ/81H2Wf4Emz4Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVzNvZ1VrVHhjT0x0R2hP
            WEZRd29qR1VJR2QvZDZDTUVCQ04vTGNkdmhRCmZ0anBWMTBGVWNHaHhVOHJXNlcv
            WWt3S3VUdXpKdW1Ub0x1aUlZSk9VWlUKLS0tIDhzVEIzVWMzczROdk9aRStQcnpw
            UGo2bS9CQW9YWHBjZEpjODdySUZxWGMKFMgD+sfgBRdcy65R9YOi4LdoMxkp4lSF
            Y1tGkUo8581ZXzDGS2K0YDbgX9HeBYGqRUZbSsKMf2lXa3Oit6CWhg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-01T00:02:30Z"
    mac: ENC[AES256_GCM,data:CasQbdn1s3jx26x58nJ/Vl3NrqWknPX9fq1kPixZg06vxiS5xgPJEvIf85PPDJ4pzeNJCaIM9juVE9r8bZoKkQS2N7leBJZ831Ym/y2Uy0JFsIeySHl8bnGj1CJEBiJ6uv3yG9K6p9NXPoO8Dy9sCbicWyCBSvxkodAU+w6ar6g=,iv:4cOs2RmgnRXCsQuxuof/fOJQ5aLMKKjs9CZfcUB+aPI=,tag:IrONs3uB53uYV4fGm15+hQ==,type:str]
    version: 3.13.3
