apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: xyops-s3
    namespace: xyops
spec:
    secretTemplates:
        - name: xyops-s3
          stringData:
            ACCESS_KEY: ENC[AES256_GCM,data:HApK9gxf6C3T1jVj88UdJ6KD5C4rhim8,iv:rfjrvTeGx4NJ3L86Ot5ygtEX8hO3sysGOrPAjMD5IFo=,tag:SZdgI2GwfkeynOzWXnQQOg==,type:str]
            SECRET_KEY: ENC[AES256_GCM,data:JVMSjDKnREba1+rWZmD8yxz5RubOFoqU76o1fI2RDvqVIcFbL1DU5ZSFjcyNMVjOmFRCqnabt8qdmXe463FlcA==,iv:zmM4tKLhkQgeeIQArMWMSjZg060cSyTF0l+CUaquFa4=,tag:T/U9gIEokSPIuS90xk7mwA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoQzNKUTFOeDBoNmUzR003
            SmN3aEJUSXZGVUE2UWZFcmhONUtLVWxYVWdzCi8rSHFqVk5EN29LdTVReC9rYmdR
            aEN3VytIM0tPUzNUSnhidWhkWGlFVnMKLS0tIDNIdDYwdGZRclp4cFJjU21ZWHhz
            bTYrbzYwMExXNEx1SmdWRGN0NitZTE0K0Jo5fld8mSvBq2O1vO/18v6oFIFYr3L3
            mfNpXPDNmfyAX+xhfN+x3BMWYOs9pYiR+8A2AHJb+z9pMS49+dBuvg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-01T00:02:30Z"
    mac: ENC[AES256_GCM,data:yUe0TyjWTjXIOi37Ou6bQzKKa6QvOJ7GiIiGAvItjCdCoJJoPHuQS9ctOwP1+6qSY8Tec6kuc2l/+VnbvKKzOK6gcdaxpSZwaFa2qyTff8d7B8SD6ifW93VFgvrjaKeT/KgmSFOohvH9otOPBmIBuj28xp4fjc36Gd7CnEYVqfI=,iv:eIHWtxLrU3t6c5OTW1RDo4uGw+mIXESUegRg7704LsM=,tag:pvqSNPetJ4NXxkU3big10w==,type:str]
    version: 3.13.3
