apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: mealie-database-password
    namespace: mealie
spec:
    secretTemplates:
        - name: mealie-database-password
          stringData:
            password: ENC[AES256_GCM,data:R5LM3fungFObXilDP3CnrBupPJfFReDMtIiB93bJq9yQaEWDhfOS6pASBQ==,iv:52YedKYGbFiW54nhCP2sHcZNX47M18enygdqRM8RLHY=,tag:1V7faKrN9w1vr5KEVbPF2g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSWlGNnl5YlduL3JLSElB
            RTVZSHlMTTlDSXFlM1VGbWpYMG4wRTN1bUdzClFlZEZ0dlR6MnVObTQxK3hIVGxE
            RmlZZHdRZ05aUGRnTXZBQ29pVWdqTGMKLS0tIGtXVmJsV3BjWFNJMTZidUMxSmNk
            VGY2cnpnUzNZeEsyeU84WFdqSVQxejgKES8VXTVCOTlx6HdJA/Ur5QO6wyNc4wpn
            mlaBC8VCouoCZ6hqArgT35di5cPuyvescVQQC5nur0nzdgHS5Z3Dwg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-07T00:01:26Z"
    mac: ENC[AES256_GCM,data:cFIz1hX9N/vzWNP6eKEw1oNYL/RBnvNz6nrbPyxAjBRPvf5iRpMKil8GaZAJLJrLTe9a7HItbH8azcPWO7BjMdVq7gNXFVN20HWYaatg5d2jNzd+AdtJDuAubIiSJ5tFyAWUBn3ukBakVZ/PysBKIwpW5NzZuWX0lAj1rV/h2bg=,iv:ZYUeWdRsYyBJlv6vY70tKGPJ+21qkaspuiNgYlaSNIc=,tag:qmigrbO0SkDarxw+ZUsZNQ==,type:str]
    version: 3.13.1
