apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: mealie-database-password
    namespace: mealie
spec:
    secretTemplates:
        - name: mealie-database-password
          stringData:
            password: ENC[AES256_GCM,data:n/PbK71DJupncUt3iYAncBhCeUNlqnRDYScLmRuetwFtRpk2vB0MqtDhxw==,iv:wQy5rdEPcz2BBL57HTptvHo1fcVdptfkf+gYkhwX29w=,tag:h7dbyC1rfYnghMPX2DB8xg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUGpEWjc0LzZXanNRRkpi
            UjBPYzlzSGpFeXFCcXFMOUVZOXgxd3I4azF3CldMNThtcmM2SThla3ErNEU1dnZS
            MTZIb3BzdlY1NE8vK1dPc3IxdEVuM0kKLS0tIFgvRktWZm1ibEhKS0U1dEZsY0Zy
            SFdqUlIyOThSekx2TnAwLytGajdmV3MKXURKIwYvZYfQKSPQIB+ss+GodCiy5yCR
            9q+Ibgg0MyBVjjngC87BbYSStkQbDDWAyhrRxhIeFj63us5LQbRXaw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-07T00:19:35Z"
    mac: ENC[AES256_GCM,data:uZG8qqYhA2pxCtQ6e9ruVioX9Y9sVRKPSRlN9z87xSlbT++i1YYzCquGAJLKfB3/kPzW9qG0a95SiD3FYLOpqq3AQSMxG6alG5ygCbHxwuzhne6YohgcY4IO6hlDCwkySoM7bTLPIe/lkNLEVtPFvoCkRv++G6efV1fWbXCtRxo=,iv:W1AQgv7kPLU9hgykgqcKG9rILBZj0YQ78AWtMi8K8IY=,tag:/RxlIEBksir//h+GwUVzhw==,type:str]
    version: 3.13.1
