apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: mealie-database-password
    namespace: mealie
spec:
    secretTemplates:
        - name: mealie-database-password
          stringData:
            password: ENC[AES256_GCM,data:RHKl97MJRxb10/TSTxvB37vBqxo361S7Q4oB1ZwKD3Vjt3xDTq9qDs6SIw==,iv:6mVdhnQvOpPnrE9fDmlTjqudpILrEGAZXW9wAe0+33g=,tag:VtWgrKjA1Fp6xDbEU1cvgQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvVUFWZElCeDZEalhXZzdn
            SVc0NC95blZVbWppMVFCSTA2N0JLbWFZdnh3CnhYWVU2bmxBTzIwUHRFcTNaeFVW
            QlJFUmVrNk9vR3hTVHcrQVpGNWhlaGsKLS0tIEE5TUVRS3pnTzg0ZzBYOXkybUE5
            L2dnVk9jU3VJd3FYbjIvckJCZGxhd3MKWkXVIM9viPzbE/aw/jnsNDF2p/EZCEui
            6oO+r0416eD0OHV2Ov8cWT2+FNbBBsuUCAa/ehLssizb+dh3fme28g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-16T00:34:46Z"
    mac: ENC[AES256_GCM,data:hp9o7r/r3j6ikxfp/F6LYA3q3JsIoj5xrtV0x0MkbmZ0TD/LJkm4Yp0kRYGJhaUMfgtcgL1679ir0iSh8GhpE3l3PJFGzDP/05pj3g+i/fYDX8y43Wx3wREnQ7iociYGZVmOu8mkg03UwDf8FM5VhFKBbnftAuqRszE0Mfwz4DY=,iv:uNyxi5x8q3z23xTYGpWS42xKXj6RC1FfnwzoTVLK16Q=,tag:tcr6JgTZ/jTQRjeSE45Eow==,type:str]
    version: 3.13.2
