apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Replace=true,Force=true
  name: paperless-ngx-export-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      dataEngine: v1
      dataLocality: disabled
      disableRevisionCounter: "true"
      fromBackup: ""
      fsType: ext4
      numberOfReplicas: "1"
      staleReplicaTimeout: "30"
      unmapMarkSnapChainRemoved: ignored
    volumeHandle: pvc-867ee2c3-0479-48dd-8788-45cbc629bf59
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
