apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Replace=true,Force=true
  name: paperless-ngx-consume-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      dataEngine: v1
      dataLocality: disabled
      disableRevisionCounter: "true"
      fromBackup: ""
      fsType: ext4
      numberOfReplicas: "1"
      staleReplicaTimeout: "30"
      unmapMarkSnapChainRemoved: ignored
    volumeHandle: pvc-594d132e-e8f6-444a-988d-f649856d055a
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
