apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: paperless-ngx-admin
    namespace: paperless-ngx
spec:
    secretTemplates:
        - name: paperless-ngx-admin
          stringData:
            password: ENC[AES256_GCM,data:Zqk63C046BhsqttGISird2MXscaM5BVi,iv:MfZSXWO+ZzIl0YhDVxdCgDbZgI6/bTKGEK2gimAlHLA=,tag:sIdWhSNMdnKsHf529XpT8g==,type:str]
            username: ENC[AES256_GCM,data:Nl5A3Q==,iv:oGFH6tsqIMhxrDOEGUMpJwkQ73dGNKtbVxjeJNzDkUU=,tag:x240yxoeSWsoXG2KRJOv+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0K2JZSk42bkVYTzcvKytR
            SGw4M3dLS05PQ0FvREYyKzlPNlhucS9GT1RFCmxScTBlaDYxVlZYN0ZmNGk1bGZ5
            K2ZUTDVqTWh0M1RkejhIQktlTHhnSEUKLS0tIHhtbHJFWGs3ZHJmT3hxQ3c1azcv
            dXNJVGtCRGw0SEFueTZibkYwVVdCZDQK/SjwhvEVbdTBOE+APkcVmRNkXEY0/8EJ
            tRm0U/evS22rAJkZg425wuOmOIJFFoQ7R4DLEV4nFW45MUP+cT+Qxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-05T18:54:52Z"
    mac: ENC[AES256_GCM,data:/kEOqDx/9EnkToTfHeFUh9m0z1tAAvEbYuJ1yDhx9JAqlDIfTMbVDzYYO8KLdeG4XxTcHt3BZ/EY6Q9TB4eX66au5tyyjPGwlYOSsbE4nxFIHbHuOW46vip/5x170rgsD80zpgH+2MCU4TYJhhFrO+93O1c6DYPfB4sidC4SxWQ=,iv:9Z8KHcdctuTOO7Nx6dzhlT+1FVO0FDD1Y4NdmHCuUxk=,tag:U2qZvb4ScDhQ3Ujmn3NYsg==,type:str]
    version: 3.13.3
