apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: paperless-ngx-redis
    namespace: paperless-ngx
spec:
    secretTemplates:
        - name: paperless-ngx-redis
          stringData:
            url: ENC[AES256_GCM,data:E8E8EWCf3wRhuu3lwzj6YTb68OMvS5/IJiI6bYxXMG63lVTpLhMy8705Yh8Mg1hb+UdbSqSKcI9Ee2yCf35hqg==,iv:zs0CX64ZsicsnI50htRofnAxDenwxr66buH23b1DLt4=,tag:8j4pADi3FPAUfhwUiJHmdQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHV3kySXJjUnVpS20xdmNX
            a09TOGxhUTBoZjdYQ1JSUjNRMFVVbHJGK0NrCm5iSGNOckVtQmxoMlpkeGpiQkZE
            Skt1dlM4S3pBTXpSc080dURLYUsyYmMKLS0tIEZUZ0MxejUzeHJOY3IvYmxqeWNS
            WHlJU0dNYnoxR1pSRklFMzIxVnpQMWMKD9Ayl67igWMU5L1vDIeDAqpUiCZ5kxlD
            teOA6GnR2zGWIKjrk6Uj7hTFyqVo8vd4sjv5zQ7H3EwlNgaA4bjicg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-05T18:54:52Z"
    mac: ENC[AES256_GCM,data:c283hWmK52TYDi/fXGS0fCo9DHEfjdaPxHrAOUXyj8X+cv5yBwnOdp1G1j4c87b7JhM3t6GNDT6j5nkEjq2MK92+FJRyczsnNpleQNCy3SoQ5q1IWwjYesrrrO6LzuqgIJ+r1n7Yii81anl8sWZstUT+qx7/l84O+s+R8i+qPX8=,iv:bTLUs8GCB6MCkzzIJ4fVxhuhuiIFcz0ykccBKJoaQW8=,tag:fzMzBaoDe/d70Onlz5Tc6Q==,type:str]
    version: 3.13.3
