apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: paperless-ngx-database
    namespace: paperless-ngx
spec:
    secretTemplates:
        - name: paperless-ngx-database
          stringData:
            password: ENC[AES256_GCM,data:5RDuwr5Y1u9fBJMJvVcmJh/CGyU=,iv:Vhb8i3lZYtjsCJnRoDhvf4Wgehq9AGnhPskSthFvkWE=,tag:M5GGq2rQdWpNeFyGaTAbUA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzS01DK1FhOVlwQndZT2Vv
            QU9wb2tyRnd5NWQvUXdUMjl2alRka2J2L3pZCnltdElac3hFMzVxbkFWZGhTakFr
            dTFiZkJDQlV1Myt0MDFuVmpVTGs5eEkKLS0tIGRzdXlZZlhMRXd3YXl6NWdFa0VG
            My9DN2RUOVlvYmV3bVZXUHd6VlE2RGsKW0DW5BzzNR+B8d88QW04EhB865UTx9/r
            5tqZV3RrmTfQHPDwsHtDs3oA8x5+edS0ZzaB9xP/PAXZYJGTXMlMZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-05T18:54:52Z"
    mac: ENC[AES256_GCM,data:TYFVIdWsPHWvycpkZbwwYcF5bvX6UxLW1lXcQPPxNkfaVBdqIt7pkUmpC81u8SpTrbTyAvMzX+r+uuwS8VXCufs9s1P4l5a4xsr1EUZw89Cbo1958km0dmH/dilKNinPYZPsldi5feCYojDbK0yal+U8gRLu/FMoNg+pV/R8SjY=,iv:m6R2+4jiOctp+DZ18fH/55wg7EnHHUuXg1P8w3Fzuf4=,tag:88BnAGmK0q77nZLd4mt3Cg==,type:str]
    version: 3.13.3
