apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: paperless-ngx-secret-key
    namespace: paperless-ngx
spec:
    secretTemplates:
        - name: paperless-ngx-secret-key
          stringData:
            key: ENC[AES256_GCM,data:hNE+E8nBW9KyPZ6TBCpD2X1vo3AvAPPBqAKqhumhuWtoCeJfv6+Lk0HjqkENkQp5milChlpHrr6fmHjHQvItqgdQy62fDsjXBDtmrzlRrooCTkXTETQ=,iv:g9rTNPwX0QDaJw6UyN/Q08jCvdYKiAJ7f6S0LwUfpps=,tag:1dp/PzycVwzKXRdXu3/NBg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VzJITkZoTFMzcm1CWTFx
            YjMrclE4VERmV0JTZ1MwSDFiY3VXNmk3aEZFClY5T2J4bWhaOTA4a1VPaDBZQVFZ
            WEhuTU1ONVVLU2NOazZDaXpJczF6ckUKLS0tIENLcGNGTHhyRzFyZmx5V2lTcENH
            ODJlR29TOHVpWjcvRHRRcU9ZWmZvaGMKzdArP7Bv2vaBjnOEJzGPc8iziuEpKhWD
            AW49IdE8X1scq04nvoKsEFvBlJ1F/2bs8VSv3ZO2OGrtq7Zl0bKszQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-05T20:26:00Z"
    mac: ENC[AES256_GCM,data:A4qAaVuqi12XuW3Y/3WdkaH1AJJiqgigYcdIVmWjWVVYl1VqXMowuVKN5GiFFW6tmHjb+H5eRyHVvIMGxMFHFDNyejlOUThklSp4iBrAWNwPCk3X1IQuK0jZ76GPXS5aujS1vEX3W0PK6ktBlsuAzUug7vC6cnDJwn5BE3cjeFI=,iv:ZVOnnL3WvZVuu9XT0h9D6ssR62/B6enYghRQWV9GZi8=,tag:hpVx7T2v4cQa3mIX4IbfPg==,type:str]
    version: 3.13.3
