apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: sonarr-database-password
    namespace: sonarr
spec:
    secretTemplates:
        - name: sonarr-database-password
          stringData:
            password: ENC[AES256_GCM,data:Q/JzBaQBo/Nuppw3itihxyaUUaY=,iv:eWuMOepjrnZgL1xPTlDeH5C0GGdqBIq4gBHWfPDBneI=,tag:ZVKXzy+OdYAKl0lcSGFbvA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2M2YySXc2YWhaWTZWdFdq
            enZBMGJPNVE4Q3c1R3ppZ2E3bW10UEdpUUdNCmFxZW0yRlJQNk1Xd0h6M3FjOEg4
            TUh1TDhCZnFGNU1kWkNsRFZ2dXhscG8KLS0tIDNoVUJybzhKdEk3WWR2R1R5TVJs
            amZFNFZPVENSeHkyeFVaeWdPZlNlaG8KFR1ZEh3t7Ut3X6DxsL8Qcg9NUayqIE+U
            sRmVpLlZ1NAV1YYhnm2Gr4JbnWNrgWrDH0Am1UOm8IjVQuwKAm/zSw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-05-26T01:57:42Z"
    mac: ENC[AES256_GCM,data:Ss5pOc3taomLPnlz9Nw7cWw+mDBmz0SXny+bNihYeQQ6naedK4I4krc/Sco0fgh3oSPseqD/qQBUn6KHQQZE8zTjwz4sd48dlYuHquDtYrWG1W852M5EpG0xxgDIIjUDg25z1CJyfJEMEReuaXj8LeCiDhiAUB6ULUw4tjRwbhg=,iv:LYnlhiLeopNX2NrDhX5DX4VmCKtqtousTn2MjZJmIso=,tag:8FIDeae6PsLMVP3JhJC8MA==,type:str]
    version: 3.13.1
