apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: sonarr-database-password
    namespace: sonarr
spec:
    secretTemplates:
        - name: sonarr-database-password
          stringData:
            password: ENC[AES256_GCM,data:hmVdM7ajZcepztvijaWW7RaWnbE=,iv:940sfZrlGhfUbeezfdwvYKy4tiTajGKQAsnwaDmVpnU=,tag:KeKezoY7/2kr7mLnpVVd8A==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZWc1TklaRHJaRnZSeGJo
            UG1FdEVEZEZkMWlCZTZaNzRaSlhtc0x4UkdJCnIxM29tOEdwNlZpM3MwWTg1LzlE
            M3B3ZS83QUNQb0FTN1BvcjhKWjZ4QlUKLS0tIHh0U05Xa1V6Z1pSdE5BUDltR2xH
            YTZFMUVDQnBYWjRRRklmUStwdU0rVEEKoHeNkwbfPgObQWSavZHmIgvDVcXzrLVS
            pMaoBYVQQsbTmxBmSeu2259k3hBsABAGyq8xZZgDbBQU4j3mRvChKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T22:31:07Z"
    mac: ENC[AES256_GCM,data:2DozF1cnRf3plMU4A4JwMfqituWyIin/ofemuj0kNf07AmT+i60HsRLKdOIa5oPcnWZhH5unW1AyP2ZuxtXU2aWayV9yAiPEqQYUkBaByIl4GNZ+Zxes6LhlLFRCBUBJoMio8t81VLAcveqn+WRcIzkcvkCycPpacdEf7X0lOMY=,iv:isux9Y3OjgyTLbgs3xaMl/E++fomxitlcfLreuVSIVA=,tag:tY/q8u7H80+hEJxiNMhSgg==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
