apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: sonarr-database-password
    namespace: sonarr
spec:
    secretTemplates:
        - name: sonarr-database-password
          stringData:
            password: ENC[AES256_GCM,data:lp9BOeafPFB2rcFIhdaRrQIGFvc=,iv:9cyQE11oOyIiNkr6Dt0K+zYl7R/XPLZ10Jo3HAzJcC0=,tag:N62tyX1wX/juWuLl0/Pgzg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VnFmeWliNkhueXRaaDYr
            KzVxL0p3N29YbW5ZZ1ZLdEZnY3BVd3pYcjI0CnM1djZ3SzlSQWdNb0tJZHd6TG16
            T3NjVTdPSzJYMG1haUhzSkJOb1M3elEKLS0tIHdkU0I2S0cwenFtRExYSEoycGQw
            blFPMVY1eFlRdm9NbWg0MGs3ZC9scXcKTFczXKpF7BSfQRwpuFq5qZSEHgII0ad8
            CO5Xgubwucnz9V5YP+eBWULx21O+9tDUA9am7W50I+kQu6GgjpdjKQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-05-26T03:38:16Z"
    mac: ENC[AES256_GCM,data:CmvrPUhXjccZLHoUEWKd5oR39tnHiBVR/5YTuX7QoIShzalAlXsM4GCq+WGasPrJtjXgeBEre3OcjpN3uaCOJoJJllwHOGX2Dxsr2Ulwio8IesSyjHS5qrCSPsHY63XfTDM6lpKGP47uTIkf5S3QYxYDJV56Eh/FRnBGH/ftlc0=,iv:rA+jYQcGGMxHsm4jIZY9Ddc0VPFXw0NrzKUMv3/ZtnY=,tag:UBU0xqK78A1EovAXmj5jyQ==,type:str]
    version: 3.13.1
