apiVersion: v1
data:
  attic.json: '{"name":"attic","type":"http","url":"https://attic.home.kronkltd.net"}'
  bookorbit.json: '{"name":"bookorbit","type":"http","url":"https://bookorbit.home.kronkltd.net"}'
  ditto-relay.json: '{"name":"ditto-relay","type":"http","url":"https://relay.duck1123.com"}'
  duck1123.json: '{"name":"duck1123","type":"http","url":"https://duck1123.com"}'
  garage.json: '{"name":"garage","type":"http","url":"http://garage.garage.svc.cluster.local:3903/health"}'
  gramps-web.json: '{"name":"gramps-web","type":"http","url":"https://gramps-web.home.kronkltd.net"}'
  homepage.json: '{"name":"homepage","type":"http","url":"https://homepage.home.kronkltd.net"}'
  immich.json: '{"name":"immich","type":"http","url":"https://immich.home.kronkltd.net"}'
  lidarr.json: '{"name":"lidarr","type":"http","url":"https://lidarr.home.kronkltd.net"}'
  longhorn.json: '{"name":"longhorn","type":"http","url":"https://longhorn.home.kronkltd.net"}'
  metabase.json: '{"name":"metabase","type":"http","url":"https://metabase.home.kronkltd.net"}'
  paperless-ngx.json: '{"name":"paperless-ngx","type":"http","url":"https://paperless-ngx.home.kronkltd.net"}'
  pinchflat.json: '{"name":"pinchflat","type":"http","url":"https://pinchflat.home.kronkltd.net"}'
  prowlarr.json: '{"name":"prowlarr","type":"http","url":"https://prowlarr.home.kronkltd.net"}'
  qbittorrent.json: '{"name":"qbittorrent","type":"http","url":"https://qbittorrent.home.kronkltd.net"}'
  radarr.json: '{"name":"radarr","type":"http","url":"https://radarr.home.kronkltd.net"}'
  romm.json: '{"name":"romm","type":"http","url":"https://romm.home.kronkltd.net"}'
  sabnzbd.json: '{"name":"sabnzbd","type":"http","url":"https://sabnzbd.home.kronkltd.net"}'
  securo.json: '{"name":"securo","type":"http","url":"https://securo.home.kronkltd.net"}'
  slskd.json: '{"name":"slskd","type":"http","url":"https://slskd.home.kronkltd.net"}'
  sonarr.json: '{"name":"sonarr","type":"http","url":"https://sonarr.home.kronkltd.net"}'
  stashapp.json: '{"name":"stashapp","type":"http","url":"https://stashapp.home.kronkltd.net"}'
  superset.json: '{"name":"superset","type":"http","url":"https://superset.home.kronkltd.net"}'
  trilium.json: '{"name":"trilium","type":"http","url":"https://trilium.home.kronkltd.net"}'
  uptime-kuma.json: '{"name":"uptime-kuma","type":"http","url":"https://uptime-kuma.home.kronkltd.net"}'
  windmill.json: '{"name":"windmill","type":"http","url":"https://windmill.home.kronkltd.net"}'
  xyops.json: '{"name":"xyops","type":"http","url":"https://xyops.home.kronkltd.net"}'
kind: ConfigMap
metadata:
  name: autokuma-monitors
  namespace: autokuma
