apiVersion: v1
data:
  audiobookshelf.json: '{"name":"audiobookshelf","type":"http","url":"https://audiobookshelf.home.kronkltd.net"}'
  fileflows.json: '{"name":"fileflows","type":"http","url":"https://fileflows.home.kronkltd.net"}'
  homarr.json: '{"name":"homarr","type":"http","url":"https://homarr.home.kronkltd.net"}'
  home-assistant.json: '{"name":"home-assistant","type":"http","url":"https://home-assistant.home.kronkltd.net"}'
  immich.json: '{"name":"immich","type":"http","url":"https://immich.home.kronkltd.net"}'
  lidarr.json: '{"name":"lidarr","type":"http","url":"https://lidarr.home.kronkltd.net"}'
  memos.json: '{"name":"memos","type":"http","url":"https://memos.home.kronkltd.net"}'
  rustfs.json: '{"name":"rustfs","type":"http","url":"https://rustfs.home.kronkltd.net/health"}'
kind: ConfigMap
metadata:
  name: autokuma-monitors
  namespace: autokuma
