apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: autokuma-kuma-credentials
    namespace: autokuma
spec:
    secretTemplates:
        - name: autokuma-kuma-credentials
          stringData:
            PASSWORD: ENC[AES256_GCM,data:FsIR8OOo1DTonN5YJ3PJWOHOZV/IRR8KvYQJA9oiM78=,iv:crR+Z0kRs7Wbi2moMlh3TVBlSJBqOLGJTWz2RNlvjGk=,tag:c14yt+st7ssJM9ZhQ5bQYg==,type:str]
            USERNAME: ENC[AES256_GCM,data:QKgYeA==,iv:7BZ0EbOhuanS/u89Ga35oM/IYemY6oayVE1GkhIvmpQ=,tag:ugDyyQetEYVDDcfpN557AQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4RzdLR3g2aExKV0pNVDRN
            QzZVYmlUdW0yWXhjbEVNN1lYZXM5SExBdEVzClRXN2NrS3ZUOVQwZXZLUmxOS2ky
            eGY0S1FMcWttMDJRL0JZNCs5TTJHY2cKLS0tIFhiT1EveWZkYVNvTTFwOVlDVE42
            ajA0OEFVbDNCdDNQSnB5UEdTby9yZ1UKryU4n2MZ7ohjYaqpeKe8fpZlBKgvaD2U
            XzQd7ybNcW+DVHKbYSITQFB+I9cIKvCNFTzUs/auZ7RPqC2M8qq7eQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-08-22T02:40:57Z"
    mac: ENC[AES256_GCM,data:e7E3pfiZ/pnmHijtlMkQSOFv7JOlimL0jCjGPJ7dSEM6Ey2r8iVsVvGEgVcjSpu3k8kUOrmVpGUmL6Veyh+G2BQWjvemQLXQFQAePbPxiwRcm0cOxL1zAjxEu4aZBTtXrkx3PwTeMlAb/XiaJZtqt+3xVv+TU0E7UH+hw+mAP3s=,iv:fteH0I+KI9moY8FyIGgUrq9w67qa5bSskdam1xa5Sow=,tag:iXXd8c3Zra+9GSV3w1YOmg==,type:str]
    version: 3.13.3
