#!/usr/bin/env bash
# CI build: encrypt secrets from environment variables, run the nix build + activate,
# then write SopsSecret YAML manifests to manifests/dev/.
#
# Secrets come from SOPS_<secretName> env vars (replace - with _ in the name, uppercase).
# Example: SOPS_RADARR_DATABASE_PASSWORD='{"password":"mypass"}'
#
# The secret VALUES never enter the Nix store. Encryption happens in this script
# using sops before and after the nix build, matching the local dev flow in
# scripts/write-sops-secrets.sh.
#
# Usage:
#   AGE_RECIPIENTS=age1... ./scripts/encrypt-secrets-and-build.sh
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
MANIFESTS_DIR="$REPO_ROOT/manifests/dev"
SYSTEM="${SYSTEM:-x86_64-linux}"
BUILD_CMD="${BUILD_CMD:-nix build .#nixidyEnvs.${SYSTEM}.dev.activationPackage --impure --no-link --print-out-paths}"

if [[ -z "${AGE_RECIPIENTS:-}" ]]; then
  echo "AGE_RECIPIENTS is required (age public key for sops)." >&2
  exit 1
fi

if [[ -z "${DECRYPTED_SECRET_FILE:-}" ]]; then
  echo "DECRYPTED_SECRET_FILE is required (path to decrypted secrets YAML)." >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# 1. Build the nix activationPackage (no sopsSecrets generated by Nix)
# ---------------------------------------------------------------------------
cd "$REPO_ROOT"
DRV_PATH="$(eval "$BUILD_CMD")"
"$DRV_PATH/activate"

# ---------------------------------------------------------------------------
# 2. Write SopsSecret YAMLs from SOPS_* env vars.
#    Read the secret manifest to know which secrets exist and their namespaces.
# ---------------------------------------------------------------------------
MANIFEST_OUT="$(nix build ".#packages.${SYSTEM}.devSecretManifest" --impure --no-link --print-out-paths 2>/dev/null)"
MANIFEST_JSON="$(cat "$MANIFEST_OUT")"

if [[ -z "$MANIFEST_JSON" || "$MANIFEST_JSON" == "[]" ]]; then
  echo "encrypt-secrets-and-build: no secrets in manifest, nothing to write"
  exit 0
fi

declare -A desired_files

encrypt_one() {
  local secret_name="$1"
  local namespace="$2"
  local output_file="$MANIFESTS_DIR/$namespace/SopsSecret-${secret_name}.yaml"

  desired_files["$output_file"]=1

  if [[ -f "$output_file" ]]; then
    echo "encrypt-secrets-and-build: reusing ciphertext for $secret_name"
    return 0
  fi

  local env_var_name
  env_var_name="SOPS_${secret_name//-/_}"
  env_var_name="${env_var_name^^}"
  local json_val="${!env_var_name:-}"

  if [[ -z "$json_val" ]]; then
    echo "encrypt-secrets-and-build: WARNING: $env_var_name not set, skipping $secret_name" >&2
    return 0
  fi

  echo "encrypt-secrets-and-build: encrypting $secret_name"

  local string_data_lines
  string_data_lines="$(echo "$json_val" | jq -r 'to_entries[] | "        \(.key): \(.value | tostring)"')"

  local plaintext_yaml="apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: ${secret_name}
  namespace: ${namespace}
spec:
  secretTemplates:
    - name: ${secret_name}
      stringData:
${string_data_lines}"

  echo "$plaintext_yaml" \
    | sops --encrypt \
        --age "$AGE_RECIPIENTS" \
        --encrypted-regex '^(stringData)$' \
        --input-type yaml \
        --output-type yaml \
        /dev/stdin \
    > "$output_file"
}

while IFS= read -r entry; do
  secret_name="$(echo "$entry" | jq -r '.secretName')"
  namespace="$(echo "$entry" | jq -r '.namespace')"
  encrypt_one "$secret_name" "$namespace"
done < <(echo "$MANIFEST_JSON" | jq -c '.[]')

# Remove stale SopsSecret files (secrets removed from config)
while IFS= read -r existing; do
  if [[ -z "${desired_files[$existing]+_}" ]]; then
    echo "encrypt-secrets-and-build: removing stale secret: $existing"
    rm -f "$existing"
  fi
done < <(find "$MANIFESTS_DIR" -name "SopsSecret-*.yaml" 2>/dev/null)

echo "encrypt-secrets-and-build: done"
