apiVersion: apps/v1
kind: Deployment
metadata:
  name: duck1123
  namespace: duck1123
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: duck1123
  template:
    metadata:
      labels:
        app.kubernetes.io/name: duck1123
    spec:
      containers:
        - command:
            - python3
            - /scripts/server.py
          env:
            - name: PORT
              value: "8080"
          image: ghcr.io/lillecarl/nix-csi/scratch:1.0.1
          name: duck1123
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /nix
              name: nix
              subPath: nix
            - mountPath: /scripts
              name: scripts
      volumes:
        - csi:
            driver: nix.csi.store
            volumeAttributes:
              nixExpr: |
                let
                  pkgs = import (builtins.fetchTree {
                    type = "github";
                    owner = "nixos";
                    repo = "nixpkgs";
                    ref = "nixos-unstable";
                  }) {};
                  site = builtins.storePath "/nix/store/a67d18pv0ffpmsl4bvl7v8yrisb6h8y0-duck1123-site-0.1.0";
                in
                pkgs.symlinkJoin {
                  name = "duck1123-runtime";
                  paths = [
                    pkgs.python3
                    site
                  ];
                }
          name: nix
        - configMap:
            name: duck1123-server
          name: scripts
