apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: whisparr-database-password
    namespace: whisparr
spec:
    secretTemplates:
        - name: whisparr-database-password
          stringData:
            password: ENC[AES256_GCM,data:ECqOt9RFk+LQP2FpsozAZQjxtcA=,iv:Q+qW/eAaNFHGGKcp4VV1ELiaoOdKFWGy83V6Ju34+KA=,tag:tuCUUiJtghgr7aWFZXxF+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOOTJLc1EwUlovTG1qYzFC
            Wkd5MnpvQmlPNTBBM285RklieWt3TlczRjE0CmJUSnpiWEdPOHdLVVBERmNNK2F6
            bUJPK1owNHpsZjJranJBSHpxSUVzOVEKLS0tIDZOSnZCK2dUQ1NLQk83dWIrckg2
            UndIUGpIa0IrSmZWaENkc0RHNjVJUm8KsMWsk1aAuj5ehoGUcDer0NW613nUP9J0
            IG7P6iWyNKq34olMsCZ1j+lHlt45cb2FFQ5OrUx+YDE35WInJR2wcg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-05-24T20:28:32Z"
    mac: ENC[AES256_GCM,data:JshAhhiZ2g5HYzwCgIxIld2aHtZxaWrCuaLfQyQq96PkNkMWq2eXan9ooChQ71+VqJi1uTMENdA2XgviQiQiQCD/9iPeoCL0PP+J2cMU2xVDbTohH53Umvae1m8sIZE1O3ntt00ziH+gWrWCL9Sx7h36JRysYeuqzU/J6+2cGFI=,iv:KffH9Fm6FRE57Sm9VFUViZdrgLCGGVdCsFr3XDBjMFw=,tag:ZaAPeu3Y91rcLvB+wFKjgw==,type:str]
    version: 3.13.0
