apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: whisparr-database-password
    namespace: whisparr
spec:
    secretTemplates:
        - name: whisparr-database-password
          stringData:
            password: ENC[AES256_GCM,data:COuapw4xDhMiEBY3oJ2E3E4ztak=,iv:CiS07NTeqAWhQWftCb5/kWlWvAo84QV08IetlBGTiJw=,tag:4DVe8aU2BGv+l5Ms4tRplQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUckk3MlIyMnJpdk16UWJw
            ckFIYXVXZFRHUmRCQUpFZEIrcFp4Zms1WXdzCmQ1RkN5aEp3V0l2OVM1SHpaeFdB
            NW1lN1B4bks4bSswNzdmYUh3U3NNQlUKLS0tIHc4eUhkcnQrUXN2YlVkZFg2NXlM
            NEtrUGtmNzdML1AyaEtYc3BDNzV0RnMKzz1b5Vy7OwJNCExVKd/uvi0uspY38sIV
            ePsLLOOcSWwPr8QO6vX3pJ2w+nNH/B/7MX71JM4NjOqTzdIGpGR3yA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-05-24T20:18:08Z"
    mac: ENC[AES256_GCM,data:EdsyGTZM8rAQHOGC7+ckn21cd8p6XLgJ9jaJgmkBJ1PnP/LVObk6d5DC9w2kBIhk2xWTmzOoSNc2syfRjsaNqfZpUK2rwF8WV/TAObXNbQlUfsHvBAohgfkcJAVgFRNvPr0vtWzzUa0R8aWTshDsnUxdSiwLh1rqoHWs07T4u0c=,iv:nt2Z+DLyXOSdmKdE/o21Nko02zNlXBYUGT2rZX8MAxI=,tag:Wsr7sUuPM6pPBi1ljSur5g==,type:str]
    version: 3.13.0
