apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: whisparr-database-password
    namespace: whisparr
spec:
    secretTemplates:
        - name: whisparr-database-password
          stringData:
            password: ENC[AES256_GCM,data:HHheLBh0NvuqD3mEfiy1k/obxH8=,iv:/2StNMOhrNYTwE8CaTPspbiFjOQBnSG2qL5WH70W2dc=,tag:m3I8L0DjxNo1lKWPM+BylA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUFlMY3p0aU91N0VjamR1
            YldXNWs3aHlXQi95SWh0bmJsOWdmYVBqbEE4Cno2TXhBL1lZRThIelYvRzUvanI2
            RDBFc0crc2xMcGd3Q09odFhBNjZGOG8KLS0tIGNQL28yZlFsMGs1L0d2S0ZKS3F2
            aGVndWJCb3FXWTFaUnM1L1MveEk0UGMKYrkUpJmAycQYjgfwdmo1wLZiv+KwP5Vq
            4KM0J6npi4+BJQf5DF2LwltNagzT0n494UFtbX4tTqOU9nS4kDIQpQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-05-24T20:46:21Z"
    mac: ENC[AES256_GCM,data:BlmAaaMO3UPKsSIkIhpLDgtSnAcmLVCobVn8Vw3C/G0n+Zzl6ZW0FFkz5QTPAW4PK51Ne5a5T1ISUuwhk8YqgLRae4kS2Ots2qFi0d2PlQ5gjhjyt7lEGV77j/Ahn/98Hp2RchNzn9mUmAMjtLA8h4oT+4vzsrxTb/HlJ8fM48U=,iv:MTEO6nrd7p49LxH5cua8lU/2WuJV2wWtXADFSq6UF4g=,tag:ZLB0XcCszEqCHKB5KRwfng==,type:str]
    version: 3.13.0
