apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: listenarr
  namespace: listenarr
spec:
  ingressClassName: traefik
  rules:
    - host: listenarr.home.kronkltd.net
      http:
        paths:
          - backend:
              service:
                name: listenarr
                port:
                  name: http
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - listenarr.home.kronkltd.net
      secretName: listenarr.home.kronkltd.net-tls
