apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: listenarr
  namespace: listenarr
spec:
  ingressClassName: tailscale
  rules:
    - host: listenarr.bearded-snake.ts.net
      http:
        paths:
          - backend:
              service:
                name: listenarr
                port:
                  name: http
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - listenarr.bearded-snake.ts.net
