apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: listenarr-listenarr-audiobooks
  namespace: listenarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: listenarr-listenarr-audiobooks-nfs
