apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: listenarr-listenarr-config
  namespace: listenarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
