apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: listenarr-listenarr-downloads
  namespace: listenarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: listenarr-listenarr-downloads-nfs
