apiVersion: v1
kind: Service
metadata:
  name: listenarr
  namespace: listenarr
spec:
  ports:
    - name: http
      port: 4545
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: listenarr
    app.kubernetes.io/name: listenarr
  type: ClusterIP
