apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: listenarr-database-password
    namespace: listenarr
spec:
    secretTemplates:
        - name: listenarr-database-password
          stringData:
            password: ENC[AES256_GCM,data:UZgJrJQqUXS0DFv0+jHpvkp8V1E=,iv:h8cjaO19HkW8ulrNKNnsNXCdA0LGtmvneIzW1pk4ED0=,tag:R6VgCeuM12/nx0kYksyHWQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEa0liZVpHTnJSS3ZUY3oy
            WWJaMit1V21qTXZDTm9SNGxXZGVXQ3d6UnljCkRLdnBUcE5EeFdUR2M4VGo2TWlC
            aTNGZ0ZTRXIvY1VndCtLVnpQVnU4NVUKLS0tIEdBSGhkcC8yUm90THlWTU5KY3F1
            QnVqVkdhOWFWbFJka0dEN2FQRkNsaDQKIW2w5Hwo34zFvcKlnntLQd5W4jPuNa8U
            VAPCIfb6VbBNdvZAvgHK16Rb9u6PXIb7hDvjnsaKMCWcN7vc1fOsJg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-08-04T21:52:35Z"
    mac: ENC[AES256_GCM,data:pyZjlFQHJdmVxJ22Qo/0J7aRH530u7L9ULXAnHiH2v0LJXAmS37dnXE11gX5pZot7kox6c8itRWMVSD1ePqOd5sAvYFJEJ9vYqEJbX2U6KttiZyQ/Eh5DkHKHizXuWET7Ns1Cq+gJ4IN8Xnqilx15Ac6vTmGOunCjqfSoUqLlC4=,iv:5zkzvRqI83TY/1rHrJlHit2qod/gJHpyJ7Iss5G8Z1U=,tag:He1FZg8hYTi0oK2GyW4Dsg==,type:str]
    version: 3.13.2
