apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: listenarr-database-password
    namespace: listenarr
spec:
    secretTemplates:
        - name: listenarr-database-password
          stringData:
            password: ENC[AES256_GCM,data:PEl0uZKRgv7MKeGFPrpqJqdUpnY=,iv:6v0sr7GccwOJY6e3CsNxgSVESEUjPu/JkFKQI8hvLYM=,tag:N3uqqYd/2cWSnejMXrUOtQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacDhkTGFQd3g5SXlFR0xK
            UURQV1Q1S1dpVGVkUmtGeVBOcXR6a1VZVHpVCnhLdWRIMWN2NithSTQwYVhKSFpl
            cTE3TXJsYkpSNHNQYTdDUUFid3pWUkkKLS0tIE9XT2dRYVJ6czNLNTBxay9KbTlD
            RXlNMTZmSDh0MUJFR09OSitTa0pFaG8K33EiTfSiLbq1Qxxdejg3w9jb36PcEl6l
            xiym3YaHSRxI6Fphs3XSfcour0yVu9nL7/WQyWucjLz0G6c6rOpxeA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-05-24T20:28:31Z"
    mac: ENC[AES256_GCM,data:Yqs8ka52Ie5xzpUxIptRfjk5TVeuq1Td17r+U+NKDABTCuswVwFhtYw9Q7H5f/GLI95+TpepGex86DQlXRYTSNRVUONfmuYPQ0+UVeZa698CaSs99D8gZQCe31jry3fraEaHKUuOMhxzV21tj/xQUvM+UU3TBreWWf3Jg0+pS8g=,iv:RpZ1R5kzNINDPmg5/QmnsGTGQwuxqrGO/vWmyyrvyRQ=,tag:xY2SwEjXibQB1ffZJu+FkQ==,type:str]
    version: 3.13.0
