apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: listenarr-database-password
    namespace: listenarr
spec:
    secretTemplates:
        - name: listenarr-database-password
          stringData:
            password: ENC[AES256_GCM,data:PyIe/g0JMNGnyHTX2OiZYjv5mhE=,iv:TqaEWwj27Gb6hNCxrF33UIZjQur0nGDlgEJbM9Wxfnc=,tag:FVieiiEFoc6gYUnz2YiowA==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMcEp3U2QzVVVwcGw2Wkxl
            M2RuWEExRUtGMjlVRC9WRDdEMU5ZdUhtbTFvCi9TTCtGblZBYk5nRlplWUxKZHkx
            YzhXSTMyTGd6SDZSc0dwVTF1bE5hTDAKLS0tIFAvbUJqdzluSm14MGpVMGoyWDZk
            WkhwTXdiVGd0UStyZnhleHBQOHdOcWMK//HXA3Vz4tmZMUAlX1l6xx8ToocSzwQ2
            0AiOJlXpCQ0Z35iag/OGsovxpsNRfiUjwUwA2r009XieuDWJPqLnnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T21:39:16Z"
    mac: ENC[AES256_GCM,data:1S8CLx3ipQsEf3Tk4OrwxSGbPXXEzXqGZgWjYYyfqDyTLDsWFZEcH3LjnkgnZKMaRxsyOeuNsIOe1c8pgYU5z6ctjx9lUGjvSAEl/oxiPbYgM72q7sRnPxJRjvDrUyXHfXZ5p/WBRVl1qyZL63W8dZXc4Mrp95ZZAH4ZI5ISqWs=,iv:gLBhFg2xO+ftWGe8s+10LK8v5Lwm+iBU34i50ArEwcw=,tag:d9QZ79ifJYc82QOlsZeSgg==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
