apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: prowlarr-database-password
    namespace: prowlarr
spec:
    secretTemplates:
        - name: prowlarr-database-password
          stringData:
            password: ENC[AES256_GCM,data:7kLwZ4M9D4X5mWHkq6puUlKSj40=,iv:hh5eVLXe2fIYCQfjWbJT7qm2gUW0kSrglyQxxasQii8=,tag:7iGHtBhQCANmSdeEn5GMRA==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwMnc3MlorQm0wc1lidWYz
            aEE3UkRBMTlFWG9wbzZXdURSMGJMdW9xT2lJClN6aXIxTVRFTk9jZ3R6UjhseGl6
            VWVkZjNaU00zN3lHTjMrczA3Sk1wRzgKLS0tIEpmTmdKdkFmNDRXWk1rTkpVeGdV
            bERXSXV5dmM1VHEzdnlVcTF0RXE3SUEKBRjqVoGV+5gDHpSeaH028rozzrGFdOgt
            xRLS06QA6fWU6SdqylJr1Ki7iaV/bByVIjBlQ/ftDl6/8whBwu4Z7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T15:54:20Z"
    mac: ENC[AES256_GCM,data:DjH20eGTlTsbXCpoK40aed4nAI4/PDXOadA05XtfpRANEM3qV2V5WTJC4qXVdPIu1/I4REiafIJq0t0/jLNxVVCWGTAnpNLUxtTHZv/LzxzJxRp5wztl4cZB+puwJe+2aC9mek/FTDIxlHHi7ttjIi6xGTn5vTYHZhfcnf2blHk=,iv:cIXvG9pt0i/E04RS1mkkiq9Ky4C9bqDhl2VUVgiLm+4=,tag:cm6AI0NWyrdUqGLDiqaoCw==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
