apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: prowlarr-database-password
    namespace: prowlarr
    annotations:
        checksum.fleetops/plaintext: 009afccb750f6051294980b54e9ef9c6c8ebdc207a05f5a7dcf9f244ec217fb7
spec:
    secretTemplates:
        - name: prowlarr-database-password
          stringData:
            password: ENC[AES256_GCM,data:qrVKWd+ue6IowCZpMwi7cgmiUw0=,iv:qQCqlxs2VH2T+/gp8cpjACfT/wLbDd4KSHLWyyWm4n8=,tag:oIaqGJTCSwIIn+iRZBpCMw==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZ0h0QTZGUi9wOHNOZFVL
            d3MzaWd3Y014RmUvTlZhSnk5VU5KMXV6VTJNCjhSaDlhbUtrTUJ2RktNbXlMMThW
            M0htU3NBV2RPekpUb2pGamVRb3dQQmcKLS0tIFptMEtkUDZnMG1KZWg2MjJJSWZW
            bWlSWUhtcWtVb2xmVm9GenI3emEwcEkKRRP7RrMaZMIn914A0QByWsBUXZLzy1GC
            y10t9W4fIyutB6b6OOVO9swX5Q59G8jde0uh+gvVH0lwsfe/B55nOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T17:37:11Z"
    mac: ENC[AES256_GCM,data:UtguzfDH/96VfShPsAa74GLMwfn0A+rIhtEJWPGSS+RsnNFAVAPwe12ZZMAILRVQUWmxAYx7f3dxp7jvO3nYnwzK8oFHJEkLnUZcq0TilgQ92ph8GZpikXB6Re4p7iRKJfRZxkX8Twih8AXHJkaR3bbtafV+IFnavZRgNcPX6mI=,iv:2vWJjT5oDbb0bue2b8uyWNy90DDbRMyVSAgArioUv5w=,tag:EP59y2vG2Glz4o3zVKSfRQ==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
