apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: prowlarr-database-password
    namespace: prowlarr
spec:
    secretTemplates:
        - name: prowlarr-database-password
          stringData:
            password: ENC[AES256_GCM,data:bmuI3udHaaEe5RqWvi0ESBld1Ek=,iv:ZEBTQcsnrOqPoTv8GOdGDewFwlAoMm60PQrMO0LqZpk=,tag:PHGWgIaxb3XHRUXlTxI3Lg==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dXlQelM1aDhkWHBvYTF5
            U2d0UGdrWG9uc0JucXlMUUxFY09FcGRRMTJjCmlQYlhSVGUvb3VZOEZRM3ZDS2pI
            OVBPYmtjRDBKbEtvSWJjY1A2RUtSUjgKLS0tIFpYRThicEpFdFJCQW8xc3pyWkJs
            VUN4ckVTTEdIY0hlclF3OGJYcEtzcncKxFFSbFsdvIR3ytMUFajvupzH9yJ3cHV4
            abHwbQa1kcPclvAwQ1hGmUty3byo5WDpQSVdkeQzhVAJMCVKgvzC0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T17:13:10Z"
    mac: ENC[AES256_GCM,data:vtZN8EbgZ6HK8wgMqazW3oU5hWf4OGk6tJD9gKoqgpBTUr0zgeEUzt88vtSoBCCdQR5v9i10EaQgdL+8vNgk2Xtt3M0P+yMCYDrpSQGYc6T8FuyTwf6izBnnY4Q3LDP1qMjpScIPq9v60F+7LsWOssQP8njqnWAf0W9THhsJhOU=,iv:J6GKtvCqlCqviHsYi8TAFo1pTPYThVOB8jlDrg2CNqw=,tag:bImGxFWb1G4bnB5Ynw/EWA==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
