apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: qbittorrent-webui-credentials
  namespace: qbittorrent
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrM2w1eWQyM0VmeElSRjY4
        Z3QzUnpWbzZKT0ZNajBvbWJRb3ZhY0trbkIwClBVOXN6SjdtS25YL1pvZDEzQTcv
        S0VxRnhnZ0hPYTlSaWVsVW91Mlo2b0EKLS0tIGxpZDBsdWIvWGJKVSsvcitkNWQv
        dnRaRkEzYmx1V1RnK3ZzSmVNbTVtWEEKwVvSNSdce3R/fg9TtsLwhXfeBOonIr3C
        BA66peTP+I76pn0JzvscuSxmRYG5kiavahwlWt6rhS7bb2Hw99sTVw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
  encrypted_regex: ^(stringData)$
  lastmodified: "2026-03-01T14:43:13Z"
  mac: ENC[AES256_GCM,data:Oh1PE0NYtz1moc7M2Bym47OqGPAnKSGrgFlNI6vNCE54jtiOrrmdmi1Od28CDXkUVW2ih1Ufpnxp0LP7zCsQqFh+05S4B6akxbqdlFUxpKZyI4b9LYhBeEwzQcDJT5CU7fDPJ65Fp6YoFgUPr6ZgkoPXknVyiiYb50QLRjPFYG0=,iv:X2OP9TfzTpRNCTLMvRhgkz9ZR0BACeVrh/RFQcj9cj8=,tag:DtUViatMFEQorHVTQlQUiQ==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: qbittorrent-webui-credentials
      stringData:
        password: ENC[AES256_GCM,data:sfhZZ5j7vAdHkQ==,iv:lMdKlziHIUSmlArSFGBsPzUexR1m1h3Hecup1TL9Zys=,tag:UluJHv7FMjgn73sq5ZCTIA==,type:str]
        username: ENC[AES256_GCM,data:3ppX/dw=,iv:x0vg9kWlqSrZXfuZi1WwRJHibuTAJ+PYDEhrWHMceHk=,tag:4nJ9YnHSYLWDkUTUIEHWxg==,type:str]
