apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: qbittorrent-webui-credentials
  namespace: qbittorrent
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRXp4VmQ0ejR2MFUvUnZo
        VmIzVDBsdkFNNit2RVpuQy84N3k4ZDRCM0dNCkJuUjdjYXJpVWt2UFhtYlE3RVZB
        b0dzYURZYTdUYWRQVnZXaXJiQm92eWsKLS0tIDZZN1NOSnJKZkU4eXNGRU8vb1FR
        QUNsdWE4NmZsa01ldWNYWFM5ZldRWVUKpK324aJDAiAGsxZ6Cz1D23IM/0nitooh
        46SkILxpIKU9Hh19JbW/cZB8YiHRoIQclr3N/mOHkXB425wC70RP8w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
  encrypted_regex: ^(stringData)$
  lastmodified: "2026-03-28T16:05:31Z"
  mac: ENC[AES256_GCM,data:MS7SVel4uOBt9spbS/WjcrcDfdptPBGlb609KdTBB8PQ4Gu7Cm9/QvC0oU4urpOfx6tUvISBZH0MlQERi1pP9kJWj/c1zaViiojeOtsBSli8vuUjIx1QTYUbJMx1GEfgZsRBWWyahRzd3m1LxwRhnNUolr5qc3k5g3O579zrA9g=,iv:e3fhvs40MRu9tZ55lW8+sMw8iQikH40+A0lGjIssP3E=,tag:2rBFQlRo++ipitiTsa/ciw==,type:str]
  version: 3.12.2
spec:
  secretTemplates:
    - name: qbittorrent-webui-credentials
      stringData:
        password: ENC[AES256_GCM,data:uH1jcpkdaK2J/A==,iv:byaJuWccNRlahEBQRetVaQst6A/FZuyTAbhZbeMKfUU=,tag:zWzz5yppYjmlHbsllkGMDQ==,type:str]
        username: ENC[AES256_GCM,data:T1fazuc=,iv:u2hmQwb+nF/+2wGh0BBDDwgKqlwQj4rwHDBqeZpcWEg=,tag:+3VIWjRgMTbddQvGaAHZOA==,type:str]
