apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: qbittorrent-webui-credentials
    namespace: qbittorrent
spec:
    secretTemplates:
        - name: qbittorrent-webui-credentials
          stringData:
            password: ENC[AES256_GCM,data:xyS22Fn4Pcoz+w==,iv:Qr4yAOIXCF+c33/HGzJ8rrShX74Rt74+rzUOG78aVfo=,tag:DRI/4GxZkatca+ZtRvLMkA==,type:str]
            username: ENC[AES256_GCM,data:XHvMjRs=,iv:IPzUt+2KauV3190xflQarVkN1hweigQ2Ulr8YXtq69g=,tag:kZ05QaXcAK2OxSdkKc3VOQ==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzeEtXMmEyTWRtZWFwd0Mx
            UEg4M3dScEYxTDNJZVhFWHV0cWtaUGZ6dVF3Clk3cFdGOGpCVTV0NlZzeThQVkt1
            NWhxT0U5VHhEaVMvWGhIOXFMVjhQeDQKLS0tIEk0Slk2UXMvOWtReTdoRElQaUFB
            c20zVks1RXZBSW5TbjJIb2RkY3BVSnMKgKcK+a90q5V2Q3/fPtVNF6QMYQMyGOnJ
            6I05XAc+UtJ21NNnKBa8uRbNwyZ8tmciKDuqOOb6G2ruelrghgiKNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T03:40:54Z"
    mac: ENC[AES256_GCM,data:PxGplwcbF9DlrQ55ijXCAMEM/Ovb6j+5AeSIb9OB4ylfFs7woq9vLFeYKQ4Ez6Av7XrcGgKeMlH7MkybY6q7GEGr1Cn9XghSg+eepEzYis5pm/IyiurwSzmpQngwl4Hsa/BGN3d8dINaxPsj3bG0bBQtLpkdBPt1/+9RtG5qAJo=,iv:7dGjbejNsXXs+3WXLIYk8yHwJn+KuPlTRStqsXymqx0=,tag:qYxOSf/ZvPOEWx4cp1PH1w==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
