apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: postgresql-password
  namespace: postgresql
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VDNuQ2tRSlUzNS9aWE5I
        ckR3UWRGenFXY1lEU3dwVnVxOERRVjRhbERBCndVTHl1Y3RBMFlTNzh2Q1FVWEFy
        WXZwZ3hCc3NEejM4bERseUFIWm0rUUEKLS0tIDRuam5YNmk0M1ZtQjhHaVc4UXY2
        S3dGcFpDNGhRc2Fsd21MSVljcVZLOWsKELxbcW74ZaVm8H6UZFPifG2LBOdn1HQ0
        STjEVJ4gd3cihnPFxG3khgOFthYmvMIPcCHr1PH/vjLpjTMSbFX1YA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
  encrypted_regex: ^(stringData)$
  lastmodified: "2026-03-22T17:04:31Z"
  mac: ENC[AES256_GCM,data:TwrOy/qBsDK3Kct5tCOcofYvRvIoo9W4cRChUMMe0+f6oWvRsmxd/vVGXJNmwPLNBjpbGYxK5HOBCDcDYRh3NCRRbSOJJR/BQECez/l/1W/1khtpzkhRMIIsFJoP4aKHw4LC8UBqQqDIFNWHttq7d9sFzlY5+KiNzgefpm+ubAc=,iv:2H3ZQU/JnkiCb061vPuraWrlNseEaWOCyUfWoE7CPRY=,tag:jimIs8iOm8bFRfyAb6mLBA==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: postgresql-password
      stringData:
        adminPassword: ENC[AES256_GCM,data:Dn52+cm1Dbabcq+otknKr6TCrB0=,iv:0zEVvG59pahIqbSriGVWqiIUK86AMaX/FplggwrKSGA=,tag:XzCXDO1Gqv6TKMJe08QCzg==,type:str]
        adminUsername: ENC[AES256_GCM,data:SCbfP8E=,iv:PYN5R3bMI+xqJ8W8EEAbxx8A0h/6HsVwVwFAIrdId8U=,tag:MPRrH3+lcICV/4HGnjxgTw==,type:str]
        replicationPassword: ENC[AES256_GCM,data:+X2VfNUamx7XMeV5t4wGVWWZy7o=,iv:hHkKItn8VwIGDO68LgnNlsCJc5iVU02BjW6/tBfBSNY=,tag:C0wlKV73Ms/BIY+glyimYw==,type:str]
        userPassword: ENC[AES256_GCM,data:hfGlJUKTbyBl/SvzdpdOCYL91FE=,iv:iLnolN3Q89Iv53k5ELMtWUdUOY/keTsPMoTm/jfReI4=,tag:xgjVG1cVJu5KIeHFlXpvDw==,type:str]
