apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: postgresql-password
    namespace: postgresql
spec:
    secretTemplates:
        - name: postgresql-password
          stringData:
            adminPassword: ENC[AES256_GCM,data:plRTGeW72+XgUIgaR32UGrvv7QE=,iv:NsVRo/MxTTCh2LPAbT32f/ISBf/0hlJ/mQ0pVG8+fm4=,tag:ZepuRDQTx5t2FJdf0aeYow==,type:str]
            adminUsername: ENC[AES256_GCM,data:DvSkyyA=,iv:E1aMHRHC6FWI+W5DMS8Bq0SlRM/AyR431ilDNjkoXs4=,tag:TDIfM5WIZVsvI46BFpTSoA==,type:str]
            replicationPassword: ENC[AES256_GCM,data:B4ZeO3/YllMHnRt/qqEQbSbucZ0=,iv:9EBT1BPqiBiaubTuaeuKKgUhKiDrSJFPS+laYGLfxJc=,tag:8qaNnVeSH4irAvsTyfmKcA==,type:str]
            userPassword: ENC[AES256_GCM,data:N+1P9Ll/9ugdIU6TpUzA5Uwh+38=,iv:fmGD1asztv60bhSP2QVeWyTYLUACVwPzoWla9LItLwg=,tag:T2VOVTDgItfXF6bmIQht8A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2RUU2WHZGaERnYzlmYmE3
            V09LU3pvN0RhNzk1Q0RrS0RZaGtva2VFL0RZCkNSWWVOYzJLOXAyWVNPY3M2eFhJ
            VUdCTXorc3BJZFZyaDdYWXpTQ01yblEKLS0tIEhnSTBoVVUyRXl2TlY0d2Z2cWNw
            aDJuOGtlaVgyR1pTRU9INFRaNVhEdmcK7whn0vNM90rfWuvWvpyVrChxpGk2Cy2O
            /+JCC94U8dS2LSXQ5jeDc33/fRKeEoJduy29Ji54Uboe2cvX5FiG+Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-06-12T01:03:11Z"
    mac: ENC[AES256_GCM,data:8mUDJWL8YeLR3ZgqbHu3Fc31tGLLxlvRSIp1Dq60U1qUhiZmYM9LlLf2aADWDTseR/xXqkBUIGbZZeZSYURszr6MCIqJ64XNqn7UqbLjR3v1IGiVyMeBCQgqQDPCpyXyC08q2AwpG1bAdRMKyKWfPR3KPmX6dS7YNB6dvYbfLgk=,iv:W8kcAqhHSWI2l8wdBdX14Oc9ZwRgxDGmJWZKE/2XigI=,tag:9hDZXFUmNU/eQBiXfYd2vA==,type:str]
    version: 3.13.1
