apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: postgresql-password
    namespace: postgresql
spec:
    secretTemplates:
        - name: postgresql-password
          stringData:
            adminPassword: ENC[AES256_GCM,data:2vSDrGlnZg0NCIx02tUmmPoGxpI=,iv:LNxeG8r/hjptvUtp1cpcyUJAG8KOQuafJ9a/8/wJMe0=,tag:0RWMnn4wci7et7NzfAaDeQ==,type:str]
            adminUsername: ENC[AES256_GCM,data:SDowUJs=,iv:C/uryECIESWeYoAO+2vfAL8XYrxw3qbtnTD6upKKXTI=,tag:CPU+fz2+UjCbQ3GwcI6hqw==,type:str]
            replicationPassword: ENC[AES256_GCM,data:JZqncv5AtBHQvFi0lN2ejaVOIDA=,iv:Zc0phcsPb5EXYia7Ziy8/PtZek4i1dBirqCjbWy0klk=,tag:Wybd8NzStqAWnggk3UTqew==,type:str]
            userPassword: ENC[AES256_GCM,data:jeF/4ZCrK6syKxsvkdRTtnQB/dg=,iv:6uSbhHWONajmZbGPvl0VvBJixlP5wwf6BNXLEElr+ek=,tag:r/KktU3VdOc6tiD4OH7rBw==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAybTltRlpWa0FxOERiZzFB
            UU44cjhwbEs3QnA2VlVDc3ZvTU10N2orVmw4CmJXMUZwaXdOVU10RXFjRDRUK292
            M044clNVZ2g3UE9PcWlPRTc1azg3cG8KLS0tIG1aa0RVeGpqZVpCTlJrYThxNFZH
            WFFHV3YyMldLbGMxajFUbUxITHN1bWMKzPHfEuUl0m+28MfqqjIsboGsY73TYvXb
            iGd1AM66VLfO6jE0Q1YVqEJ3bW2WFG1Y1DOVM3LSeLv32wpf7BRBDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T22:14:30Z"
    mac: ENC[AES256_GCM,data:2f7s1c3DMXi7YvRstW0c2U1pKZf4EOBixeiYPS0WnsiZ5clY9aS6pHAMESe6yq+SgdK2DO48oRI/anHxgO2JsIgYAgF3Z5Ag+n7h4R/hGDGdgKLifr6cwCbii9i/cDtSGkuViCB7CKOysKl1Oe/KFQnBwsU3vL/dtdaJ1B3E1u4=,iv:LltMEFtiTQii8e6RzYSbBUCfxXeaiuas7Wwozcnp1i8=,tag:SVSxo7Xgz/N+xZS39UhMDw==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
