apiVersion: batch/v1
kind: Job
metadata:
  name: redis-aof-repair
  namespace: redis
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - command:
            - sh
            - -c
            - for f in /data/appendonlydir/*.incr.aof; do echo "Fixing $f"; yes | redis-check-aof --fix "$f"; done
          image: redis:8-alpine
          imagePullPolicy: IfNotPresent
          name: aof-repair
          volumeMounts:
            - mountPath: /data
              name: data
      restartPolicy: Never
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: redis-redis-data
  ttlSecondsAfterFinished: 300
