apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: redis-password
    namespace: redis
spec:
    secretTemplates:
        - name: redis-password
          stringData:
            password: ENC[AES256_GCM,data:+Vjc1rUfY42aCkS2Jgb1j+O2L7I=,iv:QP11QE8qbvhgibQFfkbLBRb1GQyobj9MsikTkxoETNY=,tag:E2NYUZQvKXlWokmuaOZ8ow==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVNzBaekk4eHhuYWp5YVFl
            NG9JV2U0VnIyd2I4aVhYNEJCbng4Z1FmNkVNClRpakNleXQ3ZEVNSFpOR0RveHlR
            bmdoeHR0emJkUmZrczkwOVdQMjlMTDAKLS0tIDQvV0tuZ01wNFF3MjVrQ1ViM1Rs
            SFFUQWlBZCthaElKZ2FZQld5STdCUk0Ksz0xegY1qOjA7f0grhR4A+8pTVqyYr69
            Z9k/JPFB+L2WfTuOdmncUgbl0b2srarb3QHEe2GUNs9taRXwaUSwTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T16:10:47Z"
    mac: ENC[AES256_GCM,data:l3IxlW/qSGYSJnJVbvNsXMgbzPcxTUjre95JOJFV2Q51saE6h68T50WMasXecm21U+idZ5SLFHuDGELP5a1PpLcsqccIu/75n8T7eKa4tY5tBnMzow1Ng4B8+IYWS29yiFdtIq7I9US17YiWoIeEHrXv7odDl/kH2r4BGIQ9Hrs=,iv:DEXPqn249hvKScZrSmH9r1M5pjXV75+Rd3HbDxMWdsQ=,tag:7BcI5kg+028DCSrm5B7Zig==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
