apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: redis-password
    namespace: redis
spec:
    secretTemplates:
        - name: redis-password
          stringData:
            password: ENC[AES256_GCM,data:8FIh1XKKhPAA0tRw2eV2+w9e+cE=,iv:pGpd2K5AaRnT8A3JgtmaQ126/FVrbHjUyrftinWuiCw=,tag:OF+OmlYOO4CMGkcxr7h6Mg==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWEQ5bG1BREMyZU5wYmli
            aXV0UVZXTUNNdExmTDdteHdGWVBqVzNzemxrCktKNU9ZbTljT05oK3JjbHJZalFV
            UDBIZiswbVlKTUY2RW80NjJHcFZ1bEkKLS0tIEhoREVKV0ZkeGFBd2F1aitDMGtp
            Y1pIL2FGcEdTUkNPR0NkOHRMRjZ4bncKIxMllpPa1/RP+vkhQq5rbarcXQFjHVoK
            Q14R2Dl8L4L8ELZ1PQw7dC0+WcvJ0Iya6JGkm3q0eh/ok08j0YRilw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T21:56:33Z"
    mac: ENC[AES256_GCM,data:GX22azeh9RBvHR/1Hi4AgEmwzmIE+RzlzPLhvArXj0VcOb/67Mt6e/NlNU6yUM73Pdp3+mWDyl+01dXoYYnQm0dhO7t2zB97ck1IaJGi4aYFrNKOMyEABk1DFxlHVsw8O35Xnl+iL6mcUMXUCAOB20l7LHFuTLzKaUOuHezQxKs=,iv:ojFg4cnHVkakovwl9Jh3qIFCmuG8cPoUcOTDf0hIxNI=,tag:YUbKxd68j1dYoB6n37hdIQ==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
