apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: redis-password
  namespace: redis
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3LzQ1eDZUNWpxU0Vtam1z
        d29LRGxjMkF2TWJhVnlGN2svK2YwZkVjM0RRCjNNUVgwTEwxQmg3K05LMUU1U1RT
        L2JGU29la0srcnpOamU3ZE05ZWJzVXMKLS0tIEhWVHNSd0hod0xkYVdsbC83V0RT
        cFZmNm5hNXp2M0FMYUJ6eGRHUjlNS1EKAklxi0CfDXC4zvgqQd7b2QxZiZ+oMBqX
        l6EwSFVRBaYrMRyMK32IkHrc9BtHCEHAQ5wg35hZbYQs+O4DNjQP6w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
  encrypted_regex: ^(stringData)$
  lastmodified: "2026-03-27T03:14:41Z"
  mac: ENC[AES256_GCM,data:HMobEIcDwyKRZuP2JPS+wjmOF2wW/qyT31LsfSN77tk3si8u7iUUHm1v1QpcEyLthsDb1nqUb7MJpC+9ETcg4jA1QXdq3IV84BK5Jw78z1ETogz3Th2LHxhqBe1yDl1d22LXVSitYm10wlVvJgBJp0dr8TXFbQQ63iDM6bSQuQ4=,iv:iuIpPvYSpeMfeuB10lMc0Map8Vr+ftjIbhiztKJUJCA=,tag:z30J3wnfOVIFP4h1yrbNpA==,type:str]
  version: 3.12.2
spec:
  secretTemplates:
    - name: redis-password
      stringData:
        password: ENC[AES256_GCM,data:o+nIIYHJ+pExrc8TWQ9Svh7MpuE=,iv:4+1lLdy+he06m7cDsWwrsegK+rhNrXd5GXh62SiA5pk=,tag:/8Yb6BgGHLmpXOOYCCRd1Q==,type:str]
