apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: memos-local
  namespace: memos
spec:
  ingressClassName: traefik
  rules:
    - host: memos.local
      http:
        paths:
          - backend:
              service:
                name: memos
                port:
                  name: http
            path: /
            pathType: ImplementationSpecific
  tls: []
