apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: memos-database
    namespace: memos
spec:
    secretTemplates:
        - name: memos-database
          stringData:
            memos-dsn: ENC[AES256_GCM,data:AXjPIUNr0FKazmr8d0+RvRsGEaffraFxCZtKontqlopL+pmynj7iKRtlyzRs3Iu4P1s5bkKJX1AZWktMX2jfqIc+aZR1gzJcruLAf1poBL2px7eL8nK4f8uglP6NEYPqhnLqcmqpwg==,iv:+ELsZ4UovzGO6WM50whOnXBZTvn2guj5dzpUUY2zJR4=,tag:U7VdlSjJRGU85jQ9wVpQ3w==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ZU1JdzRhYVY5K00xNTU2
            L1ZQcTdmeCtReWUvalVDSEJFTmxwbllvQndZCk15YVM5NVBzbkdXcm1SMkQxZTFZ
            TEhVRzJEWHI1ZnAxRXBWdmEzNlZjVU0KLS0tIHlEWmlOSXpSOXRLaWhIWXRVZUlG
            azA4WXR4Y1YvNjg5RFU4a2tKSVlYQnMK5kyuaMbAz4+FIU0W9LNDtsPE6tr52H65
            iq5XrhTDQeDhXfImpFK/45LUxdomLHRlpPd3n6eSe9MZmQcXUQQeRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T22:56:00Z"
    mac: ENC[AES256_GCM,data:brhPhv2vIGQrl0lwAeMNPLgMDFilG464DFV5DYgUukxSR3aJX0x25WHe2i9EDeF4Bll0+ZBZxHLRRfyyuMH8C76CFNGmLIqBYabLWh5LUj+PPDCvTvI4TrB4jXPxnpjOOBKOTHNiogW22N2rTOx9SFcvAkJ8D6txLoSm1LVZ0ac=,iv:86npYkt/PhzwzdMbvmC2xXytG4IMHYHUJE0dr9fQX4k=,tag:xzZo5jPB4bgUqgxeZayH3g==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
