apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: memos-database
    namespace: memos
spec:
    secretTemplates:
        - name: memos-database
          stringData:
            memos-dsn: ENC[AES256_GCM,data:ko4ZpEove/nr8f13h72cFmthLXiz/GrzGM7q0QRGU8QB67/wRALbF662c1nZ3Wz1UfFHIPVS4x8tEfWPx7fGes06zpJIMmP7pfvgNbvTZsnvMcOnp5khf4t5gL+1ZDT2HeIsOeMklQ==,iv:WMMmaeuIPQl7sfRWDLAQY5hghmDEqVPocgrgdW+51/0=,tag:n+253pg9Li0kAxtXd7KwPw==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvYXY2MjVVUGRycjFWM05C
            OXZBeW9VSU1lMzc3SWlGS2dHR1gxNTBwMEgwCnhEaWV6VVpCeCt4ZHVDcXhrQWNl
            NmRoM2MrRlBqUEs3bnU2ZFZMa1VYeEkKLS0tIHdTcFJ2ZngvMHJsT3FyZXN5c3pu
            LzdZMWdMTHFSRTlHWVEyL01jZXV6RlUKNypwJNUer+NiWD6xf+qMLGQkWmhaWaHq
            fNjPrMZlmR9RdXy8sP86jAujU8J6PE+DGi16Or51HTVmeXpMYeNvSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T15:02:55Z"
    mac: ENC[AES256_GCM,data:k8KDmxdPNVrXubOsyAd+bsI873ebFvrp6yOPGSWb9EjwmLd6IAHCMmoCrOnQa7ee8vRyswxq/GZWYNJZ0Zk4pxhUXqykUXK5EO7kvQwsJFAzuo4VlJ23UBGgO7QAS8KD2F4n3vDygFpZlD+NvwlIZDxck6eGdod4FOlrdpw3xic=,iv:ElyNcvXSXXxJrxcZayO8NtcOoUSVtctNuk/YxlXCBTA=,tag:vudJQozSFZajbZ256QpsGg==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
