apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: memos-database
    namespace: memos
spec:
    secretTemplates:
        - name: memos-database
          stringData:
            memos-dsn: ENC[AES256_GCM,data:ESJP+H5NZL4n/nl4HFjON9LWzLMMLx01UrtF5AYKunp0pchtDPMbTCgyKOVKw6h15s6x6VkP0DwD9hX7Lxyi7uz4z4/YboYoEp03sT+VobsqJxfggq6oGj1jVxUE6VhGDXARFTtKVg==,iv:aO45ek/+kqrvgcLiG4ns4yM6fE4erlxPaPMIpFk8fKg=,tag:VQHJRor1yrEZEiCkB31tPg==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWjMwRGNMY0hic0JlTEl4
            dEYxbTRLOXR5Qjg2QTRZN0pJbGdPdHNnUlhRClIxdktVSGdBaE1FSEpEVjhEZjJw
            cStONW13WlFGL2EwMm4wdXN5aE0rUVEKLS0tIE1PaE5BWW5IYVgxZUpzQ25Ib2VD
            dWJwYW5pRFR1S2hkQmxYYjJUbmxQaDgK+mw/ljvZMfMdUkRF3Ld8a8GprB4/Ohb4
            NN62awGuMWNwK5aJL7J3BFS8wCqOmvHLcwYLSrXMiMXhSVmKVV6t7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T03:37:06Z"
    mac: ENC[AES256_GCM,data:pLPGYcj3wEf1iP39gQq9EMjPqDeU5DXBoDAmtt5lOhsThgtQaXfOFC6/veuJdx3aDH/Lw1YgyhMsLGcz9Adbj9v+oZW4l8fdkzHTC4IIyYf1L8VYFOOc3CbgncPqxN803SXjYHW3VFGzrWRJTxDKtqBUtNBFMfiBGoUq/E4ed14=,iv:XcPTdXbeSFURYPfY6fBvdzQVWBmRa3GnwMvcM9N1QEY=,tag:rr03OJ/97mtbBTcrTKe/Iw==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
