apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: k3s-subnet-router
spec:
  hostname: k3s-subnet-router
  subnetRouter:
    advertiseRoutes:
      - 192.168.0.0/24
  tags:
    - tag:k8s
