apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: tailscale-auth
  namespace: tailscale
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiOGJ4emx2WmFEdkU0cVN1
        YXlBZ3hJTXcwbnF1VkIrWnFGakI2S09XZzA0Ck1FL1hGcHQzOXNIQ3VYYjl2Wnl2
        QXJTbE55ekc2UWxPZ00wZGFTL05CUncKLS0tIHBPT0FjaTF4ZiszRG10REttc2lZ
        REJ3cEt2ZkFjdVJEeGxWS0NkeXh0SVkKlXLwdAS0JDALTOtWB2+uVASwQzHphUSr
        +obHp4d17ObiF8idC4s/+jyEKeEiSdWX3Yk+CrK9Bd86rA+6/4uMMQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
  encrypted_regex: ^(stringData)$
  lastmodified: "2026-03-23T03:18:47Z"
  mac: ENC[AES256_GCM,data:S9C/cQXuyHjG7T2IGYNzm+OVCZRAUhAZrVv46GJZHfRaTKQ7oePCBqk7ARQ/t+JgAbdLlD0ZaI1Hv7ycGl6G6sO1SQan5v5u2PhC4Y76K6aJMb5Mdm2p7c/sBT4m9KBYfVP1Cony6KrDBy5ieybnZMoOdb3znH/42TT2P+fqIkg=,iv:xyiS8S1dppMDrwDowfNGWowbbdmtSRAbqGdKD4lf+uE=,tag:H1Yk3xKAH8wuOYBj9MOusg==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: tailscale-auth
      stringData:
        TS_AUTHKEY: ENC[AES256_GCM,data:Sp65DVCiLyYC81jmjvcGH1OnDurneGbOUH9R8ux+pDFRHmrIVgXrHzKq4HwvjIhfVdxjiFQkZAIRDE1an+Q=,iv:VQv3he+qan3gHUXCeQm/a5OTT0PFbrGKkp781W+TrPM=,tag:B13yj7GACjL3AlizS3WgAg==,type:str]
