apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: tailscale-auth
    namespace: tailscale
spec:
    secretTemplates:
        - name: tailscale-auth
          stringData:
            TS_AUTHKEY: ENC[AES256_GCM,data:tbA18HCNceo2h6g1XdmdpYHsX6qk/svZhiEkJAgNgkPwpTKiVeLKVzTTm8OAyXU3ZLZu667wNf3VVpY5yxs=,iv:+t5dHgyd0gcLt4NgZdFFiBgUo6tmDiBNgIGpT4+0qnQ=,tag:cVaq5UhItJ2Eg1r0PjKSxA==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVmVKOTlUeHFwRVJwNURY
            UU1zcXJEazd6QXlra0hDT25NN0g4QjBscTNFClF1TWFIeHp1TkVtR3ZHek1YbElN
            V2Fna1BZdXFUWDRaVjdyOGRZUWh6UGMKLS0tIEFqUUhxd3BSVzdTRWN1TS9XUStw
            aE43RzNLVk1ncFZuemQ2MjIyaXcxV3cK3QxbWADA7e07UaEv8P4jNauqtC2gpkCO
            pH8hdUISXuak7+lXtJps8dtWvzhjJINcU5rjP9PSt/brAQkgS0kZwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T21:39:17Z"
    mac: ENC[AES256_GCM,data:TgNYvdidQ1C7J+Ns1lYmPm3DllJ2gq+9z8f1jldsr0kBRx/RqLFrEMiZmIXx6hsMrEGciFo9H7miQ6mE1awKeuHZ1sfaNFlDNxm6gXD4cD6spHpLcaK3MDBgd9B2hg4RdXBOXB+5VRf54xHjEFD3rN5I8HzESVdWGuGEqiUeT5o=,iv:3Lj4x6YhbAZFXfQXxC1FDmar6FiWd3DnWt/T8Zu3584=,tag:fu2E1Nd1JbyMF4lkmPMFHg==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
