apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: tailscale-auth
  namespace: tailscale
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2TzNLN1ZuRWRtQlEzbFMr
        ME1RZUsxK005R0wwS1MrUzVKNHYzelBtMkdZCldsWjVXYmRrcUd6LzdsN25WRUlh
        RVVnZEl2d2NjWmQ5RERmZE5HcWZDTkkKLS0tIHJocVkxYVg0SXV6Ui9tMnBhQjdj
        V083T1h5SjY1bFFoYTNBb0dTQklDQUUKVGDxqpnzVz0GFr0pStYyAdaH37lNm/Ep
        HTFvxMy19R2rrF5NyL8yz1XAwpk6PZLl/NXBD8Kjg9McOqdJ2o2vJw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
  encrypted_regex: ^(stringData)$
  lastmodified: "2026-03-24T05:38:23Z"
  mac: ENC[AES256_GCM,data:nE9H2S/JynWj+gd3NiO8XzJahKKupc3fXyuuvyrFkYnbd8lFXfbTm70qiJ61M8p3C3DSYi53GSh3PycpuUOo9CgY9XLBdXr/Ajh01NX7on9N7MoK7RjtEBjzvlp8sv4F+es6rgbbWcmNa5vrRdixPDQ9rVYCNYfqA5F+5Upic+U=,iv:pmk+9pXmkdUveIgwg8iSU3IpLb4uKoA6F6bfiSiD8iU=,tag:dEQkLov+trniAEr3J9B47w==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: tailscale-auth
      stringData:
        TS_AUTHKEY: ENC[AES256_GCM,data:YpB2vgVqi4RJaMZKtoRqn5v8eN1peIYfiYtYzdhz3TY443IbqRANIhxTLQ4M718w4C2FNOjP1JSZWf0KYwg=,iv:w6jfNSlJlc1xF0xSFrpNvunQTGYfRV2iouD0dDAQ69A=,tag:p6u77WjuIEjXDiTgFaQx/A==,type:str]
