apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: operator-oauth
    namespace: tailscale
spec:
    secretTemplates:
        - name: operator-oauth
          stringData:
            client_id: ENC[AES256_GCM,data:4fJABObj5W/mTkV+xL6k14I=,iv:KN7pM9iiMURwVhcqPBq+jme1wHIcPqRaIMPv/6PCDoA=,tag:D8/SkYXy+v1c0U/XvgQAUA==,type:str]
            client_secret: ENC[AES256_GCM,data:UjHzbydl2UwCh/afO0LHQlnjVQyBGvQdfMMKZX80k/b1sqeHuqyL4+Ks88BFNPArmC8Ul8ChiVWmp8Us3xtbLw==,iv:+10TE8VLJQFbUd1l4JDHoiboyk1PfM5tZcxx68y4CzU=,tag:jKa70fKG3i36nZ5njNRtIg==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHK090SkcyVU04TnRYRVM5
            a3JZZVhzYk1pK3VSTXdlemFDa2xvYVI2WVVRCnBxNlM2azBYZ3FRbXVhQ2NOV0tL
            QUtYVlRwbG5ZdEJpandVcWJEWWVFR3cKLS0tIGVHY3hISVlabm9yTVBUekRiY1Ry
            bHBvRzFwWU9CUGREajZlbGNhWjFNc1EKCG9kv0QvDKggcxCDokTePXZBK5enplsx
            DB470Y6/EStnznOC8+82sXyP784Z19PR9ZFgM9mPqX3M357yLony7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-07T02:12:25Z"
    mac: ENC[AES256_GCM,data:5AYn/yxn3N5TKIOlDeBbNnr0adoX9EWXjPjEF4JZcka1E2L6UzNKkbmcZiy+6VECJ8DpfpKzKkUlKTKb5PgB9nU1EYibChlXBKmjTG+/2ctwE4ZeojgtZ2c2kLc78OYi/g3hhg0goMLkDRKV3M4nQd4UxF+BYq6+xskdhWeMuzQ=,iv:2zjjVjGGQxF7ix31yGZ1L2iYtaHOioQKGEltZZQ4o3I=,tag:9E7Uds3fcnhtKF0xIXIxPw==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
