apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: operator-oauth
    namespace: tailscale
spec:
    secretTemplates:
        - name: operator-oauth
          stringData:
            client_id: ENC[AES256_GCM,data:2yRYHMU6kvj3WFf2VE0G83w=,iv:csnhLl0nk65xlatHBfIGMeXlP47U9nMaFedQAt4NZ/A=,tag:XrzBE6/SffEtN+JCVarqlg==,type:str]
            client_secret: ENC[AES256_GCM,data:MtghArYy3YclgjO3clEiH6AnQr1/+p0QD1r2dK15j3LSAbJpB+2BuseMRbJq/XqnhZqEemzDT9/afPdIvM0c/g==,iv:d70QOYEELEXeevHNpcAyk7Y0xh7gP1ZNmWdns/zU8MI=,tag:TpRzjMtb6SdVWgSrhQWtTA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKRWlDbmFtSGZVT0lnenVt
            T2tYUCtYMEFrUmptSm5UMWUrSlpPQjRJVUNNCkIyRHFlWVJnaGtqV0I3VkVaVXJQ
            b0ZtSHpvdEk3Mk5GalNiemJ3NE1pTDgKLS0tIHlxbHprT3FFc01LZHVQS1NJMlN1
            dFpoTXpHdzFkVStsWVFQYTltbmF5TVUKW5SN6VHcqdvcLT7fOf3FGiaJvWvYYe52
            56cWAuBVdg3JxINIh9pVXqKj1iER7iHIJL/ayr/j/CmPReps/1sdZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-05-25T03:00:46Z"
    mac: ENC[AES256_GCM,data:Ga8hF+cKIbIQ4Cu1BXZSmMCtHUDHcN30Z99OUtrMyl4nq3HElQAf4zGr4kNcXf1Nw7puZJ0bj/caei47tqX2fTSdnKhT9K7+5Nt+iijSTJVN+R8BHc4YfeVrlV7pS6tzyq4WEydpj916tqHUKjCOR9qAHcws2ZnPyp9+V6CpWDk=,iv:WOiQry279a4j7tBSd1Ekp86IbUXlxcxZibS4ZGvITd4=,tag:sJAZtd91Dk+uiFDSR45Mdw==,type:str]
    version: 3.13.0
