apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: operator-oauth
    namespace: tailscale
spec:
    secretTemplates:
        - name: operator-oauth
          stringData:
            client_id: ENC[AES256_GCM,data:qhaZFtTAXgavA/VsNhyo24g=,iv:u5OR49oMUjKsIssShtGRs/U8qlHmXZQFS+6z1Us5lo0=,tag:W19z/DJyxqONbdECR1KFsg==,type:str]
            client_secret: ENC[AES256_GCM,data:6qnC1yJ4LyJHTo4esQ3aB/HPTL4rePsve60If5OcDOgBnVTeGcmttPq3/c10I6PJJhPfUJCclfshqGFF7MTxxA==,iv:HvTdRor6PQMOeROct23x64ZJ8PqbEqkNxxqzz7a+lXg=,tag:HB4kq4/ZEPRjlfDvmTTr3w==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByOTNVYW5jdzhvRjN0QW1p
            T2FzMkpLdU95OGRJTFRweDJnTW9uVUI3c3dZClFhWWlkMER3YkxpRi9QaERkRTE4
            YzNOVkpIdGRIVlhudDhUSG80TmVFR0kKLS0tIHpvM3dWek0zRjdSVGVmRkZiUEQw
            SmlXcE9YdFlEVnB1bXBFaG1oUDZFbm8K3T1snKpDQswDLx+GFYZcwrRny4zUejho
            i7Yz1mDE11tRRRCTN6Dkm/0fBWpPL93O8DoN7V+oH6JDDjkX/eOQgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T03:40:54Z"
    mac: ENC[AES256_GCM,data:aztenkxqC77hz1WqxAFPpH4ZqIBgZbTvgxNfjRakyMSyYqReIfEIDDFgt0XwXlZX0O+r4iYoeCovyDG9KGoD+U876ktKANRBiMYwxGV3F8+tMXsHBIk0RPMBli52New2i/RxLx0fHp4JnQKn7dvghKxheGUshV9ZSllQgvGvuiw=,iv:TQ0ZiHVVZUQVF5tE1mcX6C/cWZAQKkSVb9ioocgcFEk=,tag:PwmSBnx/F3eruI63eu6zbw==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
