apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: n8n-encryption-key
  namespace: n8n
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhcGFaZTEyaU8vckplem1U
        VjJ4aks4bjZjTUkyVGlydWRwazZ4TDllK3o4Cm95MHoyVTF6cGR4UjYrWXA2VHNO
        VVQxUXpXdXVORXhtYS9xLzZhUXBieG8KLS0tIHQxdUlVSUxuWnhFenloVDRMaXJS
        N1V0K2N0V1AxL2txSm9XSGMvN1piWlkKfqWX+JlgydgSiV/vdeTtdQ+TSLC6R2Yh
        RBR+dw7CK4nGospkAa30KTBMtzRari1VLHC386X58kG2VuLXStOUTQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
  encrypted_regex: ^(stringData)$
  lastmodified: "2026-03-28T03:54:56Z"
  mac: ENC[AES256_GCM,data:qmWM0wgmhBbYg/9PW/OU55/WPS3Ty0pHZKkEINtrU8vf61asBtWqZnEBw/8R3pBZMgJvWI2tNC6F1VfNuHQ5Ofe3aF0Uy1fTQ8eGaVubk/Lmx5kzsNp3AtrZLpjzd9Z+J8zIEvMfVRXi3uByF3fM1oW+71x8iELOIh52GO7iHsE=,iv:hCXZcYTIwMbpDiueFu3Yts3P8O0mchpjORG+LLpm58o=,tag:XVaOZ2WteL24crgTjp1Qzg==,type:str]
  version: 3.12.2
spec:
  secretTemplates:
    - name: n8n-encryption-key
      stringData:
        N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:HUqUgDEopupH4Tv6ql2RrmVEcHhklF0dGJV5tUimJQ8=,iv:LDNMOCt6UEaQHSrgYlnuwBmWJcXFx22yATffogMrPcM=,tag:O79JX9PgS71eataZCRlVNg==,type:str]
