apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: n8n-encryption-key
    namespace: n8n
spec:
    secretTemplates:
        - name: n8n-encryption-key
          stringData:
            N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:tS5FLzE/2A/mBzNQxTKtTNyjdyMWaefJpf9jz2jxxpA=,iv:T9+2pxVfXu0F1EPkuMGnMZ/DRbAZ2/8v3+xYJ3LclXU=,tag:KIuql5doxrmXrMsibiwlmw==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZTg2b1pocEswMDhpaWMx
            VmFSNFNNTEthWW9rOXZWLzZ6aEJlNTc4eldJCmZERkJ0cnk0ZzhkaGZwZ2ovVkFW
            b0xmd3A2STZqMXcxNFNTdTZ5ejU0SVUKLS0tIHVvOWlSMXZaT1l3TlpGazZaSXhp
            d1A2d0YzWTFzMERkZklnbkJMcUxCNVEKXM3kGgz2RNhqvI6aOIFw4ldW2Svaru98
            xsQnSI4Mjsjm/TO2jSd0+ZkZS+d0F4C5A2K4oh4m8MPFBGOponOKnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T17:13:10Z"
    mac: ENC[AES256_GCM,data:7CFQ4WJ7Ti0YqISD1cx9Z35/nvWkrZ2ge7GKbEb+HQHA0eIEQblH4mi9B2EIcsZPBJF9QIUYXtxMrGGaYo9xbC7KXF2noCEGTopKocCV1lttYhWawQPs6zEBqjQ5hlc0GpRcbmPXyzupeBtiWVgWBzWtcpy8rSvZWZCnGpEDXsM=,iv:fq6vFkNxYJoPvu5f0Hitlo2zY9MeslE1KMWUB6BE8Lk=,tag:xoZB+GoMurF+vz5OC4bPmg==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
