apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: n8n-encryption-key
    namespace: n8n
spec:
    secretTemplates:
        - name: n8n-encryption-key
          stringData:
            N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:Go94TogF/2U8RFR5uhTfN/NjXFw0TjnIScFTpxjrlPo=,iv:PGouAOUqi1EnCGtraGFwlCiNvtiGsbMzD4c3ZrPlvdc=,tag:vFCVqsxnFUvZWYJjhWE7Kg==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDYnk5bWNJZnBvVjBtR0Ew
            RUlNU3lHMGhIaUlQdU9rYWZvR24zVnlLVDFFCksyMm81M3VpU1poUWlRWVdqVjVR
            b1ZLNnFOTmhFTTRycjd2RVk4VXlBdzgKLS0tIEJDL3lZaXlLU1V2MlhkeGlmYWcz
            MU9FNHBKQzloaDVoZ1N5eEo2V2lUV1kKdVglglhPGE/jRlCF/m64Va49lZZZhtI9
            +gQwKl1XY1U9KeCBeWLrIPS8ba7e5cfeZNTrDSfRVZ3ehMsVaPEyDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T16:10:47Z"
    mac: ENC[AES256_GCM,data:bRAU1lY39ubudtGBFaCGdzjjARyqhSLRgrMugMB9nUktJyFpW8tEROBWWtG7rgSyQ9Kdn7iYXisSoZCloQLLmfI4szKlIkmSXg3S+G8pXrbHyuvOHC2C5XAGwC73GAEcdA7lDYvBClcZJv1b32+TQ9Hk2mLFNeFz2rwEJsa2hyU=,iv:sRAupCvyd9/bNIWjIQpdbsf6vfjATriWg09MNdX8g7g=,tag:emZLw0ddJ9DtzJvRPRJY2A==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
