apiVersion: v1
data:
  02-custom.conf: |
    addn-hosts=/etc/addn-hosts
    address=/.local/192.168.0.241
    address=/.dev.kronkltd.net/192.168.0.241
    dhcp-option=6,192.168.0.243
  05-pihole-custom-cname.conf: ""
  addn-hosts: ""
kind: ConfigMap
metadata:
  labels:
    app: pihole
    chart: pihole-2.35.0
    heritage: Helm
    release: pihole
  name: pihole-custom-dnsmasq
  namespace: pihole
