apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: admin-password
    namespace: pihole
spec:
    secretTemplates:
        - name: admin-password
          stringData:
            password: ENC[AES256_GCM,data:AoNpTz7Gl6FXwb20dsx4CimrGgg=,iv:qM7FRMB/TW3t5XDjYGzwLthRESmU56CCbj1HTzZMLRU=,tag:6KaqHdiBf/2mqbPuFUzzxQ==,type:str]
sops:
    age:
        - recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6REtoZHY3UUw5RVZrN2dz
            NkZzNVVlVGV1QzZjR1lqRjlpSWlLTktTdmdRCmJQWFNaUjJzQ2Job29FK3l5QUJ6
            bzloM1pQcUNsc05vOHJualZhUkZGdWsKLS0tIHpHUFdYWlo3S3dwa0d1YW9RQldl
            ZlpvcnMyTS9FRWlzOXZjdmd6SUU3TXMKA+nPWqvckTjOJwWm/7BIccOMSV1XZKKg
            9EJGC5i75A6IuKM0ZCXkVQr8ST3zppc8Ib/icQ5FpbkzZ3G5leyCdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T01:21:50Z"
    mac: ENC[AES256_GCM,data:vjnGP0qHMu6Rv0rpkycB8rFz2Y+1VbvTJnqvUBf4z4pL98sl3DkLPn2u7U5zwlyy1aS/2KcxwQkDuZm8ei2gG/E2CxhYY+aYOWi4dxyx0qVtx03O4rOQUGxuE4Cw8X0kQD/LT1qBqmMQyAISN5JhKGzw6XQUd2KUOXFhZyqUYHM=,iv:tDaaMuf9iyE+Eli0DKoBtVEFxkYbkhnAoyC5vBMg46U=,tag:ENHLDJuztlCj97yOMjgw5w==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
