apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: admin-password
    namespace: pihole
spec:
    secretTemplates:
        - name: admin-password
          stringData:
            password: ENC[AES256_GCM,data:lAb+FYc4JXDiQj5MMQYplt9DMLc=,iv:Q/w6pX0m0wM3OkIu7U4MXjqx68RPcfh4c3PfvBmamtI=,tag:kzduW1IeoCPs6h9TXLIvpg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXT1dOaGM3SUJRL2Mxci9u
            azllZ0RjOWFJUnhsK3lqalV5STdjUEpRZmdNCkRwUGMvNW5aVjhRdnprSXNnbDk4
            a20ycUNLdDJGNlorQ3Y1cTg1OHJDOGsKLS0tIDJQdnRKQ2lXL2FOZFA2UnI5d2I2
            YmtMVnRvSEFqYjN3b0xla002eHl1ODgKKnNWQWqctC7r14MbsZJe6VikxEj9wbNu
            g+Q7KsWvz4kvw3yeQhTf2Wz5zjshcUmb6GHyeocRa4uXni+XrmDnQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-05-25T04:18:12Z"
    mac: ENC[AES256_GCM,data:Z4sVaWa9G3opLWjT7bR56DJEioC7BnIk936ETBai9AA7zD/XQOSw6gLcp7HWJtjG4rlVdjdXINIMYyd+Zp41idtV9hPq1P9sYeppMEr6rGI4i8eodBDvz1MAK+3OmYFOXxc7qiad1ooMPNrzyJbKej4eja+UydpqLmRTNr87JH4=,iv:MqwGEsjbMLCk8sxqOZbLdP0A3nJ/u1HA5ZwOwLtgrpk=,tag:/jTR1OB0R4vD4q02qQAT8g==,type:str]
    version: 3.13.1
