apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: admin-password
  namespace: pihole
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoeUxta094ZlVQa1dMVjN3
        N2kyQnB2c05zVk5aQlZPRXAyUGxOY2lyUlVFCmhvRm9qTnFaZVVOZTZYUkVhWExa
        elkxbWhHZjVLK2xLem1kUjFORXV6ODQKLS0tIEVPenJ0dGpLUkg4NVlIYnYvY2wz
        K21JVkI2NWJ2Q3dsQmlTcFNWbUY2WGsKJni0rKvTSVfL5aV1G3c9ZXs60ZeiKM8h
        CK009+yXgIiNA5MLo5J/C/4RDrwozKwx7m5Pe4fujY4az1ev+PAYVg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
  encrypted_regex: ^(stringData)$
  lastmodified: "2026-03-31T22:41:18Z"
  mac: ENC[AES256_GCM,data:F6tRxHznxsPLbqyLLbiriZ4EX/MWukbvOKmIeXO4G57WWVqOgpQ0TwDIqicXaJPZZayCiGlzLi8bL/FvrVf8FlbV2UIlOA90p6852n7eitzttWlfG5plGyBdTEo1f7pzKiJqDGbS/xfImhrbhJdsx3OR5MF6JDnOZgPVuPzh/bE=,iv:V103fHv9ZmsDpe+nJa/trQnXpZtTx+yWCW7WzwhYwJg=,tag:3jb8ygBW/hbUYn3BAKUEzg==,type:str]
  version: 3.12.2
spec:
  secretTemplates:
    - name: admin-password
      stringData:
        password: ENC[AES256_GCM,data:No4QHI1whSpSPyL6kATMtS5dZZM=,iv:iU/IPqcHp9gwRANAomlLIALJtCNQ8OJRDMtF9VSpEF4=,tag:d57UwhZUxOjGMRaca18Kgg==,type:str]
