apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: elasticvue
  namespace: elasticvue
spec:
  ingressClassName: traefik
  rules:
    - host: elasticvue.home.kronkltd.net
      http:
        paths:
          - backend:
              service:
                name: elasticvue
                port:
                  name: http
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - elasticvue.home.kronkltd.net
      secretName: elasticvue.home.kronkltd.net-tls
