apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: elasticvue-clusters
    namespace: elasticvue
spec:
    secretTemplates:
        - name: elasticvue-clusters
          stringData:
            ELASTICVUE_CLUSTERS: ENC[AES256_GCM,data:eVuT32qnkLJKw7gxhD7H5Qyg3XxAKUtPbGU4vpf4TE7DKwcv4PdaVLh5TOfKnVt4XvT4qt7ubhDw/lEITN9a+2K5HXb8RUVJyfG23LMidnXrOoEFJzuN/ueUpTU=,iv:Jwdlc6PfXh6b7920bMsgFKB1O6OqkdXWUzwYGDfUeSY=,tag:+PRoxMhgDwibcqxvftAxsA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1K0VzWmVVWE80elowSHZK
            dkhZaG9GV1FqWjFvb1hxUzJzcS9xOGFsd21ZCnJLQVliY2RXOW9DY2hrZzBBOXVt
            YU5mQnU4L3hROGxTVVkxQnlFOThnZ0EKLS0tIEJRakdzNERiNUYzZzVUVFVSSEpT
            Sjh0dHJ5OTBENGIzY0c2NWduOUR0SEEKOcGS4w2IKBp0BqnoDITCmpJyy8OuGPqN
            BgfyaRgkxffHsaD9KkHWa8J2mks3cwrgR5i/c951vE12XUzjDia/Qg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-08T03:16:18Z"
    mac: ENC[AES256_GCM,data:CGin+4JH75vSsmgfHanBqhERDSNOvPpVNsGAE/lukpN8IQ0GFsvMN9DTuoOByDD1Rg1SAuwPR656KO5vwmGMl99AbM9h99/HncwJf/bQBplmDk97THjnTkEOTK6VILFC6Lp4696kw5ngFu6iwPctPJ/iKzViw+NB/XKQr2v+Obo=,iv:wMvlNZ3pu/MCpG4mGI3mqr7Klnas7ntGRuMUJPPZ/Vw=,tag:4wagcwm10M4CVw90OYUBqw==,type:str]
    version: 3.13.3
