apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: elasticvue-clusters
    namespace: elasticvue
spec:
    secretTemplates:
        - name: elasticvue-clusters
          stringData:
            ELASTICVUE_CLUSTERS: ENC[AES256_GCM,data:N1q0zguk6l7tk6UtFm24JFe1HQT/GdmJaJNy0Cdt1RcLzH8CLNVxiSmz70TN5rv0Vr2CVPKdDGrLF8Mtmdw6MOp1pb3RmfWg2v9uTIQxzSUiX6ypBFHJSSsYKafEUyyRYhbJRJjwJIvpqXSCIugcdHsHoQ1kE7V98wL1GLJJswrTHBWX+V2Q5DV8NKAM7QobLLbGsqJtVK1O+z39kBYFi3+utAIZJ08h8Fwv8OrXFWuyQi/iqYrD1r7uTw/0V+U/vR5QLhSWSDGQoT82H/AUcIDTlWJdKg5wjjvYQQzXXFaFpbIZ5tfqhJOo4VOhmKPlC5Y5uT8XNUjFQ8vgLqA=,iv:d4K8QEYNUFmvZaNoNJp857pK7qbFyiF9xAQS5C+SkXE=,tag:SliOYiiomJK08WY/9lpqEw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQeXZPNTdEUmtSeVpLMjBw
            MENQS1hVS0syTEtuWTFSZEYzV0tnZHFpdTNBCktyU2Q1Q0NzK2hXd3dEN05YV0k5
            aHcyQWlqM21za0FRNkt6QlFTYS81V3cKLS0tIHVsTCtyY0VGZXh6QnZKekxMcE5B
            N3hrN0VFRDNYM29vK2VHTEY4MFNaUXMKTreM6qI+BtZ9xjfQSOjXWngN5JP8OzHG
            SjF9XgRBkaG10E5iZO9rvJda2bkCgJ9Ac0R/+RACYuALnkeIG9WxJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n372e8dgautnjhecllf7uvvldw9g6vyx3kggj0kyduz5jr2upvysue242c
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-08T03:06:10Z"
    mac: ENC[AES256_GCM,data:+95s6gkhilSoaWMKPdDTnhTp+mD6Y9Oj0s2awPyUYrsg5oaymyqac1fFiVjrMeSA5N86mJWCfqSzn7CAENcrVEgTkQgBB8Xqlt0/Ym0ozZOpmz9otco0j0H5Gp4WWCKlDJ1lGfc+PpvESly9wwB4ziiaVYQYs6V/AZ8yjpboTEU=,iv:1Hqtj1bzYs7oZRPTYwP3U8VXTyKoyfdMYbb2BBa/uUU=,tag:JNstsFCfAKpRZhUllgmXSw==,type:str]
    version: 3.13.3
